---
permalink: protect-scsql/concept_type_of_backups_supported.html 
sidebar: sidebar 
keywords:  
summary: 'SnapCenter를 사용하여 SQL Server 시스템 및 사용자 데이터베이스를 백업하려면 데이터베이스, SQL Server 인스턴스 및 Availability Groups\(AG\)와 같은 리소스 유형을 선택해야 합니다. 스냅샷 복사본 기술은 리소스가 상주하는 볼륨의 온라인 읽기 전용 복사본을 생성하는 데 사용됩니다.' 
---
= 지원되는 백업 유형입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하여 SQL Server 시스템 및 사용자 데이터베이스를 백업하려면 데이터베이스, SQL Server 인스턴스 및 AG(가용성 그룹)와 같은 리소스 유형을 선택해야 합니다. 스냅샷 복사본 기술은 리소스가 상주하는 볼륨의 온라인 읽기 전용 복사본을 생성하는 데 사용됩니다.

복사 전용 옵션을 선택하여 SQL Server가 트랜잭션 로그를 자르지 않도록 지정할 수 있습니다. 다른 백업 응용 프로그램과 함께 SQL Server를 관리하는 경우에도 이 옵션을 사용해야 합니다. 트랜잭션 로그를 그대로 유지하면 모든 백업 애플리케이션이 시스템 데이터베이스를 복구할 수 있습니다. 복사 전용 백업은 예약된 백업의 시퀀스와 독립적이며 데이터베이스의 백업 및 복원 절차에 영향을 주지 않습니다.

|===
| 백업 유형 | 설명 | 백업 유형이 포함된 복사 전용 옵션입니다 


 a| 
전체 백업 및 로그 백업
 a| 
시스템 데이터베이스를 백업하고 트랜잭션 로그를 잘라냅니다.

SQL Server는 데이터베이스에 이미 커밋된 항목을 제거하여 트랜잭션 로그를 잘라냅니다.

전체 백업이 완료되면 이 옵션은 트랜잭션 정보를 캡처하는 트랜잭션 로그를 생성합니다. 일반적으로 이 옵션을 선택해야 합니다. 그러나 백업 시간이 짧은 경우에는 전체 백업을 사용하여 트랜잭션 로그 백업을 실행하지 않도록 선택할 수 있습니다.

마스터 및 msdb 시스템 데이터베이스에 대한 로그 백업을 만들 수 없습니다. 그러나 모델 시스템 데이터베이스에 대한 로그 백업을 생성할 수 있습니다.
 a| 
로그를 자르지 않고 시스템 데이터베이스 파일 및 트랜잭션 로그를 백업합니다.

복제 전용 백업은 차등 기본 또는 차등 백업 역할을 할 수 없으며 차등 베이스에 영향을 주지 않습니다. 복사 전용 전체 백업을 복원하는 것은 다른 전체 백업을 복원하는 것과 동일합니다.



 a| 
전체 데이터베이스 백업
 a| 
시스템 데이터베이스 파일을 백업합니다.

마스터, 모델 및 msdb 시스템 데이터베이스에 대한 전체 데이터베이스 백업을 만들 수 있습니다.
 a| 
시스템 데이터베이스 파일을 백업합니다.



 a| 
트랜잭션 로그 백업
 a| 
가장 최근의 트랜잭션 로그가 백업된 이후에 커밋된 트랜잭션만 복사하여 잘린 트랜잭션 로그를 백업합니다.

전체 데이터베이스 백업과 함께 트랜잭션 로그 백업을 자주 예약하는 경우 세분화된 복구 지점을 선택할 수 있습니다.
 a| 
트랜잭션 로그를 잘라내지 않고 백업합니다.

이 백업 유형은 일반 로그 백업의 시퀀싱에 영향을 주지 않습니다. 복사 전용 로그 백업은 온라인 복원 작업을 수행하는 데 유용합니다.

|===