---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_features.html 
sidebar: sidebar 
keywords:  
summary: SQL Server용 플러그인은 Windows 호스트의 Microsoft SQL Server 및 스토리지 시스템의 NetApp Snapshot 복사본 기술과 통합됩니다. SQL Server용 플러그인으로 작업하려면 SnapCenter 인터페이스를 사용합니다. 
---
= Microsoft SQL Server용 SnapCenter 플러그인 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SQL Server용 플러그인은 Windows 호스트의 Microsoft SQL Server 및 스토리지 시스템의 NetApp Snapshot 복사본 기술과 통합됩니다. SQL Server용 플러그인으로 작업하려면 SnapCenter 인터페이스를 사용합니다.

SQL Server용 플러그인에는 다음과 같은 주요 기능이 포함되어 있습니다.

* * SnapCenter * 기반 통합 그래픽 사용자 인터페이스
+
SnapCenter 인터페이스는 전체 플러그인과 환경에 걸쳐 표준화와 일관성을 제공합니다. SnapCenter 인터페이스를 사용하면 플러그인 전체에 걸쳐 일관된 백업 및 복원 프로세스를 완료하고, 중앙 집중식 보고, 대시보드 뷰 사용량을 한 눈에 확인 하고, RBAC(역할 기반 액세스 제어)를 설정하고, 모든 플러그인에 걸쳐 작업을 모니터링할 수 있습니다. 또한 SnapCenter는 중앙 집중식 스케줄링 및 정책 관리 기능을 제공하여 백업 및 클론 작업을 지원합니다.

* * 자동화된 중앙 관리 *
+
일상적인 SQL Server 백업을 예약하고, 정책 기반 백업 보존을 구성하고, 시점 및 최신 복원 작업을 설정할 수 있습니다. 또한 전자 메일 경고를 보내도록 SnapCenter를 구성하여 SQL Server 환경을 사전 예방적으로 모니터링할 수도 있습니다.

* * 무중단 NetApp 스냅샷 복사본 기술 *
+
SQL Server용 플러그인은 NetApp Snapshot 복사본 기술을 Microsoft Windows용 SnapCenter 플러그인과 함께 사용합니다. 따라서 SQL Server를 오프라인으로 전환하지 않고도 몇 초 내에 데이터베이스를 백업하고 신속하게 복원할 수 있습니다. 스냅샷 복사본은 최소 스토리지 공간을 사용합니다.



이러한 주요 기능 외에도 SQL Server용 플러그인은 다음과 같은 이점을 제공합니다.

* 백업, 복원, 클론, 검증 워크플로우 지원
* RBAC 지원 보안 및 중앙 집중식 역할 위임
* NetApp FlexClone 기술을 사용하여 테스트 또는 데이터 추출을 위한 공간 효율적인 운영 데이터베이스 시점 복사본 생성
+
클론을 보유하는 스토리지 시스템에는 FlexClone 라이센스가 필요합니다.

* 무중단 및 자동화된 백업 검증
* 여러 서버에서 동시에 여러 백업을 실행할 수 있습니다
* 백업, 확인, 복원 및 클론 작업의 스크립팅을 위한 PowerShell cmdlet
* SQL Server의 AGS(AlwaysOn Availability Groups)를 지원하여 AG 설정, 백업 및 복원 작업을 가속화합니다
* SQL Server 2014의 일부로 인메모리 데이터베이스 및 BPE(Buffer Pool Extension)를 지원합니다
* LUN 및 가상 머신 디스크(VMDK)의 백업 지원
* 물리적 인프라와 가상화 인프라 지원
* iSCSI, Fibre Channel, FCoE, RDM(Raw Device Mapping) 및 VMDK over NFS 및 VMFS 지원
+

NOTE: NAS 볼륨은 스토리지 가상 시스템(SVM)에서 기본 엑스포트 정책을 사용해야 합니다.

* SQL Server 독립 실행형 데이터베이스의 FileStream 및 파일 그룹 지원

