---
permalink: protect-scsql/concept_requirements_for_restoring_a_database.html 
sidebar: sidebar 
keywords:  
summary: Microsoft SQL Server 백업용 SnapCenter 플러그인에서 SQL Server 데이터베이스를 복원하기 전에 몇 가지 요구 사항이 충족되는지 확인해야 합니다. 
---
= 데이터베이스 복원 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft SQL Server 백업용 SnapCenter 플러그인에서 SQL Server 데이터베이스를 복원하기 전에 몇 가지 요구 사항이 충족되는지 확인해야 합니다.

* 데이터베이스를 복구하려면 대상 SQL Server 인스턴스가 온라인 상태이고 실행 중이어야 합니다.
+
이는 사용자 데이터베이스 복원 작업과 시스템 데이터베이스 복원 작업 모두에 적용됩니다.

* 원격 관리 또는 원격 검증 서버에서 예약된 작업을 포함하여 복원하려는 SQL Server 데이터에 대해 실행되도록 예약된 SnapCenter 작업을 비활성화해야 합니다.
* 시스템 데이터베이스가 작동하지 않는 경우 먼저 SQL Server 유틸리티를 사용하여 시스템 데이터베이스를 재구성해야 합니다.
* 플러그인을 설치하는 경우 다른 역할에 대한 사용 권한을 부여하여 AG(Availability Group) 백업을 복원해야 합니다.
+
다음 조건 중 하나가 충족되면 AG 복원이 실패합니다.

+
** RBAC 사용자가 플러그인을 설치하고 관리자가 AG 백업을 복원하려고 할 경우
** 관리자가 플러그인을 설치하고 RBAC 사용자가 AG 백업을 복원하려고 하면


* 사용자 지정 로그 디렉토리 백업을 대체 호스트로 복원하는 경우 SnapCenter 서버 및 플러그인 호스트에 동일한 SnapCenter 버전이 설치되어 있어야 합니다.
* Microsoft 핫픽스 KB2887595를 설치해야 합니다. KB2887595에 대한 자세한 내용은 Microsoft 지원 사이트 를 참조하십시오.
+
https://support.microsoft.com/kb/2887595["Microsoft 지원 문서 2887595: Windows RT 8.1, Windows 8.1, Windows Server 2012 R2 업데이트 롤업: 2013년 11월"]

* 리소스 그룹 또는 데이터베이스를 백업해야 합니다.
* 스냅샷 복사본을 미러 또는 볼트에 복제하는 경우 SnapCenter 관리자는 소스 볼륨과 타겟 볼륨 모두에 SVM(스토리지 가상 머신)을 할당해야 합니다.
+
관리자가 사용자에게 리소스를 할당하는 방법에 대한 자세한 내용은 SnapCenter 설치 정보를 참조하십시오.

* 데이터베이스를 복구하기 전에 모든 백업 및 클론 작업을 중지해야 합니다.
* 데이터베이스 크기가 테라바이트(TB)인 경우 복원 작업 시간이 초과될 수 있습니다.
+
Set-SmConfigSettings-Agent-configSettings@{"RESTTimeout"="20000000"} 명령을 실행하여 SnapCenter 서버의 RESTTimeout 매개 변수 값을 20000000 ms로 늘려야 합니다. 데이터베이스 크기에 따라 시간 초과 값을 변경할 수 있으며 설정할 수 있는 최대값은 86400,000ms입니다.



데이터베이스가 온라인 상태일 때 복원하려면 복원 페이지에서 온라인 복원 옵션을 활성화해야 합니다.
