---
permalink: protect-scsql/quick_start_to_install_snapcenter_plug-in_for_sql_server.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter 서버 및 Microsoft SQL Server용 SnapCenter 플러그인 설치에 대한 지침은 에 나와 있습니다. 
---
= SQL Server용 SnapCenter 플러그인 설치를 빠르게 시작합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버 및 Microsoft SQL Server용 SnapCenter 플러그인 설치를 위한 일련의 설치 지침을 제공합니다.



== 설치 준비

* 도메인 및 작업 그룹 요구 사항 *

SnapCenter 서버는 도메인 또는 작업 그룹에 있는 시스템에 설치할 수 있습니다.

Active Directory 도메인을 사용하는 경우 로컬 관리자 권한이 있는 도메인 사용자를 사용해야 합니다. 도메인 사용자는 Windows 호스트에 있는 로컬 관리자 그룹의 구성원이어야 합니다.

작업 그룹을 사용하는 경우 로컬 관리자 권한이 있는 로컬 계정을 사용해야 합니다.

* 라이센스 요구 사항 *

설치하는 라이센스 유형은 환경에 따라 다릅니다.

|===
| 라이센스 | 필요한 경우 


 a| 
SnapCenter 표준 컨트롤러 기반
 a| 
FAS 또는 AFF 스토리지 컨트롤러에 필요합니다

SnapCenter 표준 라이센스는 컨트롤러 기반 라이센스이며 프리미엄 번들의 일부로 포함됩니다. SnapManager 제품군 라이센스가 있는 경우 SnapCenter 표준 라이센스 사용 권한도 제공됩니다. FAS 또는 AFF 스토리지를 사용하여 평가판을 통해 SnapCenter를 설치하려면 세일즈 담당자에게 연락하여 프리미엄 번들 평가 라이센스를 받으십시오.



 a| 
SnapCenter 표준 용량 기반
 a| 
ONTAP Select 및 Cloud Volumes ONTAP에 필요합니다

Cloud Volumes ONTAP 또는 ONTAP Select 고객인 경우 SnapCenter에서 관리하는 데이터를 기준으로 TB당 용량 기반 라이센스를 구입해야 합니다. 기본적으로 SnapCenter는 90일 100TB SnapCenter 표준 용량 기반 평가판 라이센스를 기본 제공합니다. 자세한 내용은 세일즈 담당자에게 문의하십시오.



 a| 
SnapMirror 또는 SnapVault
 a| 
ONTAP

SnapCenter에서 복제를 사용하는 경우 SnapMirror 또는 SnapVault 라이센스가 필요합니다.



 a| 
추가 라이센스(선택 사항)
 a| 
을 참조하십시오 link:../install/concept_snapcenter_licenses.html["SnapCenter 라이센스"^].



 a| 
SnapCenter 표준 라이센스(선택 사항)
 a| 
보조 대상


NOTE: SnapCenter 표준 라이센스를 보조 대상에 추가하는 것이 좋지만 필수는 아닙니다. 보조 대상에서 SnapCenter 표준 라이센스가 활성화되어 있지 않으면 페일오버 작업을 수행한 후 SnapCenter를 사용하여 보조 대상의 리소스를 백업할 수 없습니다. 그러나 복제 및 검증 작업을 수행하려면 보조 대상에 FlexClone 라이센스가 필요합니다.

|===
* 추가 요구 사항 *

ONTAP 및 애플리케이션 플러그인 최소 요구 사항은 을 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["상호 운용성 매트릭스 툴"^]

|===
| 호스트 | 최소 요구 사항 


 a| 
운영 체제(64비트)
 a| 
을 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["상호 운용성 매트릭스 툴"^]



 a| 
CPU
 a| 
* 서버 호스트: 4코어
* 플러그인 호스트: 1 코어




 a| 
RAM
 a| 
* 서버 호스트: 8GB
* 플러그인 호스트: 1GB




 a| 
하드 드라이브 공간
 a| 
서버 호스트:

* SnapCenter 서버 소프트웨어 및 로그용 4GB
* SnapCenter 리포지토리의 경우 6GB
* 각 플러그인 호스트: 플러그인 설치 및 로그의 경우 2GB, 전용 호스트에 플러그인이 설치된 경우에만 필요합니다.




 a| 
타사 라이브러리
 a| 
SnapCenter 서버 호스트 및 플러그인 호스트에 필요:

* Microsoft .NET Framework 4.5.2 이상
* WMF(Windows Management Framework) 4.0 이상
* PowerShell 4.0 이상




 a| 
브라우저
 a| 
Chrome, Internet Explorer 및 Microsoft Edge

|===
|===
| 포트 유형입니다 | 기본 포트입니다 


 a| 
SnapCenter 포트
 a| 
8146(HTTPS), 양방향, 사용자 지정 가능(URL_\https://server:8146_)



 a| 
SnapCenter SMCore 통신 포트입니다
 a| 
8145(HTTPS), 양방향, 사용자 지정 가능



 a| 
리포지토리 데이터베이스
 a| 
3306(HTTPS), 양방향



 a| 
Windows 플러그인 호스트
 a| 
135, 445(TCP)

135번 및 445번 포트 외에도 Microsoft에서 지정한 동적 포트 범위도 열려 있어야 합니다. 원격 설치 작업은 이 포트 범위를 동적으로 검색하는 WMI(Windows Management Instrumentation) 서비스를 사용합니다.

지원되는 동적 포트 범위에 대한 자세한 내용은 을 참조하십시오 https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Windows에 대한 서비스 개요 및 네트워크 포트 요구 사항"^].



 a| 
Windows용 SnapCenter 플러그인
 a| 
8145(HTTPS), 양방향, 사용자 지정 가능



 a| 
ONTAP 클러스터 또는 SVM 통신 포트
 a| 
443(HTTPS), 양방향, 80(HTTP), 양방향

이 포트는 SnapCenter 서버 호스트, 플러그인 호스트, SVM 또는 ONTAP 클러스터 간의 통신에 사용됩니다.

|===
* Microsoft SQL Server용 SnapCenter 플러그인 요구 사항 *

원격 호스트에 대한 로컬 로그인 권한이 있는 로컬 관리자 권한이 있는 사용자가 있어야 합니다. 클러스터 노드를 관리하는 경우 클러스터의 모든 노드에 대한 관리 권한이 있는 사용자가 필요합니다.

SQL Server에 대한 sysadmin 권한이 있는 사용자가 있어야 합니다. 플러그인은 Microsoft VDI 프레임워크를 사용하므로 sysadmin 액세스가 필요합니다.

Microsoft SQL Server용 SnapManager를 사용하고 있고 SnapManager for Microsoft SQL Server에서 SnapCenter로 데이터를 가져오려면 를 참조하십시오 link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["보관된 백업을 가져옵니다"^]



== SnapCenter 서버를 설치합니다

* SnapCenter 서버 * 를 다운로드하고 설치합니다

* 단계 *

. 에서 SnapCenter 서버 설치 패키지를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp Support 사이트"^] 그런 다음 exe를 두 번 클릭합니다.
+
설치를 시작한 후 모든 사전 점검을 수행하고 최소 요구사항을 충족하지 못할 경우 적절한 오류 또는 경고 메시지가 표시됩니다. 경고 메시지를 무시하고 설치를 진행할 수 있지만 오류를 수정해야 합니다.

. SnapCenter 서버 설치에 필요한 미리 채워진 값을 검토하고 필요한 경우 수정합니다.
+
MySQL Server 리포지토리 데이터베이스의 암호를 지정할 필요가 없습니다. SnapCenter 서버 설치 중에 암호는 자동으로 생성됩니다.

+

NOTE: 특수 문자 "%"는 설치를 위한 사용자 지정 경로에서 지원되지 않습니다. 경로에 "%"를 포함하면 설치가 실패합니다.

. 지금 설치 * 를 클릭합니다.


* SnapCenter에 로그인합니다 *

* 단계 *

. 호스트 바탕 화면의 바로 가기나 설치 시 제공된 URL(_\https://server:8146_ SnapCenter 서버가 설치된 기본 포트 8146의 경우 _\ )에서 SnapCenter를 시작합니다.
. 자격 증명을 입력합니다.
+
기본 제공 도메인 관리자 사용자 이름 형식의 경우, _NetBIOS\<사용자 이름>_ 또는 _<사용자 이름>@<도메인>_ 또는 _<도메인 FQDN>\<사용자 이름>_을 사용합니다.

+
기본 제공 로컬 관리자 사용자 이름 형식의 경우 _<사용자 이름>_을(를) 사용합니다.

. 로그인 * 을 클릭합니다.


* SnapCenter 표준 컨트롤러 기반 라이센스 추가 *

* 단계 *

. ONTAP 명령줄을 사용하여 컨트롤러에 로그인하고 다음을 입력합니다.
+
'System license add-license-code <license_key>'

. 라이센스를 확인합니다.
+
'라이선스 쇼'



* SnapCenter 용량 기반 라이센스 추가 *

* 단계 *

. SnapCenter GUI 왼쪽 창에서 * 설정 > 소프트웨어 * 를 클릭한 다음 라이센스 섹션에서 * + * 를 클릭합니다.
. 라이선스를 얻는 두 가지 방법 중 하나를 선택합니다.
+
** 라이센스를 가져오려면 NetApp Support 사이트 로그인 자격 증명을 입력하십시오.
** NetApp 라이센스 파일의 위치로 이동하여 * Open * 을 클릭합니다.


. 마법사의 알림 페이지에서 기본 용량 임계값인 90%를 사용합니다.
. 마침 * 을 클릭합니다.


* 스토리지 시스템 접속 설정 *

* 단계 *

. 왼쪽 창에서 * 스토리지 시스템 > 새로 만들기 * 를 클릭합니다.
. 스토리지 시스템 추가 페이지에서 다음을 수행합니다.
+
.. 스토리지 시스템의 이름 또는 IP 주소를 입력합니다.
.. 스토리지 시스템을 액세스하는 데 사용되는 자격 증명을 입력합니다.
.. 확인란을 선택하여 EMS(이벤트 관리 시스템) 및 AutoSupport를 활성화합니다.


. 플랫폼, 프로토콜, 포트 및 시간 초과에 할당된 기본값을 수정하려면 * 추가 옵션 * 을 클릭합니다.
. 제출 * 을 클릭합니다.




== Microsoft SQL Server용 플러그인을 설치합니다

* 자격 증명으로 실행 을 설정하고 Microsoft SQL Server*용 플러그인을 설치합니다

* 단계 *

. 왼쪽 창에서 * 설정 > 자격 증명 > 새로 만들기 * 를 클릭합니다.
. 자격 증명을 입력합니다.
+
기본 제공 도메인 관리자 사용자 이름 형식의 경우, _NetBIOS\<사용자 이름>_ 또는 _<사용자 이름>@<도메인>_ 또는 _<도메인 FQDN>\<사용자 이름>_을 사용합니다.

+
기본 제공 로컬 관리자 사용자 이름 형식의 경우 _<사용자 이름>_을(를) 사용합니다.



* 호스트를 추가하고 Microsoft SQL Server*용 플러그인을 설치합니다

* 단계 *

. SnapCenter GUI 왼쪽 창에서 * 호스트 > 관리 호스트 > 추가 * 를 클릭합니다.
. 마법사의 호스트 페이지에서 다음을 수행합니다.
+
.. 호스트 유형: Windows 호스트 유형을 선택합니다.
.. 호스트 이름: SQL 호스트를 사용하거나 전용 Windows 호스트의 FQDN을 지정합니다.
.. 자격 증명: 생성한 호스트의 유효한 자격 증명 이름을 선택하거나 새 자격 증명을 생성합니다.


. 설치할 플러그인 선택 섹션에서 * Microsoft SQL Server * 를 선택합니다.
. 다음 세부 정보를 지정하려면 * 추가 옵션 * 을 클릭합니다.
+
.. 포트: 기본 포트 번호를 유지하거나 포트 번호를 지정합니다.
.. 설치 경로: 기본 경로는 _C:\Program Files\NetApp\SnapCenter_입니다. 선택적으로 경로를 사용자 지정할 수 있습니다.
.. 클러스터에 모든 호스트 추가: WSFC에서 SQL을 사용하는 경우 이 확인란을 선택합니다.
.. 사전 설치 검사 건너뛰기: 플러그인을 수동으로 이미 설치했거나 호스트가 플러그인 설치 요구 사항을 충족하는지 확인하지 않으려면 이 확인란을 선택합니다.


. 제출 * 을 클릭합니다.

