---
permalink: protect-scsql/quick-start-to-prepare-for-snapcenter-plug-in-install-for-sql-server.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter 서버 및 Microsoft SQL Server용 SnapCenter 플러그인 설치 준비에 대한 지침을 제공합니다. 
---
= SnapCenter 서버 및 플러그인 설치 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버 및 Microsoft SQL Server용 SnapCenter 플러그인 설치를 위한 준비 지침의 요약 세트를 제공합니다.



== 도메인 및 작업 그룹 요구 사항

SnapCenter 서버는 도메인 또는 작업 그룹에 있는 시스템에 설치할 수 있습니다.

Active Directory 도메인을 사용하는 경우 로컬 관리자 권한이 있는 도메인 사용자를 사용해야 합니다. 도메인 사용자는 Windows 호스트에 있는 로컬 관리자 그룹의 구성원이어야 합니다.

작업 그룹을 사용하는 경우 로컬 관리자 권한이 있는 로컬 계정을 사용해야 합니다.



== 라이센스 요구 사항

설치하는 라이센스 유형은 환경에 따라 다릅니다.

[cols="1,3"]
|===
| 라이센스 | 필요한 경우 


 a| 
SnapCenter 표준 컨트롤러 기반
 a| 
FAS 또는 AFF 스토리지 컨트롤러에 필요합니다

SnapCenter 표준 라이센스는 컨트롤러 기반 라이센스이며 프리미엄 번들의 일부로 포함됩니다. SnapManager 제품군 라이센스가 있는 경우 SnapCenter 표준 라이센스 사용 권한도 제공됩니다. FAS 또는 AFF 스토리지를 사용하여 평가판을 통해 SnapCenter를 설치하려면 세일즈 담당자에게 연락하여 프리미엄 번들 평가 라이센스를 받으십시오.



 a| 
SnapMirror 또는 SnapVault
 a| 
ONTAP

SnapCenter에서 복제를 사용하는 경우 SnapMirror 또는 SnapVault 라이센스가 필요합니다.



 a| 
추가 라이센스(선택 사항)
 a| 
을 참조하십시오 link:../install/concept_snapcenter_licenses.html["SnapCenter 라이센스"^].



 a| 
SnapCenter 표준 라이센스(선택 사항)
 a| 
보조 대상


NOTE: SnapCenter 표준 라이센스를 보조 대상에 추가하는 것이 좋지만 필수는 아닙니다. 보조 대상에서 SnapCenter 표준 라이센스가 활성화되어 있지 않으면 페일오버 작업을 수행한 후 SnapCenter를 사용하여 보조 대상의 리소스를 백업할 수 없습니다. 그러나 복제 및 검증 작업을 수행하려면 보조 대상에 FlexClone 라이센스가 필요합니다.

|===


== 호스트 및 포트 요구 사항

ONTAP 및 애플리케이션 플러그인 최소 요구 사항은 을 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=117008;&solution=1259&isHWU&src=IMT["상호 운용성 매트릭스 툴"^].

[cols="1,3"]
|===
| 호스트 | 최소 요구 사항 


 a| 
운영 체제(64비트)
 a| 
을 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=117008;&solution=1259&isHWU&src=IMT["상호 운용성 매트릭스 툴"^]



 a| 
CPU
 a| 
* 서버 호스트: 4코어
* 플러그인 호스트: 4코어




 a| 
RAM
 a| 
* 서버 호스트: 8GB
* 플러그인 호스트: 4 GB




 a| 
하드 드라이브 공간
 a| 
서버 호스트:

* SnapCenter 서버 소프트웨어 및 로그용 7 GB
* SnapCenter 리포지토리의 경우 8 GB
* 각 플러그인 호스트: 플러그인 설치 및 로그의 경우 2GB, 전용 호스트에 플러그인이 설치된 경우에만 필요합니다.




 a| 
타사 라이브러리
 a| 
SnapCenter 서버 호스트 및 플러그인 호스트에 필요:

* Microsoft .NET Framework 4.7.2 이상
* ASP를 참조하십시오. NET 코어 호스팅 번들(8.0.5 이상)
* PowerShell 7.4.2 이상




 a| 
브라우저
 a| 
Chrome, Internet Explorer 및 Microsoft Edge

|===
[cols="1,3"]
|===
| 포트 유형입니다 | 기본 포트입니다 


 a| 
SnapCenter 포트
 a| 
8146(HTTPS), 양방향, 사용자 지정 가능(URL_\https://server:8146_)



 a| 
SnapCenter SMCore 통신 포트입니다
 a| 
8145(HTTPS), 양방향, 사용자 지정 가능



 a| 
리포지토리 데이터베이스
 a| 
3306(HTTPS), 양방향



 a| 
Windows 플러그인 호스트
 a| 
135, 445(TCP)

135번 및 445번 포트 외에도 Microsoft에서 지정한 동적 포트 범위도 열려 있어야 합니다. 원격 설치 작업은 이 포트 범위를 동적으로 검색하는 WMI(Windows Management Instrumentation) 서비스를 사용합니다.

지원되는 동적 포트 범위에 대한 자세한 내용은 을 참조하십시오 https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements["Windows에 대한 서비스 개요 및 네트워크 포트 요구 사항"^].



 a| 
Windows용 SnapCenter 플러그인
 a| 
8145(HTTPS), 양방향, 사용자 지정 가능



 a| 
ONTAP 클러스터 또는 SVM 통신 포트
 a| 
443(HTTPS), 양방향, 80(HTTP), 양방향

이 포트는 SnapCenter 서버 호스트, 플러그인 호스트, SVM 또는 ONTAP 클러스터 간의 통신에 사용됩니다.

|===


== Microsoft SQL Server용 SnapCenter 플러그인 요구 사항

원격 호스트에 대한 로컬 로그인 권한이 있는 로컬 관리자 권한이 있는 사용자가 있어야 합니다. 클러스터 노드를 관리하는 경우 클러스터의 모든 노드에 대한 관리 권한이 있는 사용자가 필요합니다.

SQL Server에 대한 sysadmin 권한이 있는 사용자가 있어야 합니다. 플러그인은 Microsoft VDI 프레임워크를 사용하므로 sysadmin 액세스가 필요합니다.

Microsoft SQL Server용 SnapManager를 사용하고 있고 SnapManager for Microsoft SQL Server에서 SnapCenter로 데이터를 가져오려면 를 참조하십시오 link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html["보관된 백업을 가져옵니다"^]
