---
permalink: protect-scsql/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_microsoft_sql_server.html 
sidebar: sidebar 
keywords: credentials 
summary: 호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다. 
---
= 사전 요구 사항 - 호스트를 추가하고 Microsoft SQL Server용 SnapCenter 플러그인을 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다.

* iSCSI를 사용하는 경우 iSCSI 서비스가 실행 중이어야 합니다.
* 원격 호스트에 대한 로컬 로그인 권한이 있는 로컬 관리자 권한이 있는 사용자가 있어야 합니다.
* SnapCenter에서 클러스터 노드를 관리하는 경우 클러스터의 모든 노드에 대한 관리 권한이 있는 사용자가 있어야 합니다.
* SQL Server에 대한 sysadmin 권한이 있는 사용자가 있어야 합니다.
+
Microsoft SQL Server용 SnapCenter 플러그인은 Microsoft VDI 프레임워크를 사용하므로 sysadmin 액세스가 필요합니다.

+
http://support.microsoft.com/kb/2926557/["Microsoft 지원 문서 2926557: SQL Server VDI 백업 및 복원 작업에는 sysadmin 권한이 필요합니다"]

* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자의 경우 호스트에서 UAC를 비활성화해야 합니다.
* SnapManager for Microsoft SQL Server가 설치된 경우 서비스 및 일정을 중지하거나 사용하지 않아야 합니다.
+
백업 또는 클론 작업을 SnapCenter로 가져오려는 경우 SnapManager for Microsoft SQL Server를 제거하지 마십시오.

* 호스트는 서버에서 FQDN(정규화된 도메인 이름)으로 확인할 수 있어야 합니다.
+
호스트 파일을 확인할 수 있도록 수정하고 호스트 파일에 짧은 이름과 FQDN이 모두 지정된 경우 SnapCenter hosts 파일에 <IP_address><host_FQDN><host_name> 형식으로 항목을 생성합니다


