---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html 
sidebar: sidebar 
keywords:  
summary: 'Microsoft Windows용 SnapCenter 플러그인을 사용하여 NetApp 스토리지 시스템을 프로비저닝한 후에는 SnapCenter 그래픽 사용자 인터페이스(GUI\) 또는 PowerShell cmdlet을 사용하여 리소스를 NetApp 스토리지 시스템이나 NetApp LUN 간에 마이그레이션할 수 있습니다.' 
---
= 리소스를 NetApp 스토리지 시스템으로 마이그레이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Microsoft Windows용 SnapCenter 플러그인을 사용하여 NetApp 스토리지 시스템을 프로비저닝한 후에는 SnapCenter 그래픽 사용자 인터페이스(GUI) 또는 PowerShell cmdlet을 사용하여 리소스를 NetApp 스토리지 시스템이나 NetApp LUN 간에 마이그레이션할 수 있습니다.

* 필요한 것 *

* SnapCenter 서버에 스토리지 시스템을 추가해야 합니다.
* SQL Server 리소스를 새로 고친(검색된) 상태여야 합니다.


이 마법사 페이지의 대부분의 필드는 설명이 필요 없습니다. 다음 정보는 안내가 필요할 수 있는 일부 필드에 대해 설명합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지의 * 보기 * 드롭다운 목록에서 * 데이터베이스 * 또는 * 인스턴스 * 를 선택합니다.
. 목록에서 데이터베이스 또는 인스턴스를 선택하고 * migrate * 를 클릭합니다.
. 리소스 페이지에서 다음 작업을 수행합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
* 데이터베이스 이름 * (선택 사항)
 a| 
마이그레이션할 인스턴스를 선택한 경우 * Databases * 드롭다운 목록에서 해당 인스턴스의 데이터베이스를 선택해야 합니다.



 a| 
* 목적지 선택 *
 a| 
데이터 및 로그 파일의 타겟 위치를 선택합니다.

데이터 및 로그 파일은 선택한 NetApp 드라이브 아래에 각각 Data 및 Log 폴더로 이동됩니다. 폴더 구조에 폴더가 없으면 폴더가 만들어지고 리소스가 마이그레이션됩니다.



 a| 
* 데이터베이스 파일 세부 정보 표시 * (선택 사항)
 a| 
단일 데이터베이스의 여러 파일을 마이그레이션하려는 경우 이 옵션을 선택합니다.


NOTE: 인스턴스 * 리소스를 선택하면 이 옵션이 표시되지 않습니다.



 a| 
* 옵션 *
 a| 
소스에서 데이터베이스 복사본을 삭제하려면 * Delete copy of Migrated Database at Original Location * 을 선택합니다.

선택 사항: * 데이터베이스를 분리하기 전에 테이블에 대한 업데이트 통계를 실행합니다 *.

|===
. 확인 페이지에서 다음 작업을 수행합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
* 데이터베이스 일관성 검사 옵션 *
 a| 
마이그레이션 전에 데이터베이스의 무결성을 확인하려면 * Run Before * 를 선택합니다. 마이그레이션 후 데이터베이스의 무결성을 확인하려면 * Run After * 를 선택합니다.



 a| 
* DBCC CHECKDB 옵션 *
 a| 
** 무결성 검사를 데이터베이스의 물리적 구조로 제한하고 데이터베이스에 영향을 미치는 찢어진 페이지, 체크섬 오류 및 일반적인 하드웨어 오류를 감지하려면 * physical_only * 옵션을 선택합니다.
** 모든 정보 메시지를 표시하지 않으려면 * no_INFOMSGS * 옵션을 선택합니다.
** All_ERRORMSGS * 옵션을 선택하여 객체별로 보고된 모든 오류를 표시합니다.
** 클러스터링되지 않은 인덱스를 선택하지 않으려면 * NOINDEX * 옵션을 선택합니다.
+
SQL Server 데이터베이스는 DBCC(Microsoft SQL Server Database Consistency Checker)를 사용하여 데이터베이스 개체의 논리적 무결성 및 물리적 무결성을 검사합니다.

+

NOTE: 이 옵션을 선택하면 실행 시간이 줄어들 수 있습니다.

** 내부 데이터베이스 스냅샷 복사본을 사용하는 대신** TABLOCK** 옵션을 선택하여 검사를 제한하고 잠금을 확보합니다.


|===
. 요약을 검토한 다음 ** 마침**을 클릭합니다.

