---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter를 사용하면 리소스 그룹 또는 데이터베이스에서 클론을 생성할 수 있습니다. 필요 시 클론을 수행하거나 리소스 그룹 또는 데이터베이스의 반복적인 클론 작업을 예약할 수 있습니다. 주기적으로 백업을 클론하는 경우 클론을 사용하여 애플리케이션을 개발하거나 데이터를 채우거나 데이터를 복구할 수 있습니다. 
---
= 클론 수명주기 수행
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하면 리소스 그룹 또는 데이터베이스에서 클론을 생성할 수 있습니다. 필요 시 클론을 수행하거나 리소스 그룹 또는 데이터베이스의 반복적인 클론 작업을 예약할 수 있습니다. 주기적으로 백업을 클론하는 경우 클론을 사용하여 애플리케이션을 개발하거나 데이터를 채우거나 데이터를 복구할 수 있습니다.

SnapCenter를 사용하면 여러 서버에서 동시에 여러 클론 작업을 실행하도록 예약할 수 있습니다.

* 필요한 것 *

* 독립 실행형 데이터베이스 인스턴스에 클론을 생성하는 동안 마운트 지점 경로가 있고 전용 디스크인지 확인합니다.
* FCI(장애 조치 클러스터 인스턴스)에 클론을 생성하는 동안 마운트 지점이 존재하고, 공유 디스크이며, 경로와 FCI가 동일한 SQL 리소스 그룹에 속해야 합니다.
* 소스 데이터베이스 또는 타겟 인스턴스가 클러스터 공유 볼륨(CSV)에 있으면 복제된 데이터베이스가 CSV에 있게 됩니다.



NOTE: 가상 환경(VMDK/RDM)의 경우 마운트 지점이 전용 디스크인지 확인합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지의 * 보기 * 목록에서 * 데이터베이스 * 또는 * 리소스 그룹 * 을 선택합니다.
. 리소스 그룹 또는 데이터베이스를 선택한 다음 * Clone Lifecycle * 을 클릭합니다.
. 옵션 페이지에서 다음 작업을 수행합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
클론 작업 이름입니다
 a| 
클론 라이프사이클 작업을 모니터링하고 수정하는 데 도움이 되는 클론 라이프사이클 작업 이름을 지정합니다.



 a| 
클론 서버
 a| 
클론을 배치할 호스트를 선택합니다.



 a| 
클론 인스턴스
 a| 
데이터베이스를 복제할 클론 인스턴스를 선택합니다. 이 SQL 인스턴스는 지정된 클론 서버에 있어야 합니다.



 a| 
접미사 복제
 a| 
클론 데이터베이스에 추가될 접미사를 입력하여 해당 접미사가 클론임을 나타냅니다. 클론 리소스 그룹을 생성하는 데 사용되는 각 SQL 인스턴스에는 고유한 데이터베이스 이름이 있어야 합니다. 예를 들어, 클론 리소스 그룹에 SQL 인스턴스 인스턴스 인스턴스 "inst1"의 소스 데이터베이스 "dB1"이 포함되어 있고 "dB1"이 "inst1"로 복제되는 경우 클론 데이터베이스 이름은 "dB1__clone"이어야 합니다. "__clone""은 데이터베이스가 동일한 인스턴스에 복제되기 때문에 필수 사용자 정의 접미부입니다. "dB1"이 SQL 인스턴스 "inst2"에 복제되면 데이터베이스가 다른 인스턴스로 복제되므로 클론 데이터베이스 이름은 "dB1"(접미사는 선택 사항)으로 유지될 수 있습니다.



 a| 
마운트 지점을 자동으로 할당하거나 경로 아래에 볼륨 마운트 지점을 자동으로 할당합니다
 a| 
경로 아래에 마운트 지점 또는 볼륨 마운트 지점을 자동으로 할당할지 여부를 선택합니다. 경로 아래에 있는 볼륨 마운트 지점을 자동 할당하도록 선택하면 특정 디렉토리를 제공할 수 있습니다. 마운트 지점은 해당 디렉토리 내에 생성됩니다. 이 옵션을 선택하기 전에 디렉토리가 비어 있는지 확인해야 합니다. 디렉토리에 데이터베이스가 있으면 마운트 작업 후 데이터베이스가 잘못된 상태가 됩니다.

|===
. Location 페이지에서 클론을 생성할 스토리지 위치를 선택합니다.
. 스크립트 페이지에서 복제 작업 전후에 실행해야 하는 처방인 또는 PS의 경로와 인수를 각각 입력합니다.
+
예를 들어, 스크립트를 실행하여 SNMP 트랩을 업데이트하고, 경고를 자동화하고, 로그를 보내는 등의 작업을 수행할 수 있습니다.

+
기본 스크립트 시간 초과는 60초입니다.

. 스케줄 페이지에서 다음 작업 중 하나를 수행합니다.
+
** 클론 작업을 즉시 실행하려면 * 지금 실행 * 을 선택합니다.
** 클론 작업이 수행되는 빈도, 클론 스케줄이 시작되는 시간, 클론 작업이 발생하는 날짜, 스케줄이 만료되는 날짜 및 스케줄이 만료된 후에 클론을 삭제해야 하는지 여부를 결정하려면 * Configure schedule * 을 선택합니다.


. 알림 페이지의 * 이메일 기본 설정 * 드롭다운 목록에서 이메일을 보낼 시나리오를 선택합니다.
+
또한 보낸 사람 및 받는 사람 전자 메일 주소와 전자 메일의 제목도 지정해야 합니다. 수행된 클론 작업의 보고서를 첨부하려면 * 작업 보고서 연결 * 을 선택합니다.

+

NOTE: 이메일 알림의 경우 GUI 또는 PowerShell 명령 Set-SmtpServer를 사용하여 SMTP 서버 세부 정보를 지정해야 합니다.

+
EMS의 경우 를 참조할 수 있습니다 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection.html["EMS Data 수집 관리"]

. 요약을 검토하고 * Finish * 를 클릭합니다.


모니터 * > * 작업 * 페이지를 사용하여 복제 프로세스를 모니터링해야 합니다.
