---
permalink: protect-scsql/task_define_a_clone_strategy_for_sql_server.html 
sidebar: sidebar 
keywords:  
summary: 클론 복제 전략을 정의하면 데이터베이스를 성공적으로 복제할 수 있습니다. 
---
= SQL Server에 대한 클론 생성 전략을 정의합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클론 복제 전략을 정의하면 데이터베이스를 성공적으로 복제할 수 있습니다.

. 클론 작업과 관련된 제한 사항을 검토합니다.
. 필요한 클론 유형을 결정합니다.




== 클론 작업의 제한 사항

데이터베이스를 클론 복제하기 전에 클론 작업의 제한 사항을 숙지해야 합니다.

* 11.2.0.4 ~ 12.1.0.1의 Oracle 버전을 사용하는 경우 _renamedg_ 명령을 실행하면 클론 작업이 멈춤 상태가 됩니다. Oracle 패치 19544733을 적용하여 이 문제를 해결할 수 있습니다.
* 호스트에 직접 연결된 LUN(예: Windows 호스트의 Microsoft iSCSI Initiator 사용)에서 동일한 Windows 호스트의 VMDK 또는 RDM LUN에 또는 다른 Windows 호스트의 RDM LUN에 대한 데이터베이스 클론 생성은 지원되지 않습니다.
* 볼륨 마운트 지점의 루트 디렉토리는 공유 디렉토리일 수 없습니다.
* 클론이 포함된 LUN을 새 볼륨으로 이동하면 클론을 삭제할 수 없습니다.




== 클론 작업의 유형입니다

SnapCenter를 사용하여 SQL Server 데이터베이스 백업 또는 운영 데이터베이스를 복제할 수 있습니다.

* 데이터베이스 백업에서 복제합니다
+
복제된 데이터베이스는 새 응용 프로그램 개발을 위한 기준 역할을 할 수 있으며 프로덕션 환경에서 발생하는 응용 프로그램 오류를 격리하는 데 도움이 됩니다. 또한 소프트 데이터베이스 오류로부터 복구하는 데 클론 생성된 데이터베이스를 사용할 수 있습니다.

* 클론 라이프사이클
+
SnapCenter를 사용하여 운영 데이터베이스가 사용 중이 아닐 때 발생하는 반복 클론 작업을 예약할 수 있습니다.


