---
permalink: protect-scsql/task_import_archived_backups.html 
sidebar: sidebar 
keywords: SnapVault 
summary: SnapCenter 기술을 사용하여 SnapVault for Microsoft SQL Server에서 SnapManager로 아카이빙된 백업만 명령줄 인터페이스에서 가져올 수 있습니다. 
---
= 보관된 백업을 가져옵니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 기술을 사용하여 SnapVault for Microsoft SQL Server에서 SnapManager로 아카이빙된 백업만 명령줄 인터페이스에서 가져올 수 있습니다.

* 필요한 것 *

* Microsoft SQL Server용 SnapCenter 플러그인과 Microsoft SQL Server 7.x용 SnapManager가 모두 동일한 호스트에 설치되어 있어야 합니다.
* 클러스터를 지원하려면 플러그인의 두 제품과 7.x 제품이 모두 클러스터의 각 노드에 설치되어 있어야 합니다.
* 호스트 또는 클러스터를 SnapCenter에 추가하고 호스트 또는 클러스터에서 백업에 사용할 수 있는 리소스를 검색한 상태여야 합니다.
* Microsoft SQL Server용 SnapManager SnapInfo 폴더를 백업해야 합니다.
+
가져오기 작업이 실패하면 SnapInfo 디렉토리에서 백업 메타데이터를 검색할 수 있습니다.



|===


 a| 
* 모범 사례: * Microsoft SQL Server용 SnapCenter 플러그인의 로그 백업 폴더를 구성하는 것이 가장 좋습니다.

|===
SnapCenter 설치 및 구성 작업에 대한 자세한 내용은 SnapCenter 설치 정보를 참조하십시오. Microsoft SQL Server 설치 및 구성 작업에 대한 SnapManager에 대한 자세한 내용은 SnapManager 설치 정보를 참조하십시오.

아카이빙된 백업을 SnapManager for Microsoft SQL Server에서 SnapCenter로 가져온 후에는 SnapCenter에서 이러한 백업에 대해 복원 및 클론 작업을 수행할 수 있습니다. 동시에 SnapManager for Microsoft SQL Server를 사용하여 백업, 복원 및 클론 작업을 계속 수행할 수도 있습니다.

* 단계 *

. SnapCenter에서 Microsoft SQL Server 일정에 대한 SnapManager와 유사한 스케줄을 수동으로 생성하려면 다음 단계를 수행하십시오.
+
.. Get-SmSchedule cmdlet을 사용하여 Microsoft SQL Server용 SnapManager에서 일정 정보를 검색합니다.
.. 일정 정보를 저장합니다.
+
SnapCenter에서 정책을 만드는 동안 이 일정 정보를 사용할 수 있습니다.

.. 'Get-SmSchedule-Hostname>-PluginCode SMSQL-DisableCurrentGenSchedule' cmdlet을 사용하여 Microsoft SQL Server 일정에 대한 SnapManager를 비활성화합니다.


. Invoke-SmBackupMigration cmdlet을 사용하여 아카이빙된 백업을 가져옵니다.
+
예를 들어 독립 실행형 SQL 호스트를 마이그레이션하려면: "Invoke-SmBackupMigration-Hostname<hostname>"""- PluginCode SMSQL"을 사용합니다

+
예를 들어 클러스터 호스트를 마이그레이션하려면 'Invoke-SmBackupMigration-Hostname<clustername>'-PluginCode SMSQL을 사용합니다


