---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html 
sidebar: sidebar 
keywords: credentials 
summary: SnapCenter는 자격 증명을 사용하여 SnapCenter 작업을 위해 사용자를 인증합니다. 데이터베이스 또는 Windows 파일 시스템에서 데이터 보호 작업을 수행하려면 SnapCenter 플러그인 설치를 위한 자격 증명과 추가 자격 증명을 만들어야 합니다. 
---
= Windows용 SnapCenter 플러그인 패키지에 대한 자격 증명을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter는 자격 증명을 사용하여 SnapCenter 작업을 위해 사용자를 인증합니다. 데이터베이스 또는 Windows 파일 시스템에서 데이터 보호 작업을 수행하려면 SnapCenter 플러그인 설치를 위한 자격 증명과 추가 자격 증명을 만들어야 합니다.

* 필요한 것 *

* 플러그인을 설치하기 전에 Windows 자격 증명을 설정해야 합니다.
* 원격 호스트에 대한 관리자 권한을 포함하여 관리자 권한으로 자격 증명을 설정해야 합니다.
* Windows 호스트에서 SQL 인증
+
플러그인을 설치한 후 SQL 자격 증명을 설정해야 합니다.

+
Microsoft SQL Server용 SnapCenter 플러그인을 배포하는 경우 플러그인을 설치한 후 SQL 자격 증명을 설정해야 합니다. SQL Server sysadmin 권한이 있는 사용자의 자격 증명을 설정합니다.

+
SQL 인증 메서드는 SQL Server 인스턴스에 대해 인증합니다. 즉, SnapCenter에서 SQL Server 인스턴스를 검색한 다음 따라서 SQL 자격 증명을 추가하기 전에 호스트를 추가하고 플러그인 패키지를 설치하고 리소스를 새로 고쳐야 합니다. 리소스 예약 또는 검색 등의 작업을 수행하려면 SQL Server 인증이 필요합니다.



* 단계 *

. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 자격 증명 * 을 클릭합니다.
. 새로 만들기 * 를 클릭합니다.
. 자격 증명 페이지에서 자격 증명 구성에 필요한 정보를 지정합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
자격 증명 이름입니다
 a| 
자격 증명의 이름을 입력합니다.



 a| 
사용자 이름/암호
 a| 
인증에 사용할 사용자 이름과 암호를 입력합니다.

** 도메인 관리자
+
SnapCenter 플러그인을 설치할 시스템에 도메인 관리자를 지정합니다. 사용자 이름 필드에 유효한 형식은 다음과 같습니다.

+
*** 'NetBIOS\사용자 이름'
*** Domain FQDN\username'입니다


** 로컬 관리자(작업 그룹에만 해당)
+
작업 그룹에 속한 시스템의 경우 SnapCenter 플러그인을 설치할 시스템에 기본 제공 로컬 관리자를 지정합니다. 사용자 계정에 상승된 권한이 있거나 호스트 시스템에서 사용자 액세스 제어 기능이 비활성화된 경우 로컬 관리자 그룹에 속하는 로컬 사용자 계정을 지정할 수 있습니다. 사용자 이름 필드의 올바른 형식은 '사용자 이름'입니다

+
암호에 큰따옴표(") 또는 백틱(')을 사용하지 마십시오. 보다 작음(<) 및 느낌표(!)를 사용해서는 안 됩니다. 암호를 사용한 기호. 예를 들어 LessThan <!10, Lessthan10 <!, backtick'12.





 a| 
인증 모드
 a| 
사용할 인증 모드를 선택합니다. SQL 인증 모드를 선택하는 경우 SQL 서버 인스턴스와 SQL 인스턴스가 있는 호스트도 지정해야 합니다.

|===
. 확인 * 을 클릭합니다.


자격 증명 설정을 마친 후 사용자 및 액세스 페이지의 사용자 또는 사용자 그룹에 자격 증명 유지 관리를 할당할 수 있습니다.
