---
permalink: protect-sco/alternate-ways-install-plug-in-linux-aix.html 
sidebar: sidebar 
keywords: alternate methods, install, plug-ins package, linux, aix, remote hosts, cmdlets, cluster host, silent mode, console mode 
summary: 다른 대체 방법을 사용하여 Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치할 수 있습니다. 
---
= Linux 또는 AIX용 플러그인 패키지를 설치하는 다른 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== cmdlet을 사용하여 여러 원격 호스트에 설치합니다

여러 호스트에 Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치하려면 _Install-SmHostPackage_PowerShell cmdlet을 사용해야 합니다.

* 필요한 것 *

플러그인 패키지를 설치하려는 각 호스트에 대한 로컬 관리자 권한이 있는 도메인 사용자로 SnapCenter에 로그인해야 합니다.

* 단계 *

. PowerShell을 실행합니다.
. SnapCenter 서버 호스트에서 _Open-SmConnection_cmdlet을 사용하여 세션을 설정한 다음 자격 증명을 입력합니다.
. _Install-SmHostPackage_cmdlet 및 필수 매개 변수를 사용하여 Linux 또는 AIX용 SnapCenter 플러그인 패키지용 SnapCenter 플러그인 패키지를 설치합니다.
+
플러그인을 이미 수동으로 설치했고 호스트가 플러그인을 설치하는 데 필요한 요구 사항을 충족하는지 여부를 확인하지 않으려는 경우 _-skipprecheck_옵션을 사용할 수 있습니다.

+

NOTE: 사전 확인 스크립트는 방화벽 거부 규칙에 지정된 플러그인 포트 방화벽 상태의 유효성을 검사하지 않습니다.

. 원격 설치를 위한 자격 증명을 입력합니다.


cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2880726["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].



== 클러스터 호스트에 설치합니다

클러스터 호스트의 두 노드에 Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치해야 합니다.

클러스터 호스트의 각 노드에는 2개의 IP가 있습니다. IP 중 하나는 각 노드의 공용 IP이고, 두 번째 IP는 두 노드 간에 공유되는 클러스터 IP입니다.

* 단계 *

. 클러스터 호스트의 두 노드에 Linux용 SnapCenter 플러그인 패키지 또는 AIX용 SnapCenter 플러그인 패키지를 설치합니다.
. SNAPCENTER_SERVER_HOST, SPL_PORT, SNAPCENTER_SERVER_PORT 및 SPL_ENABLED_PACGISLICATIONES 매개변수에 대한 올바른 값이 _/var/opt/snapcenter/SPL/etc/_에 있는 spl.properties 파일에 지정되어 있는지 확인합니다.
+
SPL_ENABLED_PACNEWNES가 spl.properties 에 지정되지 않은 경우 이를 추가하고 SCO, SCU 값을 할당할 수 있습니다.

. SnapCenter 서버 호스트에서 _Open-SmConnection_cmdlet을 사용하여 세션을 설정한 다음 자격 증명을 입력합니다.
. 각 노드에서 _Set-PreferredHostIPsInStorageExportPolicy_sccli 명령과 필요한 매개 변수를 사용하여 노드의 기본 설정 IP를 설정합니다.
. SnapCenter 서버 호스트에서 클러스터 IP에 대한 항목과 해당 DNS 이름을 _C:\Windows\System32\drivers\etc\hosts_에 추가합니다.
. 호스트 이름에 대한 클러스터 IP를 지정하여 _Add-SmHost_cmdlet을 사용하여 SnapCenter 서버에 노드를 추가합니다.


노드 1에서 Oracle 데이터베이스를 검색하고(클러스터 IP가 노드 1에서 호스팅된다고 가정) 데이터베이스의 백업을 생성합니다. 페일오버가 발생하면 노드 1에서 생성된 백업을 사용하여 노드 2에서 데이터베이스를 복원할 수 있습니다. 노드 1에 생성된 백업을 사용하여 노드 2에 클론을 생성할 수도 있습니다.


NOTE: 다른 SnapCenter 작업이 실행 중인 동안 페일오버가 발생하면 오래된 볼륨, 디렉토리 및 잠금 파일이 있습니다.



== Linux용 플러그인 패키지를 자동 모드 또는 콘솔 모드로 설치합니다

CLI(명령줄 인터페이스)를 사용하여 콘솔 모드 또는 자동 모드에서 Linux용 SnapCenter 플러그인 패키지를 설치할 수 있습니다.

* 필요한 것 *

* 플러그인 패키지를 설치하기 위한 사전 요구 사항을 검토해야 합니다.
* 디스플레이 환경 변수가 설정되어 있지 않은지 확인해야 합니다.
+
디스플레이 환경 변수가 설정된 경우 설정되지 않은 디스플레이를 실행한 다음 플러그인을 수동으로 설치해야 합니다.



* 이 작업에 대한 정보 *

콘솔 모드로 설치하는 동안 필요한 설치 정보를 제공해야 하지만 자동 모드 설치에서는 설치 정보를 제공할 필요가 없습니다.

* 단계 *

. SnapCenter 서버 설치 위치에서 Linux용 SnapCenter 플러그인 패키지를 다운로드합니다.
+
기본 설치 경로는 _C:\ProgramData\NetApp\SnapCenter\PackageRepository_입니다. 이 경로는 SnapCenter 서버가 설치된 호스트에서 액세스할 수 있습니다.

. 명령 프롬프트에서 설치 파일을 다운로드한 디렉토리로 이동합니다.
. 기본 설치 모드에 따라 다음 단계 중 하나를 수행합니다.
+
|===
| 설치 모드 | 단계 


 a| 
콘솔 모드
 a| 
.. 실행:
+
'./SnapCenter_linux_host_plugin.bin – i console'

.. 화면의 지시에 따라 설치를 완료합니다.




 a| 
자동 모드
 a| 
실행:

'./SnapCenter_Linux_HOST_PLUGIN.BIN-I Silent-dport=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/OPT/CUSTOM_PATH'

|===
. spL_enabled_plugins=SCO, SCU를 추가한 다음 SnapCenter 플러그인 로더 서비스를 다시 시작하려면 _/var/opt/snapcenter/spl/etc/_에 있는 spl.properties 파일을 편집합니다.



IMPORTANT: 플러그인 패키지를 설치하면 SnapCenter 서버가 아닌 호스트에 플러그인이 등록됩니다. SnapCenter GUI 또는 PowerShell cmdlet을 사용하여 호스트를 추가하여 SnapCenter 서버에 플러그인을 등록해야 합니다. 호스트를 추가하는 동안 자격 증명으로 "없음"을 선택합니다. 호스트가 추가되면 설치된 플러그인이 자동으로 검색됩니다.



== AIX용 플러그인 패키지를 자동 모드로 설치합니다

CLI(명령줄 인터페이스)를 사용하여 AIX용 SnapCenter 플러그인 패키지를 자동 모드로 설치할 수 있습니다.

* 필요한 것 *

* 플러그인 패키지를 설치하기 위한 사전 요구 사항을 검토해야 합니다.
* 디스플레이 환경 변수가 설정되어 있지 않은지 확인해야 합니다.
+
디스플레이 환경 변수가 설정된 경우 설정되지 않은 디스플레이를 실행한 다음 플러그인을 수동으로 설치해야 합니다.



* 단계 *

. SnapCenter 서버 설치 위치에서 AIX용 SnapCenter 플러그인 패키지를 다운로드합니다.
+
기본 설치 경로는 _C:\ProgramData\NetApp\SnapCenter\PackageRepository_입니다. 이 경로는 SnapCenter 서버가 설치된 호스트에서 액세스할 수 있습니다.

. 명령 프롬프트에서 설치 파일을 다운로드한 디렉토리로 이동합니다.
. 실행
+
'./snapcenter_aix_host_plugin.bsx-i silent-dport=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR=/OPT/CUSTOM_PATH-DIL_LOG_NAME=DIS_USER_USER_CHOSPL_USER.USER_USER_USER_USER_USER_USER_USER_USER_USER.USER.USER_OSPL_USER_USER_USER.USER_USER_USER_USER_USER_USER_USER_USER_

. spL_enabled_plugins=SCO, SCU를 추가한 다음 SnapCenter 플러그인 로더 서비스를 다시 시작하려면 _/var/opt/snapcenter/spl/etc/_에 있는 spl.properties 파일을 편집합니다.



IMPORTANT: 플러그인 패키지를 설치하면 SnapCenter 서버가 아닌 호스트에 플러그인이 등록됩니다. SnapCenter GUI 또는 PowerShell cmdlet을 사용하여 호스트를 추가하여 SnapCenter 서버에 플러그인을 등록해야 합니다. 호스트를 추가하는 동안 자격 증명으로 "없음"을 선택합니다. 호스트가 추가되면 설치된 플러그인이 자동으로 검색됩니다.
