---
permalink: protect-sco/concept_prepare_for_protecting_oracle_databases.html 
sidebar: sidebar 
keywords: oracle, preparation for protection, prerequisites 
summary: 백업, 클론 복제 또는 복원 작업과 같은 데이터 보호 작업을 수행하기 전에 전략을 정의하고 환경을 설정해야 합니다. SnapVault 서버에서 SnapMirror 및 SnapCenter 기술을 사용하도록 설정할 수도 있습니다. 
---
= Oracle 데이터베이스 보호를 위한 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업, 클론 복제 또는 복원 작업과 같은 데이터 보호 작업을 수행하기 전에 전략을 정의하고 환경을 설정해야 합니다. SnapVault 서버에서 SnapMirror 및 SnapCenter 기술을 사용하도록 설정할 수도 있습니다.

SnapVault 및 SnapMirror 기술을 활용하려면 스토리지 장치의 소스 볼륨과 타겟 볼륨 간의 데이터 보호 관계를 구성하고 초기화해야 합니다. NetAppSystem Manager를 사용하거나 스토리지 콘솔 명령줄을 사용하여 이러한 작업을 수행할 수 있습니다.

Oracle 데이터베이스용 플러그인을 사용하기 전에 SnapCenter 관리자는 SnapCenter 서버를 설치 및 구성하고 필수 작업을 수행해야 합니다.

* SnapCenter 서버를 설치하고 구성합니다. link:../install/task_install_the_snapcenter_server_using_the_install_wizard.html["자세한 정보"^]
* 스토리지 시스템 접속을 추가하여 SnapCenter 환경을 구성합니다. link:../install/task_add_storage_systems.html["자세한 정보"^]
+

NOTE: SnapCenter은 서로 다른 클러스터에서 동일한 이름의 여러 SVM을 지원하지 않습니다. SVM 등록 또는 클러스터 등록을 사용하여 SnapCenter에 등록된 각 SVM은 고유해야 합니다.

* 설치 사용자에 대해 인증 모드를 Linux 또는 AIX로 사용하여 자격 증명을 작성합니다. link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#set-up-credentials["자세한 정보"^]
* 호스트를 추가하고 플러그인을 설치한 다음 리소스를 검색합니다.
* SnapCenter 서버를 사용하여 VMware RDM LUN 또는 VMDK에 상주하는 Oracle 데이터베이스를 보호하는 경우 VMware vSphere용 SnapCenter 플러그인을 구축하고 SnapCenter에 플러그인을 등록해야 합니다.
* Linux 또는 AIX 호스트에 Java를 설치합니다.
+
을 참조하십시오 link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#linux-host-requirements["Linux 호스트 요구 사항"^] 또는 link:../protect-sco/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux_or_aix.html#aix-host-requirements["AIX 호스트 요구 사항"^] 를 참조하십시오.

* 애플리케이션 방화벽의 시간 초과 값을 3시간 이상으로 설정해야 합니다.
* NFS 환경에 Oracle 데이터베이스가 있는 경우 마운트, 클론, 검증 및 복원 작업을 수행하려면 운영 스토리지 또는 2차 스토리지에 대해 NFS 데이터 LIF를 하나 이상 구성해야 합니다.
* 여러 데이터 경로(LIF) 또는 dNFS 구성이 있는 경우 데이터베이스 호스트에서 SnapCenter CLI를 사용하여 다음을 수행할 수 있습니다.
+
** 기본적으로 데이터베이스 호스트의 모든 IP 주소가 클론 복제된 볼륨에 대한 SVM(Storage Virtual Machine)의 NFS 스토리지 엑스포트 정책에 추가됩니다. 특정 IP 주소를 사용하거나 IP 주소의 하위 집합으로 제한하려면 Set-PreferredHostIPsInStorageExportPolicy CLI를 실행합니다.
** SVM에 여러 데이터 경로(LIF)가 있을 경우 SnapCenter은 NFS 클론 복제된 볼륨을 마운트하기 위해 적절한 데이터 경로(LIF)를 선택합니다. 그러나 특정 데이터 경로(LIF)를 지정하려면 Set-SvmPreferredDataPath CLI를 실행해야 합니다. 자세한 내용은 명령 참조 가이드를 참조하십시오.


* SAN 환경에 Oracle 데이터베이스가 있는 경우 다음 가이드에 설명된 권장 사항에 따라 SAN 환경을 구성해야 합니다.
+
** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547957["Linux Unified Host Utilities의 권장 호스트 설정"^]
** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547958["ONTAP 스토리지에 Linux 호스트 사용"^]
** https://library.netapp.com/ecm/ecm_download_file/ECMP1119218["AIX 호스트 유틸리티의 영향을 받는 호스트 설정"^]


* Oracle Linux 또는 RHEL 운영 체제의 LVM에 Oracle 데이터베이스가 있는 경우 최신 버전의 LVM(Logical Volume Management)을 설치합니다.
* Oracle용 SnapManager를 사용하고 있고 Oracle 데이터베이스용 SnapCenter 플러그인으로 마이그레이션하려는 경우 sccli 명령 sc-migrate 를 사용하여 프로필을 SnapCenter의 정책 및 리소스 그룹으로 마이그레이션할 수 있습니다.
* 백업 복제를 원하는 경우 ONTAP에서 SnapMirror 및 SnapVault를 구성합니다


SnapCenter 4.1.1 사용자의 경우 VMware vSphere 4.1.1 용 SnapCenter 플러그인 설명서에 가상화 데이터베이스와 파일 시스템을 보호하는 방법에 대한 정보가 나와 있습니다. SnapCenter 4.2.x 사용자, NetApp Data Broker 1.0 및 1.0.1의 경우, Linux 기반 NetApp Data Broker 가상 어플라이언스(Open Virtual Appliance 형식)에서 제공하는 VMware vSphere용 SnapCenter 플러그인을 사용하여 가상화된 데이터베이스 및 파일 시스템을 보호하는 방법에 대한 정보가 수록되어 있습니다. SnapCenter 4.3.x 사용자의 경우 SnapCenter Plug-in for VMware vSphere 4.3 설명서에는 Linux 기반 SnapCenter Plug-in for VMware vSphere 가상 어플라이언스(오픈 가상 어플라이언스 형식)를 사용하여 가상화된 데이터베이스와 파일 시스템을 보호하는 방법에 대한 정보가 수록되어 있습니다.

* 자세한 정보 찾기 *

* https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["상호 운용성 매트릭스 툴"^]
* https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/index.html["VMware vSphere용 SnapCenter 플러그인 설명서"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Data_protection_operation_fails_in_a_non-multipath_environment_in_RHEL_7_and_later["RHEL 7 이상의 비 다중 경로 환경에서 데이터 보호 작업이 실패합니다"^]

