---
permalink: protect-sco/enable-consistency-group-snapshots-resource-group-level.html 
sidebar: sidebar 
keywords: consistency group, enable, create, resource group level 
summary: 리소스 그룹은 백업 및 보호할 리소스를 추가하는 컨테이너입니다. 리소스 그룹을 사용하면 지정된 애플리케이션과 연결된 모든 데이터를 동시에 백업할 수 있습니다. 
---
= 리소스 그룹 수준에서 일관성 그룹 스냅샷을 활성화합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
기본적으로 Oracle Database용 SnapCenter 플러그인은 ASM(Automatic Storage Management) 디스크 그룹 또는 LVM(Logical Volume Management) 볼륨 그룹 수준에서 일관성 그룹 스냅샷을 생성합니다. 모범 사례로, 단일 리소스 그룹 내의 데이터베이스는 ASM 디스크 그룹 또는 LVM 볼륨 그룹 간에 ONTAP 볼륨을 공유하지 않아야 합니다.

하지만 ASM 디스크 그룹이나 LVM 볼륨 그룹이 기본 ONTAP 볼륨을 공유하는 경우, 중복 스냅샷 충돌로 인해 일관성 그룹 스냅샷이 실패할 수 있습니다. 이러한 경우 SnapCenter는 자동으로 볼륨 수준 스냅샷으로 대체합니다.

.이 작업에 대해
ASM 디스크 그룹 또는 LVM 볼륨 그룹 간에 볼륨이 공유되는 시나리오에서 SnapCenter는 리소스 그룹 수준에서 일관성 그룹 스냅샷을 활성화하는 기능을 지원합니다. 이를 통해 리소스 그룹 내 데이터베이스와 연결된 모든 ASM 디스크 그룹 또는 LVM 볼륨 그룹이 단일 일관성 그룹 스냅샷으로 캡처됩니다. 다음 단계에서는 이 기능을 사용하는 방법을 설명합니다.

.단계
. SnapCenter 서버에서 다음 구성 파일로 이동하십시오.
+
`C:\Program Files\NetApp\SMCore\SMCoreServiceHost.dll.config`.

.  `isCgSnapshotForRg` 매개 변수를 찾아 값을 *false*에서 *true*로 변경합니다.
. 변경 사항을 적용하려면  `SMCoreService` 서비스를 다시 시작하십시오.

