---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-restore.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, restore 
summary: SnapCenter를 사용하면 데이터베이스를 복원하는 동안 처방과 PS를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다. 
---
= 특정 처방과 PS를 복원하기 위한 사전 정의된 환경 변수입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하면 데이터베이스를 복원하는 동안 처방과 PS를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다.

* 데이터베이스 복원을 위해 지원되는 미리 정의된 환경 변수 *

* * SC_JOB_ID * 는 작업의 작업 ID를 지정합니다.
+
예: 257

* * SC_ORACLE_SID * 는 데이터베이스의 시스템 식별자를 지정합니다.
+
작업에 여러 데이터베이스가 포함된 경우 파이프로 구분된 데이터베이스 이름이 포함됩니다.

+
예: NFSB31

* * sc_host * 는 데이터베이스의 호스트 이름을 지정합니다.
+
이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: scsmohost2.gdl.englabe.netapp.com

* * SC_OS_USER * 는 데이터베이스의 운영 체제 소유자를 지정합니다.
+
예: Oracle

* * SC_OS_GROUP * 은 데이터베이스의 운영 체제 그룹을 지정합니다.
+
예: oinstall

* * SC_BACKUP_NAME * 은 백업 이름을 지정합니다.
+
이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예:

+
** 데이터베이스가 ARCHIVELOG 모드에서 실행되고 있지 않은 경우: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
** 데이터베이스가 ARCHIVELOG 모드에서 실행 중인 경우: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1, RG2_scspr2417819002_07-21-2021_12.16.48.9267_1, RG2_scspr2417819002_07-22-2021_12.16.48.9267_1


* * SC_BACKUP_ID * 는 백업의 ID를 지정합니다.
+
이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예:

+
** 데이터베이스가 ARCHIVELOG 모드에서 실행되지 않는 경우: data@203|log@205
** 데이터베이스가 ARCHIVELOG 모드에서 실행 중인 경우: data@203|log@205,206,207


* * sc_resource_group_name * 은 리소스 그룹의 이름을 지정합니다.
+
예: RG1

* * SC_ORACLE_HOME * 은 Oracle 홈 디렉토리의 경로를 지정합니다.
+
예: /ora01/app/oracle/product/18.1.0/db_1

* * sc_recovery_type * 은 복구할 파일과 복구 범위를 지정합니다.
+
예: RESTORESCOPE:usingBackupControlfile=false|RECOVERYSCOPE:allLogs=true,nLogs=false,untiltime=false,untilscn=false입니다.



구분 기호에 대한 자세한 내용은 을 참조하십시오 link:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters["지원되는 구분 기호"^].
