---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-backup.html 
sidebar: sidebar 
keywords: environment variable, predefined, prescript, postscript, backup, policy 
summary: SnapCenter를 사용하면 백업 정책을 생성하는 동안 처방과 PS를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다. 
---
= 백업 특정 처방과 PS에 대한 사전 정의된 환경 변수입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하면 백업 정책을 생성하는 동안 처방과 PS를 실행할 때 미리 정의된 환경 변수를 사용할 수 있습니다. 이 기능은 VMDK를 제외한 모든 Oracle 구성에서 지원됩니다.

SnapCenter는 셸 스크립트가 실행되는 환경에서 직접 액세스할 수 있는 매개 변수의 값을 미리 정의합니다. 스크립트를 실행할 때 이러한 매개 변수의 값을 수동으로 지정할 필요는 없습니다.



== 백업 정책 생성을 위해 지원되는 사전 정의된 환경 변수입니다

* * SC_JOB_ID * 는 작업의 작업 ID를 지정합니다.
+
예: 256

* * SC_ORACLE_SID * 는 데이터베이스의 시스템 식별자를 지정합니다.
+
작업에 여러 데이터베이스가 포함된 경우 매개 변수는 파이프로 분리된 데이터베이스 이름을 포함합니다.

+
이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: NFSB32 | NFSB31

* * sc_host * 는 데이터베이스의 호스트 이름을 지정합니다.
+
RAC의 경우 호스트 이름은 백업이 수행되는 호스트의 이름입니다.

+
이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: scsmohost2.gdl.englabe.netapp.com

* * SC_OS_USER * 는 데이터베이스의 운영 체제 소유자를 지정합니다.
+
데이터는 <db1>@<osuser1>|<DB2>@<osuser2>로 포맷됩니다.

+
예: NFSB31@ Oracle | NFSB32@ Oracle

* * SC_OS_GROUP * 은 데이터베이스의 운영 체제 그룹을 지정합니다.
+
데이터는 <db1>@<osgroup1>|<DB2>@<osgroup2>로 포맷됩니다.

+
예: NFSB31@ 설치 | NFSB32@ oinstall

* * sc_backup_type * "은 백업 유형을 지정합니다(온라인 전체, 온라인 데이터, 온라인 로그, 오프라인 종료, 오프라인 마운트).
+
예:

+
** 전체 백업의 경우: ONLINEFULL
** 데이터 전용 백업: ONLINEDATA
** 로그 전용 백업: ONLINELOG


* * SC_BACKUP_NAME * 은 백업 이름을 지정합니다.
+
이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1 | AV@RG2_scspr2417819002_07-20-2021_12.16.48.9267

* * SC_BACKUP_ID * 는 백업 ID를 지정합니다.
+
이 매개 변수는 애플리케이션 볼륨에 대해 채워집니다.

+
예: data@203|log@205|AV@207

* * SC_ORACLE_HOME * 은 Oracle 홈 디렉토리의 경로를 지정합니다.
+
예: NFSB32@/ora01/app/oracle/product/18.1.0/db_1|NFSB31@/ora01/app/oracle/product/18.1.0/db_1

* * sc_backup_retention * 은 정책에 정의된 보존 기간을 지정합니다.
+
예:

+
** 전체 백업의 경우: hourly | data@days:3 | log@count:4
** 필요 시 데이터 백업 전용: OnDemand | data@count:2
** 필요 시 로그 전용 백업의 경우: OnDemand | log@count:2


* * sc_resource_group_name * 은 리소스 그룹의 이름을 지정합니다.
+
예: RG1

* * sc_backup_policy_name * 은 백업 정책의 이름을 지정합니다.
+
예: backup_policy

* * SC_AV_NAME * 은 애플리케이션 볼륨의 이름을 지정합니다.
+
예: AV1 | AV2

* * SC_PRIMARY_DATA_VOLUME_FULL_PATH * 는 SVM과 데이터 파일 디렉토리의 볼륨 간 스토리지 매핑을 지정합니다. LUN 및 qtree에 대한 상위 볼륨의 이름이 됩니다.
+
데이터는 <db1>@<SVM1:volume1>|<DB2>@<SVM2:volume2>로 포맷됩니다.

+
예:

+
** 동일한 리소스 그룹에 있는 2개의 데이터베이스: NFSB32@b벅:/vol/scspr2417819002_NFS_CDB_NFSB32_data | NFSB31@벅:/vol/scs42417819002_NFS_CDB_NFSB31_data
** 데이터 파일이 있는 단일 데이터베이스가 여러 볼륨에 분산되어 있는 경우: b벅:/vol/scspr2417819002_NFS_CDB_NFSB31_DATA, herculus:/vol/scspr2417819002_NFS


* * SC_PRIMARY_ARCHIVELOGS_VOLUME_FULL_PATH * 는 SVM과 로그 파일 디렉토리의 볼륨 간 스토리지 매핑을 지정합니다. LUN 및 qtree에 대한 상위 볼륨의 이름이 됩니다.
+
예:

+
** 단일 데이터베이스 인스턴스의 경우: 벅:/vol/scspr2417819002_NFS_CDB_NFSB31_REDO
** 여러 데이터베이스 인스턴스의 경우: NFSB31@벅:/vol/sspr2417819002_NFS_CDB_NFSB31_REDO|NFSB32@벅:/vol/sscspr2417819002_NFS_CDB_NFSB32_REDO


* * sc_primary_full_snapshot_name_for_tag * 는 스토리지 시스템 이름과 볼륨 이름이 포함된 스냅샷의 목록을 지정합니다.
+
예:

+
** 단일 데이터베이스 인스턴스의 경우: b벅:/vol/scspr2417819002_nfs_cdb_NFSB32_data/RG2_scspr2417819002_07-21-2021-221_02.28.26.3973_0, 벅:/vol/scspr2417819002_nfs_cdb_nfs_redo_r2032_sprsd-28.07226873_228228228721-2267_2327_02.07_02.73_02.
** 다중 데이터베이스 인스턴스의 경우: NFSB32@벅:/vol/scspr2417819002_nfs_cdb_NFSB32_data/RG2_scspr2417819002_07_07-21-2021-2021_02.28.28.26.3973_0, /vol/scsprec2417819002_sprdl_sprec282282dl_sprdl_sCDB_sprdl_s2021.22.1722.172282dl_sCDB_sCDB_sCDB_sCDB_sprdcdb_sCDB_s20122.1722.07_sCDB_22822.07_sCDB_22.1722.07_sCDB_sCDB_s2022_sCDB_S22.07_S22.1722822_22822_27.07_27.07_27.07_27.07_27.


* * sc_primary_snapshot_names * 는 백업 중에 생성된 기본 스냅샷의 이름을 지정합니다.
+
예:

+
** 단일 데이터베이스 인스턴스의 경우: RG2_scspr2417819002_07-21-2021_02.28.26.3973_0, RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** 여러 데이터베이스 인스턴스의 경우 NFSB32@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0, RG2_scspr2417819002_07-21-2021_02.28.26.3973_1|NFSB31@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0, RG2_scspr2417819002_07-21-2021_02.28.26.3973_1
** 2개의 볼륨이 포함된 정합성 보장 그룹 스냅샷: CG3_R80404CBEF5V1_04-05-2021_03.08.08.4945_0_bfc279cc-28ad-465c-9d60-5487ac17b25d_2021_4_5_3_8_58_350


* * sc_primary_mount_points * 는 백업의 일부인 마운트 지점 세부 정보를 지정합니다.
+
세부 정보에는 볼륨이 마운트되어 있으며 백업 중인 파일의 직접적인 부모가 아닌 디렉토리가 포함됩니다. ASM 구성의 경우 디스크 그룹의 이름입니다.

+
데이터는 <db1>@<mountpoint1, mountpoint2>|<DB2>@<mountpoint1, mountpoint2>로 포맷됩니다.

+
예:

+
** 단일 데이터베이스 인스턴스의 경우 /mnt/nfsdb3_data, /mnt/nfsdb3_log, /mnt/nfsdb3_data1
** 여러 데이터베이스 인스턴스의 경우: NFSB31@/mnt/nfsdb31_data, /mnt/nfsdb31_log, /mnt/nfsdb31_data1|NFSB32@/mnt/nfsdb32_data, /mnt/nfsdb32_log, /mnt/nfsdb32_data1
** ASM: + DATA2DG, + LOG2DG


* * sc_primary_snapshots_and_mount_points * 는 각 마운트 지점의 백업 중에 생성된 스냅샷의 이름을 지정합니다.
+
예:

+
** 단일 데이터베이스 인스턴스의 경우: RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb32_data, RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb31_log
** 여러 데이터베이스 인스턴스의 경우: NFSB32@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb32_data, RG2_scspr2417819002_07-21-2021_02.28.26.3973_1:/mnt/nfsb31_log | NFSB31@RG2_scspr2417819002_07-21-2021_02.28.26.3973_0:/mnt/nfsb31_data, RG2_scspr2417819002_07-2323_2mnt_323_2n32


* * sc_ARCHIVELOGS_locations * 는 아카이브 로그 디렉토리의 위치를 지정합니다.
+
디렉토리 이름은 아카이브 로그 파일의 직접적인 부모가 됩니다. 아카이브 로그가 둘 이상의 위치에 있으면 모든 위치가 캡처됩니다. 여기에는 FRA 시나리오도 포함됩니다. 디렉토리에 대해 소프트링크가 사용되는 경우 동일한 파일이 채워집니다.

+
예:

+
** NFS:/mnt/nfsdb2_log의 단일 데이터베이스
** NFS의 여러 데이터베이스와 두 개의 다른 위치에 배치된 NFSB31@/mnt/nfsdb31_log1, /mnt/nfsdb31_log2|NFSB32@/mnt/nfsdb32_log의 경우
** ASM:+LOG2DG/ASMDB2/ARCHIVELOG/2021_07_15용


* * sc_redo_logs_locations * 는 redo 로그 디렉토리의 위치를 지정합니다.
+
디렉토리 이름은 redo 로그 파일의 바로 상위 항목이 됩니다. 디렉토리에 대해 소프트링크가 사용되는 경우 동일한 파일이 채워집니다.

+
예:

+
** NFS:/mnt/nfsdb2_data/newdb1의 단일 데이터베이스
** NFS에 있는 여러 데이터베이스의 경우: NFSB31@/mnt/nfsdb31_data/newdb31|NFSB32@/mnt/nfsdb32_data/newdb32
** ASM:+LOG2DG/ASMDB2/ONLINELOG의 경우


* * sc_control_files_locations * 는 제어 파일 디렉토리의 위치를 지정합니다.
+
디렉터리 이름은 제어 파일의 바로 상위 항목이 됩니다. 디렉토리에 대해 소프트링크가 사용되는 경우 동일한 파일이 채워집니다.

+
예:

+
** NFS의 단일 데이터베이스의 경우: /mnt/nfsdb2_data/FRA/newdb1, /mnt/nfsdb2_data/newdb1
** NFS에 있는 여러 데이터베이스의 경우: NFSB31@/mnt/nfsdb31_data/FRA/newdb31, /mnt/nfsdb31_data/newdb31|NFSB32@/mnt/nfsdb32_data/FRA/nfsdb32, /mnt/nfsdb32_data/ndb32
** ASM:+LOG2DG/ASMDB2/controlfile의 경우


* * sc_data_files_locations * "는 데이터 파일 디렉토리의 위치를 지정합니다.
+
디렉터리 이름은 데이터 파일의 바로 상위 항목이 됩니다. 디렉토리에 대해 소프트링크가 사용되는 경우 동일한 파일이 채워집니다.

+
예:

+
** NFS:/mnt/nfsdb3_data1, /mnt/nfsdb3_data/NEWDB3/datafile의 단일 데이터베이스
** NFS:NFSB31@/mnt/nfsdb31_data1, /mnt/nfsdb31_data/NEWDB31/datafile|NFSB32@/mnt/nfsdb32_data1, /mnt/nfsdb32_data/NEWDB32/datafile의 여러 데이터베이스에 대해
** ASM:+DATA2DG/ASMDB2/데이터 파일, +DATA2DG/ASMDB2/TEMPFILE


* * sc_snapshot_label * 은 보조 레이블의 이름을 지정합니다.
+
예: 시간별, 일별, 주별, 월별 또는 사용자 지정 레이블





== 지원되는 구분 기호

* *: * 은 SVM 이름과 볼륨 이름을 구분하는 데 사용됩니다
+
예: buck:/vol/scspr2417819002_nfs_cdb_NFSB32_data/RG2_scspr24178002_07-21-2021_02.28.26.3973_0, b벅:/vol/sprspr2417819002_nfs_cdb_NFSB32_redo/RG2_scspr2417819002_28.07_02.73_22.73_02.07_02.73_02.73_02.73_02.73_

* * @ * 는 데이터를 데이터베이스 이름과 분리하고 해당 키와 값을 구분하는 데 사용됩니다.
+
예:

+
** NFSB32@b벅:/vol/scspr24178002_nfs_cdb_NFSB32_data/RG2_scprsprs2417819002_07_07-21-2021-2021_02.28.28.26.3973_0_sprdl: /vol/sprec1782.172262282dl_sCDB_sprdl_n22.1722.1722.1722.172dl_ndl_22.1722.1722.172dl_n22.1722.172dl_ndcdb_n22.1722.1722.1722.172dl_ndcdb_22.172dl_22.07_ndl_ndcdb_ndl_22.1722.1722.07_ndcdb_n22.1782.1722.1722.1722.1722.07_2
** NFSB31@Oracle|NFSB32@Oracle


* * | * 는 서로 다른 두 데이터베이스 간에 데이터를 분리하고 SC_BACKUP_ID, SC_BACKUP_RETENTION 및 SC_BACKUP_NAME 매개 변수에 대해 서로 다른 두 엔터티 간에 데이터를 분리하는 데 사용됩니다.
+
예:

+
** Data @ 203 | log @ 205
** hourly | data@days:3 | log@count:4
** DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0 | LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1


* * / * 는 SC_PRIMARY_SNACSHOT_NAME 및 SC_PRIMARY_FULL_SNSHOT_NAME_FOR_TAG 매개변수에 대한 스냅숏에서 볼륨 이름을 구분하는 데 사용됩니다.
+
예: NFSB32@벅:/vol/scspr2417819002_nfs_cdb_NFSB32_data/RG2_scspr2417819002_07-21-2021-2021_02.28.26.3973_0, 벅:/vol/sprspr2417819002_nfs_cdb_nfs_redo_rredo/RG2_sc2822.17226722_327_2021-282327_327_sprec2021-282327_

* *, * 는 동일한 DB에 대한 변수 세트를 구분하는 데 사용됩니다.
+
예: -NFSB32@벅:/vol/scspr24178002_nfs_cdb_NFSB32_data/RG2_scsprspr2417819002_07_07-21-2021-2021_02.28.28.28.26.3973_0, duck: /vol/scsprec17819002_sprecdl_n22.1727.21_sprdl_sprdcdb_22.1722.1722.07_27.21_sCDB_ndl_s2021_sCDB_ndl_sprdl_22.1722.1722.1722.1722.1722.17228002_ndl_sCDB_sCDB_228002_sCDB_228228002_sCDB_sCDB_228002_228002_s20127.21_27.07_27.07_s


