---
permalink: protect-sco/preferred-nodes.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter가 Oracle 데이터베이스를 검색하는 방법 
---
= RAC 설정의 1차 노드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle RAC(Real Application Clusters) 설정에서 SnapCenter가 백업 작업을 수행하는 데 사용하는 기본 노드를 지정할 수 있습니다. 기본 설정 노드를 지정하지 않으면 SnapCenter가 노드를 기본 설정 노드로 자동 할당하고 해당 노드에 백업이 생성됩니다.

선호하는 노드는 RAC 데이터베이스 인스턴스가 있는 클러스터 노드 중 하나 또는 모두가 될 수 있습니다. 백업 작업은 기본 설정 순서대로 이러한 기본 설정 노드에서만 트리거됩니다.

.예
RAC 데이터베이스 cdbrac에는 node1의 cdbrac1, node2의 cdbrac2, node3의 cdbrac3 등 세 가지 인스턴스가 있습니다.

노드 1과 노드 2 인스턴스는 노드 2가 첫 번째 기본 설정이고 노드 1이 두 번째 기본 설정인 기본 노드로 구성됩니다. 백업 작업을 수행할 때 노드 2가 첫 번째 기본 설정 노드이므로 이 작업이 먼저 시도됩니다.

플러그인 에이전트가 호스트에서 실행되고 있지 않은 등의 여러 가지 이유로 인해 노드 2가 백업할 상태가 아닌 경우 호스트의 데이터베이스 인스턴스가 지정된 백업 유형에 대해 필요한 상태가 아닌 경우 또는 FlexASM 구성에서 노드 2의 데이터베이스 인스턴스를 로컬 ASM 인스턴스에서 제공하지 않으면 노드 1에서 작업을 시도합니다.

노드 3은 기본 노드 목록에 없으므로 백업에 사용되지 않습니다.



== Flex ASM 설정

Flex ASM 설정에서 카디널리티가 RAC 클러스터의 노드 수보다 적은 경우 Leaf 노드가 기본 노드로 표시되지 않습니다. Flex ASM 클러스터 노드 역할이 변경된 경우 원하는 노드가 새로 고쳐지도록 수동으로 검색해야 합니다.



== 필요한 데이터베이스 상태입니다

기본 노드의 RAC 데이터베이스 인스턴스가 백업을 성공적으로 완료하려면 필수 상태여야 합니다.

* 구성된 기본 노드의 RAC 데이터베이스 인스턴스 중 하나가 열려 있어야 온라인 백업을 생성할 수 있습니다.
* 구성된 기본 노드의 RAC 데이터베이스 인스턴스 중 하나는 마운트 상태여야 하며, 다른 기본 노드를 비롯한 다른 모든 인스턴스는 마운트 상태 또는 그 아래에 있어야 오프라인 마운트 백업을 생성할 수 있습니다.
* RAC 데이터베이스 인스턴스는 임의의 상태에 있을 수 있지만 오프라인 종료 백업을 생성하려면 기본 노드를 지정해야 합니다.

