---
permalink: protect-sco/reference_requirements_for_cloning_an_oracle_database.html 
sidebar: sidebar 
keywords:  
summary: Oracle 데이터베이스를 복제하기 전에 필수 구성 요소가 완료되었는지 확인해야 합니다. 
---
= Oracle 데이터베이스 클론 생성 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle 데이터베이스를 복제하기 전에 필수 구성 요소가 완료되었는지 확인해야 합니다.

* SnapCenter를 사용하여 데이터베이스 백업을 만들어야 합니다.
+
클론 생성 작업을 성공적으로 수행하려면 온라인 데이터 및 로그 백업 또는 오프라인(마운트 또는 종료) 백업을 성공적으로 생성해야 합니다.

* 제어 파일 또는 redo 로그 파일 경로를 사용자 지정하려면 필요한 파일 시스템 또는 ASM(Automatic Storage Management) 디스크 그룹을 미리 프로비저닝해야 합니다.
+
기본적으로 클론 데이터베이스의 재실행 로그 및 제어 파일은 ASM 디스크 그룹 또는 SnapCenter이 클론 데이터베이스의 데이터 파일에 대해 프로비저닝한 파일 시스템에 생성됩니다.

* ASM over NFS를 사용하는 경우 ASM_diskstring 매개 변수에 정의된 기존 경로에 _/var/opt/snapcenter/SCU/clones/ */ *_를 추가해야 합니다.
* ASM_diskstring 매개 변수에서 ASMFD 또는 configure_ORCL: *_을 사용하는 경우 ASMlib를 사용하는 경우 _AFD: *_를 구성해야 합니다.
+
ASM_diskstring 매개 변수를 편집하는 방법에 대한 자세한 내용은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter["ASM_diskstring에 디스크 경로를 추가하는 방법"^].

* 대체 호스트에서 클론을 생성하는 경우 대체 호스트는 다음 요구 사항을 충족해야 합니다.
+
** Oracle 데이터베이스용 SnapCenter 플러그인을 대체 호스트에 설치해야 합니다.
** 클론 호스트는 운영 스토리지 또는 보조 스토리지에서 LUN을 검색할 수 있어야 합니다.
+
*** 운영 스토리지 또는 보조(볼트 또는 미러) 스토리지에서 대체 호스트로 클론을 생성하는 경우 iSCSI 세션이 보조 스토리지와 대체 호스트 간에 설정되거나 FC에 대해 적절하게 조닝(Zoning)되었는지 확인합니다.
+
**** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936["Linux 호스트 유틸리티 설치 및 설정 안내서"^]
**** https://library.netapp.com/ecm/ecm_download_file/ECMP1119223["AIX 호스트 유틸리티 설치 및 설정 안내서"^]


*** Vault 또는 Mirror 스토리지에서 동일한 호스트로 클론을 생성하는 경우, iSCSI 세션이 Vault 또는 Mirror 스토리지와 호스트 간에 설정되어 있는지 또는 FC에 맞게 조닝(zoning)되어 있는지 확인합니다.
*** 가상화 환경에서 클론을 생성하는 경우 iSCSI 세션이 운영 스토리지 또는 보조 스토리지와 대체 호스트를 호스팅하는 ESX 서버 간에 설정되어 있는지 또는 FC에 대해 적절하게 조닝(zoning)되어 있는지 확인합니다.


** 소스 데이터베이스가 ASM 데이터베이스인 경우:
+
*** ASM 인스턴스는 클론이 수행될 호스트에서 실행 중이어야 합니다.
*** 클론 데이터베이스의 아카이브 로그 파일을 전용 ASM 디스크 그룹에 배치하려면 클론 작업 전에 ASM 디스크 그룹을 프로비저닝해야 합니다.
*** 데이터 디스크 그룹의 이름은 구성할 수 있지만 클론이 수행될 호스트의 다른 ASM 디스크 그룹에서 해당 이름을 사용하지 않도록 해야 합니다.
+
ASM 디스크 그룹에 상주하는 데이터 파일은 SnapCenter 클론 워크플로우의 일부로 프로비저닝됩니다.





* 로그 백업을 사용하여 대체 호스트에 클론을 생성하는 동안 보조 로케이터를 검색하려면 데이터 LUN과 미러, 볼트 또는 미러 볼트와 같은 로그 LUN에 대한 보호 유형이 동일해야 합니다.
* 소스 데이터베이스 매개 변수 파일에서 exclude_seed_cdb_view 값을 false 로 설정하여 12__c__ 데이터베이스 백업 클론 생성을 위한 시드 PDB 관련 정보를 검색해야 합니다.
+
시드 PDB는 CDB가 PDB를 생성하는 데 사용할 수 있는 시스템 제공 템플릿입니다. 시드 PDB의 이름은 PDB$seed입니다. PDB$ 시드에 대한 자세한 내용은 Oracle Doc ID 1940806.1을 참조하십시오.

+

NOTE: 12__c__database를 백업하기 전에 값을 설정해야 합니다.

* SnapCenter는 autofs 서브시스템에서 관리하는 파일 시스템의 백업을 지원합니다. 데이터베이스를 복제하는 경우 플러그인 호스트의 루트 사용자에게 autofs 마운트 지점의 루트 아래에 디렉토리를 생성할 권한이 없으므로 데이터 마운트 지점이 autofs 마운트 지점의 루트 아래에 있지 않은지 확인합니다.
+
제어 및 재실행 로그 파일이 데이터 마운트 지점에 있는 경우 제어 파일 경로를 수정한 다음 그에 따라 로그 파일 경로를 다시 실행해야 합니다.

+

NOTE: 새로 클론된 마운트 지점을 autofs 하위 시스템에 수동으로 등록할 수 있습니다. 새로 클론된 마운트 지점은 자동으로 등록되지 않습니다.

* TDE(자동 로그인)가 있고 동일한 호스트 또는 대체 호스트에서 데이터베이스를 복제하려는 경우 소스 데이터베이스에서 복제된 데이터베이스로 _ /etc/oracle/wallet/$oracle_SID_ 아래의 Wallet(키 파일)을 복사해야 합니다.
* use_lvmetad = 0 in_/etc/lvm/lvm.conf_의 값을 설정하고 lvm2-lvmetad 서비스를 중지하여 Oracle Linux 7 이상 또는 Red Hat Enterprise Linux(RHEL) 7 이상의 SAN 환경에서 클론을 성공적으로 수행해야 합니다.
* Oracle 데이터베이스 11.2.0.3 이상을 사용하고 보조 인스턴스의 데이터베이스 ID가 NID 스크립트를 사용하여 변경된 경우 13366202 Oracle 패치를 설치해야 합니다.
* 볼륨을 호스팅하는 애그리게이트는 SVM(스토리지 가상 머신)의 할당된 애그리게이트 목록에 있어야 합니다.

