---
permalink: protect-sco/schedule-backups.html 
sidebar: sidebar 
keywords: oracle databases discover 
summary: SnapCenter가 Oracle 데이터베이스를 검색하는 방법 
---
= 백업 스케줄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 빈도(스케줄 유형)는 정책에 지정되며 백업 스케줄은 리소스 그룹 구성에 지정됩니다. 백업 빈도 또는 스케줄을 결정하는 가장 중요한 요소는 리소스의 변경 속도 및 데이터의 중요도입니다. 자주 사용하는 리소스를 매일 한 번씩 백업할 수도 있고, 자주 사용하지 않는 리소스를 하루에 한 번 백업할 수도 있습니다. 기타 요인으로는 조직에 대한 리소스의 중요성, SLA(서비스 수준 계약) 및 RPO(복구 시점 목표)가 있습니다.

SLA는 예상되는 서비스 수준을 정의하고 가용성 및 서비스 성능을 비롯한 다양한 서비스 관련 문제를 해결합니다. RPO는 장애 후 정상적인 작업을 재개하기 위해 백업 스토리지에서 복구해야 하는 파일의 사용 기간에 대한 전략을 정의합니다. SLA 및 RPO는 데이터 보호 전략에 기여합니다.

사용량이 많은 리소스의 경우에도 하루에 한 번 또는 두 번 이상 전체 백업을 실행할 필요가 없습니다. 예를 들어 정기적인 트랜잭션 로그 백업만으로도 필요한 백업이 있는지 확인할 수 있습니다. 데이터베이스를 더 자주 백업할수록 SnapCenter는 복원 시 사용해야 하는 트랜잭션 로그를 더 적게 사용하여 복원 작업을 더 빠르게 수행할 수 있습니다.

백업 스케줄은 다음과 같이 두 부분으로 구성됩니다.

* 백업 빈도
+
일부 플러그인에 대해 _schedule type_이라는 백업 빈도(백업 수행 빈도)는 정책 구성의 일부입니다. 정책의 백업 빈도로 시간별, 일별, 주별 또는 월별 을 선택할 수 있습니다. 이러한 빈도 중 하나를 선택하지 않으면 생성된 정책이 온디맨드 전용 정책입니다. 설정 * > * 정책 * 을 클릭하여 정책에 액세스할 수 있습니다.

* 백업 스케줄
+
백업 스케줄(백업을 수행할 정확한 시점)은 리소스 그룹 구성의 일부입니다. 예를 들어 주별 백업에 대한 정책이 구성된 리소스 그룹이 있는 경우 매주 목요일 오후 10시에 백업하도록 스케줄을 구성할 수 있습니다. 리소스 그룹 * > * 리소스 그룹 * 을 클릭하여 리소스 그룹 일정에 액세스할 수 있습니다.


