---
permalink: protect-sco/task_refresh_a_clone.html 
sidebar: sidebar 
keywords: refresh clone, clone 
summary: '"Refresh-SmClone" 명령을 실행하여 클론을 새로 고칠 수 있습니다. 이 명령은 데이터베이스의 백업을 생성하고 기존 클론을 삭제한 다음 같은 이름의 클론을 생성합니다.' 
---
= 클론을 새로 고칩니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새로 고침 - SmClone_ 명령을 실행하여 클론을 새로 고칠 수 있습니다. 이 명령은 데이터베이스의 백업을 생성하고 기존 클론을 삭제한 다음 같은 이름의 클론을 생성합니다.


NOTE: PDB 클론은 새로 고칠 수 없습니다.

* 필요한 것 *

* 예약된 백업을 사용하지 않고 온라인 전체 백업 또는 오프라인 데이터 백업 정책을 생성합니다.
* 정책에서 백업 장애에 대해서만 e-메일 알림을 구성합니다.
* 필요 시 백업의 보존 수를 적절하게 정의하여 원치 않는 백업이 없도록 합니다.
* 클론 새로 고침 작업을 위해 식별된 리소스 그룹에 온라인 전체 백업 또는 오프라인 데이터 백업 정책만 연결되어 있는지 확인합니다.
* 하나의 데이터베이스만 사용하여 리소스 그룹을 생성합니다.
* 클론 새로 고침 명령에 대해 cron 작업이 생성된 경우 SnapCenter 스케줄과 cron 일정이 데이터베이스 리소스 그룹에 대해 겹치지 않도록 해야 합니다.
+
클론 새로 고침 명령에 대해 생성된 cron 작업의 경우 24시간마다 Open-SmConnection을 실행해야 합니다.

* 클론 SID가 호스트에 대해 고유한지 확인합니다.
+
여러 번의 클론 새로 고침 작업에서 동일한 클론 사양 파일을 사용하거나 클론 SID가 동일한 클론 지정 파일을 사용하는 경우 호스트에서 SID가 있는 기존 클론이 삭제되고 클론이 생성됩니다.

* 보조 보호 기능을 사용하여 백업 정책을 설정하고 ""-IncludeSecondaryDetails""를 사용하여 클론 사양 파일을 만들어 보조 백업을 사용하여 클론을 생성해야 합니다.
+
** 기본 클론 사양 파일이 지정되었지만 정책에 보조 업데이트 옵션이 선택된 경우 백업이 생성되고 업데이트가 보조 로 전송됩니다. 그러나 클론은 기본 백업에서 생성됩니다.
** 기본 클론 사양 파일이 지정되고 정책에 보조 업데이트 옵션이 선택되지 않은 경우 백업이 운영 사이트에서 생성되고 운영 사이트에서 클론이 생성됩니다.




* 단계 *

. 지정된 사용자에 대해 SnapCenter 서버와 연결 세션을 시작합니다. _ Open - SmConnection _
. 지정된 백업에서 Oracle 데이터베이스 클론 사양을 생성합니다._New-SmOracleCloneSpecification_
+

NOTE: 보조 데이터 보호 정책이 통합 미러 볼트이면 -IncludeSecondaryDetails만 지정합니다. SecondaryStorageType 을 지정할 필요가 없습니다.

+
이 명령은 지정된 소스 데이터베이스 및 해당 백업에 대한 Oracle 데이터베이스 클론 사양 파일을 자동으로 생성합니다. 또한 생성할 클론 데이터베이스에 대해 생성된 지정 파일에 자동으로 생성된 값이 있도록 클론 데이터베이스 SID를 제공해야 합니다.

+

NOTE: 클론 사양 파일은 _/var/opt/snapcenter/sSCO/clone_spec_에서 생성됩니다.

. Run_Refresh-SmClone _ 을(를) 실행합니다.
+
"PL-SCO-20032: canExecute 작업이 실패하고 다음 오류가 발생할 경우: PL-SCO-30031: Redo 로그 파일 + SC_2959770772_clmdb/clmdb/redolog/redo01_01.log exists" 오류 메시지가 나타나면 _-WaitToTriggerClone_에 대해 더 높은 값을 지정하십시오.

+
UNIX 명령에 대한 자세한 내용은 를 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885486["SnapCenter 소프트웨어 명령 참조 가이드"^].


