---
permalink: protect-sco/task_define_a_restore_and_recovery_strategy_for_oracle_databases.html 
sidebar: sidebar 
keywords: backup types, restore methods, connect-and-copy restore, full restore, partial restore, in-place restore, recovery type, limitations 
summary: 복구 및 복구 작업을 성공적으로 수행하려면 데이터베이스를 복원 및 복구하기 전에 전략을 정의해야 합니다. 
---
= Oracle 데이터베이스에 대한 복구 및 복구 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
복구 및 복구 작업을 성공적으로 수행하려면 데이터베이스를 복원 및 복구하기 전에 전략을 정의해야 합니다.



== 복구 및 복구 작업에 지원되는 백업 유형입니다

SnapCenter는 다양한 유형의 Oracle 데이터베이스 백업의 복원 및 복구를 지원합니다.

* 온라인 데이터 백업
* 오프라인 종료 데이터 백업
* 오프라인 마운트 데이터 백업
+

NOTE: 오프라인 종료 또는 오프라인 마운트 데이터 백업을 복원하는 경우 SnapCenter는 데이터베이스를 오프라인 상태로 둡니다. 데이터베이스를 수동으로 복구하고 로그를 재설정해야 합니다.

* 전체 백업
* Data Guard 대기 데이터베이스의 오프라인 마운트 백업
* Active Data Guard 대기 데이터베이스의 데이터 전용 온라인 백업
+

NOTE: Active Data Guard 대기 데이터베이스 복구는 수행할 수 없습니다.

* 온라인 데이터 백업, 온라인 전체 백업, 오프라인 마운트 백업 및 RAC(Real Application Clusters) 구성의 오프라인 종료 백업
* 온라인 데이터 백업, 온라인 전체 백업, 오프라인 마운트 백업 및 ASM(Automatic Storage Management) 구성에서 오프라인 종료 백업




== Oracle 데이터베이스에 지원되는 복원 방법의 유형입니다

SnapCenter는 Oracle 데이터베이스에 대한 연결 및 복사 또는 이동 없는 복원을 지원합니다. 복구 작업 중에 SnapCenter는 데이터 손실 없이 복구에 사용할 파일 시스템에 적합한 복구 방법을 결정합니다.


NOTE: SnapCenter는 볼륨 기반 SnapRestore를 지원하지 않습니다.



=== 연결 및 복사 복원

데이터베이스 레이아웃이 백업과 다르거나 백업 생성 후 새 파일이 있는 경우 연결 및 복사 복원이 수행됩니다. 연결 및 복사 복원 방법에서는 다음 작업이 수행됩니다.

* 단계 *

. 볼륨은 스냅샷 복사본에서 클론 복제되며, 파일 시스템 스택은 클론 복제된 LUN 또는 볼륨을 사용하여 호스트에 구축됩니다.
. 파일은 클론 생성된 파일 시스템에서 원래 파일 시스템으로 복제됩니다.
. 그런 다음 클론된 파일 시스템이 호스트에서 마운트 해제되고 클론된 볼륨이 ONTAP에서 삭제됩니다.



NOTE: Flex ASM 설정(카디널리티가 RAC 클러스터의 노드 수보다 적은 경우) 또는 VMDK 또는 RDM의 ASM RAC 데이터베이스의 경우 연결 및 복제 복원 방법만 지원됩니다.

데이터 이동 없이 강제로 복원한 경우에도 SnapCenter는 다음과 같은 경우에 연결 및 복사 복원을 수행합니다.

* 보조 스토리지 시스템에서 복원하고 Data ONTAP이 8.3 이전 버전인 경우
* 데이터베이스 인스턴스가 구성되지 않은 Oracle RAC 설정의 노드에 있는 ASM 디스크 그룹의 복원
* Oracle RAC 설정에서 ASM 인스턴스 또는 클러스터 인스턴스가 실행되고 있지 않거나 피어 노드가 다운된 경우 피어 노드에서
* 제어 파일만 복원합니다
* ASM 디스크 그룹에 상주하는 테이블스페이스의 하위 집합을 복원합니다
* 디스크 그룹은 데이터 파일, SP 파일 및 암호 파일 간에 공유됩니다
* SnapCenter SPL(Plug-in Loader) 서비스가 RAC 환경의 원격 노드에서 설치되지 않았거나 실행되지 않습니다
* Oracle RAC에 새 노드가 추가되고 SnapCenter 서버가 새로 추가된 노드를 인식하지 못합니다




=== 데이터 이동 없이 복원

데이터베이스 레이아웃이 백업과 유사하고 스토리지 및 데이터베이스 스택에서 구성 변경을 수행하지 않은 경우, 데이터 이동 없이 복원이 수행되며, 이 경우 ONTAP에서 파일 또는 LUN 복원이 수행됩니다. SnapCenter는 현재 위치 복원 방법의 일부로 SFSR(Single File SnapRestore)만 지원합니다.


NOTE: Data ONTAP 8.3 이상은 보조 위치에서 데이터 이동 없이 복원을 지원합니다.

데이터베이스에서 데이터 이동 없이 복원을 수행하려면 ASM 디스크 그룹에 데이터 파일만 있어야 합니다. ASM 디스크 그룹 또는 데이터베이스의 물리적 구조를 변경한 후에는 백업을 생성해야 합니다. 데이터 이동 없이 복원을 수행한 후 디스크 그룹은 백업 시와 동일한 수의 데이터 파일을 포함합니다.

디스크 그룹 또는 마운트 지점이 다음 기준과 일치할 경우 현재 위치 복원이 자동으로 적용됩니다.

* 백업 후 새 데이터 파일이 추가되지 않습니다(외부 파일 검사).
* 백업 후 ASM 디스크 또는 LUN 추가, 삭제 또는 재생성 없음(ASM 디스크 그룹 구조 변경 확인)
* LVM 디스크 그룹(LVM 디스크 그룹 구조 변경 확인)에 LUN을 추가, 삭제 또는 재생성할 수 없음



NOTE: GUI, SnapCenter CLI 또는 PowerShell cmdlet을 사용하여 데이터 이동 없이 강제로 복원할 수 있으며 외부 파일 검사 및 LVM 디스크 그룹 구조 변경 검사를 재정의할 수 있습니다.



==== ASM RAC에서 데이터 이동 없이 복원 수행

SnapCenter에서 복구를 수행하는 노드를 기본 노드라고 하며 ASM 디스크 그룹이 상주하는 RAC의 다른 모든 노드를 피어 노드라고 합니다. SnapCenter는 ASM 디스크 그룹의 상태를 변경하여 스토리지 복구 작업을 수행하기 전에 ASM 디스크 그룹이 마운트 상태에 있는 모든 노드에서 마운트 해제합니다. 스토리지 복원이 완료된 후 SnapCenter는 복구 작업 전의 ASM 디스크 그룹 상태를 변경합니다.

SAN 환경에서는 SnapCenter가 모든 피어 노드에서 디바이스를 제거하고 스토리지 복구 작업 전에 LUN 매핑 해제 작업을 수행합니다. 스토리지 복구 작업 후 SnapCenter는 LUN 맵 작업을 수행하고 모든 피어 노드에 디바이스를 구성합니다. SAN 환경에서 Oracle RAC ASM 레이아웃이 LUN에 있는 경우 SnapCenter를 복구하는 동안 ASM 디스크 그룹이 상주하는 RAC 클러스터의 모든 노드에서 LUN 매핑 해제, LUN 복원 및 LUN 맵 작업을 수행합니다. LUN에 RAC 노드의 모든 이니시에이터가 사용되지 않은 경우에도 복원하기 전에 SnapCenter을 복원하면 모든 RAC 노드의 모든 이니시에이터가 포함된 새 iGroup이 생성됩니다.

* 피어 노드에서 PreRestore 작업 중에 오류가 발생한 경우 SnapCenter는 PreRestore 작업이 성공한 피어 노드에서 복원을 수행하기 전에 ASM 디스크 그룹 상태를 그대로 자동으로 롤백합니다. 롤백은 작업이 실패한 기본 노드 및 피어 노드에 대해 지원되지 않습니다. 다른 복구를 시도하기 전에 피어 노드의 문제를 수동으로 해결하고 기본 노드의 ASM 디스크 그룹을 마운트 상태로 되돌리시어야 합니다.
* 복구 작업 중에 오류가 발생하면 복구 작업이 실패하고 롤백이 수행되지 않습니다. 다른 복원을 시도하기 전에 스토리지 복원 문제를 수동으로 해결하고 기본 노드의 ASM 디스크 그룹을 마운트 상태로 되돌리시어야 합니다.
* 피어 노드에서 PostRestore 작업 중에 오류가 발생하면 SnapCenter는 다른 피어 노드에서 복구 작업을 계속합니다. 피어 노드에서 사후 복원 문제를 수동으로 해결해야 합니다.




== Oracle 데이터베이스에 지원되는 복원 작업의 유형입니다

SnapCenter를 사용하면 Oracle 데이터베이스에 대해 다양한 유형의 복원 작업을 수행할 수 있습니다.

데이터베이스를 복구하기 전에 실제 데이터베이스 파일과 비교하여 누락된 파일이 있는지 여부를 확인하기 위해 백업을 검증합니다.



=== 전체 복원

* 데이터 파일만 복구합니다
* 제어 파일만 복원합니다
* 데이터 파일 및 제어 파일을 복원합니다
* Data Guard 대기 및 Active Data Guard 대기 데이터베이스에서 데이터 파일, 제어 파일 및 재실행 로그 파일을 복구합니다




=== 부분 복원

* 선택한 테이블스페이서만 복구합니다
* 선택한 플러깅 지원 데이터베이스(PDB)만 복원합니다.
* PDB에서 선택한 테이블스페이서만 복구합니다




== Oracle 데이터베이스에 지원되는 복구 작업의 유형입니다

SnapCenter를 사용하면 Oracle 데이터베이스에 대해 다양한 유형의 복구 작업을 수행할 수 있습니다.

* 마지막 트랜잭션까지의 데이터베이스(모든 로그)
* 데이터베이스를 특정 SCN(시스템 변경 번호)까지
* 데이터베이스를 특정 날짜 및 시간까지 설정합니다
+
데이터베이스 호스트의 표준 시간대를 기준으로 복구 날짜와 시간을 지정해야 합니다.

+
또한 SnapCenter는 Oracle 데이터베이스에 대해 복구 안 함 옵션을 제공합니다.




NOTE: 데이터베이스 역할을 대기 상태로 사용하여 만든 백업을 사용하여 복원한 경우 Oracle 데이터베이스용 플러그인은 복구를 지원하지 않습니다. 물리적 대기 데이터베이스에 대해 항상 수동 복구를 수행해야 합니다.



== Oracle 데이터베이스 복원 및 복구와 관련된 제한 사항

복구 및 복구 작업을 수행하기 전에 제한 사항을 숙지해야 합니다.

11.2.0.4 ~ 12.1.0.1의 Oracle 버전을 사용하는 경우 _renamedg_command를 실행하면 복원 작업이 멈춤 상태가 됩니다. Oracle 패치 19544733을 적용하여 이 문제를 해결할 수 있습니다.

다음 복원 및 복구 작업은 지원되지 않습니다.

* 루트 컨테이너 데이터베이스(CDB)의 테이블스페이스 복구 및 복구
* PDB와 연결된 임시 테이블스페이스 및 임시 테이블스페이스의 복구
* 여러 PDB에서 테이블스페이스를 동시에 복원 및 복구합니다
* 로그 백업 복구
* 백업을 다른 위치로 복구합니다
* Data Guard 대기 또는 Active Data Guard 대기 데이터베이스 이외의 모든 구성에서 REDO 로그 파일 복원
* SPFILE 및 암호 파일 복원
* 동일한 호스트에서 기존 데이터베이스 이름을 사용하여 다시 생성된 데이터베이스에 대해 복구 작업을 수행하고, SnapCenter에서 관리하며, 유효한 백업을 가지고 있는 경우, 복구 작업은 DBID가 서로 다르지만 새로 생성된 데이터베이스 파일을 덮어씁니다.
+
다음 작업 중 하나를 수행하면 이 문제를 방지할 수 있습니다.

+
** 데이터베이스를 다시 만든 후 SnapCenter 리소스를 검색합니다
** 다시 생성된 데이터베이스의 백업을 생성합니다






== 테이블스페이스의 시점 복구와 관련된 제한 사항

* 시스템, SYSAUX 및 실행 취소 테이블스페이스의 PITR(시점 복구)은 지원되지 않습니다
* 테이블스페이스의 PITR은 다른 유형의 복원과 함께 수행할 수 없습니다
* 테이블스페이스의 이름이 바뀌었고 이름을 바꾸기 전에 테이블스페이스를 특정 지점으로 복구하려면 테이블스페이스의 이전 이름을 지정해야 합니다
* 한 테이블스페이스에 있는 테이블에 대한 제약 조건이 다른 테이블스페이스에 포함되어 있는 경우 두 테이블스페이스를 모두 복구해야 합니다
* 테이블과 해당 인덱스가 다른 테이블스페이스에 저장된 경우 PITR을 수행하기 전에 인덱스를 삭제해야 합니다
* PITR은 현재 기본 테이블스페이스를 복구하는 데 사용할 수 없습니다
* PITR은 다음 객체를 포함하는 테이블스페이스를 복구하는 데 사용할 수 없습니다.
+
** 모든 내부 또는 포함된 개체가 복구 집합에 없는 경우 기본 개체(예: 구체화된 뷰) 또는 포함된 개체(예: 분할된 테이블)가 있는 개체입니다
+
또한 분할된 테이블의 파티션이 서로 다른 테이블스페이스에 저장된 경우 PITR을 수행하기 전에 테이블을 놓거나 PITR을 수행하기 전에 모든 파티션을 동일한 테이블스페이스로 이동해야 합니다.

** 세그먼트 실행 취소 또는 롤백
** 여러 수신인이 있는 Oracle 8 호환 고급 대기열
** SYS 사용자가 소유하는 객체입니다
+
이러한 유형의 오브젝트의 예로는 PL/SQL, Java 클래스, 프로그램 호출, 보기, 동의어, 사용자, 권한, 차원, 디렉터리 및 시퀀스







== Oracle 데이터베이스 복원을 위한 소스 및 대상

운영 스토리지 또는 보조 스토리지의 백업 복사본에서 Oracle 데이터베이스를 복원할 수 있습니다. 데이터베이스를 동일한 데이터베이스 인스턴스의 동일한 위치로만 복원할 수 있습니다. 그러나 RAC(Real Application Cluster) 설정에서는 데이터베이스를 다른 노드로 복원할 수 있습니다.



=== 복구 작업을 위한 소스

운영 스토리지 또는 보조 스토리지의 백업에서 데이터베이스를 복원할 수 있습니다. 여러 미러 구성의 보조 스토리지에 있는 백업에서 복구하려면 보조 스토리지 미러를 소스로 선택할 수 있습니다.



=== 복원 작업의 대상

데이터베이스를 동일한 데이터베이스 인스턴스의 동일한 위치로만 복원할 수 있습니다.

RAC 설정에서는 클러스터의 모든 노드에서 RAC 데이터베이스를 복원할 수 있습니다.
