---
permalink: protect-sco/task_clone_oracle_database_backups_using_unix_commands.html 
sidebar: sidebar 
keywords: clone, CLI, commands 
summary: 클론 워크플로우에는 계획, 클론 작업 수행 및 작업 모니터링이 포함됩니다. 
---
= UNIX 명령을 사용하여 Oracle 데이터베이스 백업의 클론을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클론 워크플로우에는 계획, 클론 작업 수행 및 작업 모니터링이 포함됩니다.

* 이 작업에 대한 정보 *

다음 명령을 실행하여 Oracle 데이터베이스 클론 사양 파일을 생성하고 클론 작업을 시작해야 합니다.

명령에 사용할 수 있는 매개 변수 및 해당 설명에 대한 정보는 get-Help_command_name_을 실행하여 얻을 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885486["SnapCenter 소프트웨어 명령 참조 가이드"^].

* 단계 *

. 지정된 백업에서 Oracle 데이터베이스 클론 사양을 생성합니다._New-SmOracleCloneSpecification_
+

NOTE: 보조 데이터 보호 정책이 통합 미러 볼트이면 -IncludeSecondaryDetails만 지정합니다. SecondaryStorageType 을 지정할 필요가 없습니다.

+
이 명령은 지정된 소스 데이터베이스 및 해당 백업에 대한 Oracle 데이터베이스 클론 사양 파일을 자동으로 생성합니다. 또한 생성할 클론 데이터베이스에 대해 생성된 지정 파일에 자동으로 생성된 값이 있도록 클론 데이터베이스 SID를 제공해야 합니다.

+

NOTE: 클론 사양 파일은 _/var/opt/snapcenter/sSCO/clone_spec_에서 생성됩니다.

. 클론 리소스 그룹 또는 기존 백업에서 클론 작업을 시작합니다. _ New - SmClone _
+
이 명령은 클론 작업을 시작합니다. 또한 클론 작업을 위한 Oracle 클론 사양 파일 경로를 제공해야 합니다. 복구 옵션, 클론 작업을 수행할 호스트, 처방점, 사후 스크립트 및 기타 세부 정보를 지정할 수도 있습니다.

+
기본적으로 클론 데이터베이스의 아카이브 로그 대상 파일은 _$ORACLE_HOME/clone_SID_에 자동으로 채워집니다.


