---
permalink: protect-sce/task_create_backup_policies_for_exchange_server_databases.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter를 사용하여 Microsoft Exchange Server 리소스를 백업하기 전에 Exchange 리소스 또는 리소스 그룹에 대한 백업 정책을 만들거나 리소스 그룹을 만들거나 단일 리소스를 백업할 때 백업 정책을 만들 수 있습니다. 
---
= Exchange Server 데이터베이스에 대한 백업 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하여 Microsoft Exchange Server 리소스를 백업하기 전에 Exchange 리소스 또는 리소스 그룹에 대한 백업 정책을 만들거나 리소스 그룹을 만들거나 단일 리소스를 백업할 때 백업 정책을 만들 수 있습니다.

* 필요한 것 *

* 데이터 보호 전략을 정의해야 합니다.
+
자세한 내용은 Exchange 데이터베이스에 대한 데이터 보호 전략 정의에 대한 정보를 참조하십시오.

* SnapCenter 설치, 호스트 추가, 리소스 식별 및 스토리지 시스템 접속 생성과 같은 작업을 완료하여 데이터 보호를 위한 준비를 갖추어야 합니다.
* Exchange Server 리소스를 새로 고친(검색된) 상태여야 합니다.
* 스냅샷 복사본을 미러 또는 볼트에 복제하는 경우 SnapCenter 관리자는 소스 볼륨과 타겟 볼륨 모두에 SVM(스토리지 가상 머신)을 할당해야 합니다.
* powershell 스크립트를 p규정된 ppts 및 postscripts로 실행하려면 web.config 파일에서 usePowershellProcessforScripts 매개 변수의 값을 true로 설정해야 합니다.
+
기본값은 false 입니다



* 이 작업에 대한 정보 *

백업 정책은 백업을 관리 및 유지하는 방법과 리소스 또는 리소스 그룹을 백업하는 빈도를 제어하는 규칙의 집합입니다. 또한 스크립트 설정을 지정할 수도 있습니다. 정책에 옵션을 지정하면 다른 리소스 그룹에 대한 정책을 다시 사용할 때 시간이 절약됩니다.

전체 백업 보존은 특정 정책에 따라 다릅니다. 정책 A를 사용하여 전체 백업 보존 기간이 4인 데이터베이스 또는 리소스는 전체 백업 4개를 보유하며 동일한 데이터베이스 또는 리소스에 대해 정책 B에 영향을 미치지 않습니다. 이 경우 3개의 전체 백업을 유지하기 위해 보존 기간이 3일 수 있습니다.

로그 백업 보존은 정책에 따라 효과적이며 데이터베이스 또는 리소스의 모든 로그 백업에 적용됩니다. 따라서 정책 B를 사용하여 전체 백업을 수행할 경우 로그 보존 설정은 정책 A가 동일한 데이터베이스 또는 리소스에 생성한 로그 백업에 영향을 줍니다. 마찬가지로 정책 A의 로그 보존 설정은 정책 B가 동일한 데이터베이스의 로그 백업에 영향을 줍니다.

|===


| * 모범 사례: * 보존하려는 전체 및 로그 백업 수에 따라 보조 보존 정책을 구성하는 것이 좋습니다. 2차 보존 정책을 구성할 때는 데이터베이스와 로그가 서로 다른 볼륨에 있을 때 각 백업마다 3개의 스냅샷 복사본을 가질 수 있고 데이터베이스와 로그가 같은 볼륨에 있을 때는 각 백업마다 2개의 스냅샷 복사본을 가질 수 있다는 점을 유의해야 합니다. 
|===
* 단계 *

. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 정책 * 을 클릭합니다.
. 새로 만들기 * 를 클릭합니다.
. 이름 페이지에 정책 이름과 설명을 입력합니다.
. 백업 유형 페이지에서 다음 단계를 수행하십시오.
+
.. 백업 유형 선택:
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
데이터베이스 파일 및 필요한 트랜잭션 로그를 백업합니다
 a| 
전체 백업 및 로그 백업 * 을 선택합니다.

데이터베이스는 로그 잘라내기를 통해 백업되며 잘린 로그를 포함하여 모든 로그가 백업됩니다.


NOTE: 권장되는 백업 유형입니다.



 a| 
데이터베이스 파일 및 커밋되지 않은 트랜잭션 로그를 백업합니다
 a| 
전체 백업 * 을 선택합니다.

데이터베이스는 로그 잘라내기를 통해 백업되며 잘린 로그는 백업되지 않습니다.



 a| 
모든 트랜잭션 로그를 백업합니다
 a| 
Log backup * 을 선택합니다.

활성 파일 시스템의 모든 트랜잭션 로그가 백업되며 로그 잘라내기가 없습니다.

_scebackupinfo_directory가 라이브 로그와 동일한 디스크에 생성됩니다. 이 디렉토리에는 Exchange 데이터베이스의 증가분 변경 사항에 대한 포인터가 포함되어 있으며 전체 로그 파일과 동일하지는 않습니다.



 a| 
트랜잭션 로그 파일을 자르지 않고 모든 데이터베이스 파일 및 트랜잭션 로그를 백업합니다
 a| 
백업 복사 * 를 선택합니다.

모든 데이터베이스 및 모든 로그가 백업되며 로그 잘라내기가 없습니다. 일반적으로 이 백업 유형을 사용하여 복제본을 다시 시드하거나 문제를 테스트 또는 진단할 수 있습니다.

|===
+

NOTE: UTM(최신) 보존이 아닌 전체 백업 보존을 기준으로 로그 백업에 필요한 공간을 정의해야 합니다.

.. 데이터베이스 사용 가능 그룹 설정 섹션에서 작업을 선택합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
활성 복사본을 백업합니다
 a| 
선택한 데이터베이스의 활성 사본만 백업하려면 이 옵션을 선택합니다.

DAG(데이터베이스 가용성 그룹)의 경우 이 옵션은 DAG에 있는 모든 데이터베이스의 액티브 복제본만 백업합니다.

패시브 복사본은 백업되지 않습니다.



 a| 
백업 작업 생성 시 선택할 서버의 복사본을 백업합니다
 a| 
활성 서버와 수동 서버 모두에서 선택한 서버의 데이터베이스 복사본을 백업하려면 이 옵션을 선택합니다.

DAG의 경우 이 옵션은 선택한 서버에 있는 모든 데이터베이스의 액티브 복제본과 패시브 복제본을 모두 백업합니다.

|===
+

NOTE: 클러스터 구성에서 백업은 정책에 설정된 보존 설정에 따라 클러스터의 각 노드에 유지됩니다. 클러스터의 소유자 노드가 변경되면 이전 소유자 노드의 백업이 유지됩니다. 보존은 노드 레벨에서만 적용됩니다.

.. 일정 빈도 섹션에서 * On demand *, * Hourly *, * Daily *, * Weekly *, * Monthly * 등의 빈도 유형을 하나 이상 선택합니다.
+

NOTE: 리소스 그룹을 생성하는 동안 백업 작업의 스케줄(시작 날짜, 종료 날짜)을 지정할 수 있습니다. 이렇게 하면 동일한 정책 및 백업 빈도를 공유하는 리소스 그룹을 생성할 수 있지만 각 정책에 서로 다른 백업 스케줄을 할당할 수 있습니다.

+

NOTE: 오전 2시에 예약된 경우 DST(일광 절약 시간) 중에는 일정이 트리거되지 않습니다.



. 보존 페이지에서 보존 설정을 구성합니다.
+
표시되는 옵션은 이전에 선택한 백업 유형 및 빈도 유형에 따라 달라집니다.

+

NOTE: 최대 보존 값은 ONTAP 9.4 이상의 리소스에 대해 1018이고, ONTAP 9.3 이전 버전의 리소스에 대해서는 254입니다. 보존이 기본 ONTAP 버전에서 지원하는 값보다 높은 값으로 설정된 경우 백업이 실패합니다.

+

IMPORTANT: SnapVault 복제를 설정하려면 보존 수를 2 이상으로 설정해야 합니다. 보존 횟수를 1로 설정하면 새 스냅샷 복사본이 타겟으로 복제될 때까지 첫 번째 스냅샷 복사본이 SnapVault 관계의 참조 스냅샷 복사본이므로 보존 작업이 실패할 수 있습니다.

+
.. 로그 백업 보존 설정 섹션에서 다음 중 하나를 선택합니다.
+
|===
| 원하는 작업 | 수행할 작업... 


 a| 
특정 수의 로그 백업만 유지합니다
 a| 
로그가 유지되는 전체 백업 수 * 를 선택하고 최신 복원 기능을 원하는 전체 백업 수를 지정합니다.

UTM(최신) 보존은 전체 또는 로그 백업을 통해 생성된 로그 백업에 적용됩니다. 예를 들어, UTM 보존 설정이 마지막 5개의 전체 백업의 로그 백업을 유지하도록 구성된 경우 마지막 5개의 전체 백업의 로그 백업이 보존됩니다.

전체 및 로그 백업의 일부로 생성된 로그 폴더는 UTM의 일부로 자동으로 삭제됩니다. 로그 폴더는 수동으로 삭제할 수 없습니다. 예를 들어 전체 또는 전체 및 로그 백업의 보존 설정이 1개월로 설정되고 UTM 보존이 10일로 설정된 경우, UTM에 따라 이러한 백업의 일부로 생성된 로그 폴더가 삭제됩니다. 따라서 10일 로그 폴더만 있고 다른 모든 백업은 시점 복원으로 표시됩니다.

최신 복원을 수행하지 않으려는 경우 UTM 보존 값을 0으로 설정할 수 있습니다. 그러면 시점 복원 작업이 활성화됩니다.

* 모범 사례: * 전체 백업 보존 설정 섹션의 전체 스냅샷 복사본(전체 백업) 설정과 같은 설정을 사용하는 것이 좋습니다. 이렇게 하면 각 전체 백업에 대해 로그 파일이 유지됩니다.



 a| 
백업 사본을 특정 기간 동안 보관합니다
 a| 
Keep log backups for Last * 옵션을 선택하고 로그 백업 사본을 보관할 일 수를 지정합니다.

전체 백업 일수까지 로그 백업이 보존됩니다.

|===
+
백업 유형으로 * 로그 백업 * 을 선택한 경우 로그 백업은 전체 백업에 대한 최신 보존 설정의 일부로 보존됩니다.

.. 전체 백업 보존 설정 섹션에서 필요 시 백업에 대해 다음 중 하나를 선택한 다음 전체 백업에 대해 하나를 선택합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
특정 수의 스냅샷 복사본만 보유합니다
 a| 
유지할 전체 백업 수를 지정하려면 * 유지할 총 스냅샷 복사본 * 옵션을 선택하고 유지할 스냅샷 복사본(전체 백업) 수를 지정합니다.

전체 백업 수가 지정된 수를 초과하면 지정된 수를 초과하는 전체 백업이 삭제되며 가장 오래된 복제본이 먼저 삭제됩니다.



 a| 
특정 기간 동안 전체 백업을 보존합니다
 a| 
스냅샷 복사본 보관 * 옵션을 선택하고 스냅샷 복사본을 보관할 일 수(전체 백업)를 지정합니다.

|===
+

NOTE: DAG 구성에서 호스트에 대한 전체 백업이 없는 로그 백업만 있는 데이터베이스가 있는 경우 로그 백업은 다음과 같은 방식으로 유지됩니다.

+
*** 기본적으로 SnapCenter는 DAG의 다른 모든 호스트에서 이 데이터베이스에 대해 가장 오래된 전체 백업을 찾고 전체 백업 전에 이 호스트에서 수행된 모든 로그 백업을 삭제합니다.
*** DAG의 호스트에 있는 데이터베이스의 기본 보존 동작은 _C:\Program Files\NetApp\SnapCenter WebApp\web.config_file에 * MaxLogBackupOnlyWithoutFullBackup * 키를 추가하여 로그 백업만 사용하여 재정의할 수 있습니다.
+
 <add key="MaxLogBackupOnlyCountWithoutFullBackup" value="10">
+
이 예에서 값 10은 호스트에 최대 10개의 로그 백업을 유지하는 것을 의미합니다.





. 복제 페이지에서 다음 보조 복제 옵션 중 하나 또는 둘 다를 선택합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
로컬 스냅샷 복사본을 생성한 후 SnapMirror를 업데이트합니다
 a| 
백업 세트의 미러 복사본을 다른 볼륨(SnapMirror)에 유지하려면 이 옵션을 선택합니다.



 a| 
로컬 스냅샷 복사본을 생성한 후 SnapVault를 업데이트합니다
 a| 
디스크 간 백업 복제를 수행하려면 이 옵션을 선택합니다.



 a| 
보조 정책 레이블입니다
 a| 
스냅샷 레이블을 선택합니다.

선택한 스냅샷 복사본 레이블에 따라 ONTAP에서는 해당 레이블과 일치하는 2차 스냅샷 복사본 보존 정책을 적용합니다.


NOTE: 로컬 스냅샷 복사본 * 을 생성한 후 SnapMirror 업데이트 * 를 선택한 경우, 선택적으로 보조 정책 레이블을 지정할 수 있습니다. 그러나 로컬 스냅샷 복사본 * 을 생성한 후 * SnapVault 업데이트 * 를 선택한 경우에는 보조 정책 레이블을 지정해야 합니다.



 a| 
오류 재시도 횟수입니다
 a| 
프로세스가 중지되기 전에 수행해야 하는 복제 시도 횟수를 입력합니다.

|===
+

NOTE: 보조 스토리지에 대한 ONTAP의 SnapMirror 보존 정책을 구성하면 보조 스토리지에서 스냅샷 복사본의 최대 제한에 도달하지 않도록 해야 합니다.

. 스크립트 페이지에서 백업 작업 전후에 실행해야 하는 처방인 또는 PS의 경로와 인수를 각각 입력합니다.
+
** Prescript 백업 인수에는 ""$Database" 및 ""$ServerInstance" 가 포함됩니다.
** 포스트스크립트 백업 인수에는 ""$Database", "$ServerInstance", "$BackupName", "$LogDirectory" 및 "$LogSnapshot""이 포함됩니다.
+
스크립트를 실행하여 SNMP 트랩을 업데이트하고, 경고를 자동화하고, 로그를 보내는 등의 작업을 수행할 수 있습니다.



. 요약을 검토하고 * Finish * 를 클릭합니다.

