---
permalink: protect-sce/task_set_up_credentials_for_the_snapcenter_plug_in_for_windows_sce.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter는 자격 증명을 사용하여 SnapCenter 작업을 위해 사용자를 인증합니다. 플러그인 패키지를 설치하기 위한 자격 증명과 데이터베이스에서 데이터 보호 작업을 수행하기 위한 추가 자격 증명을 만들어야 합니다. 
---
= Windows용 SnapCenter 플러그인의 자격 증명을 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter는 자격 증명을 사용하여 SnapCenter 작업을 위해 사용자를 인증합니다. 플러그인 패키지를 설치하기 위한 자격 증명과 데이터베이스에서 데이터 보호 작업을 수행하기 위한 추가 자격 증명을 만들어야 합니다.

* 이 작업에 대한 정보 *

Windows 호스트에 플러그인을 설치하기 위한 자격 증명을 설정해야 합니다. 호스트를 구축하고 플러그인을 설치한 후 Windows에 대한 자격 증명을 생성할 수 있지만, 호스트를 구축하고 플러그인을 설치하기 전에 SVM을 추가한 후에 자격 증명을 생성하는 것이 가장 좋습니다.

원격 호스트에 대한 관리자 권한을 포함하여 관리자 권한으로 자격 증명을 설정합니다.

개별 리소스 그룹에 대한 자격 증명을 설정했고 사용자 이름에 전체 관리자 권한이 없는 경우 최소한 리소스 그룹 및 백업 권한을 사용자 이름에 할당해야 합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 자격 증명 * 을 클릭합니다.
. 새로 만들기 * 를 클릭합니다.
+
자격 증명 창이 표시됩니다.

. 자격 증명 페이지에서 다음을 실행합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
자격 증명 이름입니다
 a| 
자격 증명의 이름을 입력합니다.



 a| 
사용자 이름
 a| 
인증에 사용되는 사용자 이름을 입력합니다.

** 도메인 관리자 또는 관리자 그룹의 구성원
+
SnapCenter 플러그인을 설치할 시스템의 도메인 관리자 또는 관리자 그룹의 구성원을 지정합니다. 사용자 이름 필드에 유효한 형식은 다음과 같습니다.

+
*** 'NetBIOS\사용자 이름'
*** Domain FQDN\username'입니다


** 로컬 관리자(작업 그룹에만 해당)
+
작업 그룹에 속한 시스템의 경우 SnapCenter 플러그인을 설치할 시스템에 기본 제공 로컬 관리자를 지정합니다. 사용자 계정에 상승된 권한이 있거나 호스트 시스템에서 사용자 액세스 제어 기능이 비활성화된 경우 로컬 관리자 그룹에 속하는 로컬 사용자 계정을 지정할 수 있습니다. 사용자 이름 필드의 올바른 형식은 '사용자 이름'입니다





 a| 
암호
 a| 
인증에 사용되는 암호를 입력합니다.



 a| 
인증
 a| 
인증 모드로 Windows를 선택합니다.

|===
. 확인 * 을 클릭합니다.

