---
permalink: protect-sce/task_restore_exchange_resources_using_powershell_cmdlets.html 
sidebar: sidebar 
keywords: restore 
summary: Exchange 데이터베이스 복구에는 SnapCenter 서버와의 연결 세션 시작, 백업 목록 표시 및 백업 정보 검색, 백업 복구가 포함됩니다. 
---
= PowerShell cmdlet을 사용하여 Exchange 리소스를 복원합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Exchange 데이터베이스 복구에는 SnapCenter 서버와의 연결 세션 시작, 백업 목록 표시 및 백업 정보 검색, 백업 복구가 포함됩니다.

PowerShell cmdlet을 실행하려면 PowerShell 환경을 준비해야 합니다.

* 단계 *

. Open-SmConnection cmdlet을 사용하여 지정된 사용자에 대해 SnapCenter Server와 연결 세션을 시작합니다.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146/
----
. Get-SmBackup cmdlet을 사용하여 복원하려는 하나 이상의 백업에 대한 정보를 검색합니다.
+
이 예에서는 사용 가능한 모든 백업에 대한 정보를 표시합니다.

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
341                           ResourceGroup_36304978_UTM... 12/8/2017 4:13:24 PM          Full Backup
342                           ResourceGroup_36304978_UTM... 12/8/2017 4:16:23 PM          Full Backup
355                           ResourceGroup_06140588_UTM... 12/8/2017 6:32:36 PM          Log Backup
356                           ResourceGroup_06140588_UTM... 12/8/2017 6:36:20 PM          Full Backup
----
. Restore-SmBackup cmdlet을 사용하여 백업에서 데이터를 복원합니다.
+
이 예에서는 최신 백업을 복원합니다.

+
[listing]
----
C:\PS> Restore-SmBackup -PluginCode SCE -AppObjectId 'sce-w2k12-exch.sceqa.com\sce-w2k12-exch_DB_2' -BackupId 341 -IsRecoverMount:$true
----
+
이 예에서는 시점 백업을 복원합니다.

+
[listing]
----
C:\ PS> Restore-SmBackup -PluginCode SCE -AppObjectId 'sce-w2k12-exch.sceqa.com\sce-w2k12-exch_DB_2' -BackupId 341 -IsRecoverMount:$true -LogRestoreType ByTransactionLogs -LogCount 2
----
+
이 예에서는 보조 스토리지의 백업을 1차 사례로 복원합니다.

+
[listing]
----
C:\ PS> Restore-SmBackup -PluginCode 'SCE' -AppObjectId 'DB2' -BackupId 81 -IsRecoverMount:$true -Confirm:$false
-archive @{Primary="paw_vs:vol1";Secondary="paw_vs:vol1_mirror"} -logrestoretype All
----
+
'-archive' 매개 변수를 사용하면 복원에 사용할 운영 볼륨과 2차 볼륨을 지정할 수 있습니다.

+
'-IsRecoverMount:$true' 매개 변수를 사용하면 복구 후에 데이터베이스를 마운트할 수 있습니다.



cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2880726["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].
