---
permalink: protect-sce/task_define_a_restore_strategy_for_exchange_databases.html 
sidebar: sidebar 
keywords:  
summary: Exchange Server에 대한 복원 전략을 정의하면 데이터베이스를 성공적으로 복원할 수 있습니다. 
---
= Exchange 데이터베이스에 대한 복구 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Exchange Server에 대한 복원 전략을 정의하면 데이터베이스를 성공적으로 복원할 수 있습니다.



== Exchange Server의 복구 작업에 대한 소스

기본 스토리지의 백업 복사본에서 Exchange Server 데이터베이스를 복원할 수 있습니다.

운영 스토리지에서만 데이터베이스를 복원할 수 있습니다.



== Exchange Server에 대해 지원되는 복구 작업 유형입니다

SnapCenter를 사용하여 Exchange 리소스에 대해 다양한 유형의 복구 작업을 수행할 수 있습니다.

* 최신 상태로 복원합니다
* 이전 시점으로 복원합니다




=== 최대 1분 내에 복원합니다

최신 복원 작업에서 데이터베이스는 장애 지점까지 복구됩니다. SnapCenter는 다음 시퀀스를 실행하여 이를 수행합니다.

. 선택한 전체 데이터베이스 백업에서 데이터베이스를 복원합니다.
. 백업된 모든 트랜잭션 로그와 가장 최근 백업 이후에 생성된 새 로그를 적용합니다.
+
트랜잭션 로그가 앞으로 이동되어 선택한 데이터베이스에 적용됩니다.

+
복구가 완료된 후 Exchange에서 새 로그 체인을 생성합니다.

+
|===


| * 모범 사례: * 복원이 완료된 후 새 전체 및 로그 백업을 수행하는 것이 좋습니다. 
|===
+
최신 복원 작업을 수행하려면 일련의 트랜잭션 로그가 필요합니다.

+
최신 복원을 수행한 후에는 복구에 사용한 백업을 시점 복원 작업에만 사용할 수 있습니다.

+
모든 백업에 대해 최신 복원 기능을 유지할 필요가 없는 경우 백업 정책을 통해 시스템의 트랜잭션 로그 백업 보존을 구성할 수 있습니다.





=== 이전 시점으로 복원합니다

시점 복원 작업에서는 데이터베이스가 과거의 특정 시간으로만 복원됩니다. 시점 복원 작업은 다음과 같은 복원 상황에서 수행됩니다.

* 데이터베이스는 백업된 트랜잭션 로그에서 지정된 시간으로 복원됩니다.
* 데이터베이스가 복원되고 백업된 트랜잭션 로그의 하위 집합만 데이터베이스에 적용됩니다.

