---
permalink: protect-sce/task_define_a_backup_strategy_for_exchange_server_resources.html 
sidebar: sidebar 
keywords:  
summary: '백업 작업을 생성하기 전에 백업 전략을 정의하면 데이터베이스를 성공적으로 복원하는 데 필요한 백업이 있는지 확인하는 데 도움이 됩니다. 서비스 수준 계약(SLA), 복구 시간 목표(RTO) 및 복구 시점 목표\(RPO\)에 따라 백업 전략이 주로 결정됩니다.' 
---
= Exchange Server 리소스에 대한 백업 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 작업을 생성하기 전에 백업 전략을 정의하면 데이터베이스를 성공적으로 복원하는 데 필요한 백업이 있는지 확인하는 데 도움이 됩니다. SLA(서비스 수준 계약), RTO(복구 시간 목표) 및 RPO(복구 시점 목표)에 따라 백업 전략이 크게 결정됩니다.

SLA는 예상되는 서비스 수준을 정의하고 가용성 및 서비스 성능을 비롯한 다양한 서비스 관련 문제를 해결합니다. RTO는 서비스 중단 후 비즈니스 프로세스를 복원해야 하는 시간입니다. RPO는 장애 후 정상적인 작업을 재개하기 위해 백업 스토리지에서 복구해야 하는 파일의 사용 기간에 대한 전략을 정의합니다. SLA, RTO 및 RPO는 백업 전략에 기여합니다.



== Exchange 데이터베이스에 대해 지원되는 백업 유형입니다

SnapCenter를 사용하여 Exchange 메일박스를 백업하려면 데이터베이스 및 DAG(데이터베이스 가용성 그룹)와 같은 리소스 유형을 선택해야 합니다. 스냅샷 복사본 기술은 리소스가 상주하는 볼륨의 온라인 읽기 전용 복사본을 생성하는 데 사용됩니다.

|===
| 백업 유형 | 설명 


 a| 
전체 및 로그 백업
 a| 
잘린 로그를 포함하여 데이터베이스와 모든 트랜잭션 로그를 백업합니다.

전체 백업이 완료되면 Exchange Server는 데이터베이스에 이미 커밋된 트랜잭션 로그를 잘라냅니다.

일반적으로 이 옵션을 선택해야 합니다. 그러나 백업 시간이 짧은 경우에는 전체 백업을 사용하여 트랜잭션 로그 백업을 실행하지 않도록 선택할 수 있습니다.



 a| 
전체 백업
 a| 
데이터베이스 및 트랜잭션 로그를 백업합니다.

잘린 트랜잭션 로그는 백업되지 않습니다.



 a| 
로그 백업
 a| 
모든 트랜잭션 로그를 백업합니다.

데이터베이스에 이미 커밋된 잘린 로그는 백업되지 않습니다. 전체 데이터베이스 백업 간에 트랜잭션 로그 백업을 자주 예약하는 경우 세분화된 복구 지점을 선택할 수 있습니다.

|===


== 데이터베이스 플러그인에 대한 백업 스케줄입니다

백업 빈도(스케줄 유형)는 정책에 지정되며 백업 스케줄은 리소스 그룹 구성에 지정됩니다. 백업 빈도 또는 스케줄을 결정하는 가장 중요한 요소는 리소스의 변경 속도 및 데이터의 중요도입니다. 자주 사용하는 리소스를 매일 한 번씩 백업할 수도 있고, 자주 사용하지 않는 리소스를 하루에 한 번 백업할 수도 있습니다. 기타 요인으로는 조직에 대한 리소스의 중요성, SLA(서비스 수준 계약) 및 RPO(복구 시점 목표)가 있습니다.

SLA는 예상되는 서비스 수준을 정의하고 가용성 및 서비스 성능을 비롯한 다양한 서비스 관련 문제를 해결합니다. RPO는 장애 후 정상적인 작업을 재개하기 위해 백업 스토리지에서 복구해야 하는 파일의 사용 기간에 대한 전략을 정의합니다. SLA 및 RPO는 데이터 보호 전략에 기여합니다.

사용량이 많은 리소스의 경우에도 하루에 한 번 또는 두 번 이상 전체 백업을 실행할 필요가 없습니다. 예를 들어 정기적인 트랜잭션 로그 백업만으로도 필요한 백업이 있는지 확인할 수 있습니다. 데이터베이스를 더 자주 백업할수록 SnapCenter는 복원 시 사용해야 하는 트랜잭션 로그를 더 적게 사용하여 복원 작업을 더 빠르게 수행할 수 있습니다.

백업 스케줄은 다음과 같이 두 부분으로 구성됩니다.

* 백업 빈도
+
일부 플러그인에 대해 _schedule type_이라는 백업 빈도(백업 수행 빈도)는 정책 구성의 일부입니다. 정책의 백업 빈도로 시간별, 일별, 주별 또는 월별 을 선택할 수 있습니다. 이러한 빈도 중 하나를 선택하지 않으면 생성된 정책이 온디맨드 전용 정책입니다. 설정 * > * 정책 * 을 클릭하여 정책에 액세스할 수 있습니다.

* 백업 스케줄
+
백업 스케줄(백업을 수행할 정확한 시점)은 리소스 그룹 구성의 일부입니다. 예를 들어 주별 백업에 대한 정책이 구성된 리소스 그룹이 있는 경우 매주 목요일 오후 10시에 백업하도록 스케줄을 구성할 수 있습니다. 리소스 그룹 * > * 리소스 그룹 * 을 클릭하여 리소스 그룹 일정에 액세스할 수 있습니다.





== 데이터베이스에 필요한 백업 작업 수입니다

필요한 백업 작업 수를 결정하는 요인에는 리소스 크기, 사용된 볼륨 수, 리소스 변경 속도 및 SLA(서비스 수준 계약)가 포함됩니다.



== 백업 명명 규칙

기본 스냅샷 복사본 명명 규칙을 사용하거나 사용자 지정된 명명 규칙을 사용할 수 있습니다. 기본 백업 명명 규칙은 스냅샷 복사본 이름에 타임 스탬프를 추가하여 복사본이 생성된 시간을 식별하도록 도와줍니다.

스냅샷 복사본은 다음과 같은 기본 명명 규칙을 사용합니다.

'resourcegroupname_hostname_timestamp'

다음 예제와 같이 백업 리소스 그룹의 이름을 논리적으로 지정해야 합니다.

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
이 예제에서 구문 요소는 다음과 같은 의미를 가집니다.

* _dts1_은(는) 리소스 그룹 이름입니다.
* _mach1x88_은 호스트 이름입니다.
* _03-12-2015_23.17.26_은 날짜 및 타임스탬프입니다.


또는 * Use custom name format for Snapshot copy * 를 선택하여 리소스 또는 리소스 그룹을 보호하면서 스냅샷 복사본 이름 형식을 지정할 수 있습니다. 예를 들어 customtext_resourcegroup_policy_hostname 또는 resourcegroup_hostname을 입력합니다. 기본적으로 타임스탬프 접미사가 스냅샷 복사본 이름에 추가됩니다.



== 백업 보존 옵션

백업 복사본을 보존할 일 수를 선택하거나 유지할 백업 복사본 수를 최대 255개 사본의 ONTAP로 지정할 수 있습니다. 예를 들어, 조직에서 10일간 백업 복사본 또는 130개의 백업 복사본을 보존해야 할 수도 있습니다.

정책을 생성하는 동안 백업 유형 및 스케줄 유형에 대한 보존 옵션을 지정할 수 있습니다.

SnapMirror 복제를 설정하면 보존 정책이 대상 볼륨에 미러링됩니다.

SnapCenter는 스케줄 유형과 일치하는 보존 레이블이 있는 보존된 백업을 삭제합니다. 리소스 또는 리소스 그룹에 대한 스케줄 유형이 변경된 경우 이전 스케줄 유형 레이블이 있는 백업이 시스템에 남아 있을 수 있습니다.


NOTE: 백업 복사본을 장기간 보존하려면 SnapVault 백업을 사용해야 합니다.



== Exchange Server의 소스 스토리지 볼륨에 트랜잭션 로그 백업을 유지하는 기간

Microsoft Exchange Server용 SnapCenter 플러그인에는 최신 복원 작업을 수행하기 위한 트랜잭션 로그 백업이 필요합니다. 이 작업은 데이터베이스를 두 개의 전체 백업 사이의 시간으로 복원합니다.

예를 들어 Exchange용 플러그인이 오전 8시에 전체 및 트랜잭션 로그 백업을 수행하는 경우 또한 오후 5시에 전체 및 트랜잭션 로그 백업을 추가로 수행하면 최신 트랜잭션 로그 백업을 사용하여 오전 8시 사이에 언제든지 데이터베이스를 복원할 수 있습니다 오후 5시까지 운영됩니다 트랜잭션 로그를 사용할 수 없는 경우 Exchange용 플러그인은 시점 복원 작업만 수행할 수 있습니다. 그러면 Exchange용 플러그인에서 전체 백업을 완료한 시점으로 데이터베이스를 복원할 수 있습니다.

일반적으로 하루 또는 이틀 동안만 최신 복원 작업이 필요합니다. 기본적으로 SnapCenter는 최소 2일을 유지합니다.
