---
permalink: protect-scw/concept_snapcenter_plug_in_for_windows_features.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Windows용 플러그인은 스토리지 시스템의 NetApp Snapshot 기술과 통합됩니다. Windows용 플러그인으로 작업하려면 SnapCenter 인터페이스를 사용합니다. 
---
= Windows용 SnapCenter 플러그인 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows용 플러그인은 스토리지 시스템의 NetApp Snapshot 기술과 통합됩니다. Windows용 플러그인으로 작업하려면 SnapCenter 인터페이스를 사용합니다.

Windows용 플러그인에는 다음과 같은 주요 기능이 포함되어 있습니다.

* * SnapCenter * 기반 통합 그래픽 사용자 인터페이스
+
SnapCenter 인터페이스는 전체 플러그인과 환경에 걸쳐 표준화와 일관성을 제공합니다. SnapCenter 인터페이스를 사용하면 플러그인 전체에 걸쳐 일관된 백업 및 복원 프로세스를 완료하고, 중앙 집중식 보고, 대시보드 뷰 사용량을 한 눈에 확인 하고, RBAC(역할 기반 액세스 제어)를 설정하고, 모든 플러그인에 걸쳐 작업을 모니터링할 수 있습니다. 또한 SnapCenter는 중앙 집중식 스케줄링 및 정책 관리 기능을 제공하여 백업 및 클론 작업을 지원합니다.

* * 자동화된 중앙 관리 *
+
일상적인 파일 시스템 백업을 예약하고, 정책 기반 백업 보존을 구성하고, 복구 작업을 설정할 수 있습니다. 또한 e-메일 알림을 보내도록 SnapCenter를 구성하여 파일 시스템 환경을 사전 예방적으로 모니터링할 수도 있습니다.

* * 무중단 NetApp 스냅샷 기술 *
+
Windows용 플러그인은 NetApp 스냅샷 기술을 사용합니다. 따라서 몇 초 내에 파일 시스템을 백업하고 호스트를 오프라인으로 전환하지 않고도 신속하게 복구할 수 있습니다. 스냅샷은 최소한의 스토리지 공간을 사용합니다.



이러한 주요 기능 외에도 Windows용 플러그인은 다음과 같은 이점을 제공합니다.

* 백업, 복원 및 클론 워크플로우 지원
* RBAC 지원 보안 및 중앙 집중식 역할 위임
* NetApp FlexClone 기술을 사용하여 테스트 또는 데이터 추출을 위한 공간 효율적인 운영 파일 시스템 복사본 생성
+
FlexClone 라이센스에 대한 자세한 내용은 을 참조하십시오 link:../install/concept_snapcenter_licenses.html["SnapCenter 라이센스"^].

* 여러 서버에서 동시에 여러 백업을 실행할 수 있습니다
* 백업, 복원 및 클론 작업의 스크립팅을 위한 PowerShell cmdlet
* 파일 시스템 및 가상 시스템 디스크(VMDK)의 백업 지원
* 물리적 인프라와 가상화 인프라 지원
* iSCSI, Fibre Channel, FCoE, RDM(Raw Device Mapping), ALM(Asymmetric LUN Mapping), NFS 및 VMFS를 통한 VMDK 및 가상 FC 지원
* Windows Server 2022에서 비휘발성 메모리 익스프레스(NVMe) 지원
+
** TCP/IP를 통해 NVMe에 생성된 VMDK 레이아웃의 백업, 복원, 클론 복제 및 검증 워크플로우를 제공합니다.
** ESX 8.0 업데이트 2부터 NVMe 펌웨어 버전 1.3을 지원하며 가상 하드웨어 버전 21이 필요합니다.
** WSFC(Windows Server Failover Clustering)는 NVMe over TCP/IP의 VMDK 응용 프로그램에 대해 지원되지 않습니다.


* SnapMirror 액티브 동기화(처음에 SnapMirror Business Continuity[SM-BC]로 릴리스)를 지원하므로 전체 사이트 장애 시에도 비즈니스 서비스의 운영을 지속할 수 있으며, 2차 복사본을 사용하여 애플리케이션을 투명하게 페일오버할 수 있습니다. SnapMirror 액티브 동기화로 페일오버를 트리거하는 데 수동 개입이나 추가 스크립팅이 필요하지 않습니다.

