---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html 
sidebar: sidebar 
keywords: requirements 
summary: Windows용 플러그인을 설치하기 전에 특정 설치 요구 사항을 알고 있어야 합니다. 
---
= Microsoft Windows용 SnapCenter 플러그인 설치 요구 사항
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows용 플러그인을 설치하기 전에 특정 설치 요구 사항을 알고 있어야 합니다.

Windows용 플러그인을 사용하려면 먼저 SnapCenter 관리자가 SnapCenter 서버를 설치 및 구성하고 필수 작업을 수행해야 합니다.

* Windows용 플러그인을 설치하려면 SnapCenter 관리자 권한이 있어야 합니다.
+
SnapCenter 관리자 역할에는 관리자 권한이 있어야 합니다.

* SnapCenter 서버를 설치하고 구성해야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자의 경우 호스트에서 UAC를 비활성화해야 합니다.
* 백업 복제를 원하면 SnapMirror 및 SnapVault를 설정해야 합니다.




== Windows용 SnapCenter 플러그인 패키지를 설치하기 위한 호스트 요구 사항

Windows용 SnapCenter 플러그인 패키지를 설치하기 전에 몇 가지 기본적인 호스트 시스템 공간 요구 사항 및 사이징 요구 사항을 숙지해야 합니다.

|===
| 항목 | 요구 사항 


 a| 
운영 체제
 a| 
Microsoft Windows

지원되는 버전에 대한 최신 정보는 를 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].



 a| 
호스트의 SnapCenter 플러그인에 대한 최소 RAM입니다
 a| 
1GB



 a| 
호스트의 SnapCenter 플러그인에 대한 최소 설치 및 로그 공간
 a| 
5GB


NOTE: 충분한 디스크 공간을 할당하고 로그 폴더의 스토리지 사용량을 모니터링해야 합니다. 필요한 로그 공간은 보호할 엔터티의 수와 데이터 보호 작업의 빈도에 따라 달라집니다. 디스크 공간이 충분하지 않으면 최근 실행 작업에 대한 로그가 생성되지 않습니다.



 a| 
필요한 소프트웨어 패키지
 a| 
* Microsoft .NET Framework 4.5.2 이상
* WMF(Windows Management Framework) 4.0 이상
* PowerShell 4.0 이상


지원되는 버전에 대한 최신 정보는 를 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].

|===


== Windows용 플러그인의 자격 증명을 설정합니다

SnapCenter는 자격 증명을 사용하여 SnapCenter 작업을 위해 사용자를 인증합니다. SnapCenter 플러그인을 설치하기 위한 자격 증명과 Windows 파일 시스템에서 데이터 보호 작업을 수행하기 위한 추가 자격 증명을 만들어야 합니다.

* 필요한 것 *

* 플러그인을 설치하기 전에 Windows 자격 증명을 설정해야 합니다.
* 원격 호스트에서 관리자 권한을 비롯한 관리자 권한으로 자격 증명을 설정해야 합니다.
* 개별 리소스 그룹에 대한 자격 증명을 설정했고 사용자에게 전체 관리자 권한이 없는 경우 최소한 리소스 그룹 및 백업 권한을 사용자에게 할당해야 합니다.


* 단계 *

. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 자격 증명 * 을 클릭합니다.
. 새로 만들기 * 를 클릭합니다.
. 자격 증명 페이지에서 다음을 실행합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
자격 증명 이름입니다
 a| 
자격 증명의 이름을 입력합니다.



 a| 
사용자 이름/암호
 a| 
인증에 사용되는 사용자 이름과 암호를 입력합니다.

** 도메인 관리자 또는 관리자 그룹의 구성원
+
SnapCenter 플러그인을 설치할 시스템의 도메인 관리자 또는 관리자 그룹의 구성원을 지정합니다. 사용자 이름 필드의 올바른 형식은 다음과 같습니다.

+
*** 'NetBIOS\사용자 이름'
*** Domain FQDN\username'입니다
*** '사용자 이름@UPN'


** 로컬 관리자(작업 그룹에만 해당)
+
작업 그룹에 속한 시스템의 경우 SnapCenter 플러그인을 설치할 시스템에 기본 제공 로컬 관리자를 지정합니다. 사용자 계정에 상승된 권한이 있거나 호스트 시스템에서 사용자 액세스 제어 기능이 비활성화된 경우 로컬 관리자 그룹에 속하는 로컬 사용자 계정을 지정할 수 있습니다. 사용자 이름 필드의 올바른 형식은 다음과 같습니다

+
암호에 큰따옴표(")를 사용하지 마십시오.





 a| 
암호
 a| 
인증에 사용되는 암호를 입력합니다.

|===
. 확인 * 을 클릭합니다.
+
자격 증명 설정을 마친 후 * 사용자 및 액세스 * 페이지의 사용자 또는 사용자 그룹에 자격 증명 유지 관리를 할당할 수 있습니다.





== Windows Server 2012 이상에서 GMSA를 구성합니다

Windows Server 2012 이상을 사용하면 관리되는 도메인 계정에서 자동화된 서비스 계정 암호 관리를 제공하는 그룹 GMSA(Managed Service Account)를 만들 수 있습니다.

* 필요한 것 *

* Windows Server 2012 이상의 도메인 컨트롤러가 있어야 합니다.
* 도메인의 구성원인 Windows Server 2012 이상 호스트가 있어야 합니다.


* 단계 *

. KDS 루트 키를 생성하여 GMSA의 각 개체에 대해 고유한 암호를 생성합니다.
. 각 도메인에 대해 Windows 도메인 컨트롤러에서 Add-KDSRootKey-EffectiveImmediately 명령을 실행합니다
. GMSA 생성 및 구성:
+
.. 사용자 그룹 계정을 만듭니다.
.. 그룹에 컴퓨터 개체를 추가합니다.
.. 방금 생성한 사용자 그룹을 사용하여 GMSA를 생성합니다.
+
예를 들면, 다음과 같습니다.

+
 New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>
.. Get-ADServiceAccount 명령을 실행하여 서비스 계정을 확인한다.


. 호스트에서 GMSA를 구성합니다.
+
.. GMSA 계정을 사용할 호스트에서 Windows PowerShell용 Active Directory 모듈을 활성화합니다.
+
이렇게 하려면 PowerShell에서 다음 명령을 실행합니다.

+
[listing]
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
.. 호스트를 다시 시작합니다.
.. PowerShell 명령 프롬프트에서 'Install-AdServiceAccount<GMSA>'를 실행하여 호스트에 GMSA를 설치합니다
.. 'Test-AdServiceAccount <GMSA>' 명령을 실행하여 GMSA 계정을 확인합니다


. 호스트에서 구성된 GMSA에 관리 권한을 할당합니다.
. SnapCenter 서버에서 구성된 GMSA 계정을 지정하여 Windows 호스트를 추가합니다.
+
SnapCenter 서버는 선택한 플러그인을 호스트에 설치하고 지정된 GMSA는 플러그인 설치 중에 서비스 로그온 계정으로 사용됩니다.


