---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: SnapCenter를 사용하여 파일 시스템 백업을 복구할 수 있습니다. 파일 시스템 복구는 지정된 백업의 모든 데이터를 파일 시스템의 원래 위치로 복사하는 다단계 프로세스입니다. 
---
= Windows 파일 시스템 백업을 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하여 파일 시스템 백업을 복구할 수 있습니다. 파일 시스템 복구는 지정된 백업의 모든 데이터를 파일 시스템의 원래 위치로 복사하는 다단계 프로세스입니다.

* 필요한 것 *

* 파일 시스템을 백업해야 합니다.
* 백업 작업과 같은 예약된 작업이 현재 파일 시스템에 대해 진행 중인 경우 복구 작업을 시작하기 전에 해당 작업을 취소해야 합니다.
* 파일 시스템 백업은 대체 경로가 아닌 원래 위치로만 복구할 수 있습니다.
+
복구된 파일 시스템이 파일 시스템의 원래 위치에 있는 데이터를 덮어쓰므로 백업에서 단일 파일을 복구할 수 없습니다. 파일 시스템 백업에서 단일 파일을 복구하려면 백업을 클론하고 클론의 파일에 액세스해야 합니다.

* 시스템 또는 부팅 볼륨을 복원할 수 없습니다.
* SnapCenter는 클러스터 그룹을 오프라인으로 전환하지 않고도 Windows 클러스터에서 파일 시스템을 복구할 수 있습니다.


* 단계 *

. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 목록을 필터링하려면 파일 시스템 및 리소스 그룹 옵션을 선택합니다.
. 목록에서 리소스 그룹을 선택한 다음 * 복원 * 을 클릭합니다.
. 백업 페이지에서 운영 스토리지 시스템이나 보조 스토리지 시스템에서 복구할지 여부를 선택한 다음 복구할 백업을 선택합니다.
. 복원 마법사에서 옵션을 선택합니다.
. 복원 작업 전후에 SnapCenter를 실행할 경로 및 처방된 postscript의 인수를 각각 입력할 수 있습니다.
+
예를 들어, 스크립트를 실행하여 SNMP 트랩을 업데이트하고, 경고를 자동화하고, 로그를 보내는 등의 작업을 수행할 수 있습니다.

. 알림 페이지에서 다음 옵션 중 하나를 선택합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
SnapCenter 서버 이벤트를 스토리지 시스템 syslog에 기록합니다
 a| 
SnapCenter 서버 이벤트를 스토리지 시스템의 syslog에 로깅하려면 이 옵션을 선택합니다.



 a| 
실패한 작업에 대한 AutoSupport 알림을 스토리지 시스템으로 보냅니다
 a| 
AutoSupport를 사용하여 실패한 작업에 대한 정보를 NetApp에 보내려면 이 옵션을 선택합니다.



 a| 
이메일 기본 설정
 a| 
백업을 복원한 후 수신자에게 이메일 메시지를 보내려면 * Always *, * On Failure * 또는 * On failure 또는 Warning * 을 선택합니다. SMTP 서버, 기본 이메일 제목 줄 및 받는 사람 및 보낸 사람 이메일 주소를 입력합니다.

|===
. 요약을 검토하고 * Finish * 를 클릭합니다.
. 모니터 * > * 작업 * 을 클릭하여 작업 진행 상황을 모니터링합니다.



IMPORTANT: 복구된 파일 시스템에 데이터베이스가 포함되어 있는 경우 데이터베이스도 복원해야 합니다. 데이터베이스를 복원하지 않으면 데이터베이스가 잘못된 상태일 수 있습니다. 데이터베이스 복원에 대한 자세한 내용은 해당 데이터베이스의 데이터 보호 가이드 를 참조하십시오.
