---
permalink: protect-scw/task_back_up_resources_using_powershell_cmdlets_for_windows.html 
sidebar: sidebar 
keywords: backup 
summary: PowerShell cmdlet을 사용하여 SQL Server 데이터베이스 또는 Windows 파일 시스템을 백업할 수 있습니다. 여기에는 SQL Server 데이터베이스 또는 Windows 파일 시스템 백업에는 SnapCenter Server와의 연결 설정, SQL Server 데이터베이스 인스턴스 또는 Windows 파일 시스템 검색, 정책 추가, 백업 리소스 그룹 생성, 백업 및 백업 확인이 포함됩니다. 
---
= PowerShell cmdlet을 사용하여 리소스를 백업합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShell cmdlet을 사용하여 SQL Server 데이터베이스 또는 Windows 파일 시스템을 백업할 수 있습니다. 여기에는 SQL Server 데이터베이스 또는 Windows 파일 시스템 백업에는 SnapCenter Server와의 연결 설정, SQL Server 데이터베이스 인스턴스 또는 Windows 파일 시스템 검색, 정책 추가, 백업 리소스 그룹 생성, 백업 및 백업 확인이 포함됩니다.

* 필요한 것 *

* PowerShell cmdlet을 실행하려면 PowerShell 환경을 준비해야 합니다.
* 스토리지 시스템 접속을 추가하고 자격 증명을 생성해야 합니다.
* 호스트 및 검색된 리소스를 추가해야 합니다.


* 단계 *

. Open-SmConnection cmdlet을 사용하여 지정된 사용자에 대한 SnapCenter Server 연결 세션을 시작합니다.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146
----
+
사용자 이름 및 암호 프롬프트가 표시됩니다.

. Add-SmPolicy cmdlet을 사용하여 백업 정책을 만듭니다.
+
이 예제에서는 SQL 백업 유형이 FullBackup인 새 백업 정책을 만듭니다.

+
[listing]
----
PS C:\> Add-SmPolicy -PolicyName TESTPolicy
-PluginPolicyType SCSQL -PolicyType Backup
-SqlBackupType FullBackup -Verbose
----
+
이 예에서는 Windows 파일 시스템 백업 유형이 Crash일관성(crash일관성)인 새 백업 정책을 생성합니다.

+
[listing]
----
PS C:\> Add-SmPolicy -PolicyName FileSystemBackupPolicy
-PluginPolicyType SCW -PolicyType Backup
-ScwBackupType CrashConsistent -Verbose
----
. Get-SmResources cmdlet을 사용하여 호스트 리소스를 검색합니다.
+
이 예제에서는 지정된 호스트에서 Microsoft SQL 플러그인에 대한 리소스를 검색합니다.

+
[listing]
----
C:\PS>PS C:\> Get-SmResources -HostName vise-f6.sddev.mycompany.com
-PluginCode SCSQL
----
+
이 예제에서는 지정된 호스트에서 Windows 파일 시스템에 대한 리소스를 검색합니다.

+
[listing]
----
C:\PS>PS C:\> Get-SmResources -HostName vise2-f6.sddev.mycompany.com
-PluginCode SCW
----
. 추가 SmResourceGroup cmdlet을 사용하여 SnapCenter에 새 리소스 그룹을 추가합니다.
+
이 예제에서는 지정된 정책 및 리소스를 사용하여 새 SQL 데이터베이스 백업 리소스 그룹을 만듭니다.

+
[listing]
----
PS C:\> Add-SmResourceGroup -ResourceGroupName AccountingResource
-Resources @{"Host"="visef6.org.com";
"Type"="SQL Database";"Names"="vise-f6\PayrollDatabase"}
-Policies "BackupPolicy"
----
+
이 예에서는 지정된 정책 및 리소스를 사용하여 새 Windows 파일 시스템 백업 리소스 그룹을 생성합니다.

+
[listing]
----
PS C:\> Add-SmResourceGroup -ResourceGroupName EngineeringResource
-PluginCode SCW -Resources @{"Host"="WIN-VOK20IKID5I";
"Type"="Windows Filesystem";"Names"="E:\"}
-Policies "EngineeringBackupPolicy"
----
. New-SmBackup cmdlet을 사용하여 새 백업 작업을 시작합니다.
+
[listing]
----
PS C:> New-SmBackup -ResourceGroupName PayrollDataset -Policy FinancePolicy
----
. Get-SmBackupReport cmdlet을 사용하여 백업 작업의 상태를 봅니다.
+
이 예는 지정된 날짜에 실행된 모든 작업의 작업 요약 보고서를 표시합니다.

+
[listing]
----
PS C:\> Get-SmJobSummaryReport -Date '1/27/2016'
----


cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].
