---
permalink: protect-scw/task_restore_windows_file_system_backups.html 
sidebar: sidebar 
keywords: restore 
summary: SnapCenter를 사용하여 파일 시스템 백업을 복구할 수 있습니다. 파일 시스템 복구는 지정된 백업의 모든 데이터를 파일 시스템의 원래 위치로 복사하는 다단계 프로세스입니다. 
---
= Windows 파일 시스템 백업을 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하여 파일 시스템 백업을 복구할 수 있습니다. 파일 시스템 복구는 지정된 백업의 모든 데이터를 파일 시스템의 원래 위치로 복사하는 다단계 프로세스입니다.

.시작하기 전에
* 파일 시스템을 백업해야 합니다.
* 백업 작업과 같은 예약된 작업이 현재 파일 시스템에 대해 진행 중인 경우 복구 작업을 시작하기 전에 해당 작업을 취소해야 합니다.
* 파일 시스템 백업은 대체 경로가 아닌 원래 위치로만 복구할 수 있습니다.
+
복구된 파일 시스템이 파일 시스템의 원래 위치에 있는 데이터를 덮어쓰므로 백업에서 단일 파일을 복구할 수 없습니다. 파일 시스템 백업에서 단일 파일을 복구하려면 백업을 클론하고 클론의 파일에 액세스해야 합니다.

* 시스템 또는 부팅 볼륨을 복원할 수 없습니다.
* SnapCenter는 클러스터 그룹을 오프라인으로 전환하지 않고도 Windows 클러스터에서 파일 시스템을 복구할 수 있습니다.


.이 작업에 대해
* scripts_path는 플러그인 호스트의 SMCoreServiceHost.exe.Config 파일에 있는 PredefinedWindowsScriptsDirectory 키를 사용하여 정의됩니다.
+
필요한 경우 이 경로를 변경하고 SMcore 서비스를 다시 시작할 수 있습니다. 보안을 위해 기본 경로를 사용하는 것이 좋습니다.

+
키 값은 swagger에서 API:API/4.7/configsettings를 통해 표시할 수 있습니다

+
Get API를 사용하여 키 값을 표시할 수 있습니다. API 설정은 지원되지 않습니다.

* SnapMirror 활성 동기화 복원 작업의 경우 기본 위치에서 백업을 선택해야 합니다.
* ONTAP 9.12.1 이하 버전의 경우, 복원 과정에서 SnapLock 볼트 스냅샷에서 생성된 클론은 SnapLock 볼트 만료 시간을 상속합니다. 스토리지 관리자는 SnapLock 만료 시간 이후 클론을 수동으로 정리해야 합니다.


[role="tabbed-block"]
====
.SnapCenter UI
--
.단계
. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 목록을 필터링하려면 파일 시스템 및 리소스 그룹 옵션을 선택합니다.
. 목록에서 리소스 그룹을 선택한 다음 * 복원 * 을 클릭합니다.
. 백업 페이지에서 운영 스토리지 시스템이나 보조 스토리지 시스템에서 복구할지 여부를 선택한 다음 복구할 백업을 선택합니다.
. 복원 마법사에서 옵션을 선택합니다.
. 복원 작업 전후에 SnapCenter를 실행할 경로 및 처방된 postscript의 인수를 각각 입력할 수 있습니다.
+
예를 들어, 스크립트를 실행하여 SNMP 트랩을 업데이트하고, 경고를 자동화하고, 로그를 보내는 등의 작업을 수행할 수 있습니다.

+

NOTE: 처방자 또는 사후 스크립트 경로에는 드라이브 또는 공유가 포함되어서는 안 됩니다. 경로는 scripts_path에 상대해야 합니다.

. 알림 페이지에서 다음 옵션 중 하나를 선택합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
SnapCenter 서버 이벤트를 스토리지 시스템 syslog에 기록합니다
 a| 
SnapCenter 서버 이벤트를 스토리지 시스템의 syslog에 로깅하려면 이 옵션을 선택합니다.



 a| 
실패한 작업에 대한 AutoSupport 알림을 스토리지 시스템으로 보냅니다
 a| 
AutoSupport를 사용하여 실패한 작업에 대한 정보를 NetApp에 보내려면 이 옵션을 선택합니다.



 a| 
이메일 기본 설정
 a| 
백업을 복원한 후 수신자에게 이메일 메시지를 보내려면 * Always *, * On Failure * 또는 * On failure 또는 Warning * 을 선택합니다. SMTP 서버, 기본 이메일 제목 줄 및 받는 사람 및 보낸 사람 이메일 주소를 입력합니다.

|===
. 요약을 검토하고 * Finish * 를 클릭합니다.
. 모니터 * > * 작업 * 을 클릭하여 작업 진행 상황을 모니터링합니다.



IMPORTANT: 복구된 파일 시스템에 데이터베이스가 포함되어 있는 경우 데이터베이스도 복원해야 합니다. 데이터베이스를 복원하지 않으면 데이터베이스가 잘못된 상태일 수 있습니다. 데이터베이스 복원에 대한 자세한 내용은 해당 데이터베이스의 데이터 보호 가이드 를 참조하십시오.

--
.PowerShell cmdlet
--
.단계
. Open-SmConnection cmdlet을 사용하여 지정된 사용자에 대한 SnapCenter Server 연결 세션을 시작합니다.
+
[listing]
----
PS C:\> Open-Smconnection
----
. Get-SmBackup 및 Get-SmBackupReport cmdlet을 사용하여 복원하려는 하나 이상의 백업에 대한 정보를 검색합니다.
+
이 예에서는 사용 가능한 모든 백업에 대한 정보를 표시합니다.

+
[listing]
----
PS C:\> Get-SmBackup

BackupId                      BackupName                    BackupTime                    BackupType
--------                      ----------                    ----------                    ----------
  1               Payroll Dataset_vise-f6_08... 8/4/2015    11:02:32 AM                 Full Backup
  2               Payroll Dataset_vise-f6_08... 8/4/2015    11:23:17 AM
----
+
이 예는 2015년 1월 29일부터 2015년 2월 3일까지 백업에 대한 자세한 정보를 표시합니다.

+
[listing]
----
PS C:\> Get-SmBackupReport -FromDateTime "1/29/2015" -ToDateTime "2/3/2015"

   SmBackupId           : 113
   SmJobId              : 2032
   StartDateTime        : 2/2/2015 6:57:03 AM
   EndDateTime          : 2/2/2015 6:57:11 AM
   Duration             : 00:00:07.3060000
   CreatedDateTime      : 2/2/2015 6:57:23 AM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_06.57.08
   VerificationStatus   : NotVerified

   SmBackupId           : 114
   SmJobId              : 2183
   StartDateTime        : 2/2/2015 1:02:41 PM
   EndDateTime          : 2/2/2015 1:02:38 PM
   Duration             : -00:00:03.2300000
   CreatedDateTime      : 2/2/2015 1:02:53 PM
   Status               : Completed
   ProtectionGroupName  : Clone
   SmProtectionGroupId  : 34
   PolicyName           : Vault
   SmPolicyId           : 18
   BackupName           : Clone_SCSPR0019366001_02-02-2015_13.02.45
   VerificationStatus   : NotVerified
----
. Restore-SmBackup cmdlet을 사용하여 백업에서 데이터를 복원합니다.
+
[listing]
----
Restore-SmBackup -PluginCode 'DummyPlugin' -AppObjectId 'scc54.sccore.test.com\DummyPlugin\NTP\DB1' -BackupId 269 -Confirm:$false
output:
Name                : Restore 'scc54.sccore.test.com\DummyPlugin\NTP\DB1'
Id                  : 2368
StartTime           : 10/4/2016 11:22:02 PM
EndTime             :
IsCancellable       : False
IsRestartable       : False
IsCompleted         : False
IsVisible           : True
IsScheduled         : False
PercentageCompleted : 0
Description         :
Status              : Queued
Owner               :
Error               :
Priority            : None
Tasks               : {}
ParentJobID         : 0
EventId             : 0
JobTypeId           :
ApisJobKey          :
ObjectId            : 0
PluginCode          : NONE
PluginName          :
----


cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 cmdlet 참조 가이드"^]있습니다.

--
====