---
permalink: protect-scw/task_clone_from_a_windows_file_system_backup.html 
sidebar: sidebar 
keywords: clone 
summary: SnapCenter를 사용하여 Windows 파일 시스템 백업을 복제할 수 있습니다. 실수로 삭제되거나 변경된 단일 파일의 복제본을 원하는 경우 백업을 복제하고 클론에서 해당 파일에 액세스할 수 있습니다. 
---
= Windows 파일 시스템 백업에서 클론을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하여 Windows 파일 시스템 백업을 복제할 수 있습니다. 실수로 삭제되거나 변경된 단일 파일의 복제본을 원하는 경우 백업을 복제하고 클론에서 해당 파일에 액세스할 수 있습니다.

* 필요한 것 *

* 호스트 추가, 리소스 식별 및 SVM(스토리지 가상 머신) 연결 생성과 같은 작업을 완료하여 데이터 보호를 준비할 수 있어야 합니다.
* 파일 시스템의 백업이 있어야 합니다.
* 볼륨을 호스팅하는 애그리게이트는 SVM(스토리지 가상 머신)의 할당된 애그리게이트 목록에 있어야 합니다.
* 리소스 그룹을 복제할 수 없습니다. 개별 파일 시스템 백업만 복제할 수 있습니다.
* 백업이 VMDK 디스크가 있는 가상 시스템에 상주하는 경우 SnapCenter는 백업을 물리적 서버에 복제할 수 없습니다.
* Windows 클러스터(예: 공유 LUN 또는 CSV(클러스터 공유 볼륨) LUN)의 클론을 생성하면 지정한 호스트의 전용 LUN으로 클론이 저장됩니다.
* 클론 생성 작업의 경우 볼륨 마운트 지점의 루트 디렉토리는 공유 디렉토리일 수 없습니다.
* Aggregate의 홈 노드가 아닌 노드에서는 클론을 생성할 수 없습니다.
* Windows 파일 시스템에 대해 반복 클론(클론 라이프사이클) 작업을 예약할 수 없으며 필요 시에만 백업을 클론 복제할 수 있습니다.
* 클론이 포함된 LUN을 새 볼륨으로 이동하면 SnapCenter에서 더 이상 클론을 지원할 수 없습니다. 예를 들어, SnapCenter를 사용하여 해당 클론을 삭제할 수는 없습니다.
* 여러 환경에서 클론을 생성할 수는 없습니다. 예를 들어, 물리적 디스크에서 가상 디스크로 복제하거나 그 반대로 복제할 수 있습니다.


* 단계 *

. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지의 목록에서 * 파일 시스템 * 을 선택합니다.
. 호스트를 선택합니다.
+
리소스가 보호된 경우 토폴로지 뷰가 자동으로 표시됩니다.

. 리소스 목록에서 클론 복제할 백업을 선택한 다음 클론 아이콘을 클릭합니다.
. 옵션 페이지에서 다음을 실행합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
클론 서버
 a| 
클론을 생성할 호스트를 선택합니다.



 a| 
""마운트 지점 자동 할당"" 또는 ""경로 아래 볼륨 마운트 지점 자동 할당""
 a| 
경로 아래에 마운트 지점을 자동으로 할당할지, 볼륨 마운트 지점을 자동으로 할당할지 여부를 선택합니다.

경로 아래의 볼륨 마운트 지점 자동 할당: 경로 아래의 마운트 지점을 사용하여 마운트 지점을 생성할 특정 디렉토리를 제공할 수 있습니다. 이 옵션을 선택하기 전에 디렉토리가 비어 있는지 확인해야 합니다. 디렉토리에 백업이 있으면 마운트 작업 후 백업이 잘못된 상태가 됩니다.



 a| 
보관 위치
 a| 
보조 백업을 클론하는 경우 아카이브 위치를 선택합니다.

|===
. 스크립트 페이지에서 실행할 처방이나 소인을 지정합니다.
. 요약을 검토하고 * Finish * 를 클릭합니다.
. 모니터 * > * 작업 * 을 클릭하여 작업 진행 상황을 모니터링합니다.

