---
permalink: protect-scw/task_create_backup_policies_for_windows_file_systems.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter를 사용하여 Windows 파일 시스템을 백업하기 전에 리소스에 대한 새 백업 정책을 만들거나 리소스 그룹을 만들 때 또는 리소스를 백업할 때 새 백업 정책을 만들 수 있습니다. 
---
= Windows 파일 시스템에 대한 백업 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하여 Windows 파일 시스템을 백업하기 전에 리소스에 대한 새 백업 정책을 만들거나 리소스 그룹을 만들 때 또는 리소스를 백업할 때 새 백업 정책을 만들 수 있습니다.

* 필요한 것 *

* 백업 전략을 정의해야 합니다. link:task_define_a_backup_strategy_for_windows_file_systems.html["자세한 정보"^]
* 데이터 보호를 위한 준비가 되어 있어야 합니다.
+
데이터 보호를 준비하려면 SnapCenter 설치, 호스트 추가, 리소스 검색, SVM(스토리지 가상 시스템) 연결 생성 등의 작업을 완료해야 합니다.

* 스냅샷 복사본을 미러 또는 소산 보조 스토리지에 복제하는 경우 SnapCenter 관리자는 소스 및 대상 볼륨 모두에 대해 SVM을 할당한 상태여야 합니다.
* powershellProcessforScripts 매개 변수의 값을 web.config 파일에서 true 로 설정하여 powerpare 및 postscripts 로 PowerShell 스크립트를 실행해야 합니다.
+
기본값은 false 입니다



* 단계 *

. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 정책 * 을 클릭합니다.
. 기존 정책을 사용할 수 있는지 확인하려면 정책 이름을 선택한 다음 * 세부 정보 * 를 클릭합니다.
+
기존 정책을 검토한 후 다음 중 하나를 수행할 수 있습니다.

+
** 기존 정책을 사용합니다.
** 기존 정책을 복사하고 정책 구성을 수정합니다.
** 새 정책을 생성합니다.


. 새 정책을 만들려면 * New * 를 클릭합니다.
. 이름 페이지에 정책 이름과 설명을 입력합니다.
. 백업 옵션 페이지에서 다음 작업을 수행합니다.
+
.. 백업 설정을 선택합니다.
+
|===
| 옵션을 선택합니다 | 설명 


 a| 
파일 시스템 정합성 보장 백업
 a| 
백업 작업이 시작되기 전에 SnapCenter가 파일 시스템이 상주하는 디스크 드라이브를 일시 중지한 다음 백업 작업이 종료된 후 디스크 드라이브를 다시 시작하도록 하려면 이 옵션을 선택합니다.



 a| 
파일 시스템 충돌 - 정합성 보장 백업
 a| 
SnapCenter가 파일 시스템이 상주하는 디스크 드라이브를 중지하지 않도록 하려면 이 옵션을 선택합니다.

|===
.. 스케줄 빈도(정책 유형이라고도 함)를 선택합니다.
+
정책은 백업 빈도만 지정합니다. 백업에 대한 특정 보호 스케줄은 리소스 그룹에 정의됩니다. 따라서 둘 이상의 리소스 그룹이 동일한 정책 및 백업 빈도를 공유할 수 있지만 백업 스케줄은 다릅니다.

+

NOTE: 오전 2시에 예약된 경우 DST(일광 절약 시간) 중에는 일정이 트리거되지 않습니다.



. 보존 페이지에서 필요 시 백업 및 선택한 각 스케줄 빈도에 대한 보존 설정을 지정합니다.
+
|===
| 옵션을 선택합니다 | 설명 


 a| 
유지할 총 스냅샷 복사본
 a| 
SnapCenter에서 자동으로 삭제하기 전에 자동으로 저장되는 스냅샷 복사본의 수를 지정하려면 이 옵션을 선택합니다.



 a| 
다음보다 오래된 스냅샷 복사본을 삭제합니다
 a| 
SnapCenter에서 백업 복사본을 삭제하기 전에 보존할 일 수를 지정하려면 이 옵션을 선택합니다.

|===
+

IMPORTANT: SnapVault 복제를 사용하도록 설정하려는 경우 보존 수를 2 이상으로 설정해야 합니다. 복제 수를 1로 설정하면 보존 작업이 실패할 수 있습니다. 그 이유는 첫 번째 스냅샷 복사본이 SnapVault 관계에 대한 참조 스냅샷 복사본으로, 새로운 스냅샷 복사본이 타겟으로 복제되기 때문입니다.

+

NOTE: 최대 보존 값은 ONTAP 9.4 이상의 리소스에 대해 1018이고, ONTAP 9.3 이전 버전의 리소스에 대해서는 254입니다. 보존이 기본 ONTAP 버전에서 지원하는 값보다 높은 값으로 설정된 경우 백업이 실패합니다.

. 복제 페이지에서 보조 스토리지 시스템에 대한 복제를 지정합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
로컬 스냅샷 복사본을 생성한 후 SnapMirror를 업데이트합니다
 a| 
다른 볼륨(SnapMirror)에 백업 세트의 미러 복사본을 생성하려면 이 옵션을 선택합니다.



 a| 
스냅샷 복사본을 생성한 후 SnapVault를 업데이트합니다
 a| 
디스크 간 백업 복제를 수행하려면 이 옵션을 선택합니다.



 a| 
보조 정책 레이블입니다
 a| 
스냅샷 레이블을 선택합니다.

선택한 스냅샷 복사본 레이블에 따라 ONTAP에서는 해당 레이블과 일치하는 2차 스냅샷 복사본 보존 정책을 적용합니다.


NOTE: 로컬 스냅샷 복사본 * 을 생성한 후 SnapMirror 업데이트 * 를 선택한 경우, 선택적으로 보조 정책 레이블을 지정할 수 있습니다. 그러나 로컬 스냅샷 복사본 * 을 생성한 후 * SnapVault 업데이트 * 를 선택한 경우에는 보조 정책 레이블을 지정해야 합니다.



 a| 
오류 재시도 횟수입니다
 a| 
프로세스가 중지되기 전에 수행해야 하는 복제 시도 횟수를 입력합니다.

|===
+

NOTE: 보조 스토리지에 대한 ONTAP의 SnapMirror 보존 정책을 구성하면 보조 스토리지에서 스냅샷 복사본의 최대 제한에 도달하지 않도록 해야 합니다.

. 스크립트 페이지에서 SnapCenter 서버가 백업 작업 전후에 실행할 처방인 경로 또는 PS를 각각 입력하고 SnapCenter가 스크립트가 시간 초과 전에 실행될 때까지 대기하는 시간 제한을 입력합니다.
+
예를 들어 스크립트를 실행하여 SNMP 트랩을 업데이트하고, 경고를 자동화하고, 로그를 보낼 수 있습니다.

. 요약을 검토하고 * Finish * 를 클릭합니다.

