---
permalink: protect-scw/task_define_a_backup_strategy_for_windows_file_systems.html 
sidebar: sidebar 
keywords:  
summary: '백업을 생성하기 전에 백업 전략을 정의하면 파일 시스템을 성공적으로 복원하거나 복제하는 데 필요한 백업을 얻을 수 있습니다. SLA(서비스 수준 계약), RTO(복구 시간 목표) 및 RPO(복구 시점 목표)에 따라 백업 전략이 주로 결정됩니다.' 
---
= Windows 파일 시스템에 대한 백업 전략 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업을 생성하기 전에 백업 전략을 정의하면 파일 시스템을 성공적으로 복원하거나 복제하는 데 필요한 백업을 얻을 수 있습니다. SLA(서비스 수준 계약), RTO(복구 시간 목표) 및 RPO(복구 시점 목표)에 따라 백업 전략이 주로 결정됩니다.

SLA는 예상되는 서비스 수준을 정의하고 서비스의 가용성 및 성능을 비롯한 다양한 서비스 관련 문제를 해결합니다. RTO는 서비스 중단 후 비즈니스 프로세스를 복원해야 하는 시간입니다. RPO는 장애 후 정상적인 작업을 재개하기 위해 백업 스토리지에서 복구해야 하는 파일의 사용 기간에 대한 전략을 정의합니다. SLA, RTO 및 RPO는 데이터 보호 전략에 기여합니다.



== Windows 파일 시스템에 대한 백업 스케줄입니다

백업 빈도는 정책에 지정되며 백업 스케줄은 리소스 그룹 구성에 지정됩니다. 백업 빈도 또는 스케줄을 결정하는 가장 중요한 요소는 리소스의 변경 속도 및 데이터의 중요도입니다. 자주 사용하는 리소스를 매일 한 번씩 백업할 수도 있고, 자주 사용하지 않는 리소스를 하루에 한 번 백업할 수도 있습니다. 기타 요인으로는 조직에 대한 리소스의 중요성, SLA(서비스 수준 계약) 및 RPO(복구 시점 목표)가 있습니다.

SLA는 예상되는 서비스 수준을 정의하고 가용성 및 서비스 성능을 비롯한 다양한 서비스 관련 문제를 해결합니다. RPO는 장애 후 정상적인 작업을 재개하기 위해 백업 스토리지에서 복구해야 하는 파일의 사용 기간에 대한 전략을 정의합니다. SLA 및 RPO는 데이터 보호 전략에 기여합니다.

사용량이 많은 리소스의 경우에도 하루에 한 번 또는 두 번 이상 전체 백업을 실행할 필요가 없습니다.

백업 스케줄은 다음과 같이 두 부분으로 구성됩니다.

* 백업 빈도
+
일부 플러그인에 대해 _schedule type_이라는 백업 빈도(백업 수행 빈도)는 정책 구성의 일부입니다. 예를 들어 백업 빈도를 매시간, 일별, 주별 또는 월별로 구성하거나, 해당 정책을 주문형 전용 정책으로 만드는 * 없음 * 을 지정할 수 있습니다. 설정 * > * 정책 * 을 클릭하여 정책에 액세스할 수 있습니다.

* 백업 스케줄
+
백업 스케줄(백업을 수행할 정확한 시점)은 리소스 그룹 구성의 일부입니다. 예를 들어 주별 백업에 대한 정책이 구성된 리소스 그룹이 있는 경우 매주 목요일 오후 10시에 백업하도록 스케줄을 구성할 수 있습니다. 리소스 그룹 * > * 리소스 그룹 * 을 클릭하여 리소스 그룹 일정에 액세스할 수 있습니다.





== Windows 파일 시스템에 필요한 백업 수입니다

필요한 백업 수를 결정하는 요소에는 Windows 파일 시스템의 크기, 사용된 볼륨 수, 파일 시스템의 변경 속도 및 SLA(서비스 수준 계약)가 포함됩니다.



== Windows 파일 시스템의 백업 명명 규칙

Windows 파일 시스템 백업에는 기본 스냅샷 복사본 명명 규칙이 사용됩니다. 기본 백업 명명 규칙은 스냅샷 복사본 이름에 타임 스탬프를 추가하여 복사본이 생성된 시간을 식별하도록 도와줍니다.

스냅샷 복사본은 resourcegroupname_hostname_timestamp라는 기본 명명 규칙을 사용합니다

다음 예제와 같이 백업 리소스 그룹의 이름을 논리적으로 지정해야 합니다.

[listing]
----
dts1_mach1x88_03-12-2015_23.17.26
----
이 예제에서 구문 요소는 다음과 같은 의미를 가집니다.

* dts1은 자원 그룹 이름입니다.
* 호스트 이름은 mach1x88입니다.
* 03-12-2016_23.17.26은 날짜와 타임 스탬프입니다.


백업을 생성할 때 백업을 식별하는 데 도움이 되는 설명 태그를 추가할 수도 있습니다. 반면, 사용자 지정 백업 명명 규칙을 사용하려면 백업 작업이 완료된 후 백업 이름을 변경해야 합니다.



== 백업 보존 옵션

백업 복사본을 보존할 일 수를 선택하거나 유지할 백업 복사본 수를 최대 255개 사본의 ONTAP로 지정할 수 있습니다. 예를 들어, 조직에서 10일간 백업 복사본 또는 130개의 백업 복사본을 보존해야 할 수도 있습니다.

정책을 생성하는 동안 백업 유형 및 스케줄 유형에 대한 보존 옵션을 지정할 수 있습니다.

SnapMirror 복제를 설정하면 보존 정책이 대상 볼륨에 미러링됩니다.

SnapCenter는 스케줄 유형과 일치하는 보존 레이블이 있는 보존된 백업을 삭제합니다. 리소스 또는 리소스 그룹에 대한 스케줄 유형이 변경된 경우 이전 스케줄 유형 레이블이 있는 백업이 시스템에 남아 있을 수 있습니다.


NOTE: 백업 복사본을 장기간 보존하려면 SnapVault 백업을 사용해야 합니다.
