---
permalink: protect-scw/task_install_the_snapcenter_plug_in_for_windows_silently_from_the_command_line.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter GUI에서 원격으로 플러그인을 설치할 수 없는 경우 Windows 호스트에 Microsoft Windows용 SnapCenter 플러그인을 로컬로 설치할 수 있습니다. Windows 명령줄에서 Microsoft Windows 설치 프로그램용 SnapCenter 플러그인을 자동 모드로 실행할 수 있습니다. 
---
= 명령줄에서 Microsoft Windows용 SnapCenter 플러그인을 자동으로 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter GUI에서 원격으로 플러그인을 설치할 수 없는 경우 Windows 호스트에 Microsoft Windows용 SnapCenter 플러그인을 로컬로 설치할 수 있습니다. Windows 명령줄에서 Microsoft Windows 설치 프로그램용 SnapCenter 플러그인을 자동 모드로 실행할 수 있습니다.

* 필요한 것 *

* Microsoft .Net 4.5.2 이상을 설치해야 합니다.
* PowerShell 4.0 이상을 설치해야 합니다.
* Windows 메시지 큐잉을 켜야 합니다.
* 호스트의 로컬 관리자여야 합니다.


* 단계 *

. 설치 위치에서 Microsoft Windows용 SnapCenter 플러그인을 다운로드합니다.
+
예를 들어 기본 설치 경로는 C:\ProgramData\NetApp\SnapCenter\Package Repository입니다.

+
이 경로는 SnapCenter 서버가 설치된 호스트에서 액세스할 수 있습니다.

. 플러그인을 설치할 호스트에 설치 파일을 복사합니다.
. 명령 프롬프트에서 설치 파일을 다운로드한 디렉토리로 이동합니다.
. 변수를 데이터로 대치하는 다음 명령을 입력합니다.
+
""snapcenter_windows_host_plugin.exe"/silent/debuglog""/log""BI_SNAPCENTER_PORT=Suite_INSTALLDIR=""BI_ServiceAccount=BI_SERVICEPWD=ISFeatureInstall=SCW"

+
예를 들면 다음과 같습니다.

+
 `"C:\ProgramData\NetApp\SnapCenter\Package Repository \snapcenter_windows_host_plugin.exe"/silent /debuglog"C: \HPPW_SCW_Install.log" /log"C:\" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C: \Program Files\NetApp\SnapCenter" BI_SERVICEACCOUNT=domain\administrator BI_SERVICEPWD=password ISFeatureInstall=SCW`
+

NOTE: Windows용 플러그인 설치 중에 전달되는 모든 매개 변수는 대/소문자를 구분합니다.

+
다음 변수의 값을 입력합니다.

+
|===
| 변수 | 값 


 a| 
_ /debuglog "<Debug_Log_Path> _
 a| 
Setup.exe /debuglog "C:\PathToLog\setupexe.log" 예제와 같이 제품군 설치 관리자 로그 파일의 이름과 위치를 지정합니다.



 a| 
Bi_SNAPCENTER_PORT
 a| 
SnapCenter가 SMCore와 통신하는 포트를 지정합니다.



 a| 
Suite_INSTALLDIR
 a| 
호스트 플러그인 패키지 설치 디렉토리를 지정합니다.



 a| 
BI_서비스 계정
 a| 
Microsoft Windows 웹 서비스 계정용 SnapCenter 플러그인을 지정합니다.



 a| 
BI_세비셀
 a| 
Microsoft Windows 웹 서비스 계정용 SnapCenter 플러그인 암호를 지정합니다.



 a| 
ISFeatureInstall을 선택합니다
 a| 
SnapCenter가 원격 호스트에 구축할 솔루션을 지정합니다.

|===
+
_debuglog_parameter에는 SnapCenter에 대한 로그 파일의 경로가 포함됩니다. 이 로그 파일에 기록하는 것이 문제 해결 정보를 얻는 데 권장되는 방법입니다. 이 파일에는 설치 시 플러그인 사전 요구 사항에 대해 수행한 검사 결과가 포함되어 있기 때문입니다.

+
필요한 경우 Windows용 SnapCenter 패키지의 로그 파일에서 추가 문제 해결 정보를 찾을 수 있습니다. 패키지의 로그 파일은 _%Temp%_ 폴더에 (가장 오래된 파일 먼저) 나열됩니다(예: _C:\temp\_).

+

NOTE: Windows용 플러그인을 설치하면 SnapCenter 서버가 아닌 호스트에 플러그인이 등록됩니다. SnapCenter GUI 또는 PowerShell cmdlet을 사용하여 호스트를 추가하여 SnapCenter 서버에 플러그인을 등록할 수 있습니다. 호스트가 추가되면 플러그인이 자동으로 검색됩니다.


