---
permalink: concept/concept_prescripts_and_postscripts.html 
sidebar: sidebar 
keywords: prescript, postscript, script path, script timeout, script types supported 
summary: 데이터 보호 작업의 일부로 사용자 지정 처방과 사후 스크립트를 사용할 수 있습니다. 이러한 스크립트를 사용하면 데이터 보호 작업 전 또는 이후에 자동화를 수행할 수 있습니다. 예를 들어 데이터 보호 작업 장애 또는 경고를 자동으로 알리는 스크립트를 포함할 수 있습니다. 처방전과 소인을 설정하기 전에 이러한 스크립트를 만들기 위한 몇 가지 요구 사항을 이해해야 합니다. 
---
= 사전 스크립트 및 포스트스크립트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 보호 작업의 일부로 사용자 지정 처방과 사후 스크립트를 사용할 수 있습니다. 이러한 스크립트를 사용하면 데이터 보호 작업 전 또는 이후에 자동화를 수행할 수 있습니다. 예를 들어 데이터 보호 작업 장애 또는 경고를 자동으로 알리는 스크립트를 포함할 수 있습니다. 처방전과 소인을 설정하기 전에 이러한 스크립트를 만들기 위한 몇 가지 요구 사항을 이해해야 합니다.



== 지원되는 스크립트 유형입니다

Windows에서 지원되는 스크립트 유형은 다음과 같습니다.

* 배치 파일
* PowerShell 스크립트
* Perl 스크립트


UNIX에서 지원되는 스크립트 유형은 다음과 같습니다.

* Perl 스크립트
* Python 스크립트
* 쉘 스크립트
+

NOTE: 기본 bash shell과 함께 sh-shell, k-shell 및 c-shell과 같은 다른 쉘도 지원됩니다.





== 스크립트 경로

가상화되지 않은 스토리지 시스템과 가상화된 스토리지 시스템에서 SnapCenter 작업의 일부로 실행되는 모든 처방과 사후 스크립트는 플러그인 호스트에서 실행됩니다.

* Windows 스크립트는 플러그인 호스트에 있어야 합니다.



NOTE: 처방자 또는 사후 스크립트 경로에는 드라이브 또는 공유가 포함되어서는 안 됩니다. 경로는 scripts_path에 상대해야 합니다.

* UNIX 스크립트는 플러그인 호스트에 있어야 합니다.



NOTE: 스크립트 경로는 실행 시 검증됩니다.



== 스크립트 지정 위치

스크립트는 백업 정책에 지정됩니다. 백업 작업이 시작되면 정책은 자동으로 스크립트를 백업 중인 리소스와 연결합니다. 백업 정책을 만들 때 처방과 PS 인수를 지정할 수 있습니다.


NOTE: 여러 스크립트를 지정할 수 없습니다.



== 스크립트 시간 초과

시간 초과는 기본적으로 60초로 설정됩니다. 시간 초과 값을 수정할 수 있습니다.



== 스크립트 출력

Windows prescpts 및 postscripts 출력 파일의 기본 디렉터리는 Windows\System32입니다.

UNIX 처방과 postscript에 대한 기본 위치는 없습니다. 원하는 위치로 출력 파일을 리디렉션할 수 있습니다.
