---
permalink: concept/concept_types_of_role_based_access_control_in_snapcenter.html 
sidebar: sidebar 
keywords: RBAC, roles, permissions, application-level RBAC, ONTAP permissions 
summary: 'ONTAP RBAC(역할 기반 액세스 제어) 및 SnapCenter 권한을 사용하면 SnapCenter 관리자가 역할을 만들고 액세스 권한을 설정할 수 있습니다. 이러한 중앙 관리형 액세스를 통해 애플리케이션 관리자는 위임된 환경 내에서 안전하게 작업할 수 있습니다.' 
---
= RBAC 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP RBAC(역할 기반 액세스 제어) 및 SnapCenter 권한을 사용하여 SnapCenter 관리자는 SnapCenter 리소스에 대한 제어 권한을 다른 사용자 또는 사용자 그룹에 위임할 수 있습니다. 이러한 중앙 관리형 액세스를 통해 애플리케이션 관리자는 위임된 환경 내에서 안전하게 작업할 수 있습니다.

언제든지 역할을 만들고 수정할 수 있으며 사용자에게 리소스 액세스 권한을 추가할 수 있지만 SnapCenter를 처음 설정할 때는 최소한 역할에 Active Directory 사용자 또는 그룹을 추가한 다음 이러한 사용자 또는 그룹에 리소스 액세스 권한을 추가해야 합니다.


NOTE: SnapCenter를 사용하여 사용자 또는 그룹 계정을 만들 수 없습니다. 운영 체제 또는 데이터베이스의 Active Directory에서 사용자 또는 그룹 계정을 만들어야 합니다.

SnapCenter는 다음과 같은 유형의 역할 기반 액세스 제어를 사용합니다.

* SnapCenter RBAC
* SnapCenter 플러그인 RBAC(일부 플러그인의 경우)
* 애플리케이션 레벨 RBAC
* ONTAP 권한




== SnapCenter RBAC



=== 역할 및 권한

SnapCenter에는 권한이 이미 할당된 미리 정의된 역할이 제공됩니다. 이러한 역할에 사용자 또는 사용자 그룹을 할당할 수 있습니다. 새 역할을 만들고 사용 권한 및 사용자를 관리할 수도 있습니다.

* 사용자 또는 그룹에 권한 할당 *

사용자 또는 그룹에 권한을 할당하여 호스트, 스토리지 접속 및 리소스 그룹과 같은 SnapCenter 객체를 액세스할 수 있습니다. SnapCenterAdmin 역할의 권한은 변경할 수 없습니다.

동일한 포리스트 내의 사용자와 그룹 및 다른 포리스트에 속한 사용자에게 RBAC 권한을 할당할 수 있습니다. 포리스트 전체의 중첩된 그룹에 속하는 사용자에게는 RBAC 권한을 할당할 수 없습니다.


NOTE: 사용자 지정 역할을 만드는 경우 SnapCenter 관리자 역할의 모든 권한이 있어야 합니다. 호스트 추가 또는 호스트 제거 등의 일부 권한만 복사하는 경우에는 해당 작업을 수행할 수 없습니다.



=== 인증

사용자는 로그인 시 그래픽 사용자 인터페이스(GUI) 또는 PowerShell cmdlet을 사용하여 인증을 제공해야 합니다. 사용자가 둘 이상의 역할의 구성원인 경우 로그인 자격 증명을 입력한 후 사용할 역할을 지정하라는 메시지가 표시됩니다. 또한 사용자는 API를 실행하기 위한 인증을 제공해야 합니다.



== 애플리케이션 레벨 RBAC

SnapCenter는 자격 증명을 사용하여 권한이 있는 SnapCenter 사용자에게 응용 프로그램 수준 권한도 있는지 확인합니다.

예를 들어 SQL Server 환경에서 스냅샷 복사본 및 데이터 보호 작업을 수행하려면 적절한 Windows 또는 SQL 자격 증명을 사용하여 자격 증명을 설정해야 합니다. SnapCenter 서버는 두 가지 방법 중 하나를 사용하여 설정된 자격 증명을 인증합니다. ONTAP 스토리지의 Windows 파일 시스템 환경에서 스냅샷 복사본 및 데이터 보호 작업을 수행하려면 SnapCenter 관리자 역할에 Windows 호스트에 대한 관리자 권한이 있어야 합니다.

마찬가지로 Oracle 데이터베이스에서 데이터 보호 작업을 수행하고 데이터베이스 호스트에서 운영 체제(OS) 인증을 사용하지 않도록 설정한 경우 Oracle 데이터베이스 또는 Oracle ASM 자격 증명을 사용하여 자격 증명을 설정해야 합니다. SnapCenter 서버는 작업에 따라 이러한 방법 중 하나를 사용하여 설정된 자격 증명을 인증합니다.



== VMware vSphere용 SnapCenter 플러그인 RBAC

VM 일관성 있는 데이터 보호를 위해 SnapCenter VMware 플러그인을 사용하는 경우 vCenter Server는 추가 RBAC 수준을 제공합니다. SnapCenter VMware 플러그인은 vCenter Server RBAC와 Data ONTAP RBAC를 모두 지원합니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_role_based_access_control.html["VMware vSphere용 SnapCenter 플러그인 RBAC"^]



== ONTAP 권한

스토리지 시스템에 액세스하는 데 필요한 권한이 있는 vsadmin 계정을 생성해야 합니다.

계정을 만들고 권한을 할당하는 방법에 대한 자세한 내용은 을 참조하십시오 link:../install/task_create_an_ontap_cluster_role_with_minimum_privileges.html["최소 권한으로 ONTAP 클러스터 역할을 생성합니다"^]
