---
permalink: concept/concept_prescripts_and_postscripts.html 
sidebar: sidebar 
keywords: prescript, postscript, script path, script timeout, script types supported 
summary: 데이터 보호 작업의 일부로 사용자 지정 처방과 사후 스크립트를 사용할 수 있습니다. 이러한 스크립트를 사용하면 데이터 보호 작업 전 또는 이후에 자동화를 수행할 수 있습니다. 예를 들어 데이터 보호 작업 장애 또는 경고를 자동으로 알리는 스크립트를 포함할 수 있습니다. 처방전과 소인을 설정하기 전에 이러한 스크립트를 만들기 위한 몇 가지 요구 사항을 이해해야 합니다. 
---
= 사전 스크립트 및 포스트스크립트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 보호 작업의 일부로 사용자 지정 처방과 사후 스크립트를 사용할 수 있습니다. 이러한 스크립트를 사용하면 데이터 보호 작업 전 또는 이후에 자동화를 수행할 수 있습니다. 예를 들어 데이터 보호 작업 장애 또는 경고를 자동으로 알리는 스크립트를 포함할 수 있습니다. 처방전과 소인을 설정하기 전에 이러한 스크립트를 만들기 위한 몇 가지 요구 사항을 이해해야 합니다.



== 지원되는 스크립트 유형입니다

지원되는 스크립트 유형은 다음과 같습니다.

* 배치 파일
* PowerShell 스크립트
* Perl 스크립트




== 스크립트 경로

가상화되지 않은 스토리지 시스템과 가상화된 스토리지 시스템에서 SnapCenter 작업의 일부로 실행되는 모든 처방과 사후 스크립트는 플러그인 호스트에서 실행됩니다. 따라서 플러그인 호스트 또는 플러그인 호스트에서 액세스할 수 있는 SMB 공유에 스크립트가 있어야 합니다.


NOTE: 스크립트 경로는 스크립트가 실행될 때 검증됩니다.



== 스크립트 지정 위치

스크립트는 백업 정책에 지정됩니다. 백업 작업이 시작되면 정책은 자동으로 스크립트를 백업 중인 리소스와 연결합니다. 백업 정책을 만들 때 처방과 PS 인수를 지정할 수 있습니다.

여러 스크립트를 지정하려면 각 스크립트 경로 뒤에 * Enter * 를 눌러 각 스크립트를 별도의 줄에 나열합니다. 세미콜론(;)은 허용되지 않습니다. 여러 개의 처방과 여러 개의 소인을 지정할 수 있습니다. 단일 스크립트는 처방과 PS로 모두 코딩될 수 있으며 다른 스크립트를 호출할 수 있습니다.



== 스크립트 시간 초과

백업 스크립트의 시간 제한은 15분이며 수정할 수 없습니다.



== 스크립트 출력

prescpts 및 postscripts 출력 파일의 기본 디렉터리는 Windows\System32입니다.
