---
permalink: protect-concept/concept_disaster_recovery.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter 재해 복구 기능을 사용하여 리소스 손상 또는 서버 충돌과 같은 재해 발생 시 SnapCenter 서버를 복구할 수 있습니다. 
---
= 재해 복구
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 재해 복구 기능을 사용하여 리소스 손상 또는 서버 충돌과 같은 재해 발생 시 SnapCenter 서버를 복구할 수 있습니다. SnapCenter 리포지토리, 서버 일정 및 서버 구성 요소를 복구할 수 있습니다.

SQL Server용 SnapCenter 플러그인 및 SQL Server용 SnapCenter 플러그인을 복구할 수도 있습니다.

다음은 DR(재해 복구)의 유형입니다.

* * SnapCenter 서버 DR *
+
SnapCenter 서버 데이터는 SnapCenter 서버에서 플러그인을 추가하거나 관리했는지와 관계없이 백업 및 복구됩니다.

+
SnapCenter 재해 복구 기능은 REST API를 사용하여 SnapCenter 서버를 백업합니다.

+
link:../sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html["SnapCenter 서버의 재해 복구를 위한 REST API 워크플로우"]

* * SnapCenter 플러그인 및 스토리지 DR *
+
DR은 SQL Server용 SnapCenter 플러그인에만 지원됩니다. SQL Server용 SnapCenter 플러그인이 다운된 경우 다른 SQL 호스트로 전환하고 몇 가지 단계를 수행하여 데이터를 복구합니다.

+
link:../protect-scsql/task_disaster_recovery_scsql.html["SQL Server용 SnapCenter 플러그인의 재해 복구"]



SnapCenter는 ONTAP SnapMirror 기술을 사용하여 데이터를 복제합니다. 데이터를 2차 사이트로 복제하여 DR에 사용하고 동기화 상태로 유지할 수 있습니다. SnapMirror의 복제 관계를 끊어 페일오버를 시작할 수 있습니다. 페일백 중에 동기화를 취소할 수 있으며 DR 사이트의 데이터를 기본 위치로 다시 복제할 수 있습니다.
