---
permalink: concept/reference_role_based_access_control_permissions_and_roles.html 
sidebar: sidebar 
keywords: RBAC, roles, permissions 
summary: 'SnapCenter RBAC(역할 기반 액세스 제어)를 사용하여 역할을 만들고 해당 역할에 권한을 추가한 다음 사용자나 사용자 그룹을 역할에 할당할 수 있습니다. 따라서 SnapCenter 관리자는 중앙에서 관리되는 환경을 만들 수 있고, 애플리케이션 관리자는 데이터 보호 작업을 관리할 수 있습니다. SnapCenter에는 몇 가지 미리 정의된 역할 및 권한이 제공됩니다.' 
---
= RBAC 권한 및 역할
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter RBAC(역할 기반 액세스 제어)를 사용하여 역할을 만들고 해당 역할에 권한을 할당한 다음 사용자 또는 사용자 그룹을 역할에 할당할 수 있습니다. 따라서 SnapCenter 관리자는 중앙에서 관리되는 환경을 만들 수 있고, 애플리케이션 관리자는 데이터 보호 작업을 관리할 수 있습니다. SnapCenter에는 몇 가지 미리 정의된 역할 및 권한이 제공됩니다.



== SnapCenter 역할

SnapCenter에는 다음과 같은 사전 정의된 역할이 제공됩니다. 이러한 역할에 사용자와 그룹을 할당하거나 새 역할을 만들 수 있습니다.

사용자에게 역할을 할당하면 SnapCenter 관리자 역할을 할당하지 않는 한 해당 사용자와 관련된 작업만 작업 페이지에 표시됩니다.

* 애플리케이션 백업 및 클론 관리
* 백업 및 클론 뷰어
* 인프라 관리자
* SnapCenter서버




== VMware vSphere 역할용 SnapCenter 플러그인

VM, VMDK 및 데이터 저장소의 VM 일관성 있는 데이터 보호를 관리하기 위해 VMware vSphere용 SnapCenter 플러그인을 통해 vCenter에서 다음 역할이 생성됩니다.

* SCV 관리자
* SCV 보기
* SCV 백업
* SCV 복원
* SCV 게스트 파일 복원


자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_types_of_rbac_for_snapcenter_users.html["VMware vSphere 사용자를 위한 SnapCenter 플러그인의 RBAC 유형"^]

|===


| * 모범 사례: * VMware vSphere 운영을 위한 SnapCenter 플러그인에 대해 하나의 ONTAP 역할을 생성한 후 필요한 모든 권한을 할당하는 것이 좋습니다. 
|===


== SnapCenter 권한

SnapCenter는 다음과 같은 권한을 제공합니다.

* 리소스 그룹
* 정책
* 백업
* 호스트
* 스토리지 연결
* 복제
* 프로비저닝(Microsoft SQL 데이터베이스에만 해당)
* 대시보드
* 보고서
* 복원
+
** 전체 볼륨 복원(사용자 지정 플러그인에만 해당)


* 리소스
+
관리자가 아닌 경우 리소스 검색 작업을 수행하려면 관리자에게 플러그인 권한이 필요합니다.

* 플러그인 설치 또는 제거
+

NOTE: 플러그인 설치 권한을 활성화할 경우 읽기 및 업데이트를 사용하도록 호스트 권한도 수정해야 합니다.

* 마이그레이션
* 마운트(Oracle 데이터베이스에만 해당)
* 마운트 해제(Oracle 데이터베이스에만 해당)
* 작업 모니터
+
작업 모니터 권한을 사용하면 다른 역할의 구성원이 할당된 모든 개체에 대한 작업을 볼 수 있습니다.


