---
permalink: concept/reference_data_security.html 
sidebar: sidebar 
keywords: security,authentication, CA certificates 
summary: SnapCenter는 엄격한 보안 및 인증 기능을 사용하여 데이터를 안전하게 보호합니다. 
---
= 보안 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter는 엄격한 보안 및 인증 기능을 사용하여 데이터를 안전하게 보호합니다.

SnapCenter에는 다음과 같은 보안 기능이 포함되어 있습니다.

* SnapCenter에 대한 모든 통신은 HTTP over SSL(HTTPS)을 사용합니다.
* SnapCenter의 모든 자격 증명은 AES(고급 암호화 표준) 암호화를 사용하여 보호됩니다.
* SnapCenter는 FIPS(Federal Information Processing Standard)를 준수하는 보안 알고리즘을 사용합니다.
* SnapCenter는 고객이 제공한 인증 CA 인증서 사용을 지원합니다.
* SnapCenter 4.1.1 이상은 ONTAP와의 통신을 위해 TLS(전송 계층 보안) 1.2를 지원합니다. 클라이언트와 서버 간 통신에 TLS 1.2를 사용할 수도 있습니다.
+
5.0부터 SnapCenter는 ONTAP와의 통신을 위해 (TLS) 1.3을 지원합니다.

* SnapCenter는 특정 SSL 암호화 제품군을 지원하여 네트워크 통신 전반에 보안을 제공합니다.
+
자세한 내용은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_the_supported_SSL_Cipher_Suite["지원되는 SSL 암호화 제품군을 구성하는 방법"].

* SnapCenter는 회사의 방화벽 내부에 설치되어 SnapCenter 서버에 액세스하고 SnapCenter 서버와 플러그인 간의 통신을 지원합니다.
* SnapCenter API 및 작업 액세스는 24시간 후에 만료되는 AES 암호화로 암호화된 토큰을 사용합니다.
* SnapCenter는 Windows Active Directory와 통합되어 로그인 및 액세스 권한을 제어하는 역할 기반 액세스 제어(RBAC)를 사용합니다.
* IPsec은 Windows 및 Linux 호스트 시스템용 ONTAP의 SnapCenter에서 지원됩니다. https://docs.netapp.com/us-en/ontap/networking/configure_ip_security_@ipsec@_over_wire_encryption.html#use-ipsec-identities["자세한 정보"].
* SnapCenter PowerShell cmdlet은 세션 보안입니다.
* 기본 15분 동안 비활성 상태가 지속되면 SnapCenter에서 5분 후에 로그아웃된다는 경고 메시지를 표시합니다. 20분 동안 사용하지 않으면 SnapCenter에서 로그아웃하고 다시 로그인해야 합니다. 로그아웃 기간을 수정할 수 있습니다.
* 5회 이상의 잘못된 로그인 시도 후에 로그인이 일시적으로 비활성화됩니다.
* SnapCenter 서버와 ONTAP 간의 CA 인증서 인증을 지원합니다. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_securely_connect_SnapCenter_with_ONTAP_using_CA_certificate["자세한 정보"].
* 무결성 검증 도구는 SnapCenter 서버 및 플러그인에 추가되며 새로 설치 및 업그레이드 작업을 수행하는 동안 제공된 모든 바이너리의 유효성을 검사합니다.




== CA 인증서 개요

SnapCenter 서버 설치 프로그램을 사용하면 설치하는 동안 중앙 집중식 SSL 인증서 지원을 사용할 수 있습니다. 서버와 플러그인 간의 보안 통신을 강화하기 위해 SnapCenter는 고객이 제공한 인증 CA 인증서 사용을 지원합니다.

SnapCenter 서버 및 해당 플러그인을 설치한 후 CA 인증서를 배포해야 합니다. 자세한 내용은 을 참조하십시오 link:../install/reference_generate_CA_certificate_CSR_file.html["CA 인증서 CSR 파일을 생성합니다"].

VMware vSphere용 SnapCenter 플러그인용 CA 인증서를 구축할 수도 있습니다. 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#create-and-import-certificates["인증서를 만들고 가져옵니다"^].



== 양방향 SSL 통신

양방향 SSL 통신은 SnapCenter 서버와 플러그인 간의 상호 통신을 보호합니다.



== 인증서 기반 인증 개요

인증서 기반 인증은 SnapCenter 플러그인 호스트에 액세스하려고 하는 각 사용자의 인증을 확인합니다. 사용자는 개인 키 없이 SnapCenter 서버 인증서를 내보내고 플러그인 호스트 신뢰할 수 있는 저장소에 가져와야 합니다. 인증서 기반 인증은 양방향 SSL 기능이 활성화된 경우에만 작동합니다.



== 멀티팩터 인증(MFA)

MFA는 SAML(Security Assertion Markup Language)을 통해 타사 ID 공급자(IDP)를 사용하여 사용자 세션을 관리합니다. 이 기능은 TOTP, 생체 인식, 푸시 알림 등과 같은 여러 요소를 기존 사용자 이름 및 암호와 함께 사용할 수 있는 옵션을 제공하므로 인증 보안이 향상됩니다. 또한 고객은 자신의 사용자 ID 공급자를 사용하여 포트폴리오 전체에서 통합 사용자 로그인(SSO)을 얻을 수 있습니다.

MFA는 SnapCenter 서버 UI 로그인에만 적용됩니다. 로그인은 IDP AD FS(Active Directory Federation Services)를 통해 인증됩니다. AD FS에서 다양한 인증 요소를 구성할 수 있습니다. SnapCenter는 서비스 공급자이며 AD FS에서 SnapCenter를 기반 공급업체로 구성해야 합니다. SnapCenter에서 MFA를 사용하려면 AD FS 메타데이터가 필요합니다.

MFA를 사용하는 방법에 대한 자세한 내용은 을 참조하십시오 link:../install/enable_multifactor_authentication.html["다중 요소 인증을 활성화합니다"].
