---
permalink: concept/reference_data_security.html 
sidebar: sidebar 
keywords: security,authentication, CA certificates 
summary: SnapCenter는 엄격한 보안 및 인증 기능을 사용하여 데이터를 안전하게 보호합니다. 
---
= 보안 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter는 엄격한 보안 및 인증 기능을 사용하여 데이터를 안전하게 보호합니다.

SnapCenter에는 다음과 같은 보안 기능이 포함되어 있습니다.

* SnapCenter에 대한 모든 통신은 HTTP over SSL(HTTPS)을 사용합니다.
* SnapCenter의 모든 자격 증명은 AES(고급 암호화 표준) 암호화를 사용하여 보호됩니다.
* SnapCenter는 FIPS(Federal Information Processing Standard)를 준수하는 보안 알고리즘을 사용합니다.
* SnapCenter는 고객이 제공한 인증 CA 인증서 사용을 지원합니다.
* SnapCenter 4.1.1 이상은 ONTAP와의 TLS(전송 계층 보안) 1.2 통신을 지원합니다. 클라이언트와 서버 간에 TLS 1.2 통신을 사용할 수도 있습니다.
* SnapCenter는 회사의 방화벽 내부에 설치되어 SnapCenter 서버에 액세스하고 SnapCenter 서버와 플러그인 간의 통신을 지원합니다.
* SnapCenter API 및 작업 액세스는 24시간 후에 만료되는 AES 암호화로 암호화된 토큰을 사용합니다.
* SnapCenter는 Windows Active Directory와 통합되어 로그인 및 액세스 권한을 제어하는 역할 기반 액세스 제어(RBAC)를 사용합니다.
* SnapCenter PowerShell cmdlet은 세션 보안입니다.
* 기본 15분 동안 비활성 상태가 지속되면 SnapCenter에서 5분 후에 로그아웃된다는 경고 메시지를 표시합니다. 20분 동안 사용하지 않으면 SnapCenter에서 로그아웃하고 다시 로그인해야 합니다. 로그아웃 기간을 수정할 수 있습니다.
* 5회 이상의 잘못된 로그인 시도 후에 로그인이 일시적으로 비활성화됩니다.




== CA 인증서 개요

SnapCenter 서버 설치 프로그램을 사용하면 설치하는 동안 중앙 집중식 SSL 인증서 지원을 사용할 수 있습니다. 서버와 플러그인 간의 보안 통신을 강화하기 위해 SnapCenter는 고객이 제공한 인증 CA 인증서 사용을 지원합니다.

SnapCenter 서버 및 해당 플러그인을 설치한 후 CA 인증서를 배포해야 합니다. 자세한 내용은 을 참조하십시오 link:../install/reference_generate_CA_certificate_CSR_file.html["CA 인증서 CSR 파일을 생성합니다"^].

VMware vSphere용 SnapCenter 플러그인용 CA 인증서를 구축할 수도 있습니다. 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#create-and-import-certificates["인증서를 만들고 가져옵니다"^].
