---
permalink: upgrade/task_upgrade_snapcenter.html 
sidebar: sidebar 
keywords: upgrade, upgrade snapcenter server 
summary: SnapCenter 서버 설치 관리자 실행 파일을 사용하여 SnapCenter 서버를 업그레이드할 수 있습니다. 
---
= SnapCenter 서버를 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버 설치 관리자 실행 파일을 사용하여 SnapCenter 서버를 업그레이드할 수 있습니다.

* 필요한 것 *

* SnapCenter 서버 호스트는 Windows 업데이트와 함께 최신 버전이어야 하며, 보류 중인 시스템 재시작이 없어야 합니다.
* 업그레이드 작업을 시작하기 전에 실행 중인 다른 작업이 없는지 확인해야 합니다.
* 실행 중인 작업이 없는지 확인한 후 SnapCenter 리포지토리(MySQL) 데이터베이스를 백업해야 합니다. SnapCenter 서버 및 Exchange 플러그인을 업그레이드하기 전에 이 방법을 권장합니다.
+
자세한 내용은 을 참조하십시오 link:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenter 리포지토리를 백업합니다"^].

* SnapCenter 서버 호스트 또는 플러그인 호스트에서 수정한 모든 SnapCenter 구성 파일을 백업해야 합니다.
+
SnapCenter 구성 파일의 예: SnapDriveService.exe.config, SMCoreServiceHost.exe.config 등



* 이 작업에 대한 정보 *

* 업그레이드 중에는 호스트가 예약된 작업을 실행하지 못하도록 유지 보수 모드로 자동 전환됩니다. 업그레이드 후 호스트가 자동으로 유지 보수 모드에서 해제됩니다.
* 업그레이드 중에 SQL 스크립트를 실행하여 NSM 데이터베이스에서 Exchange 데이터를 업데이트합니다. 그러면 DAG 및 호스트 단축 이름이 FQDN으로 변환됩니다. 이 기능은 Exchange 플러그인이 있는 SnapCenter 서버를 사용하는 경우에만 적용됩니다.
* 업그레이드 작업을 시작하기 전에 호스트를 유지 관리 모드로 수동으로 배치한 경우 업그레이드 후 * 호스트 * > * 스케줄 활성화 * 를 클릭하여 호스트를 유지 관리 모드에서 수동으로 해제해야 합니다.


* 단계 *

. NetApp Support 사이트에서 SnapCenter 서버 설치 패키지를 다운로드하십시오.
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[]

. C:\Program Files\NetApp\SnapCenter WebApp에 있는 web.config의 복사본을 생성합니다.
. Windows 작업 스케줄에서 플러그인 호스트와 관련된 SnapCenter 스케줄을 내보내면 업그레이드에 실패할 경우 이를 사용하여 스케줄을 복구할 수 있습니다.
+
md:\\SCBackup's chtasks/query/xml/TN TASKNAME>>"D:\SCBackup\TASKNAME.xml"

. 리포지토리 백업이 구성되지 않은 경우 SnapCenter MySQL 데이터베이스 덤프를 생성합니다.
+
md:\\SCBackup 'mysqldump -- all-databases -- single-transaction -- add-drop-database -- triggers -- routines -- events -u root -p > D:\SCBackup\ScrepoBackup.dmp'

+
메시지가 표시되면 암호를 입력합니다.

. 다운로드한 .exe 파일을 두 번 클릭하여 SnapCenter 서버 업그레이드를 시작합니다.
+
업그레이드를 시작하면 모든 사전 점검을 수행하고, 최소 요구사항을 충족하지 않을 경우 적절한 오류 또는 경고 메시지가 표시됩니다. 경고 메시지를 무시하고 설치를 계속할 수 있습니다. 그러나 오류는 수정해야 합니다.

+

NOTE: SnapCenter는 이전 버전의 SnapCenter Server 설치 중에 제공된 기존 MySQL Server 리포지토리 데이터베이스 암호를 계속 사용합니다.

. 업그레이드 * 를 클릭합니다.
+
어느 단계에서든 * 취소 * 버튼을 클릭하면 업그레이드 워크플로우가 취소됩니다. SnapCenter 서버를 이전 상태로 롤백하지 않습니다.

+
|===


| *모범 사례:* 로그아웃한 다음 SnapCenter에 로그인하거나, 닫은 다음 새 브라우저를 열어 SnapCenter GUI에 액세스해야 합니다. 
|===


* 완료 후 *

* sudo 사용자를 사용하여 플러그인을 설치하는 경우 _C:\ProgramData\NetApp\SnapCenter\Package Repository\Oracle_checksum.txt_에서 사용할 수 있는 sha224 키를 복사하여 _/etc/sudoers_file을 업데이트해야 합니다.
* 호스트에서 리소스를 새로 검색해야 합니다.
+
호스트 상태가 중지됨 으로 표시되면 잠시 기다린 후 새 검색을 수행할 수 있습니다. HostRefreshInterval* 매개 변수 값(기본값은 3600초)을 10분 이상의 값으로 변경할 수도 있습니다.

* 업그레이드에 실패하면 실패한 설치를 정리하여 이전 버전의 SnapCenter를 다시 설치한 다음 NSM 데이터베이스를 이전 상태로 복원해야 합니다.
* SnapCenter 서버 호스트를 업그레이드한 후 스토리지 시스템을 추가하기 전에 플러그인도 업그레이드해야 합니다.

