---
permalink: protect-hana/task_configure_CA_certificate_for_saphana_on_Linux_host.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: Linux 호스트에서 SnapCenter 사용자 지정 플러그인 서비스에 대한 CA 인증서를 구성합니다 
---
= Linux 호스트에서 SnapCenter SAP HANA 플러그인 서비스에 대한 CA 인증서를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


사용자 지정 플러그인 키 저장소 및 인증서의 암호를 관리하고, CA 인증서를 구성하고, 사용자 지정 플러그인 트러스트 저장소에 대한 루트 또는 중간 인증서를 구성하고, SnapCenter 사용자 지정 플러그인 서비스를 사용하여 사용자 지정 플러그인 트러스트 저장소에 CA 서명 키 쌍을 구성하여 설치된 디지털 인증서를 활성화해야 합니다.

사용자 지정 플러그인은 _/opt/netapp/snapcenter/SCC/etc_에 있는 'keystore.jks' 파일을 신뢰 저장소 및 키 저장소로 사용합니다.



== 사용자 지정 플러그인 키 저장소 및 사용 중인 CA 서명 키 쌍의 별칭에 대한 암호를 관리합니다

* 단계 *

. 사용자 지정 플러그인 에이전트 속성 파일에서 사용자 지정 플러그인 키 저장소 기본 암호를 검색할 수 있습니다.
+
'keystore_pass' 키에 해당하는 값입니다.

. 키 저장소 암호를 변경합니다.
+
 keytool -storepasswd -keystore keystore.jks
. 키 저장소에 있는 개인 키 항목의 모든 별칭에 대한 암호를 키 저장소에 사용되는 동일한 암호로 변경합니다.
+
 keytool -keypasswd -alias "alias_name_in_cert" -keystore keystore.jks
+
_agent.properties_ 파일의 keystore_pass 키에 대해서도 동일한 업데이트를 하십시오.

. 암호를 변경한 후 서비스를 다시 시작합니다.



NOTE: 사용자 지정 플러그인 키 저장소 및 개인 키의 모든 관련 별칭 암호에 대한 암호는 동일해야 합니다.



== 사용자 지정 플러그인 트러스트 저장소에 루트 또는 중간 인증서를 구성합니다

사용자 지정 플러그인 트러스트 저장소에 대한 개인 키 없이 루트 또는 중간 인증서를 구성해야 합니다.

* 단계 *

. 사용자 지정 플러그인 키 저장소가 포함된 폴더로 이동합니다. /opt/netapp/snapcenter/SCC 등
. 'keystore.jks' 파일을 찾습니다.
. 키 저장소에 추가된 인증서를 나열합니다.
+
키툴-리스트-v-keystore keystore.jks

. 루트 또는 중간 인증서 추가:
+
 keytool -import -trustcacerts -alias myRootCA -file /root/USERTrustRSA_Root.cer -keystore keystore.jks
. 루트 또는 중간 인증서를 사용자 지정 플러그인 트러스트 저장소에 구성한 후 서비스를 다시 시작합니다.



NOTE: 루트 CA 인증서와 중간 CA 인증서를 추가해야 합니다.



== 사용자 지정 플러그인 트러스트 저장소에 CA 서명 키 쌍을 구성합니다

CA 서명 키 쌍을 사용자 지정 플러그인 트러스트 저장소에 구성해야 합니다.

* 단계 *

. 사용자 지정 플러그인 키 저장소/opt/NetApp/snapcenter/SCC 등이 포함된 폴더로 이동합니다
. 'keystore.jks' 파일을 찾습니다.
. 키 저장소에 추가된 인증서를 나열합니다.
+
키툴-리스트-v-keystore keystore.jks

. 개인 키와 공개 키를 모두 사용하는 CA 인증서를 추가합니다.
+
keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS

. 키 저장소에 추가된 인증서를 나열합니다.
+
키툴-리스트-v-keystore keystore.jks

. keystore에 keystore에 추가된 새 CA 인증서에 해당하는 별칭이 포함되어 있는지 확인합니다.
. CA 인증서에 추가된 개인 키 암호를 키 저장소 암호로 변경합니다.
+
기본 사용자 지정 플러그인 키 저장소 암호는 agent.properties 파일의 keystore_pass 키 값입니다.

+
 keytool -keypasswd -alias "alias_name_in_CA_cert" -keystore keystore.jks
. CA 인증서의 별칭 이름이 길고 공백 또는 특수 문자("*",",")가 포함된 경우 별칭 이름을 단순 이름으로 변경합니다.
+
 keytool -changealias -alias "long_alias_name" -destalias "simple_alias" -keystore keystore.jks
. agent.properties 파일의 CA 인증서에서 별칭 이름을 구성합니다.
+
이 값을 SCC_CERTIFICATE_ALIAS 키에 대해 업데이트합니다.

. CA 서명 키 쌍을 사용자 지정 플러그인 트러스트 저장소에 구성한 후 서비스를 다시 시작합니다.




== SnapCenter 사용자 지정 플러그인에 대한 CRL(인증서 해지 목록)을 구성합니다

* 이 작업에 대한 정보 *

* SnapCenter 사용자 지정 플러그인은 사전 구성된 디렉터리에서 CRL 파일을 검색합니다.
* SnapCenter 사용자 지정 플러그인에 대한 CRL 파일의 기본 디렉토리는 'opt/netapp/snapcenter/SCC/etc/CRL'입니다.


* 단계 *

. agent.properties 파일의 기본 디렉터리를 수정하여 CRL_path 키에 맞게 업데이트할 수 있습니다.
+
이 디렉터리에 둘 이상의 CRL 파일을 배치할 수 있습니다. 들어오는 인증서는 각 CRL에 대해 확인됩니다.


