---
permalink: protect-hana/task_back_up_databases_using_powershell_cmdlets_sap_hana.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for SAP HANA Database 
summary: 데이터베이스 백업에는 SnapCenter 서버와의 연결 설정, 리소스 추가, 정책 추가, 백업 리소스 그룹 생성 및 백업이 포함됩니다. 
---
= PowerShell cmdlet을 사용하여 데이터베이스를 백업합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터베이스 백업에는 SnapCenter 서버와의 연결 설정, 리소스 추가, 정책 추가, 백업 리소스 그룹 생성 및 백업이 포함됩니다.

* 필요한 것 *

* PowerShell cmdlet을 실행하려면 PowerShell 환경을 준비해야 합니다.
* 스토리지 시스템 접속을 추가하고 자격 증명을 생성해야 합니다.


* 단계 *

. Open-SmConnection cmdlet을 사용하여 지정된 사용자에 대한 SnapCenter Server 연결 세션을 시작합니다.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146\
----
+
사용자 이름 및 암호 프롬프트가 표시됩니다.

. Add-SmResources cmdlet을 사용하여 리소스를 추가합니다.
+
이 예제에서는 SingleContainer 형식의 SAP HANA 데이터베이스를 추가하는 방법을 보여 줍니다.

+
[listing]
----
C:\PS> Add-SmResource -HostName '10.232.204.42' -PluginCode 'HANA' -DatabaseName H10 -ResourceType SingleContainer -StorageFootPrint (@{"VolumeName"="HanaData10";"StorageSystem"="vserver_scauto_primary"}) -SID 'H10' -filebackuppath '/tmp/HanaFileLog' -userstorekeys 'HS10' -osdbuser 'h10adm' -filebackupprefix 'H10_'
----
+
이 예제에서는 MultipleContainer 유형의 SAP HANA 데이터베이스를 추가하는 방법을 보여 줍니다.

+
[listing]
----
C:\PS> Add-SmResource -HostName 'vp-hana2.gdl.englab.netapp.com' -PluginCode 'HANA' -DatabaseName MDC_MT -ResourceType MultipleContainers -StorageFootPrint (@{"VolumeName"="VP_HANA2_data";"StorageSystem"="buck.gdl.englab.netapp.com"}) -sid 'A12' -userstorekeys 'A12KEY' -TenantType 'MultiTenant'
----
+
이 예에서는 비 데이터 볼륨 리소스를 생성하는 방법을 보여 줍니다.

+
[listing]
----
C:\PS> Add-SmResource -HostName 'SNAPCENTERN42.sccore.test.com' -PluginCode 'hana' -ResourceName NonDataVolume -ResourceType NonDataVolume -StorageFootPrint (@{"VolumeName"="ng_pvol";"StorageSystem"="vserver_scauto_primary"}) -sid 'S10'
----
. Add-SmPolicy cmdlet을 사용하여 백업 정책을 만듭니다.
+
이 예에서는 스냅샷 복사본 기반 백업에 대한 백업 정책을 생성합니다.

+
[listing]
----
C:\PS> Add-SmPolicy -PolicyName hana_snapshotbased -PolicyType Backup -PluginPolicyType hana -BackupType SnapShotBasedBackup
----
+
이 예에서는 파일 기반 백업에 대한 백업 정책을 생성합니다.

+
[listing]
----
C:\PS> Add-SmPolicy -PolicyName hana_Filebased -PolicyType Backup -PluginPolicyType hana -BackupType FileBasedBackup
----
. 추가 SmResourceGroup cmdlet을 사용하여 리소스를 보호하거나 SnapCenter에 새 리소스 그룹을 추가합니다.
+
이 예에서는 단일 컨테이너 리소스를 보호합니다.

+
[listing]
----
C:\PS> Add-SmProtectResource -PluginCode HANA  -Policies hana_snapshotbased,hana_Filebased
 -Resources @{"Host"="host.example.com";"UID"="SID"} -Description test -usesnapcenterwithoutfilesystemconsistency
----
+
이 예에서는 여러 컨테이너 리소스를 보호합니다.

+
[listing]
----
C:\PS> Add-SmProtectResource -PluginCode HANA  -Policies hana_snapshotbased,hana_Filebased
 -Resources @{"Host"="host.example.com";"UID"="MDC\SID"} -Description test -usesnapcenterwithoutfilesystemconsistency
----
+
이 예제에서는 지정된 정책 및 리소스를 사용하여 새 리소스 그룹을 만듭니다.

+
[listing]
----
C:\PS> Add-SmResourceGroup -ResourceGroupName 'ResourceGroup_with_SingleContainer_MultipleContainers_Resources' -Resources @(@{"Host"="sccorelinux61.sccore.test.com";"Uid"="SID"},@{"Host"="sccorelinux62.sccore.test.com";"Uid"="MDC\SID"})
  -Policies hana_snapshotbased,hana_Filebased  -usesnapcenterwithoutfilesystemconsistency  -plugincode 'HANA'
----
+
이 예에서는 데이터 볼륨이 아닌 리소스 그룹을 생성합니다.

+
[listing]
----
C:\PS> Add-SmResourceGroup -ResourceGroupName 'Mixed_RG_backup_when_Remove_Backup_throguh_BackupName_windows' -Resources @(@{"Host"="SNAPCENTERN42.sccore.test.com";"Uid"="H11";"PluginName"="hana"},@{"Host"="SNAPCENTERN42.sccore.test.com";"Uid"="MDC\H31";"PluginName"="hana"},@{"Host"="SNAPCENTERN42.sccore.test.com";"Uid"="NonDataVolume\S10\NonDataVolume";"PluginName"="hana"}) -Policies hanaprimary
----
. New-SmBackup cmdlet을 사용하여 새 백업 작업을 시작합니다.
+
이 예제에서는 리소스 그룹을 백업하는 방법을 보여 줍니다.

+
[listing]
----
C:\PS> New-SMBackup -ResourceGroupName 'ResourceGroup_with_SingleContainer_MultipleContainers_Resources'  -Policy hana_snapshotbased
----
+
다음 예에서는 보호된 리소스를 백업합니다.

+
[listing]
----
C:\PS> New-SMBackup -Resources @{"Host"="10.232.204.42";"Uid"="MDC\SID";"PluginName"="hana"} -Policy hana_Filebased
----
. get-smJobSummaryReport cmdlet을 사용하여 작업 상태(실행 중, 완료 또는 실패)를 모니터링합니다.
+
[listing]
----
PS C:\> Get-smJobSummaryReport -JobID 123
----
. Get-SmBackupReport cmdlet을 사용하여 백업 ID, 백업 이름과 같은 백업 작업 세부 정보를 모니터링하여 복원 또는 클론 작업을 수행합니다.
+
[listing]
----
PS C:\> Get-SmBackupReport -JobId 351
Output:
BackedUpObjects           : {DB1}
FailedObjects             : {}
IsScheduled               : False
HasMetadata               : False
SmBackupId                : 269
SmJobId                   : 2361
StartDateTime             : 10/4/2016 11:20:45 PM
EndDateTime               : 10/4/2016 11:21:32 PM
Duration                  : 00:00:46.2536470
CreatedDateTime           : 10/4/2016 11:21:09 PM
Status                    : Completed
ProtectionGroupName       : Verify_ASUP_Message_windows
SmProtectionGroupId       : 211
PolicyName                : test2
SmPolicyId                : 20
BackupName                : Verify_ASUP_Message_windows_scc54_10-04-2016_23.20.46.2758
VerificationStatus        : NotVerified
VerificationStatuses      :
SmJobError                :
BackupType                : SCC_BACKUP
CatalogingStatus          : NotApplicable
CatalogingStatuses        :
ReportDataCreatedDateTime :
----


cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].
