---
permalink: protect-hana/task_prepare_multitenant_database_containers_for_data_protection.html 
sidebar: sidebar 
keywords: multitenant database containers 
summary: 'SnapCenter에 직접 등록된 SAP HANA 호스트의 경우 SAP HANA 데이터베이스용 SnapCenter 플러그인을 설치 또는 업그레이드하면 호스트에서 리소스를 자동으로 검색할 수 있습니다. 플러그인을 설치 또는 업그레이드한 후 플러그인 호스트에 있는 모든 다중 테넌트 데이터베이스 컨테이너 \(MDC\) 리소스에 대해 다른 GUID 형식으로 다른 MDC 리소스가 자동으로 검색되어 SnapCenter에 등록됩니다. 새 리소스가 "잠김" 상태가 됩니다.' 
---
= 데이터 보호를 위한 멀티 테넌트 데이터베이스 컨테이너 준비
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter에 직접 등록된 SAP HANA 호스트의 경우 SAP HANA 데이터베이스용 SnapCenter 플러그인을 설치 또는 업그레이드하면 호스트에서 리소스를 자동으로 검색할 수 있습니다. 플러그인을 설치 또는 업그레이드한 후 플러그인 호스트에 있는 모든 MDC(멀티테넌트 데이터베이스 컨테이너) 리소스에 대해 다른 GUID 형식으로 다른 MDC 리소스가 자동으로 검색되어 SnapCenter에 등록됩니다. 새 자원은 "잠김" 상태가 됩니다.

* 이 작업에 대한 정보 *

예를 들어 SnapCenter 4.2에서 E90 MDC 리소스가 플러그인 호스트에 있고 수동으로 등록된 경우 SnapCenter 4.3으로 업그레이드한 후 다른 GUID를 가진 다른 E90 MDC 리소스가 SnapCenter에 검색되어 등록됩니다.


NOTE: SnapCenter 4.2 및 이전 버전의 리소스와 연결된 백업은 보존 기간이 만료될 때까지 보존되어야 합니다. 보존 기간이 만료된 후에는 이전 MDC 리소스를 삭제하고 자동으로 검색된 새 MDC 리소스를 계속 관리할 수 있습니다.

'기존 MDC 리소스'는 SnapCenter 4.2 이전 릴리즈에서 수동으로 추가한 플러그인 호스트의 MDC 리소스입니다.

다음 단계를 수행하여 SnapCenter 4.3에서 검색된 새 리소스를 데이터 보호 작업에 사용할 수 있습니다.

* 단계 *

. 리소스 페이지에서 이전 SnapCenter 릴리스에 추가된 백업이 있는 이전 MDC 리소스를 선택하고 토폴로지 페이지에서 "유지 관리 모드"로 배치합니다.
+
자원이 자원 그룹의 일부인 경우 자원 그룹을 "유지보수 모드"로 설정합니다.

. 리소스 페이지에서 새 리소스를 선택하여 SnapCenter 4.3으로 업그레이드한 후 검색된 새 MDC 리소스를 구성합니다.
+
"'새 MDC 리소스'는 SnapCenter 서버와 플러그인 호스트를 4.3으로 업그레이드한 후 새로 발견된 MDC 리소스입니다. 새 MDC 리소스는 기존 MDC 리소스와 동일한 SID를 가진 리소스로 식별될 수 있으며, 지정된 호스트의 경우 빨간색 자물쇠 아이콘이 리소스 페이지에 표시됩니다.

. 보호 정책, 일정 및 알림 설정을 선택하여 SnapCenter 4.3으로 업그레이드한 후 발견된 새 MDC 리소스를 보호합니다.
. 보존 설정을 기반으로 SnapCenter 4.2 이전 릴리즈에서 수행한 백업을 삭제합니다.
. 토폴로지 페이지에서 리소스 그룹을 삭제합니다.
. 리소스 페이지에서 이전 MDC 리소스를 삭제합니다.
+
예를 들어 기본 스냅샷 복사본의 보존 기간이 7일이고 보조 스냅샷 복사본의 보존 기간이 45일이고 45일이 지난 후 모든 백업을 삭제한 경우 리소스 그룹과 이전 MDC 리소스를 삭제해야 합니다.



* 자세한 정보 찾기 *

link:task_configure_hdb_user_store_key_and_hdbsql_os_user_for_the_sap_hana_database.html["SAP HANA 데이터베이스용 HDB 사용자 저장소 키 및 HDBSQL OS 사용자를 구성합니다"]

link:task_view_sap_hana_database_backups_and_clones_in_the_topology_page_sap_hana.html["토폴로지 페이지에서 SAP HANA 데이터베이스 백업 및 클론 보기"]
