---
permalink: protect-scc/concept_develop_a_plug_in_for_your_application.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter 서버를 사용하면 SnapCenter에 대한 플러그인으로 응용 프로그램을 배포 및 관리할 수 있습니다. 
---
= 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버를 사용하면 SnapCenter에 대한 플러그인으로 응용 프로그램을 배포 및 관리할 수 있습니다. 원하는 애플리케이션을 SnapCenter 서버에 연결하여 데이터 보호 및 관리 기능을 활용할 수 있습니다.

SnapCenter를 사용하면 다양한 프로그래밍 언어를 사용하여 사용자 지정 플러그인을 개발할 수 있습니다. Perl, Java, 배치 또는 기타 스크립팅 언어를 사용하여 사용자 지정 플러그인을 개발할 수 있습니다.

SnapCenter에서 사용자 지정 플러그인을 사용하려면 다음 작업을 수행해야 합니다.

* 이 가이드의 지침에 따라 응용 프로그램용 플러그인을 만듭니다
* 설명 파일을 만듭니다
* 사용자 지정 플러그인을 내보내어 SnapCenter 호스트에 설치합니다
* 플러그인 zip 파일을 SnapCenter 서버에 업로드합니다




== 모든 API 호출의 일반 플러그인 처리

[role="lead"]
모든 API 호출에 대해 다음 정보를 사용합니다.

* 플러그인 매개 변수
* 종료 코드
* 오류 메시지를 기록합니다
* 데이터 정합성




=== 플러그인 매개 변수를 사용합니다

매개 변수 집합은 모든 API 호출의 일부로 플러그인으로 전달됩니다. 다음 표에서는 매개 변수에 대한 특정 정보를 보여 줍니다.

|===
| 매개 변수 | 목적 


 a| 
조치
 a| 
워크플로 이름을 결정합니다. 예를 들어, 검색, 백업, fileOrVolRestore 또는 cloneVolAndLun을 사용할 수 있습니다



 a| 
리소스
 a| 
보호할 리소스를 나열합니다. 리소스는 UID 및 유형으로 식별됩니다. 이 목록은 다음 형식으로 플러그인에 표시됩니다.

"<UID>, <type>;<UID>, <type>". 예: “Instance1, 인스턴스;Instance2\\DB1, 데이터베이스”



 a| 
APP_NAME입니다
 a| 
사용 중인 플러그인을 결정합니다. 예: DB2, MySQL. SnapCenter 서버는 나열된 응용 프로그램에 대한 지원을 기본적으로 제공합니다. 이 매개 변수는 대/소문자를 구분합니다.



 a| 
app_ignore_error
 a| 
(Y 또는 N) 응용 프로그램 오류가 발생하면 SnapCenter가 종료되거나 종료되지 않습니다. 이 기능은 여러 데이터베이스를 백업할 때 단일 오류로 인해 백업 작업이 중지되지 않도록 하는 경우에 유용합니다.



 a| 
resource_name>__app_instance_username입니다
 a| 
리소스에 대해 SnapCenter 자격 증명이 설정되었습니다.



 a| 
resource_name>_app_instance_password
 a| 
리소스에 대해 SnapCenter 자격 증명이 설정되었습니다.



 a| 
resource_name>_<custom_pRAM>
 a| 
모든 리소스 수준 사용자 지정 키 값은 "<resource_name>_" 접두사가 붙은 플러그인에서 사용할 수 있습니다. 예를 들어 사용자 지정 키가 "MySQLDB"라는 리소스의 "master_slave"인 경우 MySQLDB_master_slave로 사용할 수 있습니다

|===


=== 종료 코드를 사용합니다

플러그인은 종료 코드를 통해 작업 상태를 호스트로 다시 반환합니다. 각 코드는 특정 의미를 가지고 있으며 플러그인은 동일한 것을 나타내기 위해 오른쪽 종료 코드를 사용합니다.

다음 표에서는 오류 코드와 그 의미를 보여 줍니다.

|===
| 종료 코드입니다 | 목적 


 a| 
0
 a| 
작업이 성공했습니다.



 a| 
99
 a| 
요청된 작업이 지원되지 않거나 구현되지 않았습니다.



 a| 
100
 a| 
작업이 실패했습니다. 일시 중지 해제를 건너뛰고 를 종료합니다. 일시 중지 해제는 기본적으로 사용됩니다.



 a| 
101
 a| 
작업이 실패했습니다. 백업 작업을 계속합니다.



 a| 
기타
 a| 
작업이 실패했습니다. 중지 해제를 실행하고 종료합니다.

|===


=== 오류 메시지를 기록합니다

오류 메시지는 플러그인에서 SnapCenter 서버로 전달됩니다. 메시지에는 메시지, 로그 수준 및 타임 스탬프가 포함됩니다.

다음 표에는 레벨 및 그 용도가 나와 있습니다.

|===
| 매개 변수 | 목적 


 a| 
정보
 a| 
정보 메시지입니다



 a| 
경고
 a| 
경고 메시지



 a| 
오류
 a| 
오류 메시지



 a| 
디버그
 a| 
디버그 메시지입니다



 a| 
트레이스
 a| 
Trace 메시지

|===


=== 데이터 일관성 유지

사용자 지정 플러그인은 동일한 워크플로우 실행 작업 간 데이터를 보존합니다. 예를 들어, 플러그인은 일시 중지 종료 시 데이터를 저장할 수 있으며, 일시 중지 해제 작업 중에 사용할 수 있습니다.

보존할 데이터는 플러그인으로 결과 객체의 일부로 설정됩니다. 특정 형식을 따르며 각 플러그인 개발 스타일에 대해 자세히 설명합니다.
