---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_features.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter는 플러그인 애플리케이션 및 스토리지 시스템의 NetApp 기술과 통합됩니다. 사용자 지정 플러그인으로 작업하려면 SnapCenter 그래픽 사용자 인터페이스를 사용합니다. 
---
= SnapCenter 맞춤형 플러그인 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter는 플러그인 애플리케이션 및 스토리지 시스템의 NetApp 기술과 통합됩니다. 사용자 지정 플러그인으로 작업하려면 SnapCenter 그래픽 사용자 인터페이스를 사용합니다.

* * 통합 그래픽 사용자 인터페이스 *
+
SnapCenter 인터페이스는 플러그인과 환경 전반에서 표준화와 일관성을 제공합니다. SnapCenter 인터페이스를 사용하면 플러그인 전체에서 일관된 백업, 복원, 복구, 클론 작업을 완료하고, 중앙 집중식 보고 기능을 사용하고, 대시보드 뷰를 한눈에 보고, RBAC(역할 기반 액세스 제어)를 설정하고, 모든 플러그인에 걸쳐 작업을 모니터링할 수 있습니다.

* * 자동화된 중앙 관리 *
+
백업 작업을 예약하고, 정책 기반 백업 보존을 구성하고, 복구 작업을 수행할 수 있습니다. 또한 SnapCenter에서 이메일 경고를 보내도록 구성하여 환경을 사전에 모니터링할 수도 있습니다.

* * 무중단 NetApp 스냅샷 복사본 기술 *
+
SnapCenter은 SnapCenter 맞춤형 플러그인과 NetApp 스냅샷 복사본 기술을 사용하여 리소스를 백업합니다. 스냅샷 복사본은 최소 스토리지 공간을 사용합니다.



사용자 지정 플러그인 기능을 사용하면 다음과 같은 이점이 있습니다.

* 백업, 복원 및 클론 워크플로우 지원
* RBAC 지원 보안 및 중앙 집중식 역할 위임
+
권한이 있는 SnapCenter 사용자가 응용 프로그램 수준 권한을 갖도록 자격 증명을 설정할 수도 있습니다.

* NetApp FlexClone 기술을 사용하여 테스트 또는 데이터 추출을 위한 공간 효율적인 특정 시점 리소스 복사본 생성
+
클론을 생성하려는 스토리지 시스템에는 FlexClone 라이센스가 필요합니다.

* 백업을 생성하는 과정에서 ONTAP의 일관성 그룹(CG) 스냅샷 복사본 기능이 지원됩니다.
* 여러 리소스 호스트에서 동시에 여러 백업을 실행할 수 있습니다
+
단일 호스트에서 단일 호스트의 리소스가 동일한 볼륨을 공유할 경우 스냅샷 복사본이 통합됩니다.

* 외부 명령을 사용하여 스냅샷 복사본을 생성하는 기능
* Windows 환경에서 파일 시스템의 일관된 Snapshot 복사본을 생성할 수 있는 기능

