---
permalink: protect-scc/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_custom_plug_ins.html 
sidebar: sidebar 
keywords: credentials 
summary: 호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다. 사용자 지정 플러그인은 Windows 및 Linux 환경 모두에서 사용할 수 있습니다. 
---
= 호스트 추가 및 SnapCenter 사용자 지정 플러그인 설치를 위한 사전 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다. 사용자 지정 플러그인은 Windows 및 Linux 환경 모두에서 사용할 수 있습니다.

* 사용자 지정 플러그인을 만들어야 합니다. 자세한 내용은 개발자 정보를 참조하십시오.
+
link:concept_develop_a_plug_in_for_your_application.html["응용 프로그램용 플러그인을 개발합니다"]

* MySQL 또는 DB2 애플리케이션을 관리하려면 NetApp에서 제공하는 MySQL 및 DB2 사용자 지정 플러그인을 다운로드해야 합니다.
* Linux 또는 Windows 호스트에 Java 1.8 또는 Java 11(64비트)을 설치해야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자에 속한 경우 호스트에서 UAC를 비활성화해야 합니다.
* 호스트 추가 작업이 수행되는 클라이언트 호스트에서 사용자 지정 플러그인을 사용할 수 있어야 합니다.




== 일반

iSCSI를 사용하는 경우 iSCSI 서비스가 실행되고 있어야 합니다.



== SHA512 해시

* NetApp에서 제공하는 사용자 지정 플러그인의 경우 사용자 지정 플러그인 파일의 SHA512 해시를 _CUSTOM_PLUGIN_CHECKSH체크섬_LIST_FILE에 추가해야 합니다.
+
** Linux 호스트의 경우 SHA512 해시는 _/var/opt/snapcenter/SCC/custom_plugin_checksum_list.txt_에 있습니다
** Windows 호스트의 경우 SHA512 해시는 _C:\Program Files\NetApp\SnapCenter Plug-in Creator\etc\custom_plugin_checksum_list.txt_에 있습니다
+
사용자 지정 설치 경로의 경우 SHA512 해시는 _<사용자 지정 경로>\NetApp\SnapCenter\Snapcenter 플러그인 생성자\etc\custom_plugin_checksum_list.txt_에 있습니다



+
custom_plugin_checksum_list 는 SnapCenter에서 호스트에 설치하는 사용자 지정 플러그인 설치의 일부입니다.

* 응용 프로그램에 대해 생성된 사용자 지정 플러그인의 경우 다음 단계를 수행해야 합니다.
+
.. 플러그인 zip 파일의 SHA512 해시를 생성했습니다.
+
과 같은 온라인 도구를 사용할 수 있습니다 https://["SHA512 해시"^].

.. 생성된 SHA512 해시를 새 줄에 CUSTOM_PLUGIN_CHECK체크섬_LIST 파일에 추가했습니다.
+
주석은 # 기호로 시작하여 해시가 속한 플러그인을 식별합니다.

+
다음은 체크섬 파일의 SHA512 해시 항목의 예입니다.

+
....
#ORASCPM
03721f567a1e4a1cb5569066b9a58af619ee12b1f8713108f81b696cfbdb81c25232fa63d6e6777a2b2a1ec068bb0a93a59a8ade71587182f8bccbe81f7e0ba6
....






== Windows 호스트

* 원격 호스트에 대한 로컬 로그인 권한이 있는 로컬 관리자 권한이 있는 도메인 사용자가 있어야 합니다.
* SnapCenter에서 클러스터 노드를 관리하는 경우 클러스터의 모든 노드에 대한 관리 권한이 있는 사용자가 있어야 합니다.




== Linux 호스트

* 루트 또는 루트 이외의 사용자에 대해 암호 기반 SSH 연결을 활성화해야 합니다.
* Linux 호스트에 Java 1.8 또는 Java 11(64비트)을 설치해야 합니다.
+
SnapCenter 서버 호스트에 Windows Server 2019 또는 Windows Server 2016을 사용하는 경우 Java 1.8 또는 Java 11(64비트)을 설치해야 합니다. 상호 운용성 매트릭스 툴(IMT): 요구사항에 대한 최신 정보를 제공합니다.

+
http://["모든 운영 체제에 대한 Java 다운로드"]

+
https://["NetApp 상호 운용성 매트릭스 툴"]

* 여러 경로에 대한 액세스를 제공하려면 비루트 사용자에 대해 sudo 권한을 구성해야 합니다. visudo Linux 유틸리티를 사용하여 /etc/sudoers 파일에 다음 행을 추가합니다.
+

NOTE: Sudo 버전 1.8.7 이상을 사용하고 있는지 확인합니다.

+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_linux_user_는 사용자가 생성한 루트가 아닌 사용자의 이름입니다.

+
_C:\ProgramData\NetApp\SnapCenter\Package Repository_에 있는 * Oracle_checksum.txt * 파일에서 _checksum_value_를 가져올 수 있습니다.

+

IMPORTANT: 이 예제는 고유한 데이터를 만들기 위한 참조로만 사용해야 합니다.


