---
permalink: protect-scc/reference_backup_schedules_of_custom_plug_in_resources.html 
sidebar: sidebar 
keywords:  
summary: 백업 스케줄을 결정할 때 가장 중요한 요소는 리소스의 변경 속도입니다. 리소스를 더 자주 백업할수록 SnapCenter에서 복원에 사용하는 아카이브 로그가 적어지므로 복원 작업이 더 빨라집니다. 
---
= 사용자 지정 플러그인 리소스의 백업 스케줄입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 스케줄을 결정할 때 가장 중요한 요소는 리소스의 변경 속도입니다. 리소스를 더 자주 백업할수록 SnapCenter에서 복원에 사용하는 아카이브 로그가 적어지므로 복원 작업이 더 빨라집니다.

자주 사용하는 리소스를 매일 한 번씩 백업할 수도 있고, 자주 사용하지 않는 리소스를 하루에 한 번 백업할 수도 있습니다. 기타 요인으로는 조직에 리소스의 중요성, SLA(서비스 수준 계약) 및 RPO(복구 지점 목표)가 있습니다.

SLA는 예상되는 서비스 수준을 정의하고 가용성 및 서비스 성능을 비롯한 다양한 서비스 관련 문제를 해결합니다. RPO는 장애 후 정상적인 작업을 재개하기 위해 백업 스토리지에서 복구해야 하는 파일의 사용 기간에 대한 전략을 정의합니다. SLA 및 RPO는 데이터 보호 전략에 기여합니다.

백업 스케줄은 다음과 같이 두 부분으로 구성됩니다.

* 백업 빈도
+
일부 플러그인의 스케줄 유형이라고도 하는 백업 빈도(백업 수행 빈도)는 정책 구성의 일부입니다. 예를 들어 백업 빈도를 매시간, 일별, 주별 또는 월별로 구성할 수 있습니다. SnapCenter GUI에서 * 설정 * > * 정책 * 을 클릭하여 정책에 액세스할 수 있습니다.

* 백업 스케줄
+
백업 스케줄(백업을 수행할 정확한 시점)은 리소스 또는 리소스 그룹 구성의 일부입니다. 예를 들어 주별 백업에 대한 정책이 구성된 리소스 그룹이 있는 경우 매주 목요일 오후 10시에 백업하도록 스케줄을 구성할 수 있습니다 SnapCenter GUI에서 * 리소스 * 를 클릭한 다음 해당 플러그인을 선택하고 * 보기 * > * 리소스 그룹 * 을 클릭하여 리소스 그룹 일정에 액세스할 수 있습니다.


