---
permalink: protect-scc/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_custom_plug_ins.html 
sidebar: sidebar 
keywords: credentials 
summary: 호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다. 사용자 지정 플러그인은 Windows 및 Linux 환경 모두에서 사용할 수 있습니다. 
---
= 호스트 추가 및 SnapCenter 사용자 지정 플러그인 설치를 위한 사전 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다. 사용자 지정 플러그인은 Windows 및 Linux 환경 모두에서 사용할 수 있습니다.

* 사용자 지정 플러그인을 만들어야 합니다. 자세한 내용은 개발자 정보를 참조하십시오.
+
link:concept_develop_a_plug_in_for_your_application.html["응용 프로그램용 플러그인을 개발합니다"]

* MySQL 또는 DB2 애플리케이션을 관리하려면 NetApp에서 제공하는 MySQL 및 DB2 사용자 지정 플러그인을 다운로드해야 합니다.
* Linux 또는 Windows 호스트에 Java 1.8, 64비트를 설치해야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자에 속한 경우 호스트에서 UAC를 비활성화해야 합니다.
* 호스트 추가 작업이 수행되는 클라이언트 호스트에서 사용자 지정 플러그인을 사용할 수 있어야 합니다.




== 일반

iSCSI를 사용하는 경우 iSCSI 서비스가 실행 중이어야 합니다.



== Windows 호스트

* 원격 호스트에 대한 로컬 로그인 권한이 있는 로컬 관리자 권한이 있는 도메인 사용자가 있어야 합니다.
* SnapCenter에서 클러스터 노드를 관리하는 경우 클러스터의 모든 노드에 대한 관리 권한이 있는 사용자가 있어야 합니다.




== Linux 호스트

* 루트 또는 루트 이외의 사용자에 대해 암호 기반 SSH 연결을 활성화해야 합니다.
* Linux 호스트에 Java 1.8 64비트를 설치해야 합니다.
+
SnapCenter 서버 호스트에 Windows 2019 또는 Windows 2016을 사용하는 경우 Java 1.8, 64비트를 설치해야 합니다. 상호 운용성 매트릭스 툴(IMT): 요구사항에 대한 최신 정보를 제공합니다.

+
http://www.java.com/en/download/manual.jsp["모든 운영 체제에 대한 Java 다운로드"]

+
https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"]

* 여러 경로에 대한 액세스를 제공하려면 비루트 사용자에 대해 sudo 권한을 구성해야 합니다. visudo Linux 유틸리티를 사용하여 /etc/sudoers 파일에 다음 행을 추가합니다. 예를 들면, 다음과 같습니다.
+
[listing]
----
Cmnd_Alias SCCMD = /opt/NetApp/snapcenter/scc/bin/scc <non_root_user> ALL=(ALL) NOPASSWD:SETENV: SCCMD
----
+
non_root_user 는 사용자가 생성한 루트가 아닌 사용자의 이름입니다.


