---
permalink: protect-scc/reference_custom_plugin_in_snapcenter.html 
sidebar: sidebar 
keywords:  
summary: 생성된 사용자 지정 플러그인은 SnapCenter 서버를 사용하여 호스트에 설치하여 응용 프로그램의 데이터 보호를 활성화할 수 있습니다. 
---
= SnapCenter의 사용자 지정 플러그인
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== SnapCenter의 사용자 지정 플러그인

Java, PERL 또는 네이티브 스타일을 사용하여 만든 사용자 지정 플러그인은 SnapCenter 서버를 사용하여 호스트에 설치하여 응용 프로그램의 데이터 보호를 활성화할 수 있습니다. 이 자습서에 제공된 절차를 사용하여 SnapCenter 호스트에 설치하려면 플러그인을 내보내야 합니다.



=== 플러그인 설명 파일 생성

생성된 모든 플러그인에 대해 설명 파일이 있어야 합니다. 설명 파일에는 플러그인의 세부 정보가 설명되어 있습니다. 파일 이름은 Plugin_descriptor.xml이어야 합니다.



==== 플러그인 설명자 파일 특성 및 그 중요성을 사용합니다

|===
| 속성 | 설명 


 a| 
이름
 a| 
플러그인의 이름입니다. 영숫자 문자는 사용할 수 있습니다. 예: DB2, MySQL, MongoDB

네이티브 스타일로 만들어진 플러그인의 경우 파일 확장명을 제공하지 않아야 합니다. 예를 들어 플러그인 이름이 mongodb.sh인 경우 이름을 mongodb로 지정합니다.



 a| 
버전
 a| 
플러그인 버전입니다. 주 버전과 부 버전을 모두 포함할 수 있습니다. 예: 1.0, 1.1, 2.0, 2.1



 a| 
표시 이름
 a| 
SnapCenter 서버에 표시할 플러그인 이름입니다. 동일한 플러그인의 여러 버전이 기록되는 경우 모든 버전에서 표시 이름이 동일한지 확인하십시오.



 a| 
PluginType입니다
 a| 
플러그인을 만드는 데 사용되는 언어입니다. 지원되는 값은 Perl, Java 및 Native입니다. 기본 플러그인 유형에는 Unix/Linux 셸 스크립트, Windows 스크립트, Python 또는 기타 스크립팅 언어가 포함됩니다.



 a| 
OSNAME
 a| 
플러그인이 설치된 호스트 OS 이름입니다. 유효한 값은 Windows 및 Linux입니다. PERL 유형 플러그인과 같은 여러 OS 유형에서 단일 플러그인을 배포할 수 있습니다.



 a| 
OSVersion(OS버전)
 a| 
플러그인이 설치된 호스트 OS 버전입니다.



 a| 
리소스 이름
 a| 
플러그인이 지원할 수 있는 리소스 유형의 이름입니다. 예를 들어 데이터베이스, 인스턴스, 컬렉션 등이 있습니다.



 a| 
모체
 a| 
이 경우 ResourceName 은 다른 리소스 형식에 따라 계층적으로 종속된 다음 Parent 는 부모 ResourceType 을 결정합니다.

예를 들어, DB2 플러그인에서 ResourceName “Database”에는 부모 “인스턴스”가 있습니다.



 a| 
RequireFileSystemPlugin
 a| 
예 또는 아니요 복구 탭이 복구 마법사에 표시되는지 여부를 결정합니다.



 a| 
ResourceRequiresAuthentication을 참조하십시오
 a| 
예 또는 아니요 스토리지를 검색한 후 데이터 보호 작업을 수행하기 위해 자동 검색되거나 자동 검색되지 않은 리소스에 자격 증명이 필요한지 여부를 결정합니다.



 a| 
RequireFileSystemClone 을 참조하십시오
 a| 
예 또는 아니요 플러그인에서 클론 워크플로우를 위해 파일 시스템 플러그인 통합이 필요한지 여부를 결정합니다.

|===
사용자 지정 플러그인 DB2에 대한 Plugin_descriptor.xml 파일의 예는 다음과 같습니다.

....
<Plugin>
<SMSServer></SMSServer>
<Name>DB2</Name>
<Version>1.0</Version>
<PluginType>Perl</PluginType>
<DisplayName>Custom DB2 Plugin</DisplayName>
<SupportedOS>
<OS>
<OSName>windows</OSName>
<OSVersion>2012</OSVersion>
</OS>
<OS>
<OSName>Linux</OSName>
<OSVersion>7</OSVersion>
</OS>
</SupportedOS>
<ResourceTypes>
<ResourceType>
<ResourceName>Database</ResourceName>
<Parent>Instance</Parent>
</ResourceType>
<ResourceType>
<ResourceName>Instance</ResourceName>
</ResourceType>
</ResourceTypes>
<RequireFileSystemPlugin>no</RequireFileSystemPlugin>
<ResourceRequiresAuthentication>yes</ResourceRequiresAuthentication>
<SupportsApplicationRecovery>yes</SupportsApplicationRecovery>
</Plugin>
....


=== ZIP 파일 생성

플러그인을 개발하고 설명자 파일을 만든 후에는 플러그인 파일과 Plugin_descriptor.xml 파일을 폴더에 추가하고 압축해야 합니다.

ZIP 파일을 작성하기 전에 다음 사항을 고려해야 합니다.

* 스크립트 이름은 플러그인 이름과 같아야 합니다.
* PERL 플러그인의 경우 ZIP 폴더에 스크립트 파일이 있는 폴더가 있어야 하고 설명자 파일이 이 폴더 외부에 있어야 합니다. 폴더 이름은 플러그인 이름과 같아야 합니다.
* PERL 플러그인 이외의 플러그인의 경우 ZIP 폴더에는 설명자와 스크립트 파일이 포함되어 있어야 합니다.
* OS 버전은 숫자여야 합니다.


예:

* DB2 플러그인: DB2.pm 및 Plugin_descriptor.xml 파일을 “DB2.zip”에 추가합니다.
* Java를 사용하여 개발된 플러그인: jar 파일, 종속 jar 파일 및 Plugin_descriptor.xml 파일을 폴더에 추가하고 압축합니다.




=== 플러그인 ZIP 파일을 업로드하는 중입니다

원하는 호스트에 플러그인을 배포할 수 있도록 플러그인 ZIP 파일을 SnapCenter 서버에 업로드해야 합니다.

UI 또는 cmdlet을 사용하여 플러그인을 업로드할 수 있습니다.

* UI: *

* 플러그인 ZIP 파일을 * 추가 * 또는 * 호스트 수정 * 워크플로우 마법사의 일부로 업로드합니다
* “사용자 지정 플러그인을 업로드하려면 선택하십시오.” * 를 클릭합니다


* PowerShell: *

* Upload-SmPluginPackage cmdlet
+
예를 들어, PS > 업로드 - SmPluginPackage - AbsolutePath c:\DB2_1.zip

+
PowerShell cmdlet에 대한 자세한 내용은 SnapCenter cmdlet 도움말을 사용하거나 cmdlet 참조 정보를 참조하십시오.



https://library.netapp.com/ecm/ecm_download_file/ECMLP2880726["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].



=== 사용자 지정 플러그인 배포

이제 업로드된 사용자 지정 플러그인을 * 추가 * 및 * 호스트 수정 * 워크플로의 일부로 원하는 호스트에 배포할 수 있습니다. 여러 버전의 플러그인을 SnapCenter 서버에 업로드할 수 있으며 특정 호스트에 배포할 버전을 선택할 수 있습니다.

플러그인을 업로드하는 방법에 대한 자세한 내용은 을 참조하십시오. link:task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html["호스트를 추가하고 원격 호스트에 플러그인 패키지를 설치합니다"]
