---
permalink: protect-scc/snapcenter_custom_plug_ins_overview.html 
sidebar: sidebar 
keywords: custom plug-ins 
summary: 사용하는 애플리케이션용 맞춤형 플러그인을 개발한 다음 SnapCenter를 사용하여 이러한 애플리케이션을 백업, 복원 또는 복제할 수 있습니다. 다른 SnapCenter 플러그인과 마찬가지로, 사용자 지정 플러그인은 NetApp SnapCenter 소프트웨어의 호스트 측 구성 요소로 작동하여 애플리케이션 인식 데이터 보호 및 리소스 관리를 지원합니다. 
---
= SnapCenter 맞춤형 플러그인 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용하는 애플리케이션용 맞춤형 플러그인을 개발한 다음 SnapCenter를 사용하여 이러한 애플리케이션을 백업, 복원 또는 복제할 수 있습니다. 맞춤형 플러그인은 NetApp SnapCenter 소프트웨어의 호스트측 구성 요소 역할을 하므로 애플리케이션 인식 데이터 보호 및 리소스 관리가 가능합니다.

사용자 지정 플러그인이 설치된 경우 SnapCenter와 NetApp SnapMirror 기술을 함께 사용하여 다른 볼륨에 있는 백업 세트의 미러 복사본을 생성하고 NetApp SnapVault 기술을 사용하여 D2D 백업 복제를 수행할 수 있습니다. 사용자 지정 플러그인은 Windows 및 Linux 환경 모두에서 사용할 수 있습니다.


NOTE: SnapCenterCLI는 사용자 지정 플러그인 명령을 지원하지 않습니다.

호스트 추가 페이지에서 사용자 지정 플러그인을 설치할 수 있습니다.

link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html["호스트를 추가하고 원격 호스트에 플러그인 패키지를 설치합니다."^]


NOTE: SnapCenter 지원 정책은 SnapCenter 맞춤형 플러그인 프레임워크, 핵심 엔진 및 관련 API에 대한 지원을 포함합니다. 지원 서비스는 플러그인 소스 코드와 사용자 지정 플러그인 프레임워크에 구축된 관련 스크립트를 지원하지 않습니다.

가이드를 참조하여 사용자 지정 플러그인을 만들 수 link:develop_a_plug_in_for_your_application.html["응용 프로그램용 플러그인을 개발합니다"^] 있습니다.
