---
sidebar: sidebar 
permalink: sc-automation/concept_basic_operational_characteristics.html 
keywords: request and response, object identifiers, synchronous, asynchronous 
summary: REST는 일반적인 기술과 모범 사례를 설정하지만 각 API의 세부 사항은 설계 선택에 따라 달라질 수 있습니다. 
---
= 기본 작동 특성
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
REST는 일반적인 기술과 모범 사례를 설정하지만 각 API의 세부 사항은 설계 선택에 따라 달라질 수 있습니다.



== 요청 및 응답 API 트랜잭션

모든 REST API 호출은 클라이언트에 대한 관련 응답을 생성하는 SnapCenter 서버 시스템에 대한 HTTP 요청으로 수행됩니다. 이 요청 및 응답 쌍은 API 트랜잭션으로 간주됩니다.

API를 사용하기 전에 요청 및 응답 출력의 내용을 제어하는 데 사용할 수 있는 입력 변수에 대해 잘 알고 있어야 합니다.



== CRUD 작업 지원

SnapCenter REST API를 통해 사용 가능한 각 리소스는 CRUD 모델을 기반으로 액세스됩니다.

* 생성
* 읽기
* 업데이트
* 삭제


일부 리소스의 경우 일부 작업만 지원됩니다.



== 오브젝트 식별자

각 리소스 인스턴스 또는 개체는 만들 때 고유한 식별자가 할당됩니다. 대부분의 경우 식별자는 128비트 UUID입니다. 이러한 식별자는 특정 SnapCenter 서버 내에서 전역적으로 고유합니다.

새 개체 인스턴스를 만드는 API 호출을 실행하면 연결된 ID가 있는 URL이 HTTP 응답의 위치 헤더에 있는 호출자에게 반환됩니다. 식별자를 추출하여 리소스 인스턴스를 참조할 때 후속 호출에 사용할 수 있습니다.


IMPORTANT: 개체 식별자의 내용 및 내부 구조는 언제든지 변경할 수 있습니다. 관련 객체를 참조할 때는 필요한 경우 해당 API 호출에서만 식별자를 사용해야 합니다.



== 개체 인스턴스 및 컬렉션

API 호출은 리소스 경로 및 HTTP 메서드에 따라 특정 개체 인스턴스 또는 개체 컬렉션에 적용될 수 있습니다.



== 동기 및 비동기 작업

SnapCenter는 클라이언트로부터 받은 HTTP 요청을 동기적 또는 비동기적으로 수행합니다.



=== 동기 처리

SnapCenter는 요청을 즉시 수행하고 HTTP 상태 코드가 200 또는 201인 경우 응답한다.

Get 메서드를 사용하는 모든 요청은 항상 동기적으로 수행됩니다. 또한 POST를 사용하는 요청은 2초 이내에 완료될 것으로 예상되는 경우 동기적으로 실행되도록 설계되었습니다.



=== 비동기 처리

비동기 요청이 유효한 경우 SnapCenter는 요청을 처리하기 위한 백그라운드 작업과 작업을 고정하기 위한 작업 개체를 만듭니다. HTTP 상태 코드 202가 작업 객체와 함께 호출자에게 반환됩니다. 작업의 상태를 검색하여 성공 또는 실패를 결정해야 합니다.

POST 및 DELETE 메서드를 사용하는 요청은 완료하는 데 2초 이상 걸릴 것으로 예상되는 경우 비동기적으로 실행되도록 설계되었습니다.



== 보안

REST API와 함께 제공되는 보안은 주로 SnapCenter에서 사용할 수 있는 기존 보안 기능을 기반으로 합니다. 다음 보안은 API에서 사용됩니다.



=== 전송 계층 보안

SnapCenter 서버와 클라이언트 사이에서 네트워크를 통해 전송되는 모든 트래픽은 일반적으로 SnapCenter 구성 설정에 따라 TLS를 사용하여 암호화됩니다.



=== HTTP 인증

HTTP 수준에서는 API 트랜잭션에 기본 인증이 사용됩니다. base64 문자열에 사용자 이름과 암호가 있는 HTTP 헤더가 각 요청에 추가됩니다.
