---
permalink: sc-automation/reference_supported_rest_apis.html 
sidebar: sidebar 
keywords: REST API categories 
summary: SnapCenter REST API를 통해 사용 가능한 리소스는 SnapCenter API 설명서 페이지에 표시된 대로 범주로 구성됩니다. 
---
= REST API는 다른 플러그인에 대해 지원됩니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter REST API를 통해 사용 가능한 리소스는 SnapCenter API 설명서 페이지에 표시된 대로 범주로 구성됩니다. 다음은 기본 리소스 경로가 있는 각 리소스에 대한 간략한 설명과 함께 적절한 경우 추가 사용 고려 사항입니다.



== 인증

이 API 호출을 사용하여 SnapCenter 서버에 로그인할 수 있습니다. 이 API는 후속 요청을 인증하는 데 사용되는 사용자 인증 토큰을 반환합니다.



== 도메인

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 모든 도메인을 검색합니다
* 특정 도메인의 세부 정보를 검색합니다
* 도메인을 등록 또는 등록 취소합니다
* 도메인을 수정합니다




== 작업

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 모든 작업을 검색합니다
* 작업의 상태를 검색합니다
* 작업을 취소하거나 중지합니다




== 설정

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 자격 증명을 등록, 보기, 수정 또는 제거합니다
* 알림 설정을 구성합니다




== 호스트

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 호스트 세부 정보를 검색합니다
* 설치된 플러그인과 해당 리소스 세부 정보를 검색합니다
* 플러그인 호스트를 추가, 제거 또는 수정합니다
* 플러그인을 설치하거나 업그레이드합니다




== 리소스

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 리소스를 검색합니다
* 리소스를 생성, 수정 또는 제거합니다
* 리소스를 보호합니다
* 리소스를 백업, 복원 또는 복제합니다




== 백업

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 백업 세부 정보를 검색합니다
* 백업 이름 바꾸기 또는 삭제




== 복제

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 클론 세부 정보를 검색합니다
* 클론 삭제




== 클리네플린

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 클론 분할 작업의 상태를 검색합니다
* 클론 분할 작업을 시작하거나 중지합니다




== 리소스 그룹

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 리소스 그룹의 세부 정보를 검색합니다
* 자원 그룹을 작성, 수정 또는 삭제합니다
* 리소스 그룹을 백업합니다




== 정책

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 정책 세부 정보를 검색합니다
* 정책을 생성, 수정 또는 삭제합니다




== 스토리지

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 저장소 세부 정보를 검색합니다
* 스토리지를 생성, 수정 또는 삭제합니다
* 스토리지에서 리소스를 검색합니다
* 스토리지에서 공유를 생성하거나 삭제합니다




== 공유

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 공유의 세부 정보를 검색합니다
* 스토리지에서 공유를 생성하거나 삭제합니다




== 플러그인

이러한 API 호출을 사용하여 호스트의 모든 플러그인을 검색하고 다른 작업을 수행할 수 있습니다.



== 보고서

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 백업, 복원, 클론 복제 및 플러그인 보고서를 생성합니다
* 스케줄을 추가, 실행, 삭제 또는 수정합니다




== 경고

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 모든 경고를 검색합니다
* 알림을 삭제합니다




== RBAC

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 사용자, 그룹 및 역할에 대한 세부 정보를 검색합니다
* 사용자 추가
* 역할을 생성, 수정 또는 삭제합니다
* 역할 및 그룹을 할당하거나 할당 해제합니다




== 구성

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 구성 설정을 봅니다
* 구성 설정을 수정합니다




== 인증서 설정

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* 인증서 상태를 봅니다
* 인증서 설정을 수정합니다




== 리포지토리

이러한 API 호출을 사용하여 다음을 수행할 수 있습니다.

* NSM 리포지토리 백업 및 복원
* NSM 리포지토리 보호 및 보호 해제
* 페일오버
* NSM 리포지토리를 재구축합니다

