---
permalink: sc-automation/rest_api_workflows_disaster_recovery_of_snapcenter_server.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter 재해 복구 기능은 REST API를 사용하여 SnapCenter 서버를 백업합니다. 
---
= SnapCenter 서버의 재해 복구에 REST API가 지원됩니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter DR(재해 복구) 기능은 REST API를 사용하여 SnapCenter 서버를 백업합니다. REST API를 사용하여 REST API Swagger 페이지에서 다음 작업을 수행할 수 있습니다. Swagger 페이지에 액세스하는 방법은 를 참조하십시오 link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["swagger API 웹 페이지를 사용하여 REST API에 액세스하는 방법"].

* 필요한 것 *

* SnapCenter 관리자로 로그인해야 합니다.
* DR 복원 API를 실행하려면 SnapCenter 서버가 실행 중이어야 합니다.


* 이 작업에 대한 정보 *

SnapCenter 서버 DR은 모든 플러그인을 지원합니다.

[cols="10,40,50,10"]
|===
| 단계 | 설명 | REST API | HTTP 메소드 


 a| 
1
 a| 
기존 SnapCenter 서버 DR 백업을 가져옵니다


NOTE: DR 백업을 저장해야 하는 백업 이름과 타겟 경로를 제공해야 합니다.
 a| 
`/4.5/disasterrecovery/server/backup? TargetPath={path}'
 a| 
가져오기



 a| 
2
 a| 
새 서버 DR 백업을 생성합니다. 지정된 서버 DR 백업에서 SnapCenter 서버를 복원합니다.
 a| 
'/4.5/disasterrecovery/server/backup'
 a| 
게시



 a| 
3
 a| 
지정된 서버 DR 백업에서 SnapCenter 서버를 복원합니다.

* 필수 구성 요소 *

* 2차 서버 호스트 이름은 1차 서버와 동일해야 하지만 IP 주소는 다를 수 있습니다.
* 서버 버전은 기본 서버와 동일해야 합니다.
* 호스트 이름은 운영 서버와 같아야 합니다.
* 다음 명령을 사용하여 DR 백업 파일이 새 SnapCenter 서버로 복사되었는지 확인합니다.
+
'<Ssource_Path>\<Destination_Server_IP>\<Folder_Path>/O/X/E/H/K{ex:xcopy C:\DRBackup\\10.225.81.114\c$\DRBackup/O/X/E/H/K}'



플러그인이 서버 호스트 이름을 확인할 수 없는 경우 각 플러그인 호스트에 로그인하고 새 IP에 대한 etc/host 항목을 "<New IP>SC_Server_Name" 형식으로 추가합니다

예: 10.225.81.35 SCServer1

서버 etc/host 항목은 복원되지 않습니다. DR 백업 폴더에서 수동으로 복원할 수 있습니다.
 a| 
'/4.5/Disasterrecovery/server/restore'
 a| 
게시



 a| 
4
 a| 
백업 이름을 기준으로 서버 DR 백업을 삭제합니다.
 a| 
``4.5/disasterrecovery/server/backup’’으로 표시됩니다
 a| 
삭제



 a| 
5
 a| 
스토리지 DR을 설정하거나 해제합니다
 a| 
'/4.5/disasterrecovery/storage'
 a| 
게시

|===
자세한 내용은 를 참조하십시오 https://www.youtube.com/watch?v=Nbr_wm9Cnd4&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg["재해 복구 API"^] 비디오.
