= 
:allow-uri-read: 


.단계
. Open-SmConnection cmdlet을 사용하여 지정된 사용자에 대한 SnapCenter Server 연결 세션을 시작합니다.
+
[listing]
----
Open-smconnection  -SMSbaseurl  https://snapctr.demo.netapp.com:8146
----
+
사용자 이름 및 암호 프롬프트가 표시됩니다.

. Add-SmPolicy cmdlet을 사용하여 백업 정책을 만듭니다.
+
이 예제에서는 SQL 백업 유형이 FullBackup인 새 백업 정책을 만듭니다.

+
[listing]
----
PS C:\> Add-SmPolicy -PolicyName TESTPolicy
-PluginPolicyType SCSQL -PolicyType Backup
-SqlBackupType FullBackup -Verbose
----
+
이 예에서는 Windows 파일 시스템 백업 유형이 Crash일관성(crash일관성)인 새 백업 정책을 생성합니다.

+
[listing]
----
PS C:\> Add-SmPolicy -PolicyName FileSystemBackupPolicy
-PluginPolicyType SCW -PolicyType Backup
-ScwBackupType CrashConsistent -Verbose
----
. Get-SmResources cmdlet을 사용하여 호스트 리소스를 검색합니다.
+
이 예제에서는 지정된 호스트에서 Microsoft SQL 플러그인에 대한 리소스를 검색합니다.

+
[listing]
----
C:\PS>PS C:\> Get-SmResources -HostName vise-f6.sddev.mycompany.com
-PluginCode SCSQL
----
+
이 예제에서는 지정된 호스트에서 Windows 파일 시스템에 대한 리소스를 검색합니다.

+
[listing]
----
C:\PS>PS C:\> Get-SmResources -HostName vise2-f6.sddev.mycompany.com
-PluginCode SCW
----
. 추가 SmResourceGroup cmdlet을 사용하여 SnapCenter에 새 리소스 그룹을 추가합니다.
+
이 예제에서는 지정된 정책 및 리소스를 사용하여 새 SQL 데이터베이스 백업 리소스 그룹을 만듭니다.

+
[listing]
----
PS C:\> Add-SmResourceGroup -ResourceGroupName AccountingResource
-Resources @{"Host"="visef6.org.com";
"Type"="SQL Database";"Names"="vise-f6\PayrollDatabase"}
-Policies "BackupPolicy"
----
+
이 예에서는 지정된 정책 및 리소스를 사용하여 새 Windows 파일 시스템 백업 리소스 그룹을 생성합니다.

+
[listing]
----
PS C:\> Add-SmResourceGroup -ResourceGroupName EngineeringResource
-PluginCode SCW -Resources @{"Host"="WIN-VOK20IKID5I";
"Type"="Windows Filesystem";"Names"="E:\"}
-Policies "EngineeringBackupPolicy"
----
. New-SmBackup cmdlet을 사용하여 새 백업 작업을 시작합니다.
+
[listing]
----
PS C:> New-SmBackup -ResourceGroupName PayrollDataset -Policy FinancePolicy
----
. Get-SmBackupReport cmdlet을 사용하여 백업 작업의 상태를 봅니다.
+
이 예는 지정된 날짜에 실행된 모든 작업의 작업 요약 보고서를 표시합니다.

+
[listing]
----
PS C:\> Get-SmJobSummaryReport -Date '1/27/2016'
----


cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 cmdlet 참조 가이드"^]있습니다.
