---
permalink: protect-azure/add-hosts-install-plugin-for-sql.html 
sidebar: sidebar 
keywords: add host, install, install plug-in, SQL 
summary: 호스트를 추가한 다음 플러그인 패키지를 설치합니다. 
---
= 호스트를 추가하고 SQL Server 데이터베이스용 SnapCenter 플러그인을 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter는 Azure NetApp Files의 SMB 공유에서 SQL 인스턴스의 데이터 보호를 지원합니다. 독립 실행형 및 가용성 그룹(AG) 구성이 지원됩니다.

SnapCenter 호스트 추가 페이지를 사용하여 호스트를 추가한 다음 플러그인 패키지를 설치해야 합니다. 플러그인은 원격 호스트에 자동으로 설치됩니다.

.시작하기 전에
* 플러그인 설치 및 제거 권한이 있는 역할(예: SnapCenter 관리자 역할)에 할당된 사용자여야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자에 속한 경우 호스트에서 UAC를 비활성화해야 합니다.


.단계
. 왼쪽 탐색 창에서 * 호스트 * 를 선택합니다.
. 맨 위에 * Managed Hosts * 탭이 선택되어 있는지 확인합니다.
. 추가 * 를 선택합니다.
. 호스트 페이지에서 다음을 수행합니다.
+
.. 호스트 유형 필드에서 호스트 유형을 선택합니다.
.. 호스트 이름 필드에 호스트의 FQDN(정규화된 도메인 이름) 또는 IP 주소를 입력합니다.
.. 자격 증명 필드에 생성한 자격 증명을 입력합니다.


. 설치할 플러그인 선택 * 섹션에서 설치할 플러그인을 선택합니다.
. (선택 사항) * 추가 옵션 * 을 클릭하고 세부 정보를 지정합니다.
. 제출 * 을 선택합니다.
. Configure log directory * 를 선택하고 Configure host log directory 페이지에서 호스트 로그 디렉토리의 SMB 경로를 입력한 후 * Save * 를 클릭합니다.
. 제출 * 을 클릭하고 설치 진행 상황을 모니터링합니다.

