---
permalink: protect-azure/create-azure-credential.html 
sidebar: sidebar 
keywords: snapcenter, azure, azure credential 
summary: SnapCenter에서 Azure 자격 증명을 생성하여 Azure NetApp 계정에 액세스합니다. 
---
= SnapCenter에서 Azure 자격 증명을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure NetApp 계정에 액세스하려면 SnapCenter에서 Azure 자격 증명을 생성해야 합니다.

.시작하기 전에
* Azure에서 서비스 보안 주체를 만들었는지 확인합니다.
* 사용 가능한 서비스 주체와 연결된 테넌트 ID, 클라이언트 ID 및 암호 키가 있는지 확인합니다.
+
** 테넌트 ID는 Entra ID에 대한 개요 페이지의 Azure Portal에서 확인할 수 있습니다.
** 클라이언트 ID는 엔터프라이즈 애플리케이션/서비스 보안 주체의 애플리케이션 ID라고도 합니다. SnapCenter의 서비스 주체 역할을 하기 위해 만든 엔터프라이즈 응용 프로그램의 개요 페이지에서 Azure 포털에서 확인할 수 있습니다.
** 클라이언트 비밀 키는 비밀 값이라고도 합니다. Entra ID 아래의 * 앱 등록 * 으로 이동하여 Azure Portal에서 이 클라이언트 암호를 생성할 수 있습니다. 생성한 엔터프라이즈 앱을 선택한 후 * 인증서 및 비밀 * 과 * 새 클라이언트 비밀 * 으로 이동합니다.
+

NOTE: 암호 값은 만들 때만 액세스할 수 있습니다. 나중에 액세스할 수 없습니다.

** 서비스 담당자에게 사용 권한을 부여해야 합니다. Contributor의 역할은 서비스 책임자가 Azure에서 필요한 작업을 수행할 수 있도록 허용합니다. 이 권한은 구독 페이지의 IAM(액세스 제어) 페이지에서 부여할 수 있습니다.




.단계
. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 자격 증명 * 을 클릭합니다.
. 새로 만들기 * 를 클릭합니다.
. 자격 증명 페이지에서 자격 증명을 만드는 데 필요한 다음 정보를 지정합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
자격 증명 이름
 a| 
자격 증명의 이름을 입력합니다.



 a| 
인증 모드
 a| 
드롭다운 목록에서 * Azure Credential * 을 선택합니다.



 a| 
테넌트 ID입니다
 a| 
테넌트 ID를 입력합니다.



 a| 
클라이언트 ID입니다
 a| 
클라이언트 ID를 입력합니다.



 a| 
클라이언트 암호 키
 a| 
클라이언트 암호 키를 입력합니다.

|===
. 확인 * 을 클릭합니다.

