---
permalink: protect-azure/install-snapcenter-azure-virtual-machine.html 
sidebar: sidebar 
keywords: snapcenter server, azure virtual machine, install 
summary: Azure 가상 머신에 SnapCenter을 다운로드하고 설치합니다. 
---
= Azure 가상 머신에 SnapCenter을 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Support 사이트에서 SnapCenter 소프트웨어를 다운로드하고 Azure 가상 머신에 소프트웨어를 설치할 수 있습니다.

.시작하기 전에
* Azure Windows 가상 머신이 SnapCenter 서버 설치 요구 사항을 충족하는지 확인합니다. 자세한 내용은 을 link:../install/requirements-to-install-snapcenter-server.html["SnapCenter 서버 설치 요구 사항"]참조하십시오.
* Azure NetApp Files를 처음 사용하는 경우 기존 NetApp 계정이 없는 경우 SnapCenter 소프트웨어에 액세스할 수 있도록 등록해야 합니다. 자세한 내용은 을 참조하십시오link:../install/register_enable_software_access.html["SnapCenter 소프트웨어에 액세스하려면 등록하십시오"].


.단계
. 에서 SnapCenter 서버 설치 패키지를 다운로드합니다 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp Support 사이트"].
. 다운로드한 .exe 파일을 두 번 클릭하여 SnapCenter 서버 설치를 시작합니다.
+
설치를 시작하면 모든 사전 검사가 수행되고 최소 요구 사항이 충족되지 않으면 적절한 오류 또는 경고 메시지가 표시됩니다. 경고 메시지를 무시하고 설치를 진행할 수 있지만 오류를 수정해야 합니다.

. SnapCenter 서버 설치에 필요한 미리 채워진 값을 검토하고 필요한 경우 수정합니다.
+
MySQL Server 리포지토리 데이터베이스의 암호를 지정할 필요가 없습니다. SnapCenter 서버 설치 중에 암호는 자동으로 생성됩니다.

+

NOTE: 리포지토리 데이터베이스의 사용자 지정 경로에서는 특수 문자 "%"가 지원되지 않습니다. 경로에 "%"를 포함하면 설치가 실패합니다.

. 지금 설치 * 를 클릭합니다.
+
잘못된 값을 지정한 경우 해당 오류 메시지가 표시됩니다. 값을 다시 입력한 다음 설치를 시작해야 합니다.

+

NOTE: Cancel * 버튼을 클릭하면 실행 중인 단계가 완료된 후 롤백 작업을 시작합니다. SnapCenter 서버가 호스트에서 완전히 제거됩니다.

+
그러나 "SnapCenter 서버 사이트 재시작" 또는 "SnapCenter 서버 시작 대기 중" 작업이 수행 중일 때 * 취소 * 를 클릭하면 작업을 취소하지 않고 설치가 진행됩니다.





== 지원을 받으려면 제품을 등록하십시오

NetApp를 처음 사용하는 경우 기존 NetApp 계정이 없는 경우 제품을 등록하여 지원을 받아야 합니다.

.단계
. SnapCenter를 설치한 후 * 도움말 > 정보 * 로 이동합니다.
. SnapCenter_정보_대화 상자에서 971로 시작하는 20자리 숫자인 SnapCenter 인스턴스를 기록해 둡니다.
. 을 https://register.netapp.com[]클릭합니다.
. 등록된 NetApp 고객이 아님 * 을 클릭합니다.
. 직접 등록할 세부 정보를 지정하십시오.
. NetApp Reference SN 필드는 비워 둡니다.
. 제품 라인 드롭다운에서 * SnapCenter * 를 선택합니다.
. 청구 공급자를 선택합니다.
. 20자리 SnapCenter 인스턴스 ID를 입력하십시오.
. 제출 * 을 클릭합니다.

