---
permalink: tech-refresh/task_tech_refresh_storage_system.html 
sidebar: sidebar 
keywords: tech refresh, storage system, 
summary: 데이터를 이전 스토리지에서 새 스토리지로 이동하고 새 스토리지를 해당 호스트에 마운트한 다음 데이터베이스를 가져와 스토리지 시스템의 기술 업데이트를 수행합니다. 
---
= 스토리지 시스템의 기술 업데이트
:allow-uri-read: 


[role="lead"]
스토리지를 기술 업데이트하면 데이터가 새 스토리지로 마이그레이션되고 애플리케이션 호스트가 새 스토리지로 마운트됩니다. SnapCenter 백업 워크플로우에서는 새 스토리지를 식별하고 새 스토리지가 SnapCenter에 등록된 경우 스냅샷을 생성합니다.

스토리지 새로 고침 후 생성된 새 백업에 대해 복구, 마운트 및 클론을 수행할 수 있습니다. 그러나 백업에 이전 스토리지 세부 정보가 있기 때문에 스토리지 새로 고침 전에 생성된 백업에 대해 이러한 작업을 수행하면 실패합니다. 스토리지 기술 업데이트 API 또는 cmdlet을 실행하여 SnapCenter의 이전 백업을 새 스토리지 세부 정보로 업데이트해야 합니다.

기술 업데이트는 다음 SnapCenter 플러그인에 대해 지원됩니다.

* Microsoft SQL Server용 SnapCenter 플러그인
* Windows용 SnapCenter 플러그인
* Oracle 데이터베이스용 SnapCenter 플러그인
* SAP HANA 데이터베이스용 SnapCenter 플러그인
* Microsoft Exchange Server용 SnapCenter 플러그인


지원되는 사용 사례는 다음과 같습니다.

* 운영 스토리지 업데이트
+
운영 스토리지를 새 스토리지로 교체할 때 스토리지 기술 업데이트가 지원됩니다. 기존 보조 스토리지를 운영 스토리지로 변환할 수 없습니다.

* 2차 스토리지 업데이트


지원되는 다른 시나리오는 다음과 같습니다.

* SVM 이름 변경
* 볼륨 이름 변경




== 운영 스토리지의 백업을 업데이트합니다

스토리지가 기술 업데이트 되면 스토리지 기술 업데이트 API 또는 cmdlet을 실행하여 SnapCenter의 이전 백업을 새 스토리지 세부 정보로 업데이트해야 합니다.

.시작하기 전에
이 워크플로는 SnapCenter 리포지토리의 데이터를 수정하므로 SnapCenter 리포지토리를 백업하는 것이 좋습니다. 데이터 문제가 발생할 경우 백업을 사용하여 SnapCenter 리포지토리를 이전 상태로 되돌릴 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenter 리포지토리를 백업합니다"].

.단계
. 이전 스토리지에서 새 스토리지로 데이터를 마이그레이션합니다.
+
마이그레이션 방법에 대한 자세한 내용은 다음을 참조하십시오.

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["새 스토리지로 데이터를 마이그레이션하는 방법"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["볼륨을 복사하고 모든 Snapshot 복사본을 보존하려면 어떻게 해야 합니까?"]


. 호스트를 유지 관리 모드로 전환합니다.
. 해당 호스트에 새 스토리지를 마운트하고 데이터베이스를 실행합니다.
+
새 스토리지는 이전과 같은 방식으로 호스트에 접속해야 합니다. 예를 들어 SAN으로 연결된 경우 SAN으로 연결해야 합니다.

+
새 스토리지는 이전 스토리지와 동일한 드라이브 또는 경로에 마운트되어야 합니다.

. 모든 리소스가 실행 중인지 확인합니다.
. SnapCenter에서 새 스토리지를 추가합니다.
+
SnapCenter의 클러스터 간에 고유한 SVM 이름을 사용하도록 합니다. 새 스토리지에서 동일한 SVM 이름을 사용하고 있으며 스토리지 업데이트를 실행하기 전에 SVM의 모든 볼륨을 마이그레이션할 수 있는 경우 그런 다음 이전 클러스터의 SVM을 삭제하고 SnapCenter에서 기존 클러스터를 다시 검색하여 캐시에서 SVM을 제거하는 것이 좋습니다.

. 호스트를 운영 모드로 전환합니다.
. SnapCenter에서 스토리지가 마이그레이션된 리소스의 백업을 생성합니다. SnapCenter에서 최신 스토리지 설치 공간을 식별하려면 새 백업이 필요하며, 이 백업은 기존 이전 백업의 메타데이터를 업데이트하는 데 사용됩니다.
+

NOTE: 새 LUN이 호스트에 연결될 때마다 새 일련 번호가 지정됩니다. Windows 파일 시스템을 검색하는 동안 SnapCenter는 모든 고유 일련 번호를 새 리소스로 처리합니다. 새 스토리지의 LUN이 동일한 드라이브 문자 또는 경로를 사용하여 호스트에 연결되면 스토리지 기술 업데이트 중에 SnapCenter에서 Windows 파일 시스템을 검색하면 기존 리소스가 동일한 드라이브 문자 또는 경로로 마운트되어 있는 경우에도 삭제됨으로 표시되고 새 LUN이 새 리소스로 표시됩니다. 리소스가 삭제됨으로 표시되므로 SnapCenter에서 스토리지 기술을 새로 고치는 것으로 간주되지 않으며 이전 리소스의 모든 백업이 손실됩니다. 스토리지 새로 고침이 발생하는 경우 Windows 파일 시스템 리소스의 경우 스토리지 새로 고침 API 또는 cmdlet을 실행하기 전에 리소스 검색을 수행하지 않아야 합니다.

. 스토리지 업데이트 API를 실행합니다. `/5.0/techrefresh/primarystorage` 또는 cmdlet:_Invoke-SmTechRefreshPrimaryStorage_.
+

NOTE: 리소스가 복제 지원 정책으로 구성된 경우 스토리지 새로 고침 이후의 최신 백업에 보조 스토리지에 대한 세부 정보가 있어야 합니다.

+
.. SQL FCI(Failover Cluster Instance) 설정을 사용하는 경우 백업이 클러스터 수준에서 유지됩니다. 스토리지 기술을 업데이트하려면 클러스터 이름을 입력값으로 제공해야 합니다.
.. SQL AG(Availability Group) 설정을 사용하는 경우 백업이 노드 레벨에서 유지됩니다. 스토리지 기술을 업데이트하려면 노드 이름을 입력해야 합니다.
.. Oracle RAC(Real Application Clusters) 설정을 사용하는 경우 모든 노드에서 스토리지 기술 업데이트를 수행할 수 있습니다.
+
_IsDryRun_attribute 는 기본적으로 True 로 설정됩니다. 스토리지 새로 고침의 리소스를 식별합니다. API '5.0/jobs/{jobid}' 또는 Cmdlet_Get-SmJobSummaryReport_를 실행하여 리소스 및 변경된 저장소 세부 정보를 볼 수 있습니다.



. 스토리지 세부 정보를 확인한 후 _IsDryRun_attribute를 False로 설정하고 스토리지 새로 고침 API를 실행합니다. `/5.0/techrefresh/primarystorage` 또는 cmdlet:_Invoke-SmTechRefreshPrimaryStorage_.
+
이전 백업의 저장소 세부 정보가 업데이트됩니다.

+
동일한 호스트에서 API 또는 cmdlet을 여러 번 실행할 수 있습니다. 스토리지를 새로 고친 경우에만 이전 백업에서 저장소 세부 정보가 업데이트됩니다.

+

NOTE: 클론 계층은 ONTAP에서 마이그레이션할 수 없습니다. 마이그레이션 중인 스토리지에 SnapCenter에 클론 메타데이터가 있으면 클론된 리소스가 독립 리소스로 표시됩니다. 클론 메타데이터의 클론은 반복적으로 제거됩니다.

. (선택 사항) 모든 스냅샷이 이전 운영 스토리지에서 새 운영 스토리지로 이동하지 않는 경우 다음 API를 실행합니다. `/5.0/hosts/primarybackupsexistencecheck` 또는 Cmdlet_Invoke-SmPrimaryBackupsExistenceCheck _.
+
이렇게 하면 새 운영 스토리지에 대한 스냅샷 존재 여부 검사가 수행되고 해당 백업이 SnapCenter의 모든 작업에 사용할 수 없음으로 표시됩니다.





== 보조 스토리지의 백업을 업데이트합니다

스토리지가 기술 업데이트 되면 스토리지 기술 업데이트 API 또는 cmdlet을 실행하여 SnapCenter의 이전 백업을 새 스토리지 세부 정보로 업데이트해야 합니다.

.시작하기 전에
이 워크플로는 SnapCenter 리포지토리의 데이터를 수정하므로 SnapCenter 리포지토리를 백업하는 것이 좋습니다. 데이터 문제가 발생할 경우 백업을 사용하여 SnapCenter 리포지토리를 이전 상태로 되돌릴 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenter 리포지토리를 백업합니다"].

.단계
. 이전 스토리지에서 새 스토리지로 데이터를 마이그레이션합니다.
+
마이그레이션 방법에 대한 자세한 내용은 다음을 참조하십시오.

+
** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Storage_tech_refresh["새 스토리지로 데이터를 마이그레이션하는 방법"]
** https://kb.netapp.com/onprem/ontap/dp/SnapMirror/How_can_I_copy_a_volume_and_preserve_all_of_the_Snapshot_copies["볼륨을 복사하고 모든 Snapshot 복사본을 보존하려면 어떻게 해야 합니까?"]


. 운영 스토리지와 새로운 2차 스토리지 간에 SnapMirror 관계를 설정하고 관계 상태가 양호한지 확인합니다.
. SnapCenter에서 스토리지가 마이그레이션된 리소스의 백업을 생성합니다.
+
SnapCenter가 최신 스토리지 공간을 식별하려면 새 백업이 필요하며, 이 백업은 기존 이전 백업의 메타데이터를 업데이트하는 데 사용됩니다.

+

IMPORTANT: 이 작업이 완료될 때까지 기다려야 합니다. 완료 전에 다음 단계로 진행하면 SnapCenter에서 이전 보조 스냅샷 메타데이터를 완전히 잃게 됩니다.

. 호스트에 있는 모든 리소스의 백업을 성공적으로 생성한 후 보조 스토리지 새로 고침 API 중 하나를 실행합니다. `/5.0/techrefresh/secondarystorage` 또는 cmdlet:_Invoke-SmTechRefreshSecondaryStorage_.
+
그러면 지정된 호스트에 있는 이전 백업의 보조 스토리지 세부 정보가 업데이트됩니다.

+
리소스 수준에서 이 작업을 실행하려면 각 리소스에 대해 * Refresh * 를 클릭하여 보조 스토리지 메타데이터를 업데이트합니다.

. 이전 백업을 성공적으로 업데이트한 후 운영 스토리지와의 이전 보조 스토리지 관계를 해제할 수 있습니다.

