---
permalink: tech-refresh/task_tech_refresh_plugin_host.html 
sidebar: sidebar 
keywords: tech refresh, plug-in host, supported plug-ins, prerequisites to refresh plug-in hosts, application hosts, limitations for tech refresh of plug-in hosts 
summary: 플러그인 호스트의 기술 업데이트를 수행하기 위해 리소스를 이전 호스트에서 새 호스트로 이동합니다. 
---
= SnapCenter 플러그인 호스트의 기술 업데이트
:allow-uri-read: 


[role="lead"]
SnapCenter 플러그인 호스트를 교체해야 하는 경우 리소스를 이전 호스트에서 새 호스트로 이동해야 합니다. 새 호스트가 SnapCenter에 추가되면 모든 리소스가 검색되지만 새 리소스로 처리됩니다.

.이 작업에 대해
API 또는 cmdlet을 실행하여 이전 호스트 이름과 새 호스트 이름을 입력으로 사용하고, 리소스를 이름별로 비교하고, 일치하는 리소스 개체를 이전 호스트에서 새 호스트로 다시 연결해야 합니다. 일치하는 리소스가 보호됨으로 표시됩니다.

* _IsDryRun_parameter 는 기본적으로 True 로 설정되며, 이는 이전 호스트와 새 호스트의 일치하는 리소스를 식별합니다.
+
일치하는 리소스를 확인한 후 _IsDryRun_parameter 를 False 로 설정하여 일치하는 리소스의 객체를 이전 호스트에서 새 호스트로 다시 연결해야 합니다.

* _AutoMigrateManualyAddedResources_매개 변수는 기본적으로 True로 설정되어 있으며 수동으로 추가한 리소스를 이전 호스트에서 새 호스트로 자동으로 복사합니다.
+
AutoMigrateManualyAddedResources_ 매개 변수는 Oracle 및 SAP HANA 리소스에만 적용됩니다.

* 인스턴스 이름이 이전 호스트와 새 호스트 간에 다른 경우 _SQLInstanceMapping_매개 변수를 사용해야 합니다. 기본 인스턴스인 경우 인스턴스 이름으로 _default_instance_를 사용합니다.


기술 업데이트는 다음 SnapCenter 플러그인에 대해 지원됩니다.

* Microsoft SQL Server용 SnapCenter 플러그인
+
** SQL 데이터베이스가 인스턴스 레벨에서 보호되고 호스트 기술 새로 고침의 일부로 부분 리소스만 새 호스트로 이동되면 기존 인스턴스 수준 보호가 리소스 그룹 보호로 변환되고 두 호스트의 인스턴스가 리소스 그룹에 추가됩니다.
** SQL 호스트(예: host1)를 다른 호스트(예: host2)의 리소스에 대한 스케줄러 또는 검증 서버로 사용하는 경우 host1에서 기술 새로 고침을 수행하는 동안 스케줄 또는 확인 세부 정보가 마이그레이션되지 않고 host1에서 계속 실행됩니다. 수정해야 하는 경우 해당 호스트에서 수동으로 변경해야 합니다.
** SQL FCI(장애 조치 클러스터 인스턴스) 설정을 사용하는 경우 FCI 클러스터에 새 노드를 추가하고 SnapCenter에서 플러그인 호스트를 새로 고쳐 기술 업데이트를 수행할 수 있습니다.
** SQL AG(Availability Group) 설정을 사용하는 경우에는 기술 업데이트가 필요하지 않습니다. 새 노드를 AG에 추가하고 SnapCenter에서 호스트를 새로 고칠 수 있습니다.


* Windows용 SnapCenter 플러그인
* Oracle 데이터베이스용 SnapCenter 플러그인
+
Oracle RAC(Real Application Cluster) 설정을 사용하는 경우 RAC 클러스터에 새 노드를 추가하고 SnapCenter에서 플러그인 호스트를 새로 고침하여 기술 업데이트를 수행할 수 있습니다.

* SAP HANA 데이터베이스용 SnapCenter 플러그인


지원되는 사용 사례는 다음과 같습니다.

* 호스트 간에 리소스를 마이그레이션하는 중입니다.
* 여러 호스트에서 하나 이하의 호스트로 리소스 마이그레이션
* 한 호스트에서 여러 호스트로 리소스를 마이그레이션하는 중입니다.


지원되는 시나리오는 다음과 같습니다.

* 새 호스트의 이름이 이전 호스트와 다릅니다
* 기존 호스트의 이름이 변경되었습니다


.시작하기 전에
이 워크플로는 SnapCenter 리포지토리의 데이터를 수정하므로 SnapCenter 리포지토리를 백업하는 것이 좋습니다. 데이터 문제가 발생할 경우 백업을 사용하여 SnapCenter 리포지토리를 이전 상태로 되돌릴 수 있습니다.

자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository["SnapCenter 리포지토리를 백업합니다"].

.단계
. 새 호스트를 구축하고 애플리케이션을 설치합니다.
. 이전 호스트의 스케줄을 일시 중단합니다.
. 필요한 리소스를 이전 호스트에서 새 호스트로 이동합니다.
+
.. 동일한 스토리지에서 새 호스트에 필요한 데이터베이스를 가져옵니다.
+
*** 스토리지가 이전 호스트와 동일한 드라이브 또는 동일한 마운트 경로에 매핑되었는지 확인합니다. 스토리지가 올바르게 매핑되지 않으면 이전 호스트에서 생성된 백업을 복구에 사용할 수 없습니다.
+

NOTE: 기본적으로 Windows는 사용 가능한 다음 드라이브를 자동으로 할당합니다.

*** 스토리지 DR이 설정된 경우 해당 스토리지가 새 호스트에 마운트되어야 합니다.


.. 응용 프로그램 버전이 변경되면 호환성을 확인합니다.
.. Oracle 플러그인 호스트에 대해서만 Oracle 및 해당 그룹 사용자의 UID 및 GID가 이전 호스트의 UID 및 GID와 동일한지 확인합니다.
+
자세한 내용은 다음을 참조하십시오.

+
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_SQL_host_tech_refresh["SQL 데이터베이스를 이전 호스트에서 새 호스트로 마이그레이션하는 방법"]
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Oracle_host_tech_refresh["Oracle 데이터베이스를 이전 호스트에서 새 호스트로 마이그레이션하는 방법"]
*** https://kb.netapp.com/mgmt/SnapCenter/How_to_perform_Hana_host_tech_refresh["SAP HANA 데이터베이스를 새 호스트로 가져오는 방법"]




. 새 호스트를 SnapCenter에 추가합니다.
. 모든 리소스가 검색되는지 확인합니다.
. 호스트 새로 고침 API: `/<snapcenter_version>/techrefresh/host` 또는 cmdlet:_Invoke-SmTechRefreshHost _ 를 실행합니다.
+

NOTE: 건식 실행이 기본적으로 활성화되며 재링크할 일치하는 리소스가 식별됩니다. API: '/jobs/{jobid}' 또는 Cmdlet_Get-SmJobSummaryReport _ 를 실행하여 리소스를 확인할 수 있습니다.

+
여러 호스트에서 리소스를 마이그레이션한 경우 모든 호스트에 대해 API 또는 cmdlet을 실행해야 합니다. 새 호스트의 드라이브 또는 마운트 경로가 이전 호스트와 동일하지 않으면 다음 복구 작업이 실패합니다.

+
** SQL 원본 위치 복원이 실패합니다. 그러나 RTAL 기능은 활용할 수 있습니다.
** Oracle 및 SAP HANA 데이터베이스 복원이 실패합니다.
+
여러 호스트로 마이그레이션하려면 모든 호스트에 대해 1단계부터 모든 단계를 수행해야 합니다.

+

NOTE: 동일한 호스트에서 API 또는 cmdlet을 여러 번 실행할 수 있으며, 새 리소스가 확인된 경우에만 다시 연결됩니다.



. (선택 사항) SnapCenter에서 이전 호스트를 제거합니다.


.관련 정보
API에 대한 자세한 내용은 Swagger 페이지에 액세스해야 합니다. 을 참조하십시오 link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html["swagger API 웹 페이지를 사용하여 REST API에 액세스하는 방법"].

cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 를 참조할 수도 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 cmdlet 참조 가이드"^]있습니다.
