---
permalink: admin/concept_manage_policies.html 
sidebar: sidebar 
keywords:  
summary: 리소스 또는 리소스 그룹에서 정책을 분리하고 수정, 삭제, 보기 및 복사할 수 있습니다. 
---
= 정책 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
리소스 또는 리소스 그룹에서 정책을 분리하고 수정, 삭제, 보기 및 복사할 수 있습니다.



== 정책을 수정합니다

정책이 리소스 또는 리소스 그룹에 연결되어 있는 동안 복제 옵션, 스냅샷 복사본 보존 설정, 오류 재시도 횟수 또는 스크립트 정보를 수정할 수 있습니다. 정책을 분리한 후에만 스케줄 유형(빈도)을 수정할 수 있습니다.

* 이 작업에 대한 정보 *

SnapCenter 서버는 정책이 리소스 또는 리소스 그룹에 연결될 때만 일정 유형을 등록하므로 정책에서 일정 유형을 수정하려면 추가 단계가 필요합니다.

|===
| 원하는 작업 | 그러면... 


 a| 
추가 일정 유형을 추가합니다
 a| 
새 정책을 만들어 필요한 리소스 또는 리소스 그룹에 연결합니다.

예를 들어 리소스 그룹 정책에서 매시간 백업만 지정하고 일별 백업도 추가하려는 경우 일별 스케줄 유형을 사용하여 정책을 생성한 후 리소스 그룹에 추가할 수 있습니다. 그러면 리소스 그룹에는 매시간 및 매일의 두 가지 정책이 있습니다.



 a| 
일정 유형을 제거 또는 변경합니다
 a| 
다음을 수행합니다.

. 해당 정책을 사용하는 모든 리소스 및 리소스 그룹에서 정책을 분리합니다.
. 스케줄 유형을 수정합니다.
. 모든 리소스 및 리소스 그룹에 정책을 다시 연결합니다.


예를 들어, 정책이 시간별 백업을 지정하고 이를 일일 백업으로 변경하려는 경우 먼저 정책을 분리해야 합니다.

|===
* 단계 *

. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 정책 * 을 클릭합니다.
. 정책을 선택한 다음 * 수정 * 을 클릭합니다.
. 정보를 수정한 다음 * 마침 * 을 클릭합니다.




== 정책을 분리합니다

이러한 정책이 리소스에 대한 데이터 보호를 더 이상 제어하지 않도록 하려는 경우 언제든지 리소스 또는 리소스 그룹에서 정책을 분리할 수 있습니다. 정책을 삭제하거나 스케줄 유형을 수정하기 전에 먼저 정책을 분리해야 합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지의 * 보기 * 목록에서 * 리소스 그룹 * 을 선택합니다.
. 자원 그룹을 선택한 다음 * 자원 그룹 수정 * 을 클릭합니다.
. 자원 그룹 수정 마법사의 정책 페이지에 있는 드롭다운 목록에서 분리할 정책 옆에 있는 확인 표시를 지웁니다.
. 마법사의 나머지 부분에서 리소스 그룹을 추가로 수정한 후 * Finish * 를 클릭합니다.




== 정책을 삭제합니다

더 이상 정책이 필요하지 않으면 삭제할 수 있습니다.

* 필요한 것 *

정책이 리소스 또는 리소스 그룹과 연결된 경우 리소스 또는 리소스 그룹에서 정책을 분리해야 합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 정책 * 을 클릭합니다.
. 정책을 선택한 다음 * 삭제 * 를 클릭합니다.
. 예 * 를 클릭합니다.

