---
permalink: admin/concept_overview_of_snapcenter_reports.html 
sidebar: sidebar 
keywords:  
summary: SnapCenter는 시스템 상태 및 운영 성공을 모니터링하고 관리할 수 있는 다양한 보고 옵션을 제공합니다. 
---
= SnapCenter 보고 기능 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter는 시스템 상태 및 운영 성공을 모니터링하고 관리할 수 있는 다양한 보고 옵션을 제공합니다.

|===
| 보고서 유형 | 설명 


 a| 
백업 보고서
 a| 
백업 보고서는 SnapCenter 환경의 백업 추세, 백업 성공률 및 지정된 시간 동안 수행된 각 백업에 대한 일부 정보에 대한 전체 데이터를 제공합니다. 백업이 삭제되면 보고서는 삭제된 백업에 대한 상태 정보를 표시하지 않습니다. 백업 세부 정보 보고서는 지정된 백업 작업에 대한 자세한 정보를 제공하고 성공적으로 백업된 리소스 및 실패한 리소스를 나열합니다.



 a| 
보고서 복제
 a| 
클론 보고서는 SnapCenter 환경의 클론 추세, 클론 성공률 및 지정된 시간 동안 수행된 각 클론 작업에 대한 일부 정보에 대한 전체 데이터를 제공합니다. 클론이 삭제되면 삭제된 클론에 대한 상태 정보가 보고서에 표시되지 않습니다. 클론 세부 정보 보고서에는 지정된 클론, 클론 호스트 및 클론 작업 작업 상태에 대한 세부 정보가 나와 있습니다. 작업이 실패하면 클론 세부 정보 보고서에 실패에 대한 정보가 표시됩니다.



 a| 
보고서 복원
 a| 
복원 보고서는 복원 작업에 대한 전체 정보를 제공합니다. 복구 세부 정보 보고서는 호스트 이름, 백업 이름, 작업 시작 및 기간, 개별 작업 작업 상태 등 지정된 복구 작업에 대한 세부 정보를 제공합니다. 작업이 실패하면 복구 세부 정보 보고서에 실패에 대한 정보가 표시됩니다.



 a| 
보호 보고서
 a| 
이러한 보고서는 모든 SnapCenter 플러그인 인스턴스에서 관리되는 리소스에 대한 보호 세부 정보를 제공합니다. 이 보고서는 모든 플러그인 인스턴스에서 관리되는 리소스에 대한 보호 세부 정보를 제공합니다. 개요, 보호되지 않은 리소스의 세부 정보, 보고서가 생성될 때 백업하지 않은 리소스, 백업 작업이 실패한 리소스 그룹의 리소스, SnapVault 상태를 확인할 수 있습니다.



 a| 
예약된 보고서
 a| 
이러한 보고서는 매일, 매주 또는 매월 정기적으로 실행되도록 예약되어 있습니다. 보고서는 지정된 날짜 및 시간에 자동으로 생성되며 전자 메일을 통해 각 사용자에게 전송됩니다 스케줄을 활성화, 비활성화, 수정 또는 삭제할 수 있습니다. 활성화된 스케줄은 * 지금 실행 * 버튼을 클릭하여 필요에 따라 실행할 수 있습니다. 관리자는 모든 일정을 실행할 수 있지만 생성된 보고서에는 일정을 만든 사용자가 제공한 권한에 따라 데이터가 포함됩니다.

관리자 이외의 다른 사용자는 자신의 권한에 따라 일정을 보거나 수정할 수 있습니다. 이 역할의 모든 구성원이 다른 구성원의 개체를 볼 수 있음 옵션이 역할 추가 페이지에서 선택된 경우 역할의 다른 구성원이 보고 수정할 수 있습니다.

|===


== 보고서에 액세스합니다

SnapCenter 대시보드를 사용하여 시스템 상태를 빠르게 파악할 수 있습니다. 대시보드에서 자세한 정보를 확인할 수 있습니다. 또는 상세 보고서에 직접 액세스할 수도 있습니다.

다음 방법 중 하나를 사용하여 보고서에 액세스할 수 있습니다.

* 왼쪽 탐색 창에서 * 대시보드 * 를 클릭한 다음 * 마지막 보호 요약 * 원형 차트 를 클릭하여 보고서 페이지에서 자세한 내용을 확인합니다.
* 왼쪽 탐색 창에서 * 보고서 * 를 클릭합니다.




== 보고서를 필터링합니다

필요한 정보의 세부 수준과 시간 범위에 따라 다양한 매개 변수에 따라 보고서 데이터를 필터링할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 보고서 * 를 클릭합니다.
. 매개변수 보기가 표시되지 않으면 보고서 도구 모음에서 * 매개변수 영역 전환 * 아이콘을 클릭합니다.
. 보고서를 실행할 시간 범위를 지정합니다. + 종료 날짜를 생략하면 사용 가능한 모든 정보가 검색됩니다.
. 다음 기준에 따라 보고서 정보를 필터링합니다.
+
** 리소스 그룹
** 호스트
** 정책
** 리소스
** 상태
** 플러그인 이름입니다


. 적용 * 을 클릭합니다.




== 보고서를 내보내거나 인쇄합니다

SnapCenter 보고서를 내보내면 다양한 대체 형식으로 보고서를 볼 수 있습니다. 보고서를 인쇄할 수도 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 보고서 * 를 클릭합니다.
. 보고서 도구 모음에서 다음 중 하나를 수행합니다.
+
** 인쇄 가능한 보고서를 미리 보려면 * 인쇄 미리 보기 전환 * 아이콘을 클릭합니다.
** 보고서를 대체 형식으로 내보내려면 * 내보내기 * 아이콘 드롭다운 목록에서 형식을 선택합니다.


. 보고서를 인쇄하려면 * 인쇄 * 아이콘을 클릭합니다.
. 특정 보고서 요약을 보려면 보고서의 해당 섹션으로 스크롤합니다.




== 이메일 알림에 대한 SMTP 서버를 설정합니다

사용자 자신 또는 다른 사람에게 데이터 보호 작업 보고서를 보내는 데 사용할 SMTP 서버를 지정할 수 있습니다. 테스트 이메일을 보내 구성을 확인할 수도 있습니다. 이 설정은 이메일 알림을 구성하는 모든 SnapCenter 작업에 전체적으로 적용됩니다.

이 옵션은 모든 데이터 보호 작업 보고서를 전송할 SMTP 서버를 구성합니다. 그러나 직접 또는 다른 사용자에게 보내진 특정 리소스에 대해 정기적으로 SnapCenter 데이터 보호 작업을 업데이트하여 해당 업데이트의 상태를 모니터링하려는 경우 리소스 그룹을 만들 때 SnapCenter 보고서를 전자 메일로 보내는 옵션을 구성할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 글로벌 설정 * 을 클릭합니다.
. SMTP 서버를 입력하고 * Save * 를 클릭합니다.
. 테스트 e-메일을 보내려면 e-메일을 보낼 e-메일 주소를 입력하고 제목을 입력한 다음 * 보내기 * 를 클릭합니다.




== 보고서를 e-메일로 보내는 옵션을 구성합니다

정기적으로 SnapCenter 데이터 보호 작업 업데이트를 자신 또는 다른 사람에게 보내 해당 업데이트의 상태를 모니터링하려는 경우 리소스 그룹을 만들 때 SnapCenter 보고서를 전자 메일로 보내는 옵션을 구성할 수 있습니다.

* 필요한 것 *

설정의 글로벌 설정 페이지에서 SMTP 서버를 구성해야 합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 보려는 리소스 유형을 선택하고 * 새 리소스 그룹 * 을 클릭하거나 기존 리소스 그룹을 선택하고 * 수정 * 을 클릭하여 기존 리소스 그룹에 대한 이메일 보고서를 구성합니다.
. 새 리소스 그룹 마법사의 알림 패널에서 풀다운 메뉴에서 보고서를 항상 수신할지, 실패했는지, 아니면 실패했는지 또는 경고인지 선택합니다.
. 이메일을 보낼 주소, 이메일을 보낼 주소 및 이메일 제목을 입력합니다.

