---
permalink: admin/concept_manage_the_storage_system.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 시스템을 추가한 후 스토리지 시스템 구성 및 접속을 수정하거나 스토리지 시스템을 삭제할 수 있습니다. 
---
= 스토리지 시스템을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 시스템을 추가한 후 스토리지 시스템 구성 및 접속을 수정하거나 스토리지 시스템을 삭제할 수 있습니다.



== 스토리지 시스템 구성을 수정합니다

SnapCenter를 사용하여 사용자 이름, 암호, 플랫폼, 포트, 프로토콜 등을 변경하려는 경우 스토리지 시스템 구성을 수정할 수 있습니다. 제한 시간, 기본 IP 주소 또는 메시징 옵션.

* 이 작업에 대한 정보 *

개별 사용자 또는 그룹에 대한 스토리지 접속을 수정할 수 있습니다. 동일한 스토리지 시스템에 대한 사용 권한이 있는 하나 이상의 그룹에 속해 있는 경우 스토리지 접속 이름은 스토리지 시스템에 대한 사용 권한이 있는 각 그룹에 대해 한 번씩 스토리지 접속 목록에 여러 번 표시됩니다.

* 단계 *

. 왼쪽 탐색 창에서 * 스토리지 시스템 * 을 클릭합니다.
. 스토리지 시스템 페이지의 * 유형 * 드롭다운에서 다음 작업 중 하나를 수행합니다.
+
|===
| 선택... | 단계... 


 a| 
ONTAP SVM
 a| 
추가된 모든 SVM(스토리지 가상 시스템)을 확인하고 필요한 SVM 구성을 수정합니다.

.. 스토리지 연결 페이지에서 적절한 SVM 이름을 클릭합니다.
.. 다음 작업 중 하나를 수행합니다.
+
*** SVM이 클러스터에 속하지 않는 경우 스토리지 시스템 수정 페이지에서 사용자 이름, 암호, EMS 및 AutoSupport 설정, 플랫폼, 프로토콜, 포트, 시간 초과 등의 구성을 수정합니다. 및 기본 IP를 선택합니다.
*** SVM이 클러스터의 일부인 경우 Modify Storage System 페이지에서 * Manage SVM Independently * 를 선택하고 사용자 이름, 암호, EMS 및 AutoSupport 설정, 플랫폼, 프로토콜, 포트, 시간 초과 등의 구성을 수정합니다. 및 기본 IP를 선택합니다.
+
SVM을 독립적으로 관리되도록 수정한 후 클러스터를 통해 관리하려는 경우 SVM을 삭제하고 * ReDiscover * 를 클릭해야 합니다. SVM이 ONTAP 클러스터에 추가됩니다.

+

NOTE: SnapCenter GUI에서 스토리지 시스템 암호를 업데이트할 경우 업데이트된 암호가 SMCore에 반영되지 않고 백업 작업이 실패하고 잘못된 자격 증명 오류가 발생하므로 해당 플러그인 또는 서버 호스트의 SMCore 서비스를 다시 시작해야 합니다.







 a| 
ONTAP 클러스터
 a| 
추가된 모든 클러스터를 확인하고 필요한 클러스터 구성을 수정합니다.

.. 스토리지 접속 페이지에서 클러스터 이름을 클릭합니다.
.. 스토리지 시스템 수정 페이지에서 사용자 이름 옆에 있는 편집 아이콘을 클릭하고 사용자 이름과 암호를 수정합니다.
.. EMS 및 AutoSupport 설정을 선택하거나 지웁니다.
.. 추가 옵션 * 을 클릭하고 플랫폼, 프로토콜, 포트, 시간 초과 및 기본 IP와 같은 다른 구성을 수정합니다.


|===
. 제출 * 을 클릭합니다.




== 스토리지 시스템을 삭제합니다

SnapCenter를 사용하여 사용하지 않는 스토리지 시스템을 삭제할 수 있습니다.

* 이 작업에 대한 정보 *

개별 사용자 또는 그룹의 스토리지 접속을 삭제할 수 있습니다. 동일한 스토리지 시스템에 대한 사용 권한이 있는 하나 이상의 그룹에 속해 있는 경우 스토리지 시스템 이름은 스토리지 시스템에 대한 사용 권한이 있는 각 그룹에 대해 한 번씩 스토리지 접속 목록에 여러 번 표시됩니다.


IMPORTANT: 스토리지 시스템을 삭제하면 해당 스토리지 시스템에서 수행 중인 모든 작업이 실패합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 스토리지 시스템 * 을 클릭합니다.
. 스토리지 시스템 페이지의 * 유형 * 드롭다운에서 * ONTAP SVM * 또는 * ONTAP 클러스터 * 를 선택합니다.
. 스토리지 연결 페이지에서 SVM 옆의 확인란을 선택하거나 삭제할 클러스터를 선택합니다.
+

NOTE: 클러스터의 일부인 SVM은 선택할 수 없습니다.

. 삭제 * 를 클릭합니다.
. 스토리지 시스템 접속 설정 삭제 페이지에서 * 확인 * 을 클릭합니다.
+

NOTE: ONTAP GUI를 사용하여 ONTAP 클러스터에서 SVM을 삭제한 경우, SnapCenter GUI에서 * 재발견 * 을 클릭하여 SVM 목록을 업데이트하십시오.


