---
permalink: admin/concept_overview_of_dashboard.html 
sidebar: sidebar 
keywords:  
summary: 'SnapCenter의 왼쪽 탐색 창에서 대시보드에서 최근 작업 활동, 경고, 보호 요약, 스토리지 효율성 및 사용, SnapCenter 작업 상태\(백업, 클론, 복원\), 독립 실행형 및 Windows 클러스터 호스트의 구성 상태 등을 한눈에 파악할 수 있습니다. SnapCenter에서 관리하는 SVM(스토리지 가상 머신) 수 및 라이센스 용량' 
---
= 대시보드 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter의 왼쪽 탐색 창에서 대시보드에서 최근 작업 활동, 경고, 보호 요약, 스토리지 효율성 및 사용, SnapCenter 작업 상태(백업, 클론, 복원), 독립 실행형 및 Windows 클러스터 호스트의 구성 상태 등을 한눈에 파악할 수 있습니다. SnapCenter에서 관리하는 SVM(스토리지 가상 머신) 수 및 라이센스 용량

대시보드 보기에 표시되는 정보는 현재 SnapCenter에 로그인한 사용자에게 할당된 역할에 따라 달라집니다. 사용자가 해당 정보를 볼 수 있는 권한이 없는 경우 일부 콘텐츠가 표시되지 않을 수 있습니다.

대부분의 경우 * i * 를 마우스 포인터로 가리키면 디스플레이에 대한 자세한 정보를 볼 수 있습니다. 경우에 따라 대시보드 디스플레이의 정보가 리소스, 모니터 및 보고서와 같은 SnapCenter GUI 페이지의 자세한 소스 정보에 링크될 수 있습니다.



== 최근 작업 활동

최근 작업 활동 타일에는 액세스 권한이 있는 모든 백업, 복원 및 클론 작업의 최신 작업 활동이 표시됩니다. 이 디스플레이의 작업에는 완료, 경고, 실패, 실행 중, 대기 중, 및 취소됨.

작업 위로 마우스를 이동하면 자세한 정보를 볼 수 있습니다. 특정 작업 번호를 클릭하여 추가 작업 정보를 볼 수 있습니다. 이 작업 번호는 Monitor 페이지로 리디렉션됩니다. 여기서 작업 세부 정보 또는 로그 정보를 얻고 해당 작업에 대한 보고서를 생성할 수 있습니다.

모든 SnapCenter 작업의 기록을 보려면 * 모두 보기 * 를 클릭합니다.



== 경고

Alerts(경고) 타일에는 호스트 및 SnapCenter 서버에 대한 최신 미해결 위험 및 경고 경고가 표시됩니다.

위험 및 경고 범주 경고의 총 개수가 디스플레이 상단에 표시됩니다. 위험 또는 경고 합계를 클릭하면 경고 페이지에 특정 필터가 적용된 경고 페이지로 리디렉션됩니다.

특정 경고를 클릭하면 해당 경고에 대한 자세한 내용을 볼 수 있는 경고 페이지로 리디렉션됩니다. 디스플레이 하단의 * 모두 보기 * 를 클릭하면 경고 페이지로 이동하여 모든 경고 목록을 볼 수 있습니다.



== 최신 보호 요약

최신 보호 요약 타일은 액세스 권한이 있는 모든 엔티티에 대한 보호 상태를 제공합니다. 기본적으로 디스플레이는 모든 플러그인의 상태를 제공하도록 설정됩니다. 상태 정보는 기본 스토리지에 Snapshot 복사본으로 백업된 리소스 및 SnapMirror 및 SnapVault 기술을 사용하는 보조 스토리지에 제공됩니다. 보조 스토리지에 대한 보호 상태 정보의 가용성은 선택한 플러그인 유형에 따라 달라집니다.


NOTE: 미러 소산 보호 정책을 사용하는 경우 보호 요약의 카운터가 SnapMirror 차트가 아니라 SnapVault 요약 차트에 표시됩니다.

개별 플러그인의 보호 상태는 드롭다운 메뉴에서 플러그인을 선택하여 사용할 수 있습니다. 도넛형 차트에는 선택한 플러그인에 대한 보호된 리소스의 백분율이 표시됩니다. 도넛 조각을 클릭하면 * 보고서 * > * 플러그인 * 페이지로 리디렉션되며, 지정된 플러그인에 대한 모든 기본 및 보조 스토리지 작업에 대한 자세한 보고서가 제공됩니다.


IMPORTANT: 보조 스토리지에 대한 보고서는 SnapVault에만 적용되고 SnapMirror 보고서는 지원되지 않습니다.


NOTE: SAP HANA는 스냅샷 복사본을 위한 운영 스토리지 및 2차 스토리지에 대한 보호 상태 정보를 제공합니다. 파일 기반 백업에는 운영 스토리지 보호 상태만 사용할 수 있습니다.

|===
| 보호 상태입니다 | 운영 스토리지 | 2차 스토리지 


 a| 
실패했습니다
 a| 
리소스 그룹에 속한 엔터티의 개수로, 리소스 그룹에서 백업을 실행했지만 백업이 실패했습니다.
 a| 
보조 대상으로 전송하지 못한 백업이 있는 엔터티의 수입니다.



 a| 
성공했습니다
 a| 
리소스 그룹이 성공적으로 백업된 리소스 그룹의 엔티티 수입니다.
 a| 
보조 대상으로 성공적으로 전송된 백업의 엔티티 수입니다.



 a| 
구성되지 않았습니다
 a| 
리소스 그룹에 속하지 않고 백업되지 않은 엔터티의 수입니다.
 a| 
백업을 위해 구성되지 않은 하나 이상의 리소스 그룹에 속한 엔터티가 보조 대상으로 전송될 수 있습니다.



 a| 
시작되지 않았습니다
 a| 
리소스 그룹에 속하지만 백업이 실행되지 않은 엔터티의 수입니다.
 a| 
해당 없음.

|===

NOTE: 백업을 생성하기 위해 SnapCenter 서버 4.2 및 이전 버전의 플러그인(4.2 이전)을 사용하는 경우 * 최신 보호 요약 * 타일에 이러한 백업의 SnapMirror 보호 상태가 표시되지 않습니다.



== 작업

작업 타일은 액세스할 수 있는 백업, 복원 및 클론 작업의 요약을 제공합니다. 드롭다운 메뉴를 사용하여 보고서의 시간 프레임을 사용자 지정할 수 있습니다. 기간 옵션은 최근 24시간, 지난 7일 및 지난 30일에 고정됩니다. 기본 보고서에는 지난 7일 동안 실행된 데이터 보호 작업이 표시됩니다.

백업, 복원 및 클론 작업 정보가 도넛형 차트에 표시됩니다. 도넛형 조각을 클릭하면 선택 항목에 미리 적용된 작업 필터가 있는 모니터 페이지로 이동합니다.

|===
| 작업 상태입니다 | 설명 


 a| 
실패했습니다
 a| 
실패한 작업 수입니다.



 a| 
경고
 a| 
오류가 발생한 작업 수입니다.



 a| 
성공했습니다
 a| 
성공적으로 완료된 작업의 수입니다.



 a| 
실행 중입니다
 a| 
현재 실행 중인 작업 수입니다.

|===


== 스토리지

Storage(스토리지) 타일은 90일 동안 보호 작업에서 사용하는 운영 및 보조 스토리지를 표시하고, 소비 추세를 그래픽으로 표시하고, 기본 스토리지 절약 효과를 계산합니다. 스토리지 정보는 24시간마다 오전 12시에 업데이트됩니다

SnapCenter에서 사용할 수 있는 총 백업 수와 이러한 백업이 차지하는 크기로 구성된 일일 총 소모량이 디스플레이 상단에 표시됩니다. 백업에는 여러 스냅샷 복사본이 연결될 수 있으며 이 수에 동일하게 반영됩니다. 이 옵션은 기본 및 보조 스냅샷 복사본에 모두 적용할 수 있습니다. 예를 들어 10개의 백업을 생성했으며, 그 중 2개는 정책 기반 백업 보존으로 인해 삭제되고 1개의 백업은 사용자가 명시적으로 삭제합니다. 따라서 7개의 백업이 차지하는 크기와 함께 7개의 백업이 표시됩니다.

운영 스토리지의 스토리지 절약 비율은 기본 스토리지의 물리적 용량에 대한 논리적 용량(클론 및 스냅샷 복사본 절약 + 스토리지 소비)의 비율입니다. 막대 차트는 스토리지 절약 효과를 보여 줍니다.

선형 그래프는 롤링 90일 동안 1차 및 2차 스토리지 소비를 일 단위로 각각 플롯합니다. 차트 위에 마우스를 놓으면 자세한 일별 결과가 표시됩니다.


NOTE: 백업을 생성하기 위해 SnapCenter 서버 4.2와 이전 버전의 플러그인(4.2 이전)을 사용하는 경우 * 스토리지 * 타일에는 백업 수, 이러한 백업에서 사용되는 스토리지, 스냅샷 절약, 클론 절감 및 스냅샷 크기가 표시되지 않습니다.



== 구성

구성 타일은 SnapCenter가 관리하고 있고 사용자가 액세스할 수 있는 모든 활성 독립 실행형 및 Windows 클러스터 호스트에 대한 통합 상태 정보를 제공합니다. 여기에는 해당 호스트와 연결된 플러그인 상태 정보가 포함됩니다.

Hosts 옆의 숫자를 클릭하면 Hosts 페이지의 Managed Hosts 섹션으로 이동합니다. 여기서 선택한 호스트에 대한 자세한 정보를 얻을 수 있습니다.

또한 이 디스플레이에 SnapCenter에서 관리하는 독립 실행형 ONTAP SVM과 클러스터 ONTAP SVM의 합계가 표시되고 액세스할 수 있는 가 표시됩니다. SVM 옆의 번호를 클릭하면 스토리지 시스템 페이지로 이동합니다. 여기서 선택한 SVM에 대한 자세한 정보를 얻을 수 있습니다.

호스트 구성 상태는 각 상태의 호스트 수와 함께 빨간색(위험), 노란색(경고) 및 녹색(활성)으로 표시됩니다. 상태 메시지는 각 상태에 대해 제공됩니다.

|===
| 구성 상태입니다 | 설명 


 a| 
업그레이드가 필수입니다
 a| 
지원되지 않는 플러그인을 실행하고 업그레이드가 필요한 호스트의 수입니다. 지원되지 않는 플러그인은 이 버전의 SnapCenter와 호환되지 않습니다.



 a| 
마이그레이션은 필수입니다
 a| 
지원되지 않는 플러그인을 실행하고 마이그레이션이 필요한 호스트의 수입니다. 지원되지 않는 플러그인은 이 버전의 SnapCenter와 호환되지 않습니다.



 a| 
설치된 플러그인이 없습니다
 a| 
성공적으로 추가되었지만 플러그인을 설치해야 하거나 플러그인 설치에 실패한 호스트의 수입니다.



 a| 
일시 중단됨
 a| 
스케줄이 일시 중단되어 유지 보수 중인 호스트의 수입니다.



 a| 
중지되었습니다
 a| 
가동되지만 플러그인 서비스가 실행되고 있지 않은 호스트의 수입니다.



 a| 
호스트가 다운되었습니다
 a| 
다운되었거나 연결할 수 없는 호스트의 수입니다.



 a| 
업그레이드 가능(선택 사항)
 a| 
최신 버전의 플러그인 패키지를 업그레이드할 수 있는 호스트의 수입니다.



 a| 
마이그레이션 사용 가능(선택 사항)
 a| 
마이그레이션을 위해 최신 버전의 플러그인을 사용할 수 있는 호스트의 수입니다.



 a| 
로그 디렉터리를 구성합니다
 a| 
트랜잭션 로그 백업을 수행하려면 SCSQL에 대해 로그 디렉토리를 구성해야 하는 호스트의 수입니다.



 a| 
VMware 플러그인을 구성합니다
 a| 
VMware vSphere용 SnapCenter 플러그인을 추가해야 하는 호스트 수입니다.



 a| 
알 수 없음
 a| 
등록되었지만 설치가 아직 트리거되지 않은 호스트의 수입니다.



 a| 
실행 중입니다
 a| 
실행 중인 호스트 및 플러그인의 수입니다. SCSQL 플러그인의 경우 로그 디렉토리와 하이퍼바이저가 구성됩니다.



 a| 
플러그인 설치\ 제거 중
 a| 
플러그인 설치 또는 제거가 진행 중인 호스트의 수입니다.

|===


== 라이센스 용량

라이센스 용량 타일은 SnapCenter 표준 용량 기반 라이센스에 대한 라이센스 만료 경고, 사용된 용량, 용량 임계값 경고 및 총 라이센스 용량에 대한 정보를 표시합니다.


NOTE: 이 표시는 Cloud Volumes ONTAP 또는 ONTAP Select 플랫폼에서 SnapCenter 표준 용량 기반 라이센스를 사용하는 경우에만 나타납니다. FAS 또는 AFF 플랫폼의 경우 SnapCenter 라이센스는 컨트롤러 기반이며 무제한 용량으로 라이센스가 부여되며, 용량 라이센스는 필요하지 않습니다.

|===
| 라이센스 상태입니다 | 설명 


 a| 
사용 중입니다
 a| 
현재 사용 중인 용량입니다.



 a| 
알림
 a| 
용량 임계값 - 알림이 대시보드에 표시되고, 구성된 경우 e-메일 알림이 전송될 때 알림이 표시되는 임계값입니다.



 a| 
허가되었습니다
 a| 
라이센스 용량의 양입니다.



 a| 
않습니다
 a| 
라이센스 용량을 초과한 용량의 양입니다.

|===