---
permalink: admin/concept_manage_ems_data_collection.html 
sidebar: sidebar 
keywords:  
summary: 'PowerShell cmdlet을 사용하여 EMS(Event Management System) 데이터 수집을 예약하고 관리할 수 있습니다. EMS 데이터 수집에는 SnapCenter 서버, 설치된 SnapCenter 플러그인 패키지, 호스트 및 이와 유사한 정보에 대한 세부 정보를 수집한 다음 지정된 ONTAP 스토리지 가상 시스템\(SVM\)으로 전송하는 작업이 포함됩니다.' 
---
= EMS Data 수집 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PowerShell cmdlet을 사용하여 EMS(Event Management System) 데이터 수집을 예약하고 관리할 수 있습니다. EMS 데이터 수집에는 SnapCenter 서버, 설치된 SnapCenter 플러그인 패키지, 호스트 및 이와 유사한 정보에 대한 세부 정보를 수집한 다음 지정된 SVM(ONTAP Storage Virtual Machine)으로 전송하는 작업이 포함됩니다.


NOTE: 데이터 수집 작업이 진행 중인 경우 시스템 CPU 사용률이 높습니다. 데이터 크기와 관계없이 작업이 진행되는 동안에는 CPU 사용률이 계속 높습니다.



== EMS 데이터 수집을 중지합니다

EMS 데이터 수집은 기본적으로 활성화되어 있으며 설치 날짜로부터 7일마다 실행됩니다. PowerShell cmdlet_Disable-SmDataCollectionEMS_를 사용하여 언제든지 데이터 수집을 비활성화할 수 있습니다.

* 단계 *

. PowerShell 명령줄에서 _Open-SmConnection_ 을 입력하여 SnapCenter와 세션을 설정합니다.
. Disable-SmDataCollectionEms_를 입력하여 EMS 데이터 수집을 비활성화합니다.




== EMS 데이터 수집을 시작합니다

EMS 데이터 수집은 기본적으로 활성화되어 있으며 설치 날짜로부터 7일마다 실행되도록 예약되어 있습니다. 이 기능을 사용하지 않도록 설정한 경우 _Enable-SmDataCollectionEMS_cmdlet을 사용하여 EMS 데이터 수집을 다시 시작할 수 있습니다.

Data ONTAP 이벤트 generate-autosupport-log 권한은 SVM(스토리지 가상 시스템) 사용자에게 부여되었습니다.

* 단계 *

. PowerShell 명령줄에서 _Open-SmConnection_ 을 입력하여 SnapCenter와 세션을 설정합니다.
. Enable-SmDataCollectionEMS_를 입력하여 EMS 데이터 수집을 활성화합니다.




== EMS Data 수집 일정 및 Target SVM 변경

PowerShell cmdlet을 사용하여 EMS 데이터 수집 스케줄 또는 대상 SVM(Storage Virtual Machine)을 변경할 수 있습니다.

* 단계 *

. PowerShell 명령줄에서 SnapCenter를 사용하여 세션을 설정하려면 _Open-SmConnection_cmdlet을 입력합니다.
. EMS 데이터 수집 대상을 변경하려면 _Set-SmDataCollectionEmsTarget_cmdlet을 입력합니다.
. EMS 데이터 수집 스케줄을 변경하려면 _Set-SmDataCollectionEmsSchedule_cmdlet을 입력합니다.




== EMS Data 수집 상태 모니터링

여러 개의 PowerShell cmdlet을 사용하여 EMS 데이터 수집 상태를 모니터링할 수 있습니다. 일정, SVM(스토리지 가상 시스템) 타겟 및 상태에 대한 정보를 얻을 수 있습니다.

* 단계 *

. PowerShell 명령줄에서 _Open-SmConnection_ 을 입력하여 SnapCenter와 세션을 설정합니다.
. get-SmDataCollectionEmsSchedule_을 입력하여 EMS 데이터 수집 스케줄에 대한 정보를 검색합니다.
. _get-SmDataCollectionEmsStatus_를 입력하여 EMS 데이터 수집 상태에 대한 정보를 조회한다.
. get-SmDataCollectionEmsTarget _ 을 입력하여 EMS 데이터 수집 대상에 대한 정보를 검색합니다.


* 자세한 정보 찾기 *

cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].
