---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html 
sidebar: sidebar 
keywords:  
summary: 작업 진행 상황을 모니터링하고, 예약된 작업에 대한 정보를 얻고, 모니터 페이지에서 이벤트 및 로그를 검토할 수 있습니다. 
---
= 작업, 일정, 이벤트 및 로그를 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
작업 진행 상황을 모니터링하고, 예약된 작업에 대한 정보를 얻고, 모니터 페이지에서 이벤트 및 로그를 검토할 수 있습니다.



== 작업을 모니터링합니다

SnapCenter 백업, 클론, 복원 및 검증 작업에 대한 정보를 볼 수 있습니다. 시작 및 종료 날짜, 작업 유형, 리소스 그룹, 정책 또는 SnapCenter 플러그인을 기준으로 이 보기를 필터링할 수 있습니다. 또한 지정된 작업에 대한 추가 세부 정보 및 로그 파일을 얻을 수 있습니다.

SnapMirror 및 SnapVault 작업과 관련된 작업을 모니터링할 수도 있습니다.


NOTE: SnapCenter 관리자 또는 다른 수퍼 사용자 역할이 할당되지 않은 경우 사용자가 생성한 작업과 사용자와 관련된 작업만 모니터링할 수 있습니다.

작업 모니터링과 관련된 다음 작업을 수행할 수 있습니다.

* 백업, 클론, 복원 및 검증 작업을 모니터링합니다.
* 작업 세부 정보 및 보고서를 봅니다.
* 예약된 작업을 중지합니다.




== 일정을 모니터링합니다

현재 스케줄을 확인하여 작업 시작 시간, 마지막 실행 시간 및 다음 실행 시기를 결정할 수 있습니다. 또한 작업이 실행되는 호스트를 작업의 리소스 그룹 및 정책 정보와 함께 확인할 수도 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 모니터 * 를 클릭합니다.
. 모니터 페이지에서 * 스케줄 * 을 클릭합니다.
. 자원 그룹과 일정 유형을 선택합니다.
. 예약된 작업 목록을 봅니다.




== 이벤트를 모니터링합니다

사용자가 리소스 그룹을 만들 때 또는 시스템이 예약된 백업 생성과 같은 작업을 시작할 때와 같이 시스템에서 SnapCenter 이벤트 목록을 볼 수 있습니다. 백업 또는 복구 작업과 같은 작업이 현재 진행 중인지 여부를 확인하기 위해 이벤트를 볼 수 있습니다.

* 이 작업에 대한 정보 *

모든 작업 정보가 이벤트 페이지에 나타납니다. 예를 들어 백업 작업이 시작되면 ""백업 시작"" 이벤트가 나타납니다. 백업이 완료되면 ""백업 완료"" 이벤트가 나타납니다.

* 단계 *

. 왼쪽 탐색 창에서 * 모니터 * 를 클릭합니다.
. 모니터 페이지에서 * 이벤트 * 를 클릭합니다.
. (선택 사항) 필터 상자에 시작 또는 종료 날짜, 이벤트 범주(예: 백업, 리소스 그룹 또는 정책) 및 심각도 수준을 입력하고 * 적용 * 을 클릭합니다. 또는 검색 상자에 문자를 입력합니다.
. 이벤트 목록을 봅니다.




== 로그를 모니터링합니다

SnapCenter 서버 로그, SnapCenter 호스트 에이전트 로그 및 플러그인 로그를 보고 다운로드할 수 있습니다. 문제 해결에 도움이 되도록 로그를 볼 수 있습니다.

* 이 작업에 대한 정보 *

로그를 필터링하여 특정 로그 심각도 수준만 표시할 수 있습니다.

* 디버그
* 정보
* 경고
* 오류
* 치명적


백업 작업 실패 원인을 해결하는 데 도움이 되는 로그 등의 작업 수준 로그를 얻을 수도 있습니다. 작업 수준 로그의 경우 * Monitor * > * Jobs * 옵션을 사용합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 모니터 * 를 클릭합니다.
. 작업 페이지에서 작업을 선택하고 로그 다운로드 를 클릭합니다.
+
다운로드된 압축 폴더에는 작업 로그 및 공통 로그가 포함됩니다. 압축된 폴더 이름에는 선택한 작업 ID와 작업 유형이 포함되어 있습니다.

. 모니터 페이지에서 * 로그 * 를 클릭합니다.
. 로그 유형, 호스트 및 인스턴스를 선택합니다.
+
로그 유형을 * plugin * 으로 선택한 경우 호스트 또는 SnapCenter 플러그인을 선택할 수 있습니다. 로그 유형이 * server * 인 경우 이 작업을 수행할 수 없습니다.

. 특정 원본, 메시지 또는 로그 수준별로 로그를 필터링하려면 열 머리글 맨 위에 있는 필터 아이콘을 클릭합니다.
+
모든 로그를 표시하려면 * 보다 크거나 같음 * 을 Debug 수준으로 선택합니다.

. 새로 고침 * 을 클릭합니다.
. 로그 목록을 봅니다.
. 로그를 다운로드하려면 * 다운로드 * 를 클릭합니다.
+
다운로드된 압축 폴더에는 작업 로그 및 공통 로그가 포함됩니다. 압축된 폴더 이름에는 선택한 작업 ID와 작업 유형이 포함되어 있습니다.



최적의 성능을 위한 대규모 구성에서는 PowerShell cmdlet을 사용하여 SnapCenter의 로그 설정을 최소 수준으로 설정해야 합니다.

셋스매로그설정 - 로그레벨 모두 - 맥스파일 크기 10MB - 맥스사이스롤 업 10 - 잡로그스맥파일 크기 10MB - 서버


NOTE: 페일오버 작업이 완료된 후 상태 또는 구성 정보에 액세스하려면 cmdlet 'Get-SmRepositoryConfig'를 실행합니다.



== SnapCenter에서 작업 및 로그를 제거합니다

SnapCenter에서 백업, 복원, 클론, 검증 작업 및 로그를 제거할 수 있습니다. SnapCenter는 사용자가 제거하지 않는 한 성공하거나 실패한 작업 로그를 무기한 저장합니다. 스토리지를 보충하기 위해 제거할 수 있습니다.

* 이 작업에 대한 정보 *

현재 작업 중인 작업이 없어야 합니다. 작업 ID를 제공하여 특정 작업을 제거하거나 지정된 기간 내에 작업을 제거할 수 있습니다.

호스트를 유지보수 모드로 전환하여 작업을 제거할 필요는 없습니다.

* 단계 *

. PowerShell을 실행합니다.
. 명령 프롬프트에서 "열기 - SMConnection"을 입력합니다
. 명령 프롬프트에서 'Remove-Smobs'를 입력합니다
. 왼쪽 탐색 창에서 * 모니터 * 를 클릭합니다.
. 모니터 페이지에서 * 작업 * 을 클릭합니다.
. 작업 페이지에서 작업의 상태를 검토합니다.


* 자세한 정보 찾기 *

cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2880726["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].
