---
permalink: admin/task_manage_resource_groups.html 
sidebar: sidebar 
keywords:  
summary: 리소스 그룹에 대해 다양한 작업을 수행할 수 있습니다. 
---
= 자원 그룹을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
리소스 그룹에 대해 다양한 작업을 수행할 수 있습니다.

자원 그룹과 관련된 다음 작업을 수행할 수 있습니다.

* 자원 그룹을 만드는 동안 제공한 정보를 편집하려면 자원 그룹을 선택하고 * 자원 그룹 수정 * 을 클릭하여 자원 그룹을 수정합니다.
+

NOTE: 자원 그룹을 수정하는 동안 일정을 변경할 수 있습니다. 그러나 스케줄 유형을 변경하려면 정책을 수정해야 합니다.

+

NOTE: 리소스 그룹에서 리소스를 제거하면 현재 리소스 그룹에 연결된 정책에 정의된 백업 보존 설정이 제거된 리소스에 계속 적용됩니다.

* 리소스 그룹의 백업을 생성합니다.
* 백업의 클론을 생성합니다.
+
SQL, Oracle, Windows 파일 시스템, 맞춤형 애플리케이션, SAP HANA 데이터베이스 리소스 또는 리소스 그룹의 기존 백업에서 클론을 생성할 수 있습니다.

* 리소스 그룹의 클론을 생성합니다.
+
이 작업은 SQL 리소스 그룹(데이터베이스만 포함)에만 지원됩니다. 리소스 그룹 클론 생성(클론 라이프사이클)에 대한 스케줄을 구성할 수 있습니다.

* 리소스 그룹에 대한 예약된 작업이 시작되지 않도록 합니다.
* 자원 그룹을 삭제합니다.




== 리소스 그룹에 대한 작업을 중지하고 다시 시작합니다

자원 그룹에서 예약된 작업을 시작하는 것을 일시적으로 해제할 수 있습니다. 나중에 원하는 경우 이러한 작업을 활성화할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지의 * 보기 * 목록에서 * 리소스 그룹 * 을 선택합니다.
. 자원 그룹을 선택하고 * 유지보수 * 를 클릭합니다.
. 확인 * 을 클릭합니다.


유지보수 모드로 설정한 리소스 그룹에 대한 작업을 재개하려면 리소스 그룹을 선택하고 * 운영 * 을 클릭합니다.



== 리소스 그룹을 삭제합니다

자원 그룹의 자원을 더 이상 보호할 필요가 없는 경우 자원 그룹을 삭제할 수 있습니다. SnapCenter에서 플러그인을 제거하기 전에 리소스 그룹이 삭제되었는지 확인해야 합니다.

* 이 작업에 대한 정보 *

리소스 그룹의 리소스에 대해 생성된 모든 클론을 수동으로 삭제해야 합니다. 선택적으로 리소스 그룹에 연결된 모든 백업, 메타데이터, 정책 및 스냅샷 복사본을 강제로 삭제할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 리소스 * 를 클릭한 다음 목록에서 적절한 플러그인을 선택합니다.
. 리소스 페이지의 * 보기 * 목록에서 * 리소스 그룹 * 을 선택합니다.
. 자원 그룹을 선택한 다음 * 삭제 * 를 클릭합니다.
. 선택 사항: 이 리소스 그룹과 연결된 백업 및 분리 정책 * 삭제 확인란을 선택하여 리소스 그룹과 연결된 모든 백업, 메타데이터, 정책 및 스냅샷 복사본을 제거합니다.
. 확인 * 을 클릭합니다.

