---
permalink: protect-postgresql/back-up-clusters-using-powershell-cmdlets-postgresql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for PostgreSQL 
summary: 클러스터 백업에는 SnapCenter 서버와의 연결 설정, 리소스 추가, 정책 추가, 백업 리소스 그룹 생성 및 백업이 포함됩니다. 
---
= PowerShell cmdlet을 사용하여 클러스터를 백업합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 백업에는 SnapCenter 서버와의 연결 설정, 리소스 추가, 정책 추가, 백업 리소스 그룹 생성 및 백업이 포함됩니다.

.시작하기 전에
* PowerShell cmdlet을 실행하려면 PowerShell 환경을 준비해야 합니다.
* 스토리지 시스템 접속을 추가하고 자격 증명을 생성해야 합니다.


.단계
. Open-SmConnection cmdlet을 사용하여 지정된 사용자에 대한 SnapCenter Server 연결 세션을 시작합니다.
+
[listing]
----
PS C:\> Open-SmConnection
----
+
사용자 이름 및 암호 프롬프트가 표시됩니다.

. Add-SmResources cmdlet을 사용하여 수동 리소스를 추가합니다.
+
이 예제에서는 PostgreSQL 인스턴스를 추가하는 방법을 보여 줍니다.

+
[listing]
----
PS C:\> Add-SmResource -HostName 10.32.212.13 -PluginCode PostgreSQL -ResourceType Instance -ResourceName postgresqlinst1 -StorageFootPrint (@{"VolumeName"="winpostgresql01_data01";"LUNName"="winpostgresql01_data01";"StorageSystem"="scsnfssvm"}) -MountPoints "D:\"
----
. Add-SmPolicy cmdlet을 사용하여 백업 정책을 만듭니다.
. 추가 SmResourceGroup cmdlet을 사용하여 리소스를 보호하거나 SnapCenter에 새 리소스 그룹을 추가합니다.
. New-SmBackup cmdlet을 사용하여 새 백업 작업을 시작합니다.
+
이 예제에서는 리소스 그룹을 백업하는 방법을 보여 줍니다.

+
[listing]
----
C:\PS> New-SMBackup -ResourceGroupName 'ResourceGroup_wback-up-clusters-using-powershell-cmdlets-postgresql.adocith_Resources'  -Policy postgresql_policy1
----
+
다음 예에서는 보호된 리소스를 백업합니다.

+
[listing]
----
C:\PS> New-SMBackup -Resources @{"Host"="10.232.204.42";"Uid"="MDC\SID";"PluginName"="postgresql"} -Policy postgresql_policy2
----
. get-smJobSummaryReport cmdlet을 사용하여 작업 상태(실행 중, 완료 또는 실패)를 모니터링합니다.
+
[listing]
----
PS C:\> Get-smJobSummaryReport -JobID 123
----
. Get-SmBackupReport cmdlet을 사용하여 백업 ID, 백업 이름과 같은 백업 작업 세부 정보를 모니터링하여 복원 또는 클론 작업을 수행합니다.
+
[listing]
----
PS C:\> Get-SmBackupReport -JobId 351
Output:
BackedUpObjects           : {DB1}
FailedObjects             : {}
IsScheduled               : False
HasMetadata               : False
SmBackupId                : 269
SmJobId                   : 2361
StartDateTime             : 10/4/2016 11:20:45 PM
EndDateTime               : 10/4/2016 11:21:32 PM
Duration                  : 00:00:46.2536470
CreatedDateTime           : 10/4/2016 11:21:09 PM
Status                    : Completed
ProtectionGroupName       : Verify_ASUP_Message_windows
SmProtectionGroupId       : 211
PolicyName                : test2
SmPolicyId                : 20
BackupName                : Verify_ASUP_Message_windows_scc54_10-04-2016_23.20.46.2758
VerificationStatus        : NotVerified
VerificationStatuses      :
SmJobError                :
BackupType                : SCC_BACKUP
CatalogingStatus          : NotApplicable
CatalogingStatuses        :
ReportDataCreatedDateTime :
----


cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 cmdlet 참조 가이드"^]있습니다.
