---
permalink: protect-postgresql/install-the-snapcenter-plug-in-for-postgresql-on-linux-hosts-using-the-command-line-interface.html 
sidebar: sidebar 
keywords: install, SnapCenter Plug-in for postgresql 
summary: 'SnapCenter UI(사용자 인터페이스)를 사용하여 PostgreSQL 클러스터용 SnapCenter 플러그인을 설치해야 합니다. 환경에서 SnapCenter UI에서 플러그인을 원격으로 설치할 수 없는 경우 명령줄 인터페이스(CLI1)를 사용하여 콘솔 모드 또는 자동 모드로 PostgreSQL 클러스터용 플러그인을 설치할 수 있습니다.' 
---
= 명령줄 인터페이스를 사용하여 Linux 호스트에 PostgreSQL용 SnapCenter 플러그인을 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter UI(사용자 인터페이스)를 사용하여 PostgreSQL 클러스터용 SnapCenter 플러그인을 설치해야 합니다. 환경에서 SnapCenter UI에서 플러그인을 원격으로 설치할 수 없는 경우 CLI(명령줄 인터페이스)를 사용하여 콘솔 모드 또는 자동 모드로 PostgreSQL 클러스터용 플러그인을 설치할 수 있습니다.

.시작하기 전에
* PostgreSQL 클라이언트가 상주하는 각 Linux 호스트에 PostgreSQL용 플러그인을 설치해야 합니다.
* PostgreSQL 클러스터용 SnapCenter 플러그인을 설치하는 Linux 호스트는 종속 소프트웨어, 클러스터 및 운영 체제 요구 사항을 충족해야 합니다.
+
상호 운용성 매트릭스 툴(IMT): 지원되는 구성에 대한 최신 정보를 제공합니다.

+
https://imt.netapp.com/matrix/imt.jsp?components=117015;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"]

* PostgreSQL 클러스터용 SnapCenter 플러그인은 Linux용 SnapCenter 플러그인 패키지의 일부입니다. Linux용 SnapCenter 플러그인 패키지를 설치하기 전에 Windows 호스트에 SnapCenter가 이미 설치되어 있어야 합니다.


.단계
. C:\ProgramData\NetApp\SnapCenter\Package Repository에서 PostgreSQL용 플러그인을 설치하려는 호스트로 Linux 설치 파일(snapcenter_linux_host_plugin.bin)을 SnapCenter 복사합니다.
+
SnapCenter 서버가 설치된 호스트에서 이 경로에 액세스할 수 있습니다.

. 명령 프롬프트에서 설치 파일을 복사한 디렉토리로 이동합니다.
. 플러그 인 'path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -dport=port_number_for_host -DSERVER_IP=server_name_or_ip_address-DSERVER_HTTPS_port=port_number_for_server'를 설치합니다
+
** -dport는 SMCore HTTPS 통신 포트를 지정합니다.
** -DSERVER_IP는 SnapCenter 서버 IP 주소를 지정합니다.
** -DSERVER_HTTPS_PORT는 SnapCenter 서버 HTTPS 포트를 지정합니다.
** -DUSER_INSTALL_DIR은 Linux용 SnapCenter 플러그인 패키지를 설치할 디렉토리를 지정합니다.
** DINSTALL_LOG_NAME은 로그 파일의 이름을 지정합니다.


+
[listing]
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. /<installation directory>/netapp/snapcenter/scc/etc/SC_SMS_Services.properties 파일을 편집한 다음 plugins_enabled=PostgreSQL:3.0 매개 변수를 추가합니다.
. Add-Smhost cmdlet 및 필수 매개 변수를 사용하여 SnapCenter 서버에 호스트를 추가합니다.
+
명령에 사용할 수 있는 매개 변수와 해당 설명에 대한 정보는 _get-Help command_name_을 실행하여 얻을 수 있습니다. 또는 을 참조할 수도 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 cmdlet 참조 가이드"^]있습니다.


