---
permalink: install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html 
sidebar: sidebar 
keywords: F5, netwoek load balancer, NLB, high availability, elastic load balancing, ELB, Azure load balancing, Amazon Web Services, AWS 
summary: F5, 네트워크 로드 밸런싱 또는 Amazon Web Services를 사용하여 SnapCenter에서 고가용성을 구성합니다 
---
= 고가용성을 위해 SnapCenter 서버를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 또는 Linux에서 실행되는 SnapCenter에서 HA(고가용성)를 지원하려면 F5 로드 밸런서를 설치할 수 있습니다. F5를 사용하면 SnapCenter 서버가 동일한 위치에 있는 최대 2개의 호스트에서 액티브-패시브 구성을 지원할 수 있습니다. SnapCenter에서 F5 로드 밸런서를 사용하려면 SnapCenter 서버를 구성하고 F5 로드 밸런서를 구성해야 합니다.

NLB(네트워크 부하 분산)를 구성하여 SnapCenter 고가용성을 설정할 수도 있습니다. 고가용성을 위해 SnapCenter 설치 외부에서 NLB를 수동으로 구성해야 합니다.

클라우드 환경의 경우 AWS(Amazon Web Services) ELB(Elastic Load Balancing) 및 Azure 로드 밸런서를 사용하여 고가용성을 구성할 수 있습니다.

[role="tabbed-block"]
====
.F5를 사용하여 고가용성을 구성합니다
--
F5 로드 밸런서를 사용하여 고가용성을 위해 SnapCenter 서버를 구성하는 방법에 대한 지침은 다음을 참조하세요.  https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_SnapCenter_Servers_for_high_availability_using_F5_Load_Balancer["F5 로드 밸런서를 사용하여 고가용성을 위해 SnapCenter 서버를 구성하는 방법"^] .

이미지

다음 cmdlet을 사용하여 F5 클러스터를 추가 및 제거하려면 SnapCenter Server의 로컬 관리자 그룹 구성원이어야 합니다(스냅센터 관리자 역할에 할당되는 것 외에).

* Add-SmServerCluster를 선택합니다
* Add-SmServer 를 클릭합니다
* 제거 - SmServerCluster
+
자세한 내용은 을 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 cmdlet 참조 가이드"^]참조하십시오.



추가 정보

* 고가용성을 위해 SnapCenter를 설치하고 구성한 후 F5 클러스터 IP를 가리키도록 SnapCenter 바탕 화면 바로 가기를 편집합니다.
* SnapCenter 서버 간에 페일오버가 발생하고 기존 SnapCenter 세션도 있는 경우 브라우저를 닫고 SnapCenter에 다시 로그온해야 합니다.
* 로드 밸런서 설정(NLB 또는 F5)에서 NLB 또는 F5 호스트에 의해 부분적으로 확인된 호스트를 추가하고 SnapCenter 호스트가 이 호스트에 도달할 수 없는 경우 SnapCenter 호스트 페이지는 호스트 중단 및 실행 중 상태로 자주 전환합니다. 이 문제를 해결하려면 두 SnapCenter 호스트가 모두 NLB 또는 F5 호스트에서 호스트를 해결할 수 있는지 확인해야 합니다.
* MFA 설정에 대한 SnapCenter 명령은 모든 호스트에서 실행해야 합니다. AD FS(Active Directory Federation Services) 서버에서 F5 클러스터 세부 정보를 사용하여 기반 당사자 구성을 수행해야 합니다. MFA가 설정된 후에는 호스트 레벨 SnapCenter UI 액세스가 차단됩니다.
* 페일오버 중에는 감사 로그 설정이 두 번째 호스트에 반영되지 않습니다. 따라서 F5 패시브 호스트가 활성화되면 수동으로 감사 로그 설정을 반복해야 합니다.


--
.NLB(Network Load Balancing)를 사용하여 고가용성 구성
--
NLB(네트워크 부하 분산)를 구성하여 SnapCenter 고가용성을 설정할 수 있습니다. 고가용성을 위해 SnapCenter 설치 외부에서 NLB를 수동으로 구성해야 합니다.

SnapCenter를 사용하여 NLB(네트워크 로드 밸런싱)를 구성하는 방법에 대한 자세한 내용은 을 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_NLB_and_ARR_with_SnapCenter["SnapCenter를 사용하여 NLB를 구성하는 방법"^]참조하십시오.

--
.AWS ELB(Elastic Load Balancing)를 사용하여 고가용성 구성
--
AWS(Amazon Web Services)에서 SnapCenter 서버 2대를 별도의 AZ(가용 영역)에 설정하고 자동 장애 조치가 가능하도록 구성하여 고가용성 SnapCenter 환경을 구성할 수 있습니다. 이 아키텍처에는 가상 사설 IP 주소, 라우팅 테이블, 활성 및 대기 MySQL 데이터베이스 간의 동기화가 포함됩니다.

.단계
. AWS에서 가상 전용 오버레이 IP를 구성합니다. 자세한 내용은 을 https://docs.aws.amazon.com/vpc/latest/userguide/replace-local-route-target.html["가상 전용 오버레이 IP를 구성합니다"^]참조하십시오.
. Windows 호스트를 준비합니다
+
.. IPv4의 우선 순위를 IPv6보다 높게 지정:
+
*** 위치: HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
*** 키: DisabledComponents
*** REG_DWORD 를 입력합니다
*** 값: 0x20


.. DNS를 통해 또는 IPv4 주소에 대한 로컬 호스트 구성을 통해 정규화된 도메인 이름을 확인할 수 있는지 확인합니다.
.. 시스템 프록시가 구성되어 있지 않은지 확인합니다.
.. Active Directory 없이 설치 프로그램을 사용할 때 Windows Server에서 관리자 암호가 동일하고 서버가 한 도메인에 있지 않은지 확인합니다.
.. 두 Windows Server에 가상 IP를 추가합니다.


. SnapCenter 클러스터를 생성합니다.
+
.. Powershell을 시작하고 SnapCenter에 연결합니다.
`Open-SmConnection`
.. 클러스터를 생성합니다.
`Add-SmServerCluster -ClusterName <cluster_name> -ClusterIP <cluster_ip> -PrimarySCServerIP <primary_ip> -Verbose -Credential administrator`
.. 보조 서버를 추가합니다.
`Add-SmServer -ServerName <server_name> -ServerIP <server_ip> -CleanUpSecondaryServer -Verbose -Credential administrator`
.. 고가용성 세부 정보를 확인하십시오.
`Get-SmServerConfig`


. Lamda 기능을 생성하여 AWS CloudWatch에서 모니터링하는 가상 사설 IP 끝점을 사용할 수 없게 될 경우 라우팅 테이블을 조정합니다. 자세한 내용은 을 https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html#getting-started-create-function["Lambda 함수를 만듭니다"^]참조하십시오.
. CloudWatch에서 모니터를 만들어 SnapCenter 끝점의 가용성을 모니터링합니다. 종점에 도달할 수 없는 경우 Lambda 기능을 트리거하도록 알람이 구성됩니다. Lambda 기능은 트래픽을 활성 SnapCenter 서버로 리디렉션하도록 라우팅 테이블을 조정합니다. 자세한 내용은 을 https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Create.html["합성 캐너리를 만듭니다"^]참조하십시오.
. CloudWatch 모니터링의 대안으로 STEP 기능을 사용하여 워크플로우를 구현하여 페일오버 시간을 줄입니다. 워크플로에는 SnapCenter URL을 테스트하는 Lambda 프로브 기능, 오류 카운트를 저장하기 위한 DynamoDB 테이블 및 Step 함수 자체가 포함됩니다.
+
.. SnapCenter URL을 탐색하는 데 lambda 함수를 사용합니다. 자세한 내용은 을 https://docs.aws.amazon.com/lambda/latest/dg/getting-started.html["Lambda 함수를 만듭니다"^]참조하십시오.
.. 2단계 함수 반복 간 실패 횟수를 저장하기 위해 DynamoDB 테이블을 만듭니다. 자세한 내용은 을 https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GettingStartedDynamoDB.html["DynamoDB 테이블을 사용해 보세요"^]참조하십시오.
.. 단계 기능을 만듭니다. 자세한 내용은 을 https://docs.aws.amazon.com/step-functions/["STEP 기능 문서화"^]참조하십시오.
.. 단일 단계를 테스트합니다.
.. 전체 기능을 테스트합니다.
.. IAM 역할을 생성하고 Lambda 기능을 실행할 수 있도록 권한을 조정합니다.
.. 단계 기능을 트리거하기 위한 스케줄을 생성합니다. 자세한 내용은 을 https://docs.aws.amazon.com/step-functions/latest/dg/using-eventbridge-scheduler.html["Amazon EventBridge Scheduler를 사용하여 단계 기능을 시작합니다"^]참조하십시오.




--
.Azure 로드 밸런서를 사용하여 고가용성을 구성합니다
--
Azure 로드 밸런서를 사용하여 고가용성 SnapCenter 환경을 구성할 수 있습니다.

.단계
. Azure Portal을 사용하여 확장 집합으로 가상 머신을 생성합니다. Azure 가상 머신 스케일 세트를 사용하여 로드 밸런싱된 가상 머신 그룹을 만들고 관리할 수 있습니다. 가상 머신 인스턴스의 수는 수요 또는 정의된 일정에 따라 자동으로 증가 또는 감소할 수 있습니다. 자세한 내용은 을 https://learn.microsoft.com/en-us/azure/virtual-machine-scale-sets/flexible-virtual-machine-scale-sets-portal["Azure Portal을 사용하여 확장 집합으로 가상 머신을 생성합니다"^]참조하십시오.
. 가상 머신을 구성한 후 VM 세트의 각 가상 머신에 로그인하고 두 노드에 SnapCenter Server를 설치합니다.
. 호스트 1에서 클러스터를 생성합니다.
`Add-SmServerCluster -ClusterName <cluster_name> -ClusterIP <specify the load balancer front end virtual ip> -PrimarySCServerIP <ip address> -Verbose -Credential <credentials>`
. 보조 서버를 추가합니다.
`Add-SmServer -ServerName <name of node2> -ServerIP <ip address of node2> -Verbose -Credential <credentials>`
. 고가용성 세부 정보를 확인합니다.
`Get-SmServerConfig`
. 필요한 경우 보조 호스트를 재구축합니다.
`Set-SmRepositoryConfig -RebuildSlave -Verbose`
. 두 번째 호스트로 페일오버합니다.
`Set-SmRepositoryConfig ActiveMaster <name of node2> -Verbose`


--
== NLB에서 F5로 전환하여 고가용성을 보장합니다

SnapCenter HA 구성을 NLB(네트워크 로드 밸런싱)에서 F5 로드 밸런서를 사용하도록 변경할 수 있습니다.

* 단계 *

. F5를 사용하여 고가용성을 위해 SnapCenter 서버를 구성합니다. https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_SnapCenter_Servers_for_high_availability_using_F5_Load_Balancer["자세한 정보"^].
. SnapCenter 서버 호스트에서 PowerShell을 실행합니다.
. Open-SmConnection cmdlet을 사용하여 세션을 시작한 다음 자격 증명을 입력합니다.
. Update-SmServerCluster cmdlet을 사용하여 F5 클러스터 IP 주소를 가리키도록 SnapCenter 서버를 업데이트합니다.
+
cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html["SnapCenter 소프트웨어 cmdlet 참조 가이드"^]있습니다.



====