---
permalink: install/concept_authentication_methods_for_your_credentials.html 
sidebar: sidebar 
keywords: credentials, authentication 
summary: 자격 증명은 응용 프로그램이나 환경에 따라 다른 인증 방법을 사용합니다. 자격 증명은 SnapCenter 작업을 수행할 수 있도록 사용자를 인증합니다. 플러그인 설치를 위한 자격 증명 세트와 데이터 보호 작업을 위한 다른 자격 증명 세트를 생성해야 합니다. 
---
= 자격 증명에 대한 인증 방법입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
자격 증명은 응용 프로그램이나 환경에 따라 다른 인증 방법을 사용합니다. 자격 증명은 SnapCenter 작업을 수행할 수 있도록 사용자를 인증합니다. 플러그인 설치를 위한 자격 증명 세트와 데이터 보호 작업을 위한 다른 자격 증명 세트를 생성해야 합니다.



== Windows 인증

Windows 인증 방법은 Active Directory에 대해 인증합니다. Windows 인증의 경우 Active Directory는 SnapCenter 외부에서 설정됩니다. SnapCenter는 추가 구성 없이 인증합니다. 호스트 추가, 플러그인 패키지 설치 및 작업 예약 등의 작업을 수행하려면 Windows 자격 증명이 필요합니다.



== 신뢰할 수 없는 도메인 인증입니다

SnapCenter를 사용하면 신뢰할 수 없는 도메인에 속하는 사용자 및 그룹을 사용하여 Windows 자격 증명을 만들 수 있습니다. 인증에 성공하려면 신뢰할 수 없는 도메인을 SnapCenter에 등록해야 합니다.



== 로컬 워크그룹 인증

SnapCenter를 사용하면 로컬 작업 그룹 사용자 및 그룹을 사용하여 Windows 자격 증명을 생성할 수 있습니다. 로컬 작업 그룹 사용자 및 그룹에 대한 Windows 인증은 Windows 자격 증명 생성 시 수행되지 않지만 호스트 등록 및 기타 호스트 작업이 수행될 때까지 지연됩니다.



== SQL Server 인증

SQL 인증 메서드는 SQL Server 인스턴스에 대해 인증합니다. 즉, SnapCenter에서 SQL Server 인스턴스를 검색한 다음 따라서 SQL 자격 증명을 추가하기 전에 호스트를 추가하고 플러그인 패키지를 설치하고 리소스를 새로 고쳐야 합니다. SQL Server에서 일정을 예약하거나 리소스를 검색하는 등의 작업을 수행하려면 SQL Server 인증이 필요합니다.



== Linux 인증

Linux 인증 방법은 Linux 호스트에 대해 인증합니다. Linux 호스트를 추가하고 SnapCenter GUI에서 Linux용 SnapCenter 플러그인 패키지를 원격으로 설치하는 초기 단계 동안 Linux 인증이 필요합니다.



== AIX 인증

AIX 인증 방법은 AIX 호스트에 대해 인증합니다. AIX 호스트를 추가하고 SnapCenter GUI에서 AIX용 SnapCenter 플러그인 패키지를 원격으로 설치하는 초기 단계 동안 AIX 인증이 필요합니다.



== Oracle 데이터베이스 인증

Oracle 데이터베이스 인증 방법은 Oracle 데이터베이스에 대해 인증합니다. 데이터베이스 호스트에서 운영 체제(OS) 인증이 비활성화되어 있는 경우 Oracle 데이터베이스에서 작업을 수행하려면 Oracle 데이터베이스 인증이 필요합니다. 따라서 Oracle 데이터베이스 자격 증명을 추가하기 전에 sysdba 권한을 사용하여 Oracle 데이터베이스에 Oracle 사용자를 생성해야 합니다.



== Oracle ASM 인증

Oracle ASM 인증 방법은 Oracle ASM(Automatic Storage Management) 인스턴스에 대해 인증합니다. Oracle ASM 인스턴스에 액세스해야 하고 데이터베이스 호스트에서 운영 체제(OS) 인증이 비활성화된 경우 Oracle ASM 인증이 필요합니다. 따라서 Oracle ASM 자격 증명을 추가하기 전에 ASM 인스턴스에서 sysasm 권한을 가진 Oracle 사용자를 생성해야 합니다.



== RMAN 카탈로그 인증

RMAN 카탈로그 인증 방법은 Oracle RMAN(Recovery Manager) 카탈로그 데이터베이스에 대해 인증합니다. 외부 카탈로그 메커니즘을 구성하고 데이터베이스를 카탈로그 데이터베이스에 등록한 경우 RMAN 카탈로그 인증을 추가해야 합니다.
