---
permalink: install/concept_provision_storage_in_vmware_environments.html 
sidebar: sidebar 
keywords: guest OS, VMware ESXi server, limitations, RDM, Microsoft cluster 
summary: VMware 환경에서 Microsoft Windows용 SnapCenter 플러그인을 사용하여 LUN을 생성 및 관리하고 스냅샷 백업 복사본을 관리할 수 있습니다. 
---
= VMware 환경에서 스토리지 프로비저닝
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware 환경에서 Microsoft Windows용 SnapCenter 플러그인을 사용하여 LUN을 생성 및 관리하고 스냅샷 복사본을 관리할 수 있습니다.



== 지원되는 VMware 게스트 OS 플랫폼

* 지원되는 Windows Server 버전
* Microsoft 클러스터 구성
+
Microsoft iSCSI Software Initiator를 사용할 경우 VMware에서 최대 16개의 노드를 지원하거나 FC를 사용하여 최대 2개의 노드를 지원합니다

* RDM LUN입니다
+
일반 RDM용 4개의 LSI Logic SCSI 컨트롤러가 있는 최대 56개의 RDM LUN 또는 Windows 구성용 VMware VM MSCS 박스-박스 플러그인에서 3개의 LSI Logic SCSI 컨트롤러가 있는 42개의 RDM LUN을 지원합니다

+
VMware ParaVirtual SCSI 컨트롤러를 지원합니다. RDM 디스크에서 256개의 디스크를 지원할 수 있습니다.



지원되는 버전에 대한 최신 정보는 를 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].



=== VMware ESXi 서버 관련 제한 사항

* ESXi 자격 증명을 사용하여 가상 컴퓨터의 Microsoft 클러스터에 Windows용 플러그인을 설치하는 것은 지원되지 않습니다.
+
클러스터링된 가상 머신에 Windows용 플러그인을 설치할 때는 vCenter 자격 증명을 사용해야 합니다.

* 클러스터된 모든 노드는 동일한 클러스터된 디스크에 대해 동일한 대상 ID(가상 SCSI 어댑터)를 사용해야 합니다.
* Windows용 플러그인 외부에서 RDM LUN을 생성하는 경우 플러그인 서비스를 다시 시작하여 새로 생성된 디스크를 인식할 수 있도록 설정해야 합니다.
* VMware 게스트 OS에서는 iSCSI 및 FC 이니시에이터를 동시에 사용할 수 없습니다.




=== SnapCenter RDM 작업에 필요한 최소 vCenter 권한

게스트 OS에서 RDM 작업을 수행하려면 호스트에 대해 다음과 같은 vCenter 권한이 있어야 합니다.

* 데이터 저장소: 파일 제거
* 호스트: 구성 > 스토리지 파티션 구성
* 가상 시스템:구성


이러한 권한은 Virtual Center Server 수준에서 역할에 할당해야 합니다. 이러한 권한을 할당하는 역할은 루트 권한이 없는 사용자에게 할당할 수 없습니다.

이러한 권한을 할당한 후 게스트 OS에 Windows용 플러그인을 설치할 수 있습니다.



== Microsoft 클러스터에서 FC RDM LUN을 관리합니다

Windows용 플러그인을 사용하여 FC RDM LUN을 사용하여 Microsoft 클러스터를 관리할 수 있지만 먼저 플러그인 외부에서 공유 RDM 쿼럼과 공유 스토리지를 생성한 다음 클러스터의 가상 머신에 디스크를 추가해야 합니다.

ESXi 5.5부터 ESX iSCSI 및 FCoE 하드웨어를 사용하여 Microsoft 클러스터를 관리할 수도 있습니다. Windows용 플러그인에는 Microsoft 클러스터에 대한 즉시 사용 가능한 지원이 포함되어 있습니다.



=== 요구 사항

Windows용 플러그인은 특정 구성 요구 사항을 충족하는 경우 두 개의 서로 다른 ESX 또는 ESXi 서버에 속하는 두 개의 서로 다른 가상 시스템에서 FC RDM LUN을 사용하는 Microsoft 클러스터를 지원합니다.

* 가상 머신(VM)은 동일한 Windows Server 버전을 실행해야 합니다.
* ESX 또는 ESXi 서버 버전은 각 VMware 상위 호스트에 대해 동일해야 합니다.
* 각 상위 호스트에는 최소한 두 개의 네트워크 어댑터가 있어야 합니다.
* 두 ESX Server 또는 ESXi Server 간에 공유되는 VMware VMFS(Virtual Machine File System) 데이터 저장소가 하나 이상 있어야 합니다.
* 공유 데이터 저장소를 FC SAN에 생성하는 것이 좋습니다.
+
필요한 경우 iSCSI를 통해 공유 데이터 저장소를 생성할 수도 있습니다.

* 공유 RDM LUN은 물리적 호환성 모드에 있어야 합니다.
* Windows용 플러그인 외부에서 공유 RDM LUN을 수동으로 생성해야 합니다.
+
공유 스토리지에는 가상 디스크를 사용할 수 없습니다.

* SCSI 컨트롤러는 클러스터의 각 가상 머신에서 물리적 호환성 모드로 구성해야 합니다.
+
Windows Server 2008 R2에서는 각 가상 머신에 LSI Logic SAS SCSI 컨트롤러를 구성해야 합니다. 공유 LUN은 유형 중 하나만 있고 이미 C: 드라이브에 연결되어 있는 경우 기존 LSI Logic SAS 컨트롤러를 사용할 수 없습니다.

+
반가상화 유형의 SCSI 컨트롤러는 VMware Microsoft 클러스터에서 지원되지 않습니다.

+

NOTE: 물리적 호환성 모드에서 가상 시스템의 공유 LUN에 SCSI 컨트롤러를 추가하는 경우 VMware Infrastructure Client에서 * Create a new disk * 옵션이 아닌 * RDM(Raw Device Mappings *) 옵션을 선택해야 합니다.

* Microsoft 가상 머신 클러스터는 VMware 클러스터에 포함될 수 없습니다.
* Microsoft 클러스터에 속한 가상 머신에 Windows용 플러그인을 설치할 때는 ESX 또는 ESXi 자격 증명이 아닌 vCenter 자격 증명을 사용해야 합니다.
* Windows용 플러그인은 여러 호스트의 이니시에이터를 포함하는 단일 igroup을 생성할 수 없습니다.
+
공유 클러스터 디스크로 사용될 RDM LUN을 생성하기 전에 모든 ESXi 호스트의 이니시에이터를 포함하는 igroup을 스토리지 컨트롤러에서 생성해야 합니다.

* FC Initiator를 사용하여 ESXi 5.0에서 RDM LUN을 생성해야 합니다.
+
RDM LUN을 생성할 때 이니시에이터 그룹은 ALUA를 통해 생성됩니다.





=== 제한 사항

Windows용 플러그인은 서로 다른 ESX 또는 ESXi 서버에 속하는 서로 다른 가상 머신에서 FC/iSCSI RDM LUN을 사용하는 Microsoft 클러스터를 지원합니다.


NOTE: 이 기능은 ESX 5.5i 이전의 릴리즈에서는 지원되지 않습니다.

* Windows용 플러그인은 ESX iSCSI 및 NFS 데이터 저장소의 클러스터를 지원하지 않습니다.
* Windows용 플러그인은 클러스터 환경에서 혼합 이니시에이터를 지원하지 않습니다.
+
이니시에이터는 FC 또는 Microsoft iSCSI 중 하나여야 하며 둘 다 사용할 수는 없습니다.

* ESX iSCSI 이니시에이터와 HBA는 Microsoft 클러스터의 공유 디스크에서 지원되지 않습니다.
* 가상 머신이 Microsoft 클러스터의 일부인 경우 Windows용 플러그인은 vMotion을 사용한 가상 머신 마이그레이션을 지원하지 않습니다.
* Windows용 플러그인은 Microsoft 클러스터의 가상 시스템에서 MPIO를 지원하지 않습니다.




=== 공유 FC RDM LUN을 생성합니다

FC RDM LUN을 사용하여 Microsoft 클러스터의 노드 간에 스토리지를 공유하려면 먼저 공유 쿼럼 디스크와 공유 스토리지 디스크를 생성한 다음 클러스터의 두 가상 머신에 추가해야 합니다.

Windows용 플러그인을 사용하여 공유 디스크가 생성되지 않습니다. 공유 LUN을 생성한 다음 클러스터의 각 가상 머신에 추가해야 합니다. 자세한 내용은 을 참조하십시오 https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.mscs.doc/GUID-1A2476C0-CA66-4B80-B6F9-8421B6983808.html["물리적 호스트에서 가상 시스템을 클러스터링합니다"^].
