---
permalink: install/concept_high_availability_for_snapcenter_mysql_repository.html 
sidebar: sidebar 
keywords: SnapCenter, MySQL high availability 
summary: 'MySQL 복제는 하나의 MySQL 데이터베이스 서버(마스터)에서 다른 MySQL 데이터베이스 서버(슬레이브)로 데이터를 복제할 수 있는 MySQL Server의 기능입니다. SnapCenter는 2개의 NLB 지원(Network Load Balancing-enabled) 노드에서만 고가용성을 위해 MySQL 복제를 지원합니다.' 
---
= SnapCenter MySQL 리포지토리의 고가용성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
MySQL 복제는 하나의 MySQL 데이터베이스 서버(마스터)에서 다른 MySQL 데이터베이스 서버(슬레이브)로 데이터를 복제할 수 있는 MySQL Server의 기능입니다. SnapCenter는 2개의 NLB 지원(Network Load Balancing-enabled) 노드에서만 고가용성을 위해 MySQL 복제를 지원합니다.

SnapCenter는 마스터 리포지토리에서 읽기 또는 쓰기 작업을 수행하고 마스터 리포지토리에 오류가 있을 때 슬레이브 리포지토리에 대한 연결을 라우팅합니다. 그러면 슬레이브 리포지토리가 마스터 리포지토리가 됩니다. SnapCenter는 페일오버 중에만 사용되는 역방향 복제도 지원합니다.

MySQL HA(고가용성) 기능을 사용하려면 첫 번째 노드에서 NLB(네트워크 로드 밸런서)를 구성해야 합니다. MySQL 리포지토리는 설치의 일부로 이 노드에 설치됩니다. 두 번째 노드에 SnapCenter를 설치하는 동안 첫 번째 노드의 F5에 가입하고 두 번째 노드에 MySQL 리포지토리의 복사본을 만들어야 합니다.

SnapCenter는 MySQL 복제를 관리하기 위해 _get-SmrepositoryConfig_and_Set-SmrepositoryConfig_PowerShell cmdlet을 제공합니다.

cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].

MySQL HA 기능과 관련된 제한 사항을 알고 있어야 합니다.

* NLB와 MySQL HA는 두 노드 이상으로 지원되지 않습니다.
* SnapCenter 독립 실행형 설치에서 NLB 설치로 또는 그 반대로 전환하고 MySQL 독립 실행형 설정에서 MySQL HA로 전환하는 것은 지원되지 않습니다.
* 슬레이브 리포지토리 데이터가 마스터 저장소 데이터와 동기화되지 않은 경우 자동 장애 조치가 지원되지 않습니다.
+
_Set-SmRepositoryConfig_cmdlet을 사용하여 강제 대체 작동을 시작할 수 있습니다.

* 페일오버가 시작되면 실행 중인 작업이 실패할 수 있습니다.
+
MySQL Server 또는 SnapCenter Server가 다운되어 페일오버가 발생하면 실행 중인 작업이 실패할 수 있습니다. 두 번째 노드로 페일오버한 후 이후의 모든 작업이 성공적으로 실행됩니다.



고가용성 구성에 대한 자세한 내용은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_NLB_and_ARR_with_SnapCenter["SnapCenter를 사용하여 NLB 및 ARR을 구성하는 방법"^].
