---
permalink: install/concept_create_and_manage_smb_shares.html 
sidebar: sidebar 
keywords: SMB shares 
summary: 'SVM(스토리지 가상 머신)에서 SMB3 공유를 구성하려면 SnapCenter 사용자 인터페이스 또는 PowerShell cmdlet을 사용할 수 있습니다.' 
---
= SMB 공유를 생성하고 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SVM(스토리지 가상 머신)에서 SMB3 공유를 구성하려면 SnapCenter 사용자 인터페이스 또는 PowerShell cmdlet을 사용할 수 있습니다.

|===


| * 모범 사례: * cmdlet을 사용하면 SnapCenter에서 제공하는 템플릿을 활용하여 공유 구성을 자동화할 수 있으므로 사용하는 것이 좋습니다. 
|===
이 템플릿은 볼륨 및 공유 구성에 대한 모범 사례를 캡슐화합니다. Windows용 SnapCenter 플러그인 패키지의 설치 폴더에 있는 Templates 폴더에서 템플릿을 찾을 수 있습니다.


TIP: 이렇게 하는 것이 편하다면 제공된 모델에 따라 템플릿을 직접 만들 수 있습니다. 사용자 지정 템플릿을 만들기 전에 cmdlet 설명서의 매개 변수를 검토해야 합니다.



== SMB 공유를 생성합니다

SnapCenter 공유 페이지를 사용하여 SVM(스토리지 가상 머신)에 SMB3 공유를 생성할 수 있습니다.

SnapCenter를 사용하여 SMB 공유의 데이터베이스를 백업할 수 없습니다. SMB 지원은 프로비저닝에만 제한됩니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 공유 * 를 클릭합니다.
. Storage Virtual Machine * 드롭다운 목록에서 SVM을 선택합니다.
. 새로 만들기 * 를 클릭합니다.
+
새 공유 대화 상자가 열립니다.

. 새 공유 대화 상자에서 공유를 정의합니다.
+
|===
| 이 필드에서... | 수행할 작업... 


 a| 
설명
 a| 
공유에 대한 설명 텍스트를 입력합니다.



 a| 
공유 이름
 a| 
공유 이름(예: test_share)을 입력합니다.

공유에 대해 입력한 이름도 볼륨 이름으로 사용됩니다.

공유 이름:

** UTF-8 문자열이어야 합니다.
** 0x00에서 0x1F(둘 다 포함), 0x22(큰따옴표), 특수 문자 "\/[]:(세로 막대) <>+=;,?"와 같은 문자는 포함할 수 없습니다




 a| 
공유 경로
 a| 
** 필드를 클릭하여 새 파일 시스템 경로(예: /)를 입력합니다.
** 필드를 두 번 클릭하여 기존 파일 시스템 경로 목록에서 선택합니다.


|===
. 입력한 내용에 만족하면 * 확인 * 을 클릭합니다.
+
SnapCenter은 SVM에서 SMB 공유를 생성합니다.





== SMB 공유를 삭제합니다

SMB 공유가 더 이상 필요하지 않은 경우 삭제할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 공유 * 를 클릭합니다.
. 공유 페이지에서 * 스토리지 가상 머신 * 필드를 클릭하여 사용 가능한 SVM(스토리지 가상 머신) 목록이 포함된 드롭다운을 표시한 다음 삭제할 공유의 SVM을 선택합니다.
. SVM의 공유 목록에서 삭제할 공유를 선택하고 * 삭제 * 를 클릭합니다.
. 공유 삭제 대화 상자에서 * 확인 * 을 클릭합니다.
+
SnapCenter는 SVM에서 SMB 공유를 삭제합니다.


