---
permalink: install/concept_create_and_manage_igroups.html 
sidebar: sidebar 
keywords: igroup 
summary: '이니시에이터 그룹(igroup)을 생성하여 스토리지 시스템에서 특정 LUN에 액세스할 수 있는 호스트를 지정합니다. SnapCenter를 사용하여 Windows 호스트에서 igroup을 생성, 이름 바꾸기, 수정 또는 삭제할 수 있습니다.' 
---
= Igroup 생성 및 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이니시에이터 그룹(igroup)을 생성하여 스토리지 시스템에서 특정 LUN에 액세스할 수 있는 호스트를 지정합니다. SnapCenter를 사용하여 Windows 호스트에서 igroup을 생성, 이름 바꾸기, 수정 또는 삭제할 수 있습니다.



== igroup 작성

SnapCenter를 사용하여 Windows 호스트에서 igroup을 생성할 수 있습니다. igroup을 LUN에 매핑할 때 디스크 생성 또는 디스크 연결 마법사에서 해당 igroup을 사용할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * iGroup * 을 클릭합니다.
. 이니시에이터 그룹 페이지에서 * 신규 * 를 클릭합니다.
. Create iGroup 대화 상자에서 igroup을 정의합니다.
+
|===
| 이 필드에서... | 수행할 작업... 


 a| 
스토리지 시스템
 a| 
igroup에 매핑할 LUN의 SVM을 선택합니다.



 a| 
호스트
 a| 
igroup을 생성할 호스트를 선택합니다.



 a| 
Igroup 이름입니다
 a| 
igroup의 이름을 입력합니다.



 a| 
이니시에이터
 a| 
이니시에이터를 선택합니다.



 a| 
유형
 a| 
이니시에이터 유형, iSCSI, FCP 또는 혼합(FCP 및 iSCSI)을 선택합니다.

|===
. 입력한 내용에 만족하면 * 확인 * 을 클릭합니다.
+
SnapCenter이 스토리지 시스템에서 igroup을 생성합니다.





== igroup의 이름을 바꿉니다

SnapCenter를 사용하여 기존 igroup의 이름을 바꿀 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * iGroup * 을 클릭합니다.
. 이니시에이터 그룹 페이지에서 * 스토리지 가상 머신 * 필드를 클릭하여 사용 가능한 SVM 목록을 표시한 다음, 이름을 바꿀 igroup에 사용할 SVM을 선택합니다.
. SVM의 igroup 목록에서 이름을 바꿀 igroup을 선택하고 * 이름 바꾸기 * 를 클릭합니다.
. igroup 이름 바꾸기 대화 상자에서 igroup의 새 이름을 입력하고 * 이름 바꾸기 * 를 클릭합니다.




== igroup을 수정합니다

SnapCenter를 사용하여 igroup 이니시에이터를 기존 igroup에 추가할 수 있습니다. igroup을 작성하는 동안 하나의 호스트만 추가할 수 있습니다. 클러스터에 대한 igroup을 작성하려는 경우 igroup을 수정하여 해당 igroup에 다른 노드를 추가할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * iGroup * 을 클릭합니다.
. 이니시에이터 그룹 페이지에서 * 스토리지 가상 머신 * 필드를 클릭하여 사용 가능한 SVM의 드롭다운 목록을 표시한 다음, 수정할 igroup에 사용할 SVM을 선택합니다.
. igroup 목록에서 igroup을 선택하고 * igroup에 이니시에이터 추가 * 를 클릭합니다.
. 호스트를 선택합니다.
. 이니시에이터를 선택하고 * OK * 를 클릭합니다.




== igroup을 삭제합니다

더 이상 필요하지 않은 경우 SnapCenter를 사용하여 igroup을 삭제할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * iGroup * 을 클릭합니다.
. 이니시에이터 그룹 페이지에서 * 스토리지 가상 머신 * 필드를 클릭하여 사용 가능한 SVM의 드롭다운 목록을 표시한 다음, 삭제할 igroup에 사용할 SVM을 선택합니다.
. SVM의 igroup 목록에서 삭제할 igroup을 선택하고 * Delete * 를 클릭합니다.
. Delete igroup (그룹 삭제) 대화 상자에서 * OK * (확인 *)를 클릭합니다.
+
SnapCenter이 igroup을 삭제합니다.


