---
permalink: install/configure_mfa_using_powershell_sccli_restapi.html 
sidebar: sidebar 
keywords: mfa, authentication, multifactor authentication 
summary: REST API, PowerShell 및 SCCLI 인터페이스를 사용하여 MFA를 구성할 수 있습니다. 
---
= SnapCenter 서버에서 PowerShell, SCCLI 및 REST API를 사용하여 MFA를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버에서 PowerShell, SCCLI 및 REST API를 사용하여 MFA를 구성할 수 있습니다.



== SnapCenter MFA CLI 인증

PowerShell 및 SCCLI에서 베어러 토큰을 사용하여 사용자를 인증하는 데 "AccessToken"이라는 필드가 하나 더 있는 기존 cmdlet(Open-SmConnection)이 확장됩니다.

`Open-SmConnection -Credential <PSCredential> [-SMSbaseUrl <String>] [-Port <String>] [-RoleName <String>] [ -AccessToken <string>]`

위의 cmdlet을 실행한 후 해당 사용자가 추가 SnapCenter cmdlet을 실행할 수 있도록 세션이 생성됩니다.



== SnapCenter MFA REST API 인증

SnapCenter로부터 성공적인 응답을 얻으려면 _Authorization=Bearer <access token>_in REST API 클라이언트(예: Postman 또는 swagger)의 형식으로 베어러 토큰을 사용하고 헤더에 사용자 RoleName을 언급하십시오.



== MFA REST API 워크플로우

MFA가 AD FS로 구성된 경우 액세스(베어러) 토큰을 사용하여 인증하여 REST API를 통해 SnapCenter 애플리케이션에 액세스해야 합니다.

* 이 작업에 대한 정보 *

* Postman, Swagger UI 또는 FireCamp와 같은 REST 클라이언트를 사용할 수 있습니다.
* 액세스 토큰을 가져와 후속 요청(SnapCenter REST API)을 인증하여 작업을 수행합니다.


* 단계 *

* AD FS MFA * 를 통해 인증합니다

. 액세스 토큰을 얻기 위해 AD FS 끝점을 호출하도록 REST 클라이언트를 구성합니다.
+
버튼을 눌러 응용 프로그램의 액세스 토큰을 가져오는 경우 AD FS SSO 페이지로 리디렉션됩니다. 이 페이지에서 AD 자격 증명을 제공하고 MFA로 인증해야 합니다.
AD FS SSO 페이지에서 사용자 이름 텍스트 상자에 사용자 이름 또는 이메일을 입력합니다.

+
를 누릅니다
사용자 이름은 user@domain 또는 domain\user 형식으로 지정해야 합니다.

. 암호 텍스트 상자에 암호를 입력합니다.
. 로그인 * 을 클릭합니다.
. 로그인 옵션 * 섹션에서 인증 옵션을 선택하고 인증(구성에 따라 다름)을 수행합니다.
+
** 푸시: 휴대폰에 전송되는 푸시 알림을 승인합니다.
** QR 코드: AUTH Point 모바일 앱을 사용하여 QR 코드를 스캔한 다음 앱에 표시된 검증 코드를 입력합니다
** 일회용 암호: 토큰의 일회용 암호를 입력합니다.


. 인증에 성공하면 액세스, ID 및 토큰 새로 고침이 포함된 팝업이 열립니다.
+
액세스 토큰을 복사하고 SnapCenter REST API에서 사용하여 작업을 수행합니다.

. REST API에서는 헤더 섹션에서 액세스 토큰 및 역할 이름을 전달해야 합니다.
. SnapCenter는 AD FS에서 이 액세스 토큰을 검증합니다.
+
유효한 토큰인 경우 SnapCenter는 해당 토큰을 디코딩하고 사용자 이름을 가져옵니다.

. SnapCenter는 사용자 이름과 역할 이름을 사용하여 API 실행을 위해 사용자를 인증합니다.
+
인증에 성공하면 SnapCenter가 결과를 반환하고 그렇지 않으면 오류 메시지가 표시됩니다.





== REST API, CLI 및 GUI에 대해 SnapCenter MFA 기능을 사용하거나 사용하지 않도록 설정합니다

* GUI *

* 단계 *

. SnapCenter 서버에 SnapCenter 관리자로 로그인합니다.
. 설정 * > * 글로벌 설정 * > * 멀티팩터인증(MFA) 설정 * 을 클릭합니다
. 인터페이스(GUI/RST API/CLI)를 선택하여 MFA 로그인을 활성화하거나 비활성화합니다.


* PowerShell 인터페이스 *

* 단계 *

. GUI, REST API, PowerShell 및 SCCLI에 대해 MFA를 사용하도록 PowerShell 또는 CLI 명령을 실행합니다.
+
`Set-SmMultiFactorAuthentication -IsGuiMFAEnabled -IsRestApiMFAEnabled`
`-IsCliMFAEnabled -Path`

+
path 매개 변수는 AD FS MFA 메타데이터 XML 파일의 위치를 지정합니다.

+
지정된 AD FS 메타데이터 파일 경로로 구성된 SnapCenter GUI, REST API, PowerShell 및 SCCLI에 대한 MFA를 활성화합니다.

. 를 사용하여 MFA 구성 상태 및 설정을 확인합니다 `Get-SmMultiFactorAuthentication` cmdlet.


SCCLI 인터페이스 *

* 단계 *

. `# sccli Set-SmMultiFactorAuthentication -IsGuiMFAEnabled true -IsRESTAPIMFAEnabled true -IsCliMFAEnabled true  -Path "C:\ADFS_metadata\abc.xml"`
. `# sccli Get-SmMultiFactorAuthentication`


* REST API *

. GUI, REST API, PowerShell 및 SCCLI에 대해 MFA를 사용하도록 다음 POST API를 실행합니다.
+
|===


| 매개 변수 | 값 


 a| 
요청된 URL입니다
 a| 
/api/4.9/settings/multipactorauthentication을 참조하십시오



 a| 
HTTP 메소드
 a| 
게시



 a| 
요청 본문
 a| 
{
  "IsGuiMFAEnabled": false,
  "IsRestApiMFAEnabled": 참,
  "IsCliMFAEnabled": false,
  "ADFSConfigFilePath":"C:\\ADFS_METADATA\\abc.xml"
}



 a| 
응답 본문
 a| 
{
  "MFAConfiguration":{을 참조하십시오
    "IsGuiMFAEnabled": false,
    "ADFSConfigFilePath":"C:\\ADFS_METADATA\\abc.xml",
    "SCConfigFilePath": null,
    "IsRestApiMFAEnabled": 참,
    "IsCliMFAEnabled": false,
    "ADFSHostName":"win-adfs-sc49.winscedom2.com"
  }
}

|===
. 다음 API를 사용하여 MFA 구성 상태 및 설정을 확인합니다.
+
|===


| 매개 변수 | 값 


 a| 
요청된 URL입니다
 a| 
/api/4.9/settings/multipactorauthentication을 참조하십시오



 a| 
HTTP 메소드
 a| 
가져오기



 a| 
응답 본문
 a| 
{
  "MFAConfiguration":{을 참조하십시오
    "IsGuiMFAEnabled": false,
    "ADFSConfigFilePath":"C:\\ADFS_METADATA\\abc.xml",
    "SCConfigFilePath": null,
    "IsRestApiMFAEnabled": 참,
    "IsCliMFAEnabled": false,
    "ADFSHostName":"win-adfs-sc49.winscedom2.com"
  }
}

|===

