---
permalink: install/install_snapcenter_server_linux.html 
sidebar: sidebar 
keywords: install, snapcenter software, install, linux host 
summary: SnapCenter 서버는 Linux 호스트에 설치할 수 있습니다. 
---
= Linux 호스트에 SnapCenter 서버를 설치합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버 설치 관리자 실행 파일을 실행하여 SnapCenter 서버를 설치할 수 있습니다.

.시작하기 전에
* SnapCenter를 설치할 수 있는 권한이 없는 루트가 아닌 사용자를 사용하여 SnapCenter 서버를 설치하려면 NetApp 지원 사이트에서 sudoers 체크섬 파일을 가져옵니다. Linux 버전에 따라 적절한 체크섬 파일을 사용해야 합니다.
* SUSE Linux에서 sudo 패키지를 사용할 수 없는 경우 인증 실패를 방지하기 위해 sudo 패키지를 설치합니다.
* SUSE Linux의 경우 설치 실패를 방지하기 위해 호스트 이름을 구성합니다.
* 명령을 실행하여 보안 Linux 상태를 `sestatus`확인하십시오. SELinux STATUS_가 "enabled"이고 _CURRENT MODE_가 "Enforcing"인 경우 다음을 수행합니다.
+
** 다음 명령을 실행합니다. `sudo semanage port -a -t http_port_t -p tcp <WEBAPP_EXTERNAL_PORT_>`
+
_WebApp_EXTERNAL_PORT_의 기본값은 8146입니다

** 방화벽이 포트를 차단하면 를 실행합니다 `sudo firewall-cmd --add-port <WEBAPP_EXTERNAL_PORT_>/tcp`
+
_WebApp_EXTERNAL_PORT_의 기본값은 8146입니다

** 읽기 및 쓰기 권한이 있는 디렉터리에서 다음 명령을 실행합니다.
+
*** `sudo ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
+
명령이 "수행할 작업 없음"을 반환하는 경우 SnapCenter 서버를 설치한 후 명령을 다시 실행하십시오.

*** 명령이 _my-nginx.pp_를 생성하는 경우 명령을 실행하여 정책 패키지를 활성화합니다. `sudo semodule -i my-nginx.pp`


** MySQL PID 디렉토리에 사용되는 경로는 _/var/opt/mysqld_입니다. 다음 명령을 실행하여 MySQL 설치에 대한 권한을 설정합니다.
+
*** `mkdir /var/opt/mysqld`
*** `sudo semanage fcontext -a -t mysqld_var_run_t "/var/opt/mysqld(/.*)?"`
*** `sudo restorecon -Rv /var/opt/mysqld`


** MySQL Data 디렉토리에 사용되는 경로는 _/install_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL/_입니다. 다음 명령을 실행하여 MySQL 데이터 디렉터리에 대한 권한을 설정합니다.
+
*** `mkdir -p /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`
*** `sudo semanage fcontext -a -t mysqld_db_t "/INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL(/.*)?"`
*** `sudo restorecon -Rv /INSTALL_DIR/NetApp/snapcenter/SnapManagerWeb/Repository/MySQL`






.이 작업에 대해
* SnapCenter 서버가 Linux 호스트에 설치되면 MySQL, RabbitMQ, Errlang과 같은 타사 서비스가 설치됩니다. 제거해서는 안 됩니다.
* Linux 호스트에 설치된 SnapCenter 서버는 다음을 지원하지 않습니다.
+
** 고가용성
** Windows 플러그인
** Active Directory(로컬 사용자만 지원, 루트 및 루트 이외의 사용자 모두 Creds 사용)
** SnapCenter에 로그인하기 위한 키 기반 인증


* 를 설치하는 동안. NET 런타임. 설치가 _libicu_library 의 종속성을 해결하지 못하면 다음 명령을 실행하여 install_libicu_를 설치합니다. `yum install -y libicu`
* SnapCenter 서버 설치가 _Perl_의 비가용성 때문에 실패하는 경우 다음 명령을 실행하여 install_perl_을(를) 설치하십시오. `yum install -y perl`


.단계
. 에서 _/home 디렉토리 _ 로 다음 파일을 https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab["NetApp Support 사이트"^] 다운로드합니다.
+
** SnapCenter 서버 설치 패키지 - * snapcenter-linux-server-(el8/el9/sles15).bin *
** 공개 키 파일 - * snapcenter_public_key.pub *
** 각 서명 파일 - * snapcenter-linux-server-(el8/el9/sles15).bin.sig*


. 서명 파일의 유효성을 검사합니다.
`$openssl dgst -sha256 -verify snapcenter_public_key.pub -signature <path to signature file> <path to bin file>`
. 루트가 아닌 사용자 설치의 경우 .bin 설치 프로그램과 함께 사용할 수 있는 * snapcenter_server_checksum_(el8/el9/sles15).txt*에 지정된 visudo 콘텐츠를 추가합니다.
. bin 설치 프로그램에 대한 실행 권한을 할당합니다.
`chmod +x snapcenter-linux-server-(el8/el9/sles15).bin`
. 다음 작업 중 하나를 수행하여 SnapCenter 서버를 설치합니다.
+
|===
| 수행할 작업 | 수행할 작업... 


 a| 
대화형 설치
 a| 
`./snapcenter-linux-server-(el8/el9/sles15).bin`

다음 세부 정보를 입력하라는 메시지가 표시됩니다.

** Linux 호스트 외부에서 SnapCenter Server에 액세스하는 데 사용되는 webapp 외부 포트입니다. 기본값은 8146입니다.
** SnapCenter 서버를 설치할 SnapCenter 서버 사용자입니다.
** 패키지를 설치할 설치 디렉터리입니다.




 a| 
비대화형 설치
 a| 
`sudo ./snapcenter-linux-server-(el8/el9/sles15).bin -i silent -DWEBAPP_EXTERNAL_PORT=<port> -DWEBAPP_INTERNAL_PORT=<port> -DSMCORE_PORT=<port> -DSCHEDULER_PORT=<port>  -DSNAPCENTER_SERVER_USER=<user> -DUSER_INSTALL_DIR=<dir> -DINSTALL_LOG_NAME=<filename>`

예: sudo./snapcenter_linux_server.bin -I silent-dwebappp_external_port=8146-DSNAPCENTER_server_user=root-DUSER_install_DIR=/opt-DINSTALL_LOG_NAME=InstallerLog.log

로그는 _/var/opt/snapcenter/logs_에 저장됩니다.

SnapCenter 서버 설치를 위해 전달할 매개 변수:

** DWEBAPP_EXTERNAL_PORT: Linux 호스트 외부에서 SnapCenter 서버에 액세스하는 데 사용되는 WebApp 외부 포트입니다. 기본값은 8146입니다.
** DWEBAPP_INTERNAL_PORT: Linux 호스트 내에서 SnapCenter 서버에 액세스하는 데 사용되는 WebApp 내부 포트입니다. 기본값은 8147입니다.
** DSMCORE_PORT: smcore 서비스가 실행되고 있는 SMCore 포트입니다. 기본값은 8145입니다.
** DSCHEDULER_PORT: 스케줄러 서비스가 실행되고 있는 스케줄러 포트입니다. 기본값은 8154입니다.
** DSNAPCENTER_SERVER_USER: SnapCenter 서버를 설치할 SnapCenter 서버 사용자입니다. DSNAPCENTER_SERVER_USER_의 경우, 기본값은 설치 프로그램을 실행하는 사용자입니다.
** DUSER_INSTALL_DIR: 패키지를 설치할 설치 디렉토리입니다. DUSER_INSTALL_DIR_의 경우 기본 설치 디렉토리는 _/opt_입니다.
** DINSTALL_LOG_NAME: 설치 로그를 저장할 로그 파일 이름입니다. 이 매개 변수는 선택 사항이며 지정된 경우 콘솔에 로그가 표시되지 않습니다. 이 매개 변수를 지정하지 않으면 로그가 콘솔에 표시되며 기본 로그 파일에도 저장됩니다.
** DSELINUX: _SELinux STATUS_가 "enabled"이고 _CURRENT MODE_가 "enforcing"이고 시작하기 전에 에 언급된 명령을 실행한 경우 이 매개변수를 지정하고 값을 1로 할당해야 합니다. 기본값은 0입니다.
** DUPGRADE: 기본값은 0입니다. SnapCenter 서버를 업그레이드하려면 이 매개 변수와 해당 값을 0 이외의 정수로 지정합니다.


|===


.다음 단계
* SELinux status_가 "enabled"이고 _current mode_가 "enforcing"이면 * nginx * 서비스가 시작되지 않습니다. 다음 명령을 실행해야 합니다.
+
.. 홈 디렉토리로 이동합니다.
.. 다음 명령을 실행합니다 `journalctl -x|grep nginx`.
.. WebApp 내부 포트(8147)가 수신 대기할 수 없는 경우 다음 명령을 실행합니다.
+
*** `ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
*** `semodule -i my-nginx.pp`


.. 를 실행합니다 `setsebool -P httpd_can_network_connect on`






== 설치 중에 Linux 호스트에서 활성화된 기능

SnapCenter 서버는 호스트 시스템의 문제 해결 및 유지 관리에 도움이 되는 아래 소프트웨어 패키지를 설치합니다.

* RabbitMQ입니다
* 에를랑

