---
permalink: install/learn-about-supporting-asa-r2-in-snapcenter.html 
sidebar: sidebar 
keywords: ASA r2 systems 
summary: SnapCenter 6.1은 ASA R2 시스템을 지원하므로 SAN 전용 고객의 요구 사항에 맞는 간편한 환경을 제공합니다. 
---
= SnapCenter에서 ASA R2 시스템을 지원하는 방법에 대해 알아보십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 6.1은 ASA R2 시스템을 지원하므로 SAN 전용 고객의 요구 사항에 맞는 간편한 환경을 제공합니다.

ASA R2 시스템은 단일 HA 쌍 구축에서 모든 SAN 프로토콜(iSCSI, FC 및 TCP/IP를 통한 NVMe)을 지원합니다. SCSI(iSCSI 및 FC) 프로토콜은 호스트와 스토리지 간의 모든 경로가 액티브/최적화되도록 다중 경로를 위해 대칭 액티브-액티브 아키텍처를 사용합니다. iSCSI 및 NVMe/TCP 프로토콜은 호스트와 스토리지 간의 직접 경로를 지원합니다.


NOTE: SnapCenter는 ASA R2 시스템에서 VMware VMFS(가상 머신 파일 시스템)만 지원합니다.

ASA R2 시스템에서는 정합성 보장 그룹이 포함된 스토리지 유닛을 사용합니다.

* 스토리지 유닛은 SAN 호스트에서 데이터 작업을 위해 스토리지 공간을 사용할 수 있도록 합니다. 스토리지 유닛은 SCSI 호스트용 LUN 또는 NVMe 호스트용 NVMe 네임스페이스를 가리킵니다.
* 정합성 보장 그룹은 단일 유닛으로 관리되는 스토리지 유닛의 모음입니다.


ASA R2 시스템은 스토리지 유닛 및 정합성 보장 그룹을 사용하여 스토리지 관리 및 데이터 보호를 간소화합니다. 예를 들어 정합성 보장 그룹에 10개의 스토리지 유닛으로 구성된 데이터베이스가 있고 전체 데이터베이스를 백업해야 한다고 가정합니다. 각 스토리지 유닛을 개별적으로 백업하는 대신 정합성 보장 그룹을 백업하여 전체 데이터베이스를 보호할 수 있습니다.

https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2 시스템에 대해 자세히 알아보십시오"]..



== ASA R2 시스템용 SnapCenter 6.1에서 지원되는 기능

ASA R2 스토리지 시스템을 사용하는 경우 SnapCenter를 사용하면 SnapCenter에서 지원하는 모든 애플리케이션에서 다음 작업을 수행할 수 있습니다.

* VMDK를 통해 애플리케이션의 기본 백업을 생성합니다
* 정합성 보장 그룹 스냅샷을 보조 스토리지 시스템으로 전송합니다
* 백업 복구 및 대체 위치에서 복구
+
** VMware vMotion을 사용하여 운영 스토리지와 보조 스토리지 모두에서 데이터 이동 없이 복구
** 운영 스토리지와 2차 스토리지 모두에서 복원 및 복제


* 백업 클론 생성 및 대체 위치에 클론 복제




== ASA R2 시스템용 SnapCenter 6.1에서 지원되지 않는 것은 무엇입니까

* RDM(Raw Device Mapping)
* Oracle용 애플리케이션 볼륨
* SAP HANA NDV
* LockVault 를 클릭합니다
* 변조 방지 스냅샷
* Flex 그룹
* 계층적 일관성 그룹
* ONTAP 9.x에서 ASA R2 시스템으로 마이그레이션
* 스냅샷 이름 바꾸기
* SnapCenter에서는 SQL 플러그인 호스트의 로그 디렉토리에 대한 보조 프로비저닝을 지원하지 않습니다. ONTAP CLI 또는 System Manager를 사용하여 수동으로 구성해야 합니다.

