---
permalink: install/reference_connection_and_port_requirements.html 
sidebar: sidebar 
keywords: ports, port requirements 
summary: SnapCenter 서버 및 응용 프로그램 또는 데이터베이스 플러그인을 설치하기 전에 연결 및 포트 요구 사항이 충족되었는지 확인해야 합니다. 
---
= 연결 및 포트 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버 및 응용 프로그램 또는 데이터베이스 플러그인을 설치하기 전에 연결 및 포트 요구 사항이 충족되었는지 확인해야 합니다.

* 응용 프로그램이 포트를 공유할 수 없습니다.
+
각 포트는 해당 애플리케이션 전용으로 사용되어야 합니다.

* 사용자 지정 가능한 포트의 경우 기본 포트를 사용하지 않으려는 경우 설치 중에 사용자 지정 포트를 선택할 수 있습니다.
+
설치 후 호스트 수정 마법사를 사용하여 플러그인 포트를 변경할 수 있습니다.

* 고정 포트의 경우 기본 포트 번호를 그대로 사용해야 합니다.
* 방화벽
+
** 방화벽, 프록시 또는 기타 네트워크 장치가 연결을 방해해서는 안 됩니다.
** SnapCenter를 설치할 때 사용자 지정 포트를 지정하는 경우 SnapCenter 플러그인 로더의 해당 포트에 대한 방화벽 규칙을 플러그인 호스트에 추가해야 합니다.




다음 표에는 여러 포트와 해당 기본값이 나와 있습니다.

|===
| 포트 이름 | 포트 번호 | 프로토콜 | 방향 | 설명 


 a| 
SnapCenter 포트
 a| 
8146
 a| 
HTTPS
 a| 
양방향
 a| 
이 포트는 SnapCenter 클라이언트(SnapCenter 사용자)와 SnapCenter 서버 간의 통신에 사용되며 플러그인 호스트에서 SnapCenter 서버로의 통신에도 사용됩니다.

포트 번호를 사용자 지정할 수 있습니다.



 a| 
SnapCenter SMCore 통신 포트입니다
 a| 
8145
 a| 
HTTPS
 a| 
양방향
 a| 
이 포트는 SnapCenter 서버와 SnapCenter 플러그인이 설치된 호스트 간의 통신에 사용됩니다.

포트 번호를 사용자 지정할 수 있습니다.



 a| 
스케줄러 서비스 포트
 a| 
8154
 a| 
HTTPS
 a| 
 a| 
이 포트는 SnapCenter 서버 호스트 내의 모든 관리형 플러그인에 대한 SnapCenter 스케줄러 워크플로우를 중앙 집중식으로 조정하는 데 사용됩니다.

포트 번호를 사용자 지정할 수 있습니다.



 a| 
RabbitMQ 포트
 a| 
5672
 a| 
TCP
 a| 
 a| 
RabbitMQ가 수신 대기하는 기본 포트이며 스케줄러 서비스와 SnapCenter 간의 게시자-가입자 모델 통신에 사용됩니다.



 a| 
MySQL 포트
 a| 
3306
 a| 
HTTPS
 a| 
 a| 
이 포트는 SnapCenter 리포지토리 데이터베이스와 통신하는 데 사용됩니다. SnapCenter 서버에서 MySQL 서버로의 보안 연결을 만들 수 있습니다. link:../install/concept_configure_secured_mysql_connections_with_snapcenter_server.html["자세한 정보"]



 a| 
Windows 플러그인 호스트
 a| 
135, 445
 a| 
TCP
 a| 
 a| 
이 포트는 SnapCenter 서버와 플러그인이 설치되고 있는 호스트 간의 통신에 사용됩니다. Microsoft에서 지정한 추가 동적 포트 범위도 열려 있어야 합니다.



 a| 
Linux 또는 AIX 플러그인 호스트
 a| 
22
 a| 
SSH를 클릭합니다
 a| 
단방향
 a| 
이 포트는 서버에서 클라이언트 호스트로 초기화된 SnapCenter 서버와 호스트 간의 통신에 사용됩니다.



 a| 
Windows, Linux 또는 AIX용 SnapCenter 플러그인 패키지
 a| 
8145
 a| 
HTTPS
 a| 
양방향
 a| 
이 포트는 플러그인 패키지가 설치된 SMCore와 호스트 간의 통신에 사용됩니다. 사용자 정의 가능.

포트 번호를 사용자 지정할 수 있습니다.



 a| 
Oracle 데이터베이스용 SnapCenter 플러그인
 a| 
27216
 a| 
 a| 
 a| 
기본 JDBC 포트는 Oracle용 플러그인에서 Oracle 데이터베이스에 연결하는 데 사용됩니다.



 a| 
Exchange 데이터베이스용 SnapCenter 플러그인
 a| 
909
 a| 
 a| 
 a| 
기본 네트입니다. TCP 포트는 Windows용 플러그인에서 Exchange VSS 콜백에 연결하는 데 사용됩니다.



 a| 
SnapCenter에 대해 NetApp 지원 플러그인
 a| 
9090
 a| 
HTTPS
 a| 
 a| 
사용자 지정 플러그인 호스트에서만 사용되는 내부 포트입니다. 방화벽 예외가 필요하지 않습니다.

SnapCenter 서버와 사용자 지정 플러그인 간의 통신은 포트 8145를 통해 라우팅됩니다.



 a| 
ONTAP 클러스터 또는 SVM 통신 포트
 a| 
* 443(HTTPS)
* 80(HTTP)

 a| 
* HTTPS
* HTTP

 a| 
양방향
 a| 
이 포트는 SnapCenter Server를 실행하는 호스트와 SVM 간 통신에 SAL(Storage Abstraction Layer)에서 사용됩니다. 이 포트는 현재 SnapCenter 플러그인 호스트와 SVM 간 통신에 SnapCenter의 SAL에서 사용됩니다.



 a| 
SAP HANA 데이터베이스용 SnapCenter 플러그인
 a| 
* 3instance_number13를 참조하십시오
* 3instance_number15를 참조하십시오

 a| 
* HTTPS
* HTTP

 a| 
양방향
 a| 
MDC(멀티테넌트 데이터베이스 컨테이너) 단일 테넌트의 경우 포트 번호는 13으로 끝나며 MDC가 아닌 경우 포트 번호는 15로 끝납니다.

포트 번호를 사용자 지정할 수 있습니다.



 a| 
PostgreSQL용 SnapCenter 플러그인
 a| 
5432
 a| 
 a| 
 a| 
이 포트는 PostgreSQL용 플러그인에서 PostgreSQL 클러스터로의 통신에 사용되는 기본 PostgreSQL 포트입니다.

포트 번호를 사용자 지정할 수 있습니다.

|===
포트 세부 정보를 수정하려면 을 참조하십시오 link:../admin/concept_manage_hosts.html#modify-plug-in-hosts["플러그인 호스트를 수정합니다"].
