---
permalink: install/reference_space_and_sizing_requirements.html 
sidebar: sidebar 
keywords: SnapCenter 
summary: SnapCenter 서버를 설치하기 전에 공간 및 크기 조정 요구 사항을 숙지해야 합니다. 사용 가능한 시스템 및 보안 업데이트도 적용해야 합니다. 
---
= 요구사항을 충족해야 합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버를 설치하기 전에 공간 및 크기 조정 요구 사항을 숙지해야 합니다. 사용 가능한 시스템 및 보안 업데이트도 적용해야 합니다.

|===
| 항목 | Windows 호스트 요구 사항 | Linux 호스트 요구 사항 


 a| 
운영 체제
 a| 
Microsoft Windows

운영 체제의 영어, 독일어, 일본어 및 중국어 간체 버전만 지원됩니다.

지원되는 버전에 대한 최신 정보는 를 참조하십시오
https://imt.netapp.com/matrix/imt.jsp?components=116859;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].
 a| 
* Red Hat Enterprise Linux(RHEL) 8 및 9
* SUSE Linux Enterprise Server(SLES) 15


지원되는 버전에 대한 최신 정보는 를 참조하십시오
https://imt.netapp.com/matrix/imt.jsp?components=116859;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].



 a| 
최소 CPU 수입니다
 a| 
4코어
 a| 
4코어



 a| 
최소 RAM
 a| 
8GB


NOTE: MySQL Server 버퍼 풀은 전체 RAM의 20%를 사용합니다.
 a| 
8GB



 a| 
SnapCenter 서버 소프트웨어 및 로그의 최소 하드 드라이브 공간
 a| 
7 GB


NOTE: SnapCenter 서버가 설치된 동일한 드라이브에 SnapCenter 저장소가 있는 경우 15 GB를 사용하는 것이 좋습니다.
 a| 
15 GB



 a| 
SnapCenter 리포지토리에 대한 최소 하드 드라이브 공간입니다
 a| 
8GB


NOTE: 참고: SnapCenter 저장소가 설치된 동일한 드라이브에 SnapCenter 서버가 있는 경우 15 GB를 사용하는 것이 좋습니다.
 a| 
해당 없음



 a| 
필요한 소프트웨어 패키지
 a| 
* Microsoft .NET Framework 4.7.2 이상
* ASP를 참조하십시오. NET 코어 호스팅 번들(8.0.5 이상)
* PowerShell 7.4.2 이상


NET 관련 문제 해결에 대한 자세한 내용은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22["인터넷에 연결되지 않은 기존 시스템의 경우 SnapCenter 업그레이드 또는 설치가 실패합니다"^].
 a| 
* ASP를 참조하십시오. NET Core Runtime 8.0.5 이상
* PowerShell 7.4.2 이상
* Nginx는 역방향 프록시로 사용할 수 있는 웹 서버입니다
* PAM-devel의 약어입니다
+
PAM(Pluggable Authentication Modules)은 시스템 관리자가 인증을 수행하는 프로그램을 다시 컴파일하지 않고도 인증 정책을 설정할 수 있는 시스템 보안 도구입니다.



|===