---
permalink: install/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: 지원되는 스토리지 시스템, 애플리케이션 및 데이터베이스를 알고 있어야 합니다. 
---
= 지원되는 스토리지 시스템 및 애플리케이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
지원되는 스토리지 시스템, 애플리케이션 및 데이터베이스를 알아야 합니다.

* SnapCenter는 데이터를 보호하기 위해 ONTAP 9.12.1 이상을 지원합니다.
* SnapCenter 6.1은 ONTAP 9.16.1을 실행하는 NetApp ASA R2 시스템(ASA A1K, ASA A70, ASA A90)을 지원합니다.
+
ASA R2 시스템은 All-Flash 플랫폼을 기반으로 구축된 SAN 전용 환경을 위한 하드웨어 및 소프트웨어 통합 솔루션을 제공합니다. ASA R2 시스템은 스토리지 계층 구현 시 다른 ONTAP 시스템(ASA, AFF 및 FAS)과 다르며 지원되는 프로토콜 및 ONTAP 성격 구현 시 서로 다릅니다.

+
ASA R2 시스템에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/asa-r2/index.html["ASA r2 설명서"^]참조하십시오.

* SnapCenter는 ONTAP 소프트웨어 4.5 P1 패치 릴리즈로부터 데이터를 보호하기 위해 NetApp SnapCenter용 Amazon FSx를 지원합니다.
+
NetApp ONTAP용 Amazon FSx를 사용하는 경우 데이터 보호 작업을 수행하기 위해 SnapCenter 서버 호스트 플러그인이 4.5 P1 이상으로 업그레이드되었는지 확인합니다.

+
TCP(Transport Control Protocol)를 통한 비휘발성 메모리 익스프레스(NVMe)를 지원합니다.

+
NetApp ONTAP용 Amazon FSx에 대한 자세한 내용은 를 참조하십시오 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx 문서"^].

* SnapCenter는 다양한 애플리케이션 및 데이터베이스의 보호를 지원합니다.
+
지원되는 응용 프로그램 및 데이터베이스에 대한 자세한 내용은 을 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].

* SnapCenter 4.9 P1 이상은 AWS(Amazon Web Services) 기반 VMware Cloud 환경에서 Oracle 및 Microsoft SQL 워크로드 보호를 지원합니다.
+
자세한 내용은 을 참조하십시오 https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["AWS SDDC 환경의 VMware Cloud에서 NetApp SnapCenter를 사용하여 Oracle, MS SQL 워크로드를 보호하십시오"].


