---
permalink: install/task_log_in_to_snapcenter.html 
sidebar: sidebar 
keywords: log in, logging, SnapCenter UI, modify timeout, GUI session timeout, disbale SSL 3.0, SSL 3.0, security 
summary: 'SnapCenter는 역할 기반 액세스 제어(RBAC)를 지원합니다. SnapCenter 관리자는 SnapCenter RBAC를 통해 역할 및 리소스를 작업 그룹 또는 Active Directory의 사용자 또는 Active Directory의 그룹에 할당합니다. 이제 RBAC 사용자는 할당된 역할을 사용하여 SnapCenter에 로그인할 수 있습니다.' 
---
= SnapCenter에 로그인합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter는 역할 기반 액세스 제어(RBAC)를 지원합니다. SnapCenter 관리자는 SnapCenter RBAC를 통해 역할 및 리소스를 작업 그룹 또는 Active Directory의 사용자 또는 Active Directory의 그룹에 할당합니다. 이제 RBAC 사용자는 할당된 역할을 사용하여 SnapCenter에 로그인할 수 있습니다.

* 필요한 것 *

* Windows Server Manager에서 WAS(Windows Process Activation Service)를 활성화해야 합니다.
* Internet Explorer를 브라우저로 사용하여 SnapCenter 서버에 로그인하려면 Internet Explorer의 보호 모드가 비활성화되어 있어야 합니다.


* 이 작업에 대한 정보 *

설치 중에 SnapCenter 서버 설치 마법사가 바로 가기를 만들어 SnapCenter가 설치된 호스트의 바탕 화면과 시작 메뉴에 배치합니다. 또한 설치 완료 시 설치 마법사는 설치 중에 제공한 정보를 기반으로 SnapCenter URL을 표시하며, 원격 시스템에서 로그인하려는 경우 이 URL을 복사할 수 있습니다.


IMPORTANT: 웹 브라우저에 여러 개의 탭이 열려 있는 경우 SnapCenter 브라우저 탭을 닫아도 SnapCenter에서 로그아웃되지 않습니다. SnapCenter와의 연결을 종료하려면 * 로그아웃 * 단추를 클릭하거나 전체 웹 브라우저를 닫아 SnapCenter에서 로그아웃해야 합니다.

|===


| *모범 사례:* 보안상의 이유로 브라우저에서 SnapCenter 암호를 저장하지 않는 것이 좋습니다. 
|===
기본 GUI URL은 SnapCenter 서버가 설치된 서버의 기본 포트 8146에 대한 보안 연결입니다(_\https://server:8146_). SnapCenter 설치 중에 다른 서버 포트를 제공한 경우 해당 포트가 대신 사용됩니다.

HA(고가용성) 구축을 위해서는 가상 클러스터 IP_\https://Virtual_Cluster_IP_or_FQDN:8146_ 를 사용하여 SnapCenter에 액세스해야 합니다. Internet Explorer(IE)에서 _\https://Virtual_Cluster_IP_or_FQDN:8146_ 으로 이동할 때 SnapCenter UI가 표시되지 않으면 각 플러그인 호스트의 IE에 가상 클러스터 IP 주소 또는 FQDN을 신뢰할 수 있는 사이트로 추가해야 합니다. 그렇지 않으면 각 플러그인 호스트에서 IE 고급 보안을 해제해야 합니다. 자세한 내용은 을 참조하십시오 https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Unable_to_access_cluster_IP_address_from_outside_network["외부 네트워크에서 클러스터 IP 주소에 액세스할 수 없습니다"^].

SnapCenter GUI 사용 외에도 PowerShell cmdlet을 사용하여 스크립트를 생성하여 구성, 백업 및 복원 작업을 수행할 수 있습니다. 일부 cmdlet은 SnapCenter 릴리즈마다 변경될 수 있습니다. 를 클릭합니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2880726["SnapCenter 소프트웨어 cmdlet 참조 가이드"^] 세부 정보가 있습니다.


NOTE: SnapCenter에 처음 로그인하는 경우 설치 프로세스 중에 제공한 자격 증명을 사용하여 로그인해야 합니다.

* 단계 *

. 로컬 호스트 데스크톱에 있는 바로 가기나 설치 마지막에 제공된 URL 또는 SnapCenter 관리자가 제공한 URL에서 SnapCenter를 실행합니다.
. 사용자 자격 증명을 입력합니다.
+
|===
| 다음을 지정하려면... | 다음 형식 중 하나를 사용합니다... 


 a| 
도메인 관리자
 a| 
** NetBIOS\사용자 이름입니다
** 사용자 이름@UPN 접미사
+
예: \username@netapp.com

** 도메인 FQDN\사용자 이름입니다




 a| 
로컬 관리자
 a| 
사용자 이름

|===
. 둘 이상의 역할이 할당된 경우 역할 상자에서 이 로그인 세션에 사용할 역할을 선택합니다.
+
로그인한 후 현재 사용자 및 관련 역할이 SnapCenter의 오른쪽 상단에 표시됩니다.



* 결과 *

대시보드 페이지가 표시됩니다.

사이트에 연결할 수 없다는 오류로 인해 로깅이 실패하는 경우 SSL 인증서를 SnapCenter에 매핑해야 합니다. https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Protection_and_Security%2FSnapCenter%2FSnapCenter_will_not_open_with_error_%2522This_site_can%2527t_be_reached%2522["자세한 정보"^]

* 완료 후 *

SnapCenter 서버에 RBAC 사용자로 처음으로 로그인한 후 리소스 목록을 새로 고칩니다.

SnapCenter에서 지원할 신뢰할 수 없는 Active Directory 도메인이 있는 경우 신뢰할 수 없는 도메인의 사용자에 대한 역할을 구성하기 전에 해당 도메인을 SnapCenter에 등록해야 합니다. link:../install/task_register_untrusted_active_directory_domains.html["자세한 정보"^]



== SnapCenter 기본 GUI 세션 시간 초과를 수정합니다

SnapCenter GUI 세션 제한 시간을 기본 제한 시간 20분 이하로 수정할 수 있습니다.

SnapCenter는 기본 15분 동안 비활성 상태가 지속되면 GUI 세션에서 5분 후에 로그아웃된다는 경고 메시지를 보안 기능으로 표시합니다. 기본적으로 SnapCenter는 20분 동안 비활성 상태가 지속되면 GUI 세션에서 로그아웃하고 다시 로그인해야 합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 설정 * > * 글로벌 설정 * 을 클릭합니다.
. 전역 설정 페이지에서 * 구성 설정 * 을 클릭합니다.
. Session Timeout(세션 시간 초과) 필드에 새 세션 시간 제한을 분 단위로 입력한 다음 * Save * (저장 *)를 클릭합니다.




== SSL 3.0을 비활성화하여 SnapCenter 웹 서버를 보호합니다

보안을 위해 SnapCenter 웹 서버에서 SSL(Secure Socket Layer) 3.0 프로토콜을 사용하는 경우 Microsoft IIS에서 SSL(Secure Socket Layer) 3.0 프로토콜을 비활성화해야 합니다.

SSL 3.0 프로토콜에 결함이 있어 공격자가 연결 장애를 일으키거나 중간자 공격을 수행하여 웹 사이트와 방문자 사이의 암호화 트래픽을 관찰할 수 있습니다.

* 단계 *

. SnapCenter 웹 서버 호스트에서 레지스트리 편집기를 시작하려면 * 시작 * > * 실행 * 을 클릭하고 regedit를 입력합니다.
. 레지스트리 편집기에서 HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SChannel\Protocols\SSL 3.0\로 이동합니다.
+
** 서버 키가 이미 있는 경우:
+
... 사용 DWORD를 선택한 다음 * 편집 * > * 수정 * 을 클릭합니다.
... 값을 0으로 변경한 다음 * 확인 * 을 클릭합니다.


** 서버 키가 없는 경우:
+
... 편집 * > * 새로 만들기 * > * 키 * 를 클릭한 다음 키 서버의 이름을 지정합니다.
... 새 서버 키를 선택한 상태에서 * 편집 * > * 새로 만들기 * > * DWORD * 를 클릭합니다.
... 새 DWORD Enabled의 이름을 지정한 다음 0을 값으로 입력합니다.




. 레지스트리 편집기를 닫습니다.

