---
permalink: install/task_create_and_manage_disks.html 
sidebar: sidebar 
keywords: disks, create, manage, clustered disks, view 
summary: Windows 호스트는 스토리지 시스템의 LUN을 가상 디스크로 인식합니다. SnapCenter를 사용하여 FC 연결 또는 iSCSI 연결 LUN을 생성하고 구성할 수 있습니다. 
---
= 디스크를 생성하고 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows 호스트는 스토리지 시스템의 LUN을 가상 디스크로 인식합니다. SnapCenter를 사용하여 FC 연결 또는 iSCSI 연결 LUN을 생성하고 구성할 수 있습니다.

* SnapCenter는 기본 디스크만 지원합니다. 동적 디스크는 지원되지 않습니다.
* GPT의 경우 하나의 데이터 파티션 및 MBR의 경우 NTFS 또는 CSVFS로 포맷된 하나의 볼륨이 있고 하나의 마운트 경로가 있는 하나의 기본 파티션이 허용됩니다.
* 지원되는 파티션 스타일: GPT, MBR; VMware UEFI VM에서는 iSCSI 디스크만 지원됩니다



NOTE: SnapCenter에서는 디스크 이름을 변경할 수 없습니다. SnapCenter에서 관리하는 디스크의 이름을 바꾸면 SnapCenter 작업이 실패합니다.



== 호스트의 디스크를 봅니다

SnapCenter로 관리하는 각 Windows 호스트에서 디스크를 볼 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 디스크 * 를 클릭합니다.
. 호스트 * 드롭다운 목록에서 호스트를 선택합니다.
+
디스크가 나열됩니다.





== 클러스터링된 디스크를 봅니다

SnapCenter로 관리하는 클러스터에서 클러스터링된 디스크를 볼 수 있습니다. 클러스터 디스크는 호스트 드롭다운에서 클러스터를 선택한 경우에만 표시됩니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 디스크 * 를 클릭합니다.
. 호스트 * 드롭다운 목록에서 클러스터를 선택합니다.
+
디스크가 나열됩니다.





== FC 연결 또는 iSCSI 연결 LUN 또는 디스크를 생성합니다

Windows 호스트는 스토리지 시스템의 LUN을 가상 디스크로 인식합니다. SnapCenter를 사용하여 FC 연결 또는 iSCSI 연결 LUN을 생성하고 구성할 수 있습니다.

SnapCenter 외부에서 디스크를 생성하고 포맷하려면 NTFS 및 CVFS 파일 시스템만 지원됩니다.

* 필요한 것 *

* 스토리지 시스템에서 LUN에 대한 볼륨을 생성해야 합니다.
+
볼륨에는 LUN만 있어야 하며 SnapCenter를 사용하여 생성한 LUN만 포함해야 합니다.

+

NOTE: 클론이 이미 분할되어 있지 않으면 SnapCenter에서 생성한 클론 볼륨에 LUN을 생성할 수 없습니다.

* 스토리지 시스템에서 FC 또는 iSCSI 서비스를 시작해야 합니다.
* iSCSI를 사용하는 경우 스토리지 시스템과 iSCSI 세션을 설정해야 합니다.
* Windows용 SnapCenter 플러그인 패키지는 디스크를 생성하는 호스트에만 설치해야 합니다.


* 이 작업에 대한 정보 *

* Windows Server 페일오버 클러스터의 호스트에서 LUN을 공유하지 않는 한 LUN을 둘 이상의 호스트에 연결할 수 없습니다.
* CSV(Cluster Shared Volumes)를 사용하는 Windows Server 페일오버 클러스터의 호스트가 LUN을 공유하는 경우 클러스터 그룹을 소유하는 호스트에 디스크를 생성해야 합니다.


* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 디스크 * 를 클릭합니다.
. 호스트 * 드롭다운 목록에서 호스트를 선택합니다.
. 새로 만들기 * 를 클릭합니다.
+
디스크 생성 마법사가 열립니다.

. LUN 이름 페이지에서 LUN을 확인합니다.
+
|===
| 이 필드에서... | 수행할 작업... 


 a| 
스토리지 시스템
 a| 
LUN의 SVM을 선택합니다.



 a| 
LUN 경로입니다
 a| 
찾아보기 * 를 클릭하여 LUN이 포함된 폴더의 전체 경로를 선택합니다.



 a| 
LUN 이름입니다
 a| 
LUN의 이름을 입력합니다.



 a| 
클러스터 크기
 a| 
클러스터의 LUN 블록 할당 크기를 선택합니다.

클러스터 크기는 운영 체제 및 애플리케이션에 따라 다릅니다.



 a| 
LUN 레이블입니다
 a| 
선택적으로 LUN에 대한 설명 텍스트를 입력합니다.

|===
. 디스크 유형 페이지에서 디스크 유형을 선택합니다.
+
|===
| 선택... | 만약... 


 a| 
전용 디스크
 a| 
LUN은 하나의 호스트만 액세스할 수 있습니다.

리소스 그룹 * 필드는 무시하십시오.



 a| 
공유 디스크
 a| 
LUN은 Windows Server 페일오버 클러스터의 호스트에서 공유됩니다.

리소스 그룹 * 필드에 클러스터 리소스 그룹의 이름을 입력합니다. 페일오버 클러스터의 한 호스트에만 디스크를 생성해야 합니다.



 a| 
CSV(클러스터 공유 볼륨)
 a| 
LUN은 CSV를 사용하는 Windows Server 페일오버 클러스터의 호스트에서 공유됩니다.

리소스 그룹 * 필드에 클러스터 리소스 그룹의 이름을 입력합니다. 디스크를 생성할 호스트가 클러스터 그룹의 소유자인지 확인합니다.

|===
. 드라이브 속성 페이지에서 드라이브 속성을 지정합니다.
+
|===
| 속성 | 설명 


 a| 
마운트 지점을 자동으로 할당합니다
 a| 
SnapCenter는 시스템 드라이브에 따라 볼륨 마운트 지점을 자동으로 할당합니다.

예를 들어, 시스템 드라이브가 C:인 경우 자동 할당은 C: 드라이브(C:\scmnpt\) 아래에 볼륨 마운트 지점을 생성합니다. 공유 디스크에는 자동 할당이 지원되지 않습니다.



 a| 
드라이브 문자를 할당합니다
 a| 
인접한 드롭다운 목록에서 선택한 드라이브에 디스크를 마운트합니다.



 a| 
볼륨 마운트 지점을 사용합니다
 a| 
인접한 필드에 지정한 드라이브 경로에 디스크를 마운트합니다.

볼륨 마운트 지점의 루트는 디스크를 생성하는 호스트가 소유해야 합니다.



 a| 
드라이브 문자 또는 볼륨 마운트 지점을 할당하지 마십시오
 a| 
Windows에서 디스크를 수동으로 마운트하려면 이 옵션을 선택합니다.



 a| 
LUN 크기입니다
 a| 
최소 150MB의 LUN 크기를 지정합니다.

인접 드롭다운 목록에서 MB, GB 또는 TB를 선택합니다.



 a| 
이 LUN을 호스팅하는 볼륨에 씬 프로비저닝을 사용합니다
 a| 
씬 LUN을 프로비저닝합니다.

씬 프로비저닝은 필요한 만큼의 스토리지 공간만 한 번에 할당하므로 LUN이 최대 가용 용량까지 효율적으로 성장할 수 있습니다.

필요한 모든 LUN 스토리지를 수용할 수 있는 충분한 공간이 볼륨에 있는지 확인하십시오.



 a| 
파티션 유형을 선택합니다
 a| 
GUID 파티션 테이블의 GPT 파티션 또는 마스터 부트 레코드의 MBR 파티션을 선택합니다.

MBR 파티션은 Windows Server 장애 조치 클러스터에서 정렬 불량 문제를 일으킬 수 있습니다.


NOTE: UEFI(Unified Extensible Firmware Interface) 파티션 디스크는 지원되지 않습니다.

|===
. LUN 매핑 페이지에서 호스트의 iSCSI 또는 FC 이니시에이터를 선택합니다.
+
|===
| 이 필드에서... | 수행할 작업... 


 a| 
호스트
 a| 
클러스터 그룹 이름을 두 번 클릭하여 클러스터에 속한 호스트를 보여 주는 드롭다운 목록을 표시한 다음, 이니시에이터의 호스트를 선택합니다.

이 필드는 LUN이 Windows Server 페일오버 클러스터의 호스트에서 공유되는 경우에만 표시됩니다.



 a| 
호스트 이니시에이터를 선택합니다
 a| 
파이버 채널 * 또는 * iSCSI * 를 선택한 다음 호스트에서 이니시에이터를 선택합니다.

다중 경로 I/O(MPIO)와 함께 FC를 사용하는 경우 여러 FC 이니시에이터를 선택할 수 있습니다.

|===
. 그룹 유형 페이지에서 기존 igroup을 LUN에 매핑할지 또는 새 igroup을 생성할지를 지정합니다.
+
|===
| 선택... | 만약... 


 a| 
선택한 이니시에이터에 대해 새 igroup을 생성합니다
 a| 
선택한 이니시에이터에 대해 새 igroup을 생성하려고 합니다.



 a| 
기존 igroup을 선택하거나 선택한 이니시에이터에 대한 새 igroup을 지정합니다
 a| 
선택한 이니시에이터에 대해 기존 igroup을 지정하거나 지정한 이름의 새 igroup을 생성합니다.

igroup 이름 * 필드에 igroup 이름을 입력합니다. 기존 igroup 이름의 처음 몇 글자를 입력하여 필드를 자동으로 작성합니다.

|===
. 요약 페이지에서 선택 사항을 검토한 다음 * 마침 * 을 클릭합니다.
+
SnapCenter는 LUN을 생성하여 호스트의 지정된 드라이브 또는 드라이브 경로에 연결합니다.





== 디스크 크기를 조정합니다

스토리지 시스템 요구사항의 변화에 따라 디스크 크기를 늘리거나 줄일 수 있습니다.

* 이 작업에 대한 정보 *

* 씬 프로비저닝된 LUN의 경우 ONTAP LUN 지오메트리 크기가 최대 크기로 표시됩니다.
* 일반 프로비저닝된 LUN의 경우 확장 가능한 크기(볼륨에서 사용 가능한 크기)가 최대 크기로 표시됩니다.
* MBR 스타일 파티션이 있는 LUN의 크기는 2TB로 제한됩니다.
* GPT 스타일 파티션이 있는 LUN의 스토리지 시스템 크기는 16TB로 제한됩니다.
* LUN 크기를 조정하기 전에 스냅샷 복사본을 만드는 것이 좋습니다.
* LUN의 크기를 변경하기 전에 생성된 스냅샷 복사본에서 LUN을 복원해야 하는 경우 SnapCenter에서는 자동으로 LUN 크기를 스냅샷 복사본 크기로 조정합니다.
+
복원 작업 후 크기 조정된 후 LUN에 추가된 데이터는 크기 조정된 후에 만들어진 스냅샷 복사본에서 복원되어야 합니다.



* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 디스크 * 를 클릭합니다.
. 호스트 드롭다운 목록에서 호스트를 선택합니다.
+
디스크가 나열됩니다.

. 크기를 조정할 디스크를 선택한 다음 * 크기 조정 * 을 클릭합니다.
. 디스크 크기 조정 대화 상자에서 슬라이더 도구를 사용하여 디스크의 새 크기를 지정하거나 크기 필드에 새 크기를 입력합니다.
+

NOTE: 크기를 수동으로 입력하는 경우 축소 또는 확장 단추가 적절하게 활성화되기 전에 크기 필드 바깥쪽을 클릭해야 합니다. 또한 MB, GB 또는 TB를 클릭하여 측정 단위를 지정해야 합니다.

. 입력한 내용에 만족하면 * 축소 * 또는 * 확장 * 을 클릭합니다.
+
SnapCenter는 디스크의 크기를 조정합니다.





== 디스크를 연결합니다

디스크 연결 마법사를 사용하여 기존 LUN을 호스트에 연결하거나 연결이 끊긴 LUN을 다시 연결할 수 있습니다.

* 필요한 것 *

* 스토리지 시스템에서 FC 또는 iSCSI 서비스를 시작해야 합니다.
* iSCSI를 사용하는 경우 스토리지 시스템과 iSCSI 세션을 설정해야 합니다.
* Windows Server 페일오버 클러스터의 호스트에서 LUN을 공유하지 않는 한 LUN을 둘 이상의 호스트에 연결할 수 없습니다.
* CSV(Cluster Shared Volumes)를 사용하는 Windows Server 페일오버 클러스터의 호스트가 LUN을 공유하는 경우 클러스터 그룹을 소유하는 호스트의 디스크를 연결해야 합니다.
* Windows용 플러그인은 디스크를 연결하는 호스트에만 설치해야 합니다.


* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 디스크 * 를 클릭합니다.
. 호스트 * 드롭다운 목록에서 호스트를 선택합니다.
. 연결 * 을 클릭합니다.
+
디스크 연결 마법사가 열립니다.

. LUN 이름 페이지에서 접속할 LUN을 확인합니다.
+
|===
| 이 필드에서... | 수행할 작업... 


 a| 
스토리지 시스템
 a| 
LUN의 SVM을 선택합니다.



 a| 
LUN 경로입니다
 a| 
찾아보기 * 를 클릭하여 LUN이 포함된 볼륨의 전체 경로를 선택합니다.



 a| 
LUN 이름입니다
 a| 
LUN의 이름을 입력합니다.



 a| 
클러스터 크기
 a| 
클러스터의 LUN 블록 할당 크기를 선택합니다.

클러스터 크기는 운영 체제 및 애플리케이션에 따라 다릅니다.



 a| 
LUN 레이블입니다
 a| 
선택적으로 LUN에 대한 설명 텍스트를 입력합니다.

|===
. 디스크 유형 페이지에서 디스크 유형을 선택합니다.
+
|===
| 선택... | 만약... 


 a| 
전용 디스크
 a| 
LUN은 하나의 호스트만 액세스할 수 있습니다.



 a| 
공유 디스크
 a| 
LUN은 Windows Server 페일오버 클러스터의 호스트에서 공유됩니다.

페일오버 클러스터의 한 호스트에만 디스크를 연결해야 합니다.



 a| 
CSV(클러스터 공유 볼륨)
 a| 
LUN은 CSV를 사용하는 Windows Server 페일오버 클러스터의 호스트에서 공유됩니다.

디스크에 접속할 호스트가 클러스터 그룹의 소유자인지 확인합니다.

|===
. 드라이브 속성 페이지에서 드라이브 속성을 지정합니다.
+
|===
| 속성 | 설명 


 a| 
자동 할당
 a| 
SnapCenter에서 시스템 드라이브에 따라 볼륨 마운트 지점을 자동으로 할당합니다.

예를 들어, 시스템 드라이브가 C:인 경우 자동 할당 속성은 C: 드라이브(C:\scmnpt\) 아래에 볼륨 마운트 지점을 만듭니다. 공유 디스크에는 자동 할당 속성이 지원되지 않습니다.



 a| 
드라이브 문자를 할당합니다
 a| 
인접 드롭다운 목록에서 선택한 드라이브에 디스크를 마운트합니다.



 a| 
볼륨 마운트 지점을 사용합니다
 a| 
인접 필드에 지정한 드라이브 경로에 디스크를 마운트합니다.

볼륨 마운트 지점의 루트는 디스크를 생성하는 호스트가 소유해야 합니다.



 a| 
드라이브 문자 또는 볼륨 마운트 지점을 할당하지 마십시오
 a| 
Windows에서 디스크를 수동으로 마운트하려면 이 옵션을 선택합니다.

|===
. LUN 매핑 페이지에서 호스트의 iSCSI 또는 FC 이니시에이터를 선택합니다.
+
|===
| 이 필드에서... | 수행할 작업... 


 a| 
호스트
 a| 
클러스터 그룹 이름을 두 번 클릭하여 클러스터에 속한 호스트를 보여 주는 드롭다운 목록을 표시한 다음, 이니시에이터의 호스트를 선택합니다.

이 필드는 LUN이 Windows Server 페일오버 클러스터의 호스트에서 공유되는 경우에만 표시됩니다.



 a| 
호스트 이니시에이터를 선택합니다
 a| 
파이버 채널 * 또는 * iSCSI * 를 선택한 다음 호스트에서 이니시에이터를 선택합니다.

MPIO에서 FC를 사용하는 경우 여러 FC 이니시에이터를 선택할 수 있습니다.

|===
. 그룹 유형 페이지에서 기존 igroup을 LUN에 매핑할지 또는 새 igroup을 생성할지를 지정합니다.
+
|===
| 선택... | 만약... 


 a| 
선택한 이니시에이터에 대해 새 igroup을 생성합니다
 a| 
선택한 이니시에이터에 대해 새 igroup을 생성하려고 합니다.



 a| 
기존 igroup을 선택하거나 선택한 이니시에이터에 대한 새 igroup을 지정합니다
 a| 
선택한 이니시에이터에 대해 기존 igroup을 지정하거나 지정한 이름의 새 igroup을 생성합니다.

igroup 이름 * 필드에 igroup 이름을 입력합니다. 기존 igroup 이름의 처음 몇 글자를 입력하여 필드를 자동으로 작성합니다.

|===
. 요약 페이지에서 선택 사항을 검토하고 * 마침 * 을 클릭합니다.
+
SnapCenter는 LUN을 호스트의 지정된 드라이브 또는 드라이브 경로에 연결합니다.





== 디스크 연결을 해제합니다

LUN의 콘텐츠에 영향을 주지 않고 호스트에서 LUN을 분리할 수 있습니다. 단, 클론을 분리하기 전에 연결을 끊으면 클론의 내용이 손실됩니다.

* 필요한 것 *

* LUN을 다른 애플리케이션에서 사용하고 있지 않은지 확인합니다.
* 모니터링 소프트웨어를 사용하여 LUN을 모니터링하고 있지 않은지 확인합니다.
* LUN을 공유하는 경우 LUN에서 클러스터 리소스 종속성을 제거하고 클러스터의 모든 노드가 켜져 있고, 제대로 작동하고, SnapCenter에서 사용할 수 있는지 확인합니다.


* 이 작업에 대한 정보 *

SnapCenter에서 생성한 FlexClone 볼륨에서 LUN의 연결을 끊은 후 볼륨의 다른 LUN이 연결되어 있지 않으면 SnapCenter가 해당 볼륨을 삭제합니다. LUN을 분리하기 전에 SnapCenter FlexClone 볼륨이 삭제되었을 수 있다는 경고 메시지가 표시됩니다.

FlexClone 볼륨이 자동으로 삭제되지 않도록 하려면 마지막 LUN을 분리하기 전에 볼륨의 이름을 바꾸어야 합니다. 볼륨의 이름을 바꿀 때는 이름의 마지막 문자보다 여러 문자를 변경해야 합니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 디스크 * 를 클릭합니다.
. 호스트 * 드롭다운 목록에서 호스트를 선택합니다.
+
디스크가 나열됩니다.

. 연결을 끊을 디스크를 선택한 다음 * 연결 해제 * 를 클릭합니다.
. 디스크 연결 끊기 대화 상자에서 * 확인 * 을 클릭합니다.
+
SnapCenter가 디스크의 연결을 끊습니다.





== 디스크를 삭제합니다

디스크가 더 이상 필요하지 않으면 삭제할 수 있습니다. 디스크를 삭제한 후에는 삭제할 수 없습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 디스크 * 를 클릭합니다.
. 호스트 * 드롭다운 목록에서 호스트를 선택합니다.
+
디스크가 나열됩니다.

. 삭제할 디스크를 선택한 다음 * 삭제 * 를 클릭합니다.
. 디스크 삭제 대화 상자에서 * 확인 * 을 클릭합니다.
+
SnapCenter가 디스크를 삭제합니다.


