---
permalink: install/task_add_storage_systems.html 
sidebar: sidebar 
keywords: add, storage system, SVM 
summary: ONTAP에서 SnapCenter 스토리지에 액세스하여 데이터 보호 및 프로비저닝 작업을 수행할 수 있도록 스토리지 시스템을 설정해야 합니다. 독립 실행형 SVM이나 여러 SVM으로 구성된 클러스터를 추가할 수 있습니다. 
---
= 스토리지 시스템을 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 보호 및 프로비저닝 작업을 수행하려면 SnapCenter 스토리지에 대한 ONTAP 액세스 권한을 제공하는 스토리지 시스템이나 NetApp ONTAP용 Amazon FSx를 설정해야 합니다.

독립 실행형 SVM이나 여러 SVM으로 구성된 클러스터를 추가할 수 있습니다. NetApp ONTAP용 Amazon FSx를 사용하는 경우 fsxadmin 계정을 사용하여 여러 SVM으로 구성된 FSx 관리 LIF를 추가하거나 SnapCenter에서 FSx SVM을 추가할 수 있습니다.

* 필요한 것 *

* 스토리지 접속을 생성하려면 인프라스트럭처 관리자 역할에 필요한 권한이 있어야 합니다.
* 플러그인 설치가 진행 중이 아닌지 확인해야 합니다.
+
호스트 캐시가 업데이트되지 않고 데이터베이스 상태가 SnapCenter GUI에 ""백업을 위해 사용할 수 없음"" 또는 ""NetApp 스토리지에 없음""으로 표시될 수 있으므로 스토리지 시스템 접속을 추가하는 동안 호스트 플러그인 설치가 진행되어서는 안 됩니다.

* 스토리지 시스템 이름은 고유해야 합니다.
+
SnapCenter는 서로 다른 클러스터에서 동일한 이름의 여러 스토리지 시스템을 지원하지 않습니다. SnapCenter에서 지원하는 각 스토리지 시스템은 고유한 이름과 고유한 데이터 LIF IP 주소를 가져야 합니다.



* 이 작업에 대한 정보 *

* 스토리지 시스템을 구성할 때 EMS(이벤트 관리 시스템) 및 AutoSupport 기능을 활성화할 수도 있습니다. AutoSupport 툴은 시스템 상태에 대한 데이터를 수집하고 데이터를 NetApp 기술 지원 팀에 자동으로 전송하여 시스템에서 문제를 해결할 수 있도록 합니다.
+
이러한 기능을 설정하면 SnapCenter는 리소스가 보호되거나, 복구 또는 클론 작업이 성공적으로 완료되거나, 작업이 실패할 때 AutoSupport 정보를 스토리지 시스템 syslog로 보내고, EMS 메시지를 스토리지 시스템 syslog에 보냅니다.

* SnapMirror 타겟 또는 SnapVault 타겟으로 스냅샷 복사본을 복제할 계획이라면, 소스 SVM 또는 클러스터뿐만 아니라 타겟 SVM 또는 클러스터에 대한 스토리지 시스템 연결을 설정해야 합니다.



NOTE: 스토리지 시스템 암호, 예약된 작업, 필요 시 백업 및 복원 작업을 변경하는 경우 작업이 실패할 수 있습니다. 스토리지 시스템 암호를 변경한 후 스토리지 탭에서 * 수정 * 을 클릭하여 암호를 업데이트할 수 있습니다.

* 단계 *

. 왼쪽 탐색 창에서 * 스토리지 시스템 * 을 클릭합니다.
. 스토리지 시스템 페이지에서 * 신규 * 를 클릭합니다.
. 스토리지 시스템 추가 페이지에서 다음 정보를 제공합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
스토리지 시스템
 a| 
스토리지 시스템 이름 또는 IP 주소를 입력합니다.


NOTE: 도메인 이름을 제외한 스토리지 시스템 이름은 15자 이하여야 하며 이름을 확인할 수 있어야 합니다. 이름이 15자를 초과하는 스토리지 시스템 접속을 생성하려면 Add-SmStorageConnectionPowerShell cmdlet을 사용합니다.


NOTE: MCC(MetroCluster Configuration)가 있는 스토리지 시스템의 경우 무중단 운영을 위해 로컬 클러스터와 피어 클러스터를 모두 등록하는 것이 좋습니다.

SnapCenter은 서로 다른 클러스터에서 동일한 이름의 여러 SVM을 지원하지 않습니다. SnapCenter에서 지원하는 각 SVM에는 고유한 이름이 있어야 합니다.


NOTE: SnapCenter에 스토리지 연결을 추가한 후에는 ONTAP를 사용하여 SVM 또는 클러스터의 이름을 변경해서는 안 됩니다.


NOTE: 짧은 이름 또는 FQDN으로 SVM을 추가하는 경우 SnapCenter 및 플러그인 호스트 모두에서 확인할 수 있어야 합니다.



 a| 
사용자 이름/암호
 a| 
스토리지 시스템을 액세스하는 데 필요한 권한이 있는 스토리지 사용자의 자격 증명을 입력합니다.



 a| 
이벤트 관리 시스템(EMS) 및 AutoSupport 설정
 a| 
EMS 메시지를 스토리지 시스템 syslog에 보내거나, 적용된 보호, 완료된 복원 작업 또는 실패한 작업을 위해 스토리지 시스템으로 AutoSupport 메시지를 보내려면 해당 확인란을 선택합니다.

스토리지 시스템에 실패한 작업에 대한 * AutoSupport 알림 전송 * 확인란을 선택하면 AutoSupport 알림을 활성화하기 위해 EMS 메시징이 필요하기 때문에 * SnapCenter 서버 이벤트를 syslog * 에 기록 확인란도 선택됩니다.

|===
. 플랫폼, 프로토콜, 포트 및 시간 초과에 할당된 기본값을 수정하려면 * 추가 옵션 * 을 클릭합니다.
+
.. 플랫폼 의 드롭다운 목록에서 옵션 중 하나를 선택합니다.
+
SVM이 백업 관계의 2차 스토리지 시스템인 경우 * 2차 * 확인란을 선택합니다. Secondary * 옵션을 선택하면 SnapCenter에서 즉시 라이센스 검사를 수행하지 않습니다.

.. 프로토콜에서 SVM 또는 클러스터 설정 중에 구성된 프로토콜(일반적으로 HTTPS)을 선택합니다.
.. 스토리지 시스템에서 허용하는 포트를 입력합니다.
+
기본 포트 443은 일반적으로 작동합니다.

.. 통신 시도가 중지되기 전에 경과되어야 하는 시간(초)을 입력합니다.
+
기본값은 60초입니다.

.. SVM에 관리 인터페이스가 여러 개 있는 경우 * Preferred IP * 확인란을 선택한 다음 SVM 연결을 위한 기본 IP 주소를 입력합니다.
.. 저장 * 을 클릭합니다.


. 제출 * 을 클릭합니다.


* 결과 *

스토리지 시스템 페이지의 * 유형 * 드롭다운에서 다음 작업 중 하나를 수행합니다.

* 추가된 모든 SVM을 보려면 * ONTAP SVM * 을 선택합니다.
+
FSx SVM을 추가한 경우 여기에 FSx SVM이 나열됩니다.

* 추가된 모든 클러스터를 보려면 * ONTAP 클러스터 * 를 선택합니다.
+
fsxadmin을 사용하여 FSx 클러스터를 추가한 경우 FSx 클러스터가 여기에 나열됩니다.

+
클러스터 이름을 클릭하면 클러스터에 포함된 모든 SVM이 스토리지 가상 시스템 섹션에 표시됩니다.

+
ONTAP GUI를 사용하여 ONTAP 클러스터에 새 SVM을 추가할 경우 * 재발견 * 을 클릭하여 새로 추가된 SVM을 확인하십시오.



* 완료 후 *

클러스터 관리자는 스토리지 시스템 명령줄에서 다음 명령을 실행하여 SnapCenter가 액세스할 수 있는 모든 스토리지 시스템에서 e-메일 알림을 보내도록 각 스토리지 시스템 노드에서 AutoSupport를 설정해야 합니다.

AutoSupport trigger modify -node nodename -autosupport -message client.app.info enable-notteto enable


NOTE: SVM(스토리지 가상 시스템) 관리자는 AutoSupport에 액세스할 수 없습니다.
