---
permalink: install/task_configure_root_or_intermediate_certificates_to_trust_store.html 
sidebar: sidebar 
keywords: enable certificate-based authentication,configure CA signed key pair,configure root, configure intermediate certificates 
summary: 루트 또는 중간 인증서를 SPL 신뢰 저장소에 구성해야 합니다. 
---
= SPL 신뢰 저장소에 루트 또는 중간 인증서를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
루트 또는 중간 인증서를 SPL 신뢰 저장소에 구성해야 합니다. 루트 CA 인증서와 중간 CA 인증서를 추가해야 합니다.

* 단계 *

. SPL 키 저장소가 포함된 폴더로 이동합니다. `/var/opt/snapcenter/spl/etc`.
. 파일을 찾습니다 `keystore.jks`.
. 키 저장소에 추가된 인증서를 나열합니다.
`$ keytool -list -v -keystore keystore.jks`
. 루트 또는 중간 인증서 추가:
`$ keytool -import -trustcacerts -alias <AliasNameForCerticateToBeImported> -file /<CertificatePath> -keystore` `keystore.jks`
. SPL 신뢰 저장소에 루트 또는 중간 인증서를 구성한 후 서비스를 다시 시작합니다.




== CA 서명 키 쌍을 SPL 신뢰 저장소에 구성합니다

CA 서명된 키 쌍을 SPL 신뢰 저장소에 구성해야 합니다.

* 단계 *

. SPL의 키 저장소가 포함된 폴더로 이동합니다 `/var/opt/snapcenter/spl/etc`.
. 파일을 찾습니다 `keystore.jks``.
. 키 저장소에 추가된 인증서를 나열합니다.
`$ keytool -list -v -keystore keystore.jks`
. 개인 키와 공개 키를 모두 사용하는 CA 인증서를 추가합니다.
`$ keytool -importkeystore -srckeystore <CertificatePathToImport> -srcstoretype pkcs12 -destkeystore keystore.jks` `-deststoretype JKS`
. 키 저장소에 추가된 인증서를 나열합니다.
`$ keytool -list -v -keystore keystore.jks`
. keystore에 keystore에 추가된 새 CA 인증서에 해당하는 별칭이 포함되어 있는지 확인합니다.
. CA 인증서에 추가된 개인 키 암호를 키 저장소 암호로 변경합니다.
+
기본 SPL 키 저장소 암호는 SPL_keystore_pass in 키의 값입니다 `spl.properties` 파일.

+
`$ keytool -keypasswd -alias "<aliasNameOfAddedCertInKeystore>" -keystore keystore.jks``

. CA 인증서의 별칭 이름이 길고 공백 또는 특수 문자("*",",")가 포함된 경우 별칭 이름을 단순 이름으로 변경합니다.
`$ keytool -changealias -alias "<OrignalAliasName>" -destalias "<NewAliasName>" -keystore keystore.jks``
. 에 있는 키 저장소에서 별칭 이름을 구성합니다 `spl.properties` 파일.
이 값을 SPL_CERTIFICATE_ALIAS 키에 대해 업데이트합니다.
. CA 서명 키 쌍을 SPL 신뢰 저장소에 구성한 후 서비스를 다시 시작합니다.

