---
permalink: install/task_configure_audit_log_settings.html 
sidebar: sidebar 
keywords: audit, log, configure 
summary: 소프트웨어 플랫폼 및 해당 플랫폼에서 실행 중인 모든 소프트웨어의 보안 이벤트를 기록하도록 를 구성할 수 있습니다. 
---
= 감사 로그 설정을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
감사 로그는 SnapCenter 서버의 모든 작업에 대해 생성됩니다. 기본적으로 감사 로그는 기본적으로 설치된 위치인 _C:\Program Files\NetApp\SnapCenter WebApp\audit\_에 보호됩니다.

감사 로그는 각 감사 이벤트에 대해 디지털 서명된 다이제스트를 생성하여 무단 수정으로부터 보호합니다. 생성된 다이제스트는 별도의 감사 체크섬 파일에 보관되며, 컨텐츠의 무결성을 보장하기 위해 정기적인 무결성 검사를 수행합니다.

"SnapCenterAdmin" 역할로 로그인해야 합니다.

* 이 작업에 대한 정보 *

* 경고는 다음과 같은 경우에 전송됩니다.
+
** 감사 로그 무결성 검사 스케줄 또는 Syslog 서버가 활성화 또는 비활성화되어 있습니다
** 감사 로그 무결성 검사, 감사 로그 또는 Syslog 서버 로그 실패
** 디스크 공간이 부족합니다


* 무결성 검사가 실패한 경우에만 이메일이 전송됩니다.
* 감사 로그 디렉토리와 감사 체크섬 로그 디렉토리 경로를 함께 수정해야 합니다. 이 중 하나만 수정할 수 없습니다.
* 감사 로그 디렉토리 및 감사 체크섬 로그 디렉토리 경로가 수정되면 이전 위치에 있는 감사 로그에 대한 무결성 검사를 수행할 수 없습니다.
* 감사 로그 디렉토리 및 감사 체크섬 로그 디렉토리 경로는 SnapCenter 서버의 로컬 드라이브에 있어야 합니다.
+
공유 또는 네트워크 마운트 드라이브는 지원되지 않습니다.

* Syslog 서버 설정에서 UDP 프로토콜을 사용하는 경우 포트가 중단되었거나 사용할 수 없어 발생한 오류는 SnapCenter에서 오류 또는 경고로 캡처될 수 없습니다.
* Set-SmAuditSettings 및 Get-SmAuditSettings 명령을 사용하여 감사 로그를 구성할 수 있습니다.
+
cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 Get-Help command_name을 실행하여 얻을 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["SnapCenter 소프트웨어 cmdlet 참조 가이드"^].



* 단계 *

. 설정 * 페이지에서 * 설정 * > * 글로벌 설정 * > * 감사 로그 설정 * 으로 이동합니다.
. Audit log(감사 로그) 섹션에서 세부 정보를 입력합니다.
. 감사 로그 디렉토리 * 및 * 감사 체크섬 로그 디렉토리 * 를 입력합니다
+
.. 최대 파일 크기를 입력합니다
.. 최대 로그 파일을 입력합니다
.. 경고를 보낼 디스크 공간 사용 비율을 입력합니다


. (선택 사항) * Log UTC Time * 을 활성화합니다.
. (선택 사항) * 감사 로그 무결성 검사 일정 * 을 활성화하고 * 무결성 검사 시작 * 을 클릭하여 필요 시 무결성 검사를 수행합니다.
+
또한 * Start-SmAuditIntegrityCheck * 명령을 실행하여 요청 시 무결성 검사를 시작할 수도 있습니다.

. (선택 사항) 전달된 감사 로그를 원격 syslog 서버로 활성화하고 Syslog Server 세부 정보를 입력합니다.
+
Syslog 서버에서 TLS 1.2 프로토콜용 '신뢰할 수 있는 루트'로 인증서를 가져와야 합니다.

+
.. Syslog 서버 호스트를 입력합니다
.. Syslog 서버 포트를 입력합니다
.. Syslog Server Protocol을 입력합니다
.. RFC 형식을 입력합니다


. 저장 * 을 클릭합니다.
. 모니터 * > * 작업 * 을 클릭하면 감사 무결성 검사 및 디스크 공간 검사를 볼 수 있습니다.

