---
permalink: protect-scu/concept_overview_snapcenter_plug_in_for_UNIX_file_systems.html 
sidebar: sidebar 
keywords: overview, unix file system, plug-in for unix file system, backup, restore, clone 
summary: Unix 파일 시스템용 플러그인은 TOF Unix 파일 시스템의 백업, 복원 및 복제를 지원합니다. 
---
= Unix 파일 시스템용 SnapCenter 플러그인으로 수행할 수 있는 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Unix 파일 시스템용 플러그인이 사용자 환경에 설치된 경우 SnapCenter를 사용하여 Unix 파일 시스템을 백업, 복원 및 복제할 수 있습니다. 이러한 작업을 지원하는 작업을 수행할 수도 있습니다.

* 리소스를 검색합니다
* Unix 파일 시스템을 백업합니다
* 백업 작업을 예약합니다
* 파일 시스템 백업을 복구합니다
* 클론 파일 시스템 백업
* 백업, 복원 및 클론 작업을 모니터링합니다




== 지원되는 구성

|===
| 항목 | 지원되는 구성 


 a| 
확인하십시오
 a| 
* 물리적 서버
* 가상 서버
+
NFS와 SAN 모두에서 VVOL 데이터 저장소: VVOL 데이터 저장소는 VMware vSphere용 ONTAP 툴로만 프로비저닝할 수 있습니다.





 a| 
운영 체제
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server(SLES)




 a| 
파일 시스템
 a| 
* SAN:
+
** LVM 및 비 LVM 기반 파일 시스템 모두
** VMDK ext3, ext4 및 xfs를 통한 LVM


* NFS: NFS v3, NFS v4.x




 a| 
프로토콜
 a| 
* FC
* FCoE 를 참조하십시오
* iSCSI
* NFS 를 참조하십시오




 a| 
다중 경로
 a| 
예

|===


== 제한 사항

* 볼륨 그룹에서 RDM과 가상 디스크의 혼합은 지원되지 않습니다.
* 파일 레벨 복구는 지원되지 않습니다.
+
그러나 백업을 클론 생성한 다음 파일을 수동으로 복사하여 파일 레벨 복원을 수동으로 수행할 수 있습니다.

* NFS 및 VMFS 데이터 저장소 모두에서 제공되는 VMDK에 분산된 파일 시스템 혼합은 지원되지 않습니다.
* NVMe는 지원되지 않습니다.
* 프로비저닝은 지원되지 않습니다.




== 피처

* Linux 또는 AIX 시스템에서 기본 호스트 스토리지 스택을 처리함으로써 Oracle 데이터베이스용 플러그인이 Oracle 데이터베이스에서 데이터 보호 작업을 수행할 수 있습니다
* ONTAP를 실행하는 스토리지 시스템에서 NFS(Network File System) 및 SAN(Storage Area Network) 프로토콜을 지원합니다.
* Linux 시스템의 경우 VMware vSphere용 SnapCenter 플러그인을 구축하고 SnapCenter에 플러그인을 등록하면 VMDK 및 RDM LUN의 Oracle 데이터베이스가 지원됩니다.
* SAN 파일 시스템 및 LVM 레이아웃에서 AIX용 Mount Guard를 지원합니다.
* SAN 파일 시스템에 대한 인라인 로깅과 AIX 시스템에 대한 LVM 레이아웃으로 JFS2(Enhanced Journaled File System)를 지원합니다.
+
SAN 디바이스에 구축된 SAN 네이티브 디바이스, 파일 시스템 및 LVM 레이아웃이 지원됩니다.

* SnapCenter 환경에서 UNIX 파일 시스템에 대한 애플리케이션 인식 백업, 복원 및 클론 작업을 자동화합니다

