---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html 
sidebar: sidebar 
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user 
summary: 호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다. 
---
= Linux용 호스트 추가 및 플러그인 패키지 설치를 위한 사전 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트를 추가하고 Linux용 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다.

* iSCSI를 사용하는 경우 iSCSI 서비스가 실행 중이어야 합니다.
* 루트 또는 루트 이외의 사용자에 대해 암호 기반 인증을 사용하거나 SSH 키 기반 인증을 사용할 수 있습니다.
+

NOTE: RSA 키는 SnapCenter에서 지원되는 유일한 SSH 키 형식입니다. SSH 키 생성 방법에 대한 자세한 내용은 기술 자료 문서 link:https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/How_to_create_an_RSA_key_for_SnapCenter_SSH_Key_Based_credential["SnapCenter SSH 키 기반 자격 증명에 사용할 RSA 키를 생성하는 방법"^]를 참조하십시오.

+
Unix 파일 시스템용 SnapCenter 플러그인은 루트가 아닌 사용자가 설치할 수 있습니다. 그러나 비루트 사용자에 대한 sudo 권한을 구성하여 플러그인 프로세스를 설치하고 시작해야 합니다. 플러그인을 설치하면 프로세스가 루트가 아닌 효과적인 사용자로 실행됩니다.

* 설치 사용자에 대해 인증 모드를 Linux로 사용하여 자격 증명을 생성합니다.
* Linux 호스트에 Java 17, Java 11(SnapCenter 6.2의 경우에만 해당)이 설치되어 있어야 합니다.
+

NOTE: Linux 호스트에 인증된 Java 17 버전만 설치했는지, 또는 Java 11(SnapCenter 6.2에만 해당)이 설치되었는지 확인하십시오.

+
Java 다운로드에 대한 자세한 내용은 link:https://www.oracle.com/java/technologies/downloads/#java17["모든 운영 체제용 Java 다운로드"^]을(를) 참조하십시오.

* 플러그인 설치를 위한 기본 셸은 * bash * 이어야 합니다.




== Linux 호스트 요구 사항

Linux용 SnapCenter 플러그인 패키지를 설치하기 전에 호스트가 요구 사항을 충족하는지 확인해야 합니다.

|===
| 항목 | 요구 사항 


 a| 
운영 체제
 a| 
* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server(SLES)




 a| 
호스트의 SnapCenter 플러그인에 대한 최소 RAM입니다
 a| 
2GB



 a| 
호스트의 SnapCenter 플러그인에 대한 최소 설치 및 로그 공간
 a| 
2GB


NOTE: 충분한 디스크 공간을 할당하고 로그 폴더의 스토리지 사용량을 모니터링해야 합니다. 필요한 로그 공간은 보호할 엔터티의 수와 데이터 보호 작업의 빈도에 따라 달라집니다. 디스크 공간이 충분하지 않으면 최근 실행 작업에 대한 로그가 생성되지 않습니다.



 a| 
필요한 소프트웨어 패키지
 a| 
Java 17(Oracle Java 또는 OpenJDK), Java 11(SnapCenter 6.2에만 해당)


NOTE: Linux 호스트에 인증된 Java 17 버전만 설치했는지, 또는 Java 11(SnapCenter 6.2에만 해당)이 설치되었는지 확인하십시오.

Java를 최신 버전으로 업그레이드한 경우 /var/opt/snapcenter/spl/etc/spl.properties에 있는 JAVA_HOME 옵션이 올바른 Java 버전 및 올바른 경로로 설정되어 있는지 확인해야 합니다.

|===
지원되는 버전에 대한 최신 정보는 https://imt.netapp.com/imt/imt.jsp?components=180320;180338;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^]을 참조하십시오.
