---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html 
sidebar: sidebar 
keywords: backup policies, policies, unix file systems, file systems 
summary: 백업할 Unix 파일 시스템에 대한 백업 정책을 생성합니다. 
---
= Unix 파일 시스템에 대한 백업 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하여 Unix 파일 시스템을 백업하기 전에 백업하려는 리소스 또는 리소스 그룹에 대한 백업 정책을 생성해야 합니다. 백업 정책은 백업을 관리, 예약 및 유지하는 방법을 제어하는 규칙의 집합입니다. 복제, 스크립트 및 백업 유형 설정을 지정할 수도 있습니다. 정책을 만들면 다른 리소스 또는 리소스 그룹에서 정책을 다시 사용하려는 시간이 절약됩니다.

.시작하기 전에
* SnapCenter 설치, 호스트 추가, 파일 시스템 검색, 스토리지 시스템 연결 생성 등의 작업을 완료하여 데이터 보호를 준비해야 합니다.
* 미러 또는 소산 2차 스토리지에 스냅샷을 복제하는 경우, SnapCenter 관리자가 소스 볼륨과 타겟 볼륨 모두에 대해 SVM을 할당해야 합니다.
* SnapMirror 활성 동기화에 대한 사전 요구사항 및 제한 사항을 검토하십시오. 자세한 내용은 을 https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes["SnapMirror 활성 동기화에 대한 개체 제한"]참조하십시오.


.이 작업에 대해
* SnapLock
+
** '특정 기간 동안 백업 복사본 유지' 옵션을 선택한 경우 SnapLock 보존 기간은 언급된 보존 일수보다 작거나 같아야 합니다.
+
스냅샷 잠금 기간을 지정하면 보존 기간이 만료될 때까지 스냅샷이 삭제되지 않습니다.  이로 인해 정책에 지정된 개수보다 많은 수의 스냅샷이 보존될 수 있습니다.

+
ONTAP 9.12.1 이하 버전의 경우, 복원 과정에서 SnapLock 볼트 스냅샷에서 생성된 클론은 SnapLock 볼트 만료 시간을 상속합니다. 스토리지 관리자는 SnapLock 만료 시간 이후 클론을 수동으로 정리해야 합니다.





.단계
. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 정책 * 을 클릭합니다.
. 드롭다운 목록에서 * Unix 파일 시스템 * 을 선택합니다.
. 새로 만들기 * 를 클릭합니다.
. 이름 페이지에서 정책 이름과 세부 정보를 입력합니다.
. 백업 및 복제 페이지에서 다음 작업을 수행합니다.
+
.. 백업 설정을 지정합니다.
.. On demand *, * Hourly *, * Daily *, * Weekly * 또는 * Monthly * 를 선택하여 일정 빈도를 지정합니다.
.. Select secondary replication options 섹션에서 다음 보조 복제 옵션 중 하나 또는 둘 다를 선택합니다.


+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
로컬 스냅샷 복사본을 생성한 후 SnapMirror를 업데이트합니다
 a| 
다른 볼륨에 백업 세트의 미러 복사본을 생성하려면 이 필드를 선택합니다(SnapMirror 복제).

이 옵션은 SnapMirror 액티브 동기화에 대해 활성화해야 합니다.



 a| 
로컬 스냅샷 복사본을 생성한 후 SnapVault를 업데이트합니다
 a| 
디스크 간 백업 복제(SnapVault 백업)를 수행하려면 이 옵션을 선택합니다.



 a| 
오류 재시도 횟수입니다
 a| 
작업이 중지되기 전에 허용되는 최대 복제 시도 횟수를 입력합니다.

|===
. 보존 페이지에서 백업 유형 및 백업 및 복제 페이지에서 선택한 스케줄 유형에 대한 보존 설정을 지정합니다.
+
|===


| 원하는 작업 | 그러면... 


 a| 
특정 수의 스냅샷을 유지합니다
 a| 
유지할 사본 * 을 선택한 다음 유지할 스냅샷 수를 지정합니다.

스냅샷 수가 지정된 수를 초과하면 가장 오래된 복제본이 먼저 삭제되고 스냅샷이 삭제됩니다.


NOTE: 최대 보존 값은 1018입니다. 보존이 기본 ONTAP 버전에서 지원하는 값보다 높은 값으로 설정된 경우 백업이 실패합니다.


IMPORTANT: SnapVault 복제를 설정하려면 보존 수를 2 이상으로 설정해야 합니다. 보존 횟수를 1로 설정하면 새 스냅샷이 타겟으로 복제될 때까지 첫 번째 스냅샷이 SnapVault 관계에 대한 참조 스냅샷이기 때문에 보존 작업이 실패할 수 있습니다.



 a| 
스냅샷을 특정 기간 동안 보관합니다
 a| 
복제본 유지 기간 * 을 선택한 다음 스냅샷을 삭제하기 전에 보존할 일 수를 지정합니다.



 a| 
스냅샷 복사 잠금 기간
 a| 
*스냅샷 복사 잠금 기간*을 선택하고 기간을 일, 월 또는 년 단위로 지정합니다.

SnapLock 보존 기간은 100년 미만이어야 합니다.

|===
. 정책 레이블을 선택합니다.
+

NOTE: 원격 복제를 위해 기본 스냅샷에 SnapMirror 레이블을 할당하면 기본 스냅샷이 SnapCenter 에서 ONTAP 보조 시스템으로 스냅샷 복제 작업을 오프로드할 수 있습니다.  정책 페이지에서 SnapMirror 또는 SnapVault 옵션을 활성화하지 않고도 이 작업을 수행할 수 있습니다.

. 스크립트 페이지에서 백업 작업 전후에 실행할 처방인 또는 PS의 경로와 인수를 각각 입력합니다.
+

NOTE: _/opt/NetApp/SnapCenter/scc/etc/allowed_commands.config_path에서 플러그인 호스트에서 사용할 수 있는 명령 목록에 명령이 있는지 확인해야 합니다.

+
스크립트 시간 초과 값을 지정할 수도 있습니다. 기본값은 60초입니다.

. 요약을 검토하고 * Finish * 를 클릭합니다.

