---
permalink: protect-db2/prerequisites-to-adding-hosts-and-installing-snapcenter-plug-in-for-ibm-db2.html 
sidebar: sidebar 
keywords: credentials 
summary: 호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다. IBM DB2용 SnapCenter 플러그인은 Windows 및 Linux 환경 모두에서 사용할 수 있습니다. 
---
= 호스트를 추가하고 IBM DB2용 SnapCenter 플러그인을 설치하기 위한 사전 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트를 추가하고 플러그인 패키지를 설치하기 전에 모든 요구 사항을 완료해야 합니다. IBM DB2용 SnapCenter 플러그인은 Windows 및 Linux 환경 모두에서 사용할 수 있습니다.

* 호스트에 Java 11을 설치해야 합니다.
+

NOTE: IBM Java는 지원되지 않습니다.

* Windows의 경우 IBM DB2용 플러그인이 도메인 관리자로 설치된 경우 기본 동작인 ""LocalSystem"" Windows 사용자를 사용하여 플러그인 Creator Service를 실행해야 합니다.
* Windows 호스트에 플러그인을 설치할 때 기본 제공되지 않은 자격 증명을 지정하거나 사용자가 로컬 작업 그룹 사용자의 경우 호스트에서 UAC를 비활성화해야 합니다. Microsoft Windows용 SnapCenter 플러그인은 Windows 호스트에 IBM DB2 플러그인과 함께 기본적으로 배포됩니다.
* SnapCenter 서버는 IBM DB2 호스트용 플러그인의 8145 또는 사용자 지정 포트에 액세스할 수 있어야 합니다.




== Windows 호스트

* 원격 호스트에 대한 로컬 로그인 권한이 있는 로컬 관리자 권한이 있는 도메인 사용자가 있어야 합니다.
* Windows 호스트에 IBM DB2용 플러그인을 설치하는 동안 Microsoft Windows용 SnapCenter 플러그인이 자동으로 설치됩니다.
* 루트 또는 루트 이외의 사용자에 대해 암호 기반 SSH 연결을 활성화해야 합니다.
* Windows 호스트에 Java 11을 설치해야 합니다.
+
http://www.java.com/en/download/manual.jsp["모든 운영 체제에 대한 Java 다운로드"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117015;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"]





== Linux 호스트

* 루트 또는 루트 이외의 사용자에 대해 암호 기반 SSH 연결을 활성화해야 합니다.
* Linux 호스트에 * mksh * 라이브러리를 설치해야 합니다.
* Linux 호스트에 Java 11을 설치해야 합니다.
+
http://www.java.com/en/download/manual.jsp["모든 운영 체제에 대한 Java 다운로드"]

+
https://imt.netapp.com/matrix/imt.jsp?components=117015;&solution=1259&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"]

* Linux 호스트에서 실행되는 IBM DB2 데이터베이스의 경우 IBM DB2용 플러그인을 설치하는 동안 UNIX용 SnapCenter 플러그인이 자동으로 설치됩니다.
* 플러그인 설치를 위한 기본 셸은 * bash * 이어야 합니다.




== 보조 명령

IBM DB2용 SnapCenter 플러그인에서 추가 명령을 실행하려면 해당 명령을 파일에 포함해야 `allowed_commands.config` 합니다.

`allowed_commands.config` 파일은 IBM DB2용 SnapCenter 플러그인 디렉토리의 "etc" 하위 디렉토리에 있습니다.

.Windows 호스트
기본값: `C:\Program Files\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc\allowed_commands.config`

사용자 지정 경로: `<Custom_Directory>\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc\allowed_commands.config`

.Linux 호스트
기본값: `/opt/NetApp/snapcenter/scc/etc/allowed_commands.config`

사용자 지정 경로: `<custom_Directory>/NetApp/snapcenter/scc/etc/allowed_commands.config`

플러그인 호스트에서 추가 명령을 허용하려면 을 엽니다 `allowed_commands.config` 편집기의 파일. 각 명령을 별도의 줄에 입력합니다. 이름은 대소문자를 구분하지 않습니다.
예를 들면, 다음과 같습니다.

명령: mount

명령: 마운트 해제

정규화된 경로 이름을 지정해야 합니다. 공백이 포함된 경우, 경로 이름은 따옴표(")로 묶어야 합니다.
예를 들면, 다음과 같습니다.

명령: "C:\Program Files\NetApp\SnapCreator Commands\sdcli.exe"

명령: myscript.bat

를 누릅니다 `allowed_commands.config` 파일이 없거나 명령 또는 스크립트 실행이 차단되고 워크플로가 실패하고 다음 오류가 발생합니다.

"[/mnt/mount -a] 실행이 허용되지 않습니다. 플러그인 호스트의 %s 파일에 명령을 추가하여 권한을 부여하십시오."

명령 또는 스크립트가 에 없는 경우 `allowed_commands.config`, 명령 또는 스크립트 실행이 차단되고 워크플로가 실패하고 다음 오류가 발생합니다.

"[/mnt/mount -a] 실행이 허용되지 않습니다. 플러그인 호스트의 %s 파일에 명령을 추가하여 권한을 부여하십시오."


NOTE: 와일드카드 항목(*)을 사용하여 모든 명령을 허용해서는 안 됩니다.



== Linux 호스트에 대해 루트가 아닌 사용자에 대한 sudo 권한을 구성합니다

SnapCenter 2.0 이상 버전에서는 루트가 아닌 사용자가 Linux용 SnapCenter 플러그인 패키지를 설치하고 플러그인 프로세스를 시작할 수 있습니다. 플러그인 프로세스는 효과적인 비루트 사용자로 실행됩니다. 여러 경로에 대한 액세스를 제공하려면 루트가 아닌 사용자에 대해 sudo 권한을 구성해야 합니다.

* 필요한 것 *

* sudo 버전 1.8.7 이상
* 루트가 아닌 사용자의 경우 루트가 아닌 사용자 및 사용자 그룹의 이름이 동일해야 합니다.
* MAC HMAC-SHA2-256 및 MAC HMAC-SHA2-512의 메시지 인증 코드 알고리즘을 구성하려면 _/etc/ssh/sshd_config_file을 편집합니다.
+
구성 파일을 업데이트한 후 sshd 서비스를 다시 시작합니다.

+
예:

+
[listing]
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----


* 이 작업에 대한 정보 *

루트가 아닌 사용자에 대해 sudo 권한을 구성하여 다음 경로에 대한 액세스를 제공해야 합니다.

* /home/_linux_user_/.sc_netapp/snapcenter_linux_host_plugin.bin
* /custom_location/netapp/snapcenter/SPL/설치/플러그인/제거
* /custom_location/NetApp/snapcenter/SPL/bin/SPL입니다


* 단계 *

. Linux용 SnapCenter 플러그인 패키지를 설치할 Linux 호스트에 로그인합니다.
. visudo Linux 유틸리티를 사용하여 /etc/sudoers 파일에 다음 행을 추가합니다.
+
[listing, subs="+quotes"]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+

NOTE: 다른 허용 명령과 함께 RAC 설정을 사용하는 경우 다음을 /etc/sudoers 파일에 추가해야 합니다. '/<crs_home>/bin/olsnodes'



_/etc/oracle/OLR.loc_file에서 _CRS_HOME_ 값을 가져올 수 있습니다.

_linux_user_는 사용자가 생성한 루트가 아닌 사용자의 이름입니다.

다음 위치에 있는 * SC_UNIX_plugins_checksum.txt * 파일에서 _checksum_value_를 가져올 수 있습니다.

* _C:\ProgramData\NetApp\SnapCenter\Package Repository\SC_UNIX_plugins_checksum.txt_SnapCenter 서버가 Windows 호스트에 설치된 경우
* _/opt/netapp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_if SnapCenter 서버가 Linux 호스트에 설치되어 있는 경우.



IMPORTANT: 이 예제는 고유한 데이터를 만들기 위한 참조로만 사용해야 합니다.
