---
permalink: get-started/concept_disaster_recovery.html 
sidebar: sidebar 
keywords: Disaster Recovery, DR, crash, resource deleted 
summary: SnapCenter 재해 복구 기능을 사용하여 리소스 손상 또는 서버 충돌과 같은 재해 발생 시 SnapCenter 서버를 복구할 수 있습니다. 
---
= SnapCenter의 재해 복구
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter DR(재해 복구) 기능을 사용하면 리소스 손상 또는 서버 충돌과 같은 재해로부터 복구할 수 있습니다. SnapCenter 저장소, 서버 일정, 구성 구성 요소, SQL Server용 SnapCenter 플러그인 및 해당 스토리지를 복구하는 데 도움이 됩니다.

이 섹션에서는 SnapCenter의 두 가지 유형의 DR에 대해 설명합니다.



== SnapCenter 서버 DR

* SnapCenter 서버 데이터는 백업되며 SnapCenter 서버에 플러그인을 추가하거나 관리하지 않고도 복구할 수 있습니다.
* 보조 SnapCenter 서버는 운영 SnapCenter 서버와 동일한 설치 디렉토리 및 포트에 설치해야 합니다.
* 다중 인증(MFA)의 경우 SnapCenter 서버 DR 중에 모든 브라우저 탭을 닫고 브라우저를 다시 열어 다시 로그인해야 합니다. 이렇게 하면 기존 또는 활성 세션 쿠키가 지워 올바른 구성 데이터가 업데이트됩니다.
* SnapCenter 재해 복구 기능은 REST API를 사용하여 SnapCenter 서버를 백업합니다. 을 link:../tech-refresh/task_tech_refresh_server_host.html["SnapCenter 서버의 재해 복구를 위한 REST API 워크플로우"]참조하십시오.
* 감사 설정 관련 구성 파일은 DR 백업에 백업되지 않고 복원 작업 후 DR 서버에도 백업되지 않습니다. 감사 로그 설정을 수동으로 반복해야 합니다.




== SnapCenter 플러그인 및 스토리지 DR

DR은 SQL Server용 SnapCenter 플러그인에만 사용할 수 있습니다. 플러그인이 중단된 경우 다른 SQL 호스트로 전환하고 몇 가지 단계를 수행하여 데이터를 복구합니다. 을 link:../protect-scsql/task_disaster_recovery_scsql.html["SQL Server용 SnapCenter 플러그인의 재해 복구"]참조하십시오.

SnapCenter는 ONTAP SnapMirror를 사용하여 데이터를 복제하며, 이 데이터는 2차 사이트와 동기화된 상태를 유지하여 DR에 사용할 수 있습니다. 페일오버를 시작하려면 SnapMirror 복제를 중단합니다. 폴백 중에는 동기화를 반대로 수행하여 DR 사이트의 데이터를 다시 운영 위치로 복제합니다.
