---
permalink: get-started/concept_resources_resource_groups_and_policies.html 
sidebar: sidebar 
keywords: resource, resource group, policy 
summary: SnapCenter를 사용하기 전에 수행할 백업, 클론 및 복원 작업과 관련된 기본 개념을 이해하는 것이 좋습니다. 
---
= 데이터 보호의 주요 개념
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하기 전에 백업, 클론 복제 및 복원에 대한 주요 개념을 이해해야 합니다.



== 리소스

리소스에는 데이터베이스, Windows 파일 시스템 또는 SnapCenter를 통해 백업되거나 클론되는 파일 공유가 포함됩니다. 환경에 따라 데이터베이스 인스턴스, SQL Server 가용성 그룹, Oracle 데이터베이스, RAC 데이터베이스 또는 맞춤형 애플리케이션 그룹도 리소스가 될 수 있습니다.



== 리소스 그룹

리소스 그룹은 호스트 또는 클러스터의 리소스 모음으로, 잠재적으로 여러 호스트 및 클러스터에서 가져올 수 있습니다. 리소스 그룹에 대해 수행되는 작업은 지정된 일정에 따라 모든 리소스에 적용됩니다. 개별 리소스 또는 그룹에 대해 필요 시 또는 예약 백업을 수행할 수 있습니다.


NOTE: 공유 리소스 그룹의 호스트 하나가 유지 관리 모드로 전환되면 해당 그룹에 대해 예약된 모든 작업이 모든 호스트에서 일시 중단됩니다.

관련 플러그인을 사용하여 데이터베이스용 데이터베이스 플러그인, 파일 시스템용 파일 시스템 플러그인, VM 및 데이터 저장소용 VMware vSphere용 SnapCenter 플러그인 등 특정 리소스를 백업할 수 있습니다.



== 정책

정책은 백업 빈도, 복제 보존, 복제, 스크립트 및 데이터 보호 작업의 기타 특성을 지정합니다.

리소스 그룹을 생성하거나 필요 시 백업을 수행할 때 하나 이상의 정책을 선택할 수 있습니다.

리소스 그룹은 보호해야 할 항목과 날짜 및 시간 측면에서 보호해야 하는 시기를 정의합니다. 정책은 보호를 수행하는 방법을 설명합니다. 예를 들어 호스트의 모든 데이터베이스 또는 파일 시스템을 백업해야 하는 경우 호스트의 모든 데이터베이스 또는 파일 시스템을 포함하는 리소스 그룹이 생성될 수 있습니다. 그런 다음 일별 정책과 시간별 정책이라는 두 개의 정책을 리소스 그룹에 연결할 수 있습니다.

리소스 그룹을 생성하고 정책을 연결할 때 매시간 전체 백업을 수행하고 로그 백업에 대해 다른 스케줄을 수행하도록 구성할 수 있습니다.

사용자 지정 처방과 사후 스크립트를 데이터 보호 작업에 사용할 수 있습니다. 이러한 스크립트를 사용하면 데이터 보호 작업 전후에 자동화를 수행할 수 있습니다. 예를 들어, 스크립트가 데이터 보호 작업 실패 또는 경고를 자동으로 통지할 수 있습니다. 처방 및 사후 스크립트를 설정하기 전에 이러한 스크립트를 생성하기 위한 요구 사항을 이해하는 것이 중요합니다.



== 일관성 그룹(CG)

일관성 그룹은 단일 단위로 관리되는 볼륨의 모음입니다.  CG는 저장 장치와 볼륨 전체에서 데이터 일관성을 위해 동기화됩니다.  ONTAP 에서는 여러 볼륨에 걸친 애플리케이션 작업 부하에 대한 쉬운 관리와 보호 보장을 제공합니다. 자세히 알아보세요 link:https://docs.netapp.com/us-en/ontap/consistency-groups["일관성 그룹"^] .



== 처방전 및 포스트스크립트 사용

사용자 지정 처방 및 사후 스크립트는 작업 전후에 데이터 보호 작업을 자동화할 수 있습니다. 예를 들어, 작업 실패 또는 경고를 통지하는 스크립트를 추가할 수 있습니다. 설정하기 전에 이러한 스크립트의 요구 사항을 이해해야 합니다.



=== 지원되는 스크립트 유형입니다

Windows에서 지원되는 스크립트 유형은 다음과 같습니다.

* 배치 파일
* PowerShell 스크립트
* Perl 스크립트


UNIX에서 지원되는 스크립트 유형은 다음과 같습니다.

* Perl 스크립트
* Python 스크립트
* 쉘 스크립트
+

NOTE: 기본 bash shell과 함께 sh-shell, k-shell 및 c-shell과 같은 다른 쉘도 지원됩니다.





=== 스크립트 경로

가상화되지 않은 스토리지 시스템과 가상화된 스토리지 시스템에서 SnapCenter 작업의 일부로 실행되는 모든 사전 스크립트와 사후 스크립트가 플러그인 호스트에서 실행됩니다.

* Windows 스크립트는 플러그인 호스트에 있어야 합니다.



NOTE: 처방자 또는 사후 스크립트 경로에는 드라이브 또는 공유가 포함되어서는 안 됩니다. 경로는 scripts_path에 상대해야 합니다.

* UNIX 스크립트는 플러그인 호스트에 있어야 합니다.



NOTE: 스크립트 경로는 실행 시 검증됩니다.



=== 스크립트 지정 위치

스크립트는 백업 정책에 지정됩니다. 백업 작업이 시작되면 정책이 자동으로 스크립트를 백업 중인 리소스와 연결합니다. 백업 정책을 만들 때 처방과 PS 인수를 지정할 수 있습니다.


NOTE: 여러 스크립트를 지정할 수 없습니다.



=== 스크립트 시간 초과

시간 초과는 기본적으로 60초로 설정됩니다. 시간 초과 값을 수정할 수 있습니다.



=== 스크립트 출력

Windows prescpts 및 postscripts 출력 파일의 기본 디렉터리는 Windows\System32입니다.

UNIX 처방과 postscript에 대한 기본 위치는 없습니다. 원하는 위치로 출력 파일을 리디렉션할 수 있습니다.
