---
permalink: get-started/reference_supported_storage_systems_and_applications.html 
sidebar: sidebar 
keywords: storage system, ONTAP version, ASA r2 systems 
summary: 지원되는 스토리지 시스템, 애플리케이션 및 데이터베이스를 알고 있어야 합니다. 
---
= SnapCenter에서 지원하는 스토리지 시스템 및 애플리케이션
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter에서 지원하는 스토리지 시스템, 애플리케이션 및 데이터베이스를 알아야 합니다.



== 지원되는 스토리지 시스템

* NetApp ONTAP 9.12.1 이상
* Azure NetApp Files
* NetApp ONTAP용 Amazon FSx
+
TCP(Transport Control Protocol)를 통한 비휘발성 메모리 익스프레스(NVMe)를 지원합니다.

+
NetApp ONTAP용 Amazon FSx에 대한 자세한 내용은 를 참조하십시오 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx 문서"^].

* NetApp ONTAP 9.16.1을 실행하는 NetApp ASA R2 시스템입니다.
+
ASA R2 시스템은 All-Flash 플랫폼을 기반으로 구축된 SAN 전용 환경을 위한 하드웨어 및 소프트웨어 통합 솔루션을 제공합니다. https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2 시스템에 대해 자세히 알아보십시오"]..

+

NOTE: SnapCenter는 ASA R2 시스템에서 VMware VMFS(가상 머신 파일 시스템)만 지원합니다.

+
|===
| 지원되는 작업 | 작업이 지원되지 않습니다 


 a| 
** VMDK를 통해 애플리케이션의 기본 백업을 생성합니다
** 정합성 보장 그룹 스냅샷을 보조 스토리지 시스템으로 전송합니다
** 백업 복구 및 대체 위치에서 복구
+
*** VMware vMotion을 사용하여 운영 스토리지와 보조 스토리지 모두에서 데이터 이동 없이 복구
*** 운영 스토리지와 2차 스토리지 모두에서 복원 및 복제


** 백업 클론 생성 및 대체 위치에 클론 복제

 a| 
** RDM(Raw Device Mapping)
** Oracle용 애플리케이션 볼륨
** SAP HANA NDV
** LockVault 를 클릭합니다
** 변조 방지 스냅샷
** Flex 그룹
** 계층적 일관성 그룹
** ONTAP 9.x에서 ASA R2 시스템으로 마이그레이션
** 스냅샷 이름 바꾸기
** SnapCenter에서는 SQL 플러그인 호스트의 로그 디렉토리에 대한 보조 프로비저닝을 지원하지 않습니다. ONTAP CLI 또는 System Manager를 사용하여 수동으로 구성해야 합니다.


|===




== 지원되는 애플리케이션 및 데이터베이스

SnapCenter는 다양한 애플리케이션 및 데이터베이스의 보호를 지원합니다. 지원되는 응용 프로그램 및 데이터베이스에 대한 자세한 내용은 을 참조하십시오 https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT["NetApp 상호 운용성 매트릭스 툴"^].

SnapCenter는 VMware Cloud on Amazon Web Services(AWS) 소프트웨어 정의 데이터 센터(SDDC) 환경에서 Oracle 및 Microsoft SQL 워크로드를 보호할 수 있도록 지원합니다. https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168["자세한 정보"^]..
