---
permalink: uninstall/task_remove_a_host.html 
sidebar: sidebar 
keywords: uninstall, remove, remove host 
summary: SnapCenter 서버가 호스트를 제거하면 먼저 SnapCenter 리소스 페이지에서 해당 호스트에 대해 나열된 백업, 클론, 클론 작업, 리소스 그룹 및 리소스를 제거한 다음 호스트에서 플러그인 패키지를 제거합니다. 
---
= 호스트를 제거합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 서버가 호스트를 제거하면 먼저 SnapCenter 리소스 페이지에서 해당 호스트에 대해 나열된 백업, 클론, 클론 작업, 리소스 그룹 및 리소스를 제거한 다음 호스트에서 플러그인 패키지를 제거합니다.

* 이 작업에 대한 정보 *

* 호스트를 삭제하면 호스트와 연결된 백업, 클론 및 리소스 그룹도 삭제됩니다.
* 리소스 그룹을 제거하면 연결된 모든 스케줄도 제거됩니다.
* 호스트에 다른 호스트와 공유되는 리소스 그룹이 있고 호스트를 삭제하는 경우 리소스 그룹도 삭제됩니다.
* 사용 중단되거나 연결할 수 없는 플러그인 호스트를 제거하려면 _Remove-SmHost_cmdlet을 사용해야 합니다.
+
cmdlet과 함께 사용할 수 있는 매개 변수와 이에 대한 설명은 running_get-Help command_name_에서 확인할 수 있습니다. 또는 을 참조할 수도 있습니다 https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482["SnapCenter 소프트웨어 cmdlet 참조 가이드"^]

* 호스트를 제거하는 데 필요한 시간은 백업 수와 보존 설정에 따라 달라집니다. 이는 각 컨트롤러에서 스냅샷 복사본이 삭제되고 메타데이터가 정리되기 때문입니다.


* 단계 *

. 왼쪽 탐색 창에서 * 호스트 * 를 클릭합니다.
. 호스트 페이지에서 * 관리되는 호스트 * 를 클릭합니다.
. 제거할 호스트를 선택한 다음 * 제거 * 를 클릭합니다.
. Oracle RAC 클러스터의 경우 클러스터의 모든 호스트에서 SnapCenter 소프트웨어를 제거하려면 * 클러스터의 모든 호스트 포함 * 을 선택합니다.
+
또한 클러스터의 노드 하나를 제거하여 모든 노드를 하나씩 제거할 수도 있습니다.

. 확인 * 을 클릭합니다.
+

NOTE: 클러스터에서 호스트 플러그인을 제거하고 다시 설치하면 클러스터 리소스가 자동으로 검색되지 않습니다. 클러스터 호스트 이름을 선택한 다음 * 리소스 새로 고침 * 을 클릭하여 클러스터 리소스를 자동으로 검색합니다.


