---
permalink: 'release-notes/what"s-new-in-snapcenter60.html' 
sidebar: sidebar 
keywords: what is new, features, enhancements, 6.0 
summary: SnapCenter 소프트웨어의 6.0 릴리스에는 몇 가지 새로운 기능과 향상된 기능이 포함되어 있습니다. 
---
= SnapCenter 소프트웨어 6.0의 새로운 기능
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter 소프트웨어의 6.0 릴리스에는 몇 가지 새로운 기능과 향상된 기능이 포함되어 있습니다.

|===
| 업데이트 | 설명 


| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html#snapcenter-plug-ins["NetApp가 지원되는 엔터프라이즈 워크로드 플러그인 지원"]  a| 
SnapCenter는 PostgreSQL, MySQL, IBM DB2와 같은 워크로드를 관리하는 플러그인을 제공합니다. 워크로드를 자동으로 검색, 백업, 복원, 마운트 및 복제할 수 있습니다.

또한, SnapCenter은 SAP ASE, SAP MaxDB, MongoDB, Oracle Applications, ONTAP 스토리지와 같은 워크로드를 관리하는 플러그인을 제공합니다. 사용자는 워크로드를 백업, 복원 및 클론 복제할 수 있습니다.



| link:https://docs.netapp.com/us-en/snapcenter/install/install_snapcenter_server_linux.html["클라우드 및 사내 워크로드를 모두 지원하는 SnapCenter의 Linux 버전 지원"]  a| 
이제 RHEL(Red Hat Enterprise Linux), Oracle Linux, SLES(SUSE Linux Enterprise Server)와 같은 Linux 버전에 대해 별도의 SnapCenter 바이너리를 사용할 수 있습니다.

* Azure NetApp Files, Amazon FSx for NetApp ONTAP, Cloud Volumes ONTAP 및 ONTAP 스토리지를 지원합니다.
* RHEL(Red Hat Enterprise Linux), Oracle Linux, SLES(SUSE Linux Enterprise Server)와 같은 Linux 버전을 위한 별도의 바이너리
* SAP HANA, Oracle, IBM DB2, SAP ASE, SAP MaxDB와 같은 기존 데이터베이스를 지원합니다.
* PostgreSQL, MySQL, MongoDB와 같은 최신 워크로드를 지원합니다.
* 지원되지 않거나 자체 개발한 애플리케이션을 보호하기 위해 ONTAP 볼륨 및 Linux 파일 시스템용 플러그인을 지원합니다.




| link:https://docs.netapp.com/us-en/snapcenter/concept/concept_snapcenter_overview.html["SnapMirror 활성 동기화를 지원합니다"]  a| 
이제 SnapCenter를 사용하여 SnapMirror 액티브 동기화 기능을 구성하고 데이터베이스 및 VMware VM에 대한 SAN 워크로드를 효과적으로 백업, 복원 및 복제할 수 있습니다. 이를 통해 투명한 애플리케이션 페일오버 및 무중단 업무 운영을 보장할 수 있습니다.



| link:https://docs.netapp.com/us-en/snapcenter/install/concept_create_and_manage_smb_shares.html["SMB3에서 Microsoft SQL Server 지원"]  a| 
이제 SnapCenter를 사용하여 ONTAP, Azure NetApp Files, Amazon FSx for NetApp ONTAP 및 Cloud Volumes ONTAP의 SMB3 프로토콜에 배포된 Microsoft SQL Server 데이터베이스를 보호할 수 있습니다.



| link:https://docs.netapp.com/us-en/snapcenter/protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html#storage-types-supported-on-linux["NVMe/TCP 지원"]  a| 
이제 SnapCenter는 TCP 프로토콜을 통한 NVMe를 지원하여 애플리케이션과 파일 시스템을 백업 및 복구합니다.



| VVOL(VMware vSphere 가상 볼륨) 지원  a| 
이제 SnapCenter를 사용하여 VVOL에 배포된 데이터베이스와 파일 시스템을 보호할 수 있습니다.

|===