---
permalink: protect-mysql/create-backup-policies-for-mysql.html 
sidebar: sidebar 
keywords: SnapCenter Plug-in for MySQL 
summary: SnapCenter를 사용하여 MySQL 데이터베이스 리소스를 백업하기 전에 백업하려는 리소스 또는 리소스 그룹에 대한 백업 정책을 만들어야 합니다. 백업 정책은 백업을 관리, 예약 및 유지하는 방법을 제어하는 규칙의 집합입니다. 
---
= MySQL에 대한 백업 정책을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapCenter를 사용하여 MySQL 리소스를 백업하기 전에 백업하려는 리소스 또는 리소스 그룹에 대한 백업 정책을 만들어야 합니다. 백업 정책은 백업을 관리, 예약 및 유지하는 방법을 제어하는 규칙의 집합입니다.

.시작하기 전에
* 백업 전략을 정의해야 합니다.
+
자세한 내용은 MySQL 데이터베이스에 대한 데이터 보호 전략 정의에 대한 정보를 참조하십시오.

* SnapCenter 설치, 호스트 추가, 스토리지 시스템 접속 설정, 리소스 추가 등의 작업을 완료하여 데이터 보호를 위한 준비가 되어 있어야 합니다.
* 미러 또는 볼트에 스냅샷을 복제하는 경우 SnapCenter 관리자가 소스 볼륨과 타겟 볼륨 모두에 SVM을 할당해야 합니다.
+
또한 정책에서 복제, 스크립트 및 애플리케이션 설정을 지정할 수 있습니다. 이러한 옵션을 사용하면 다른 리소스 그룹에 대해 정책을 다시 사용할 때 시간을 절약할 수 있습니다.



.이 작업에 대해
* SnapLock
+
** '특정 기간 동안 백업 복사본 유지' 옵션을 선택한 경우 SnapLock 보존 기간은 언급된 보존 일수보다 작거나 같아야 합니다.
** 스냅샷 잠금 기간을 지정하면 보존 기간이 만료될 때까지 스냅샷이 삭제되지 않습니다. 이로 인해 정책에 지정된 개수보다 많은 수의 스냅샷이 보존될 수 있습니다.
** ONTAP 9.12.1 이하 버전의 경우 복원 과정에서 SnapLock 볼트 스냅샷에서 생성된 클론은 SnapLock 볼트 만료 시간을 상속합니다. 스토리지 관리자는 SnapLock 만료 시간 이후 클론을 수동으로 정리해야 합니다.




.단계
. 왼쪽 탐색 창에서 * 설정 * 을 클릭합니다.
. 설정 페이지에서 * 정책 * 을 클릭합니다.
. 새로 만들기 * 를 클릭합니다.
. 이름 페이지에서 정책 이름과 세부 정보를 입력합니다.
. 정책 유형 페이지에서 다음을 수행합니다.
+
.. 스토리지 유형을 선택합니다.
.. Custom backup settings(사용자 지정 백업 설정) 섹션에서 플러그인에 전달해야 하는 특정 백업 설정을 키 값 형식으로 제공합니다.
+
플러그인으로 전달할 여러 키 값을 제공할 수 있습니다.



. 스냅샷 및 복제 페이지에서 다음 단계를 수행합니다.
+
.. On demand *, * Hourly *, * Daily *, * Weekly * 또는 * Monthly * 를 선택하여 일정 유형을 지정합니다.
+

NOTE: 리소스 그룹을 생성하는 동안 백업 작업의 스케줄(시작 날짜, 종료 날짜 및 빈도)을 지정할 수 있습니다. 따라서 동일한 정책 및 백업 빈도를 공유하는 리소스 그룹을 생성할 수 있지만, 각 정책에 서로 다른 백업 스케줄을 할당할 수 있습니다.

+

NOTE: 오전 2시에 예약된 경우 DST(일광 절약 시간) 중에는 일정이 트리거되지 않습니다.

.. Snapshot settings(스냅샷 설정) 섹션에서 * Backup Type * 페이지에서 선택한 백업 유형 및 스케줄 유형에 대한 보존 설정을 지정합니다.
+
|===
| 원하는 작업 | 그러면... 


 a| 
특정 수의 스냅샷을 유지합니다
 a| 
유지할 사본 * 을 선택한 다음 유지할 스냅샷 수를 지정합니다.

스냅샷 수가 지정된 수를 초과하면 가장 오래된 복제본이 먼저 삭제되고 스냅샷이 삭제됩니다.


NOTE: SnapVault 복제를 설정하려면 보존 수를 2 이상으로 설정해야 합니다. 보존 횟수를 1로 설정하면 새 스냅샷이 타겟으로 복제될 때까지 첫 번째 스냅샷이 SnapVault 관계에 대한 참조 스냅샷이기 때문에 보존 작업이 실패할 수 있습니다.


NOTE: 최대 보존 값은 1018입니다. 보존이 기본 ONTAP 버전에서 지원하는 값보다 높은 값으로 설정된 경우 백업이 실패합니다.



 a| 
스냅샷을 특정 기간 동안 보관합니다
 a| 
복제본 유지 기간 * 을 선택한 다음 스냅샷을 삭제하기 전에 보존할 일 수를 지정합니다.



 a| 
스냅샷 복사 잠금 기간
 a| 
*스냅샷 복사 잠금 기간*을 선택하고 일, 월 또는 년을 지정합니다.

SnapLock 보존 기간은 100년 미만이어야 합니다.

|===
.. 정책 레이블을 선택합니다.
+

NOTE: 원격 복제를 위해 기본 스냅샷에 SnapMirror 레이블을 할당하면 기본 스냅샷이 SnapCenter 에서 ONTAP 보조 시스템으로 스냅샷 복제 작업을 오프로드할 수 있습니다.  정책 페이지에서 SnapMirror 또는 SnapVault 옵션을 활성화하지 않고도 이 작업을 수행할 수 있습니다.



. Select secondary replication options 섹션에서 다음 보조 복제 옵션 중 하나 또는 둘 다를 선택합니다.
+
|===
| 이 필드의 내용... | 수행할 작업... 


 a| 
* 로컬 스냅샷 복사본을 생성한 후 SnapMirror 업데이트 * 를 참조하십시오
 a| 
다른 볼륨에 백업 세트의 미러 복사본을 생성하려면 이 필드를 선택합니다(SnapMirror 복제).

ONTAP의 보호 관계가 미러 및 볼트 유형이고 이 옵션만 선택하는 경우, 기본 볼륨에서 생성된 스냅샷은 대상으로 전송되지 않고 대상에 나열됩니다. 복원 작업을 수행하기 위해 대상에서 이 스냅샷을 선택하면 다음 오류 메시지가 표시됩니다. 선택한 볼트 백업/미러링된 백업에 대해 보조 위치를 사용할 수 없습니다.

보조 복제 중에 SnapLock 만료 시간에 운영 SnapLock 만료 시간이 로드됩니다.

토폴로지 페이지에서 * 새로 고침 * 버튼을 클릭하면 ONTAP에서 검색된 2차 및 1차 SnapLock 만료 시간이 새로 고쳐집니다.

을 link:view-mysql-database-backups-and-clones-in-the-topology-page.html["토폴로지 페이지에서 MySQL 리소스 관련 백업 및 클론을 봅니다"]참조하십시오.



 a| 
* 로컬 스냅샷 복사본을 생성한 후 SnapVault 업데이트 * 를 클릭합니다
 a| 
디스크 간 백업 복제(SnapVault 백업)를 수행하려면 이 옵션을 선택합니다.

보조 복제 중에 SnapLock 만료 시간에 운영 SnapLock 만료 시간이 로드됩니다. 토폴로지 페이지에서 * 새로 고침 * 버튼을 클릭하면 ONTAP에서 검색된 2차 및 1차 SnapLock 만료 시간이 새로 고쳐집니다.

SnapLock가 SnapLock 볼트라고 하는 ONTAP의 보조 버전에서만 구성된 경우 토폴로지 페이지에서 * 새로 고침 * 버튼을 클릭하면 ONTAP에서 검색된 보조 시스템의 잠금 기간이 새로 고쳐집니다.

SnapLock 볼트에 대한 자세한 내용은 볼트에서 WORM에 스냅샷 커밋 을 참조하십시오
목적지

을 link:view-mysql-database-backups-and-clones-in-the-topology-page.html["토폴로지 페이지에서 MySQL 리소스 관련 백업 및 클론을 봅니다"]참조하십시오.



 a| 
* 오류 재시도 횟수 *
 a| 
작업이 중지되기 전에 허용되는 최대 복제 시도 횟수를 입력합니다.

|===
+

NOTE: 보조 스토리지의 최대 스냅샷 한도에 도달하지 않도록 ONTAP에서 보조 스토리지의 SnapMirror 보존 정책을 구성해야 합니다.

. 요약을 검토하고 * Finish * 를 클릭합니다.

